#!/bin/sh
#
#  Create copies of icons to support deprecated file names.
#

rm -f boy0.png       && cp -f boy_3.png       boy0.png
rm -f boy0.svg       && cp -f boy_3.svg       boy0.svg
rm -f boy1.png       && cp -f boy_2.png       boy1.png
rm -f boy1.svg       && cp -f boy_2.svg       boy1.svg
rm -f boy2.png       && cp -f boy_1.png       boy2.png
rm -f boy2.svg       && cp -f boy_1.svg       boy2.svg
rm -f boy3.png       && cp -f boy_4.png       boy3.png
rm -f boy3.svg       && cp -f boy_4.svg       boy3.svg
rm -f boy4.png       && cp -f boy_3.png       boy4.png
rm -f boy4.svg       && cp -f boy_3.svg       boy4.svg
rm -f boy5.png       && cp -f boy_4.png       boy5.png
rm -f boy5.svg       && cp -f boy_4.svg       boy5.svg
rm -f boy6.png       && cp -f boy_2.png       boy6.png
rm -f boy6.svg       && cp -f boy_2.svg       boy6.svg
rm -f boy7.png       && cp -f boy_2.png       boy7.png
rm -f boy7.svg       && cp -f boy_2.svg       boy7.svg

rm -f child1.png     && cp -f girl_1.png      child1.png
rm -f child1.svg     && cp -f girl_1.svg      child1.svg
rm -f child2.png     && cp -f girl_2.png      child2.png
rm -f child2.svg     && cp -f girl_2.svg      child2.svg
                                             
rm -f child1-off.png && cp -f child1.png      child1-off.png
rm -f child1-off.svg && cp -f child1.svg      child1-off.svg
rm -f child2-off.png && cp -f child2.png      child2-off.png
rm -f child2-off.svg && cp -f child2.svg      child2-off.svg

rm -f garden2.png    && cp -f garden.png      garden2.png
rm -f garden2.svg    && cp -f garden.svg      garden2.svg
rm -f garden3.png    && cp -f garden.png      garden3.png
rm -f garden3.svg    && cp -f garden.svg      garden3.svg

rm -f house-off.png  && cp -f house.png       house-off.png
rm -f house-off.svg  && cp -f house.svg       house-off.svg

rm -f parents.png    && cp -f parents_3_3.png parents.png
rm -f parents.svg    && cp -f parents_3_3.svg parents.svg

rm -f shield-2.png   && cp -f shield-1.png    shield-2.png
rm -f shield-2.svg   && cp -f shield-1.svg    shield-2.svg

rm -f wardrobe2.png  && cp -f wardrobe.png    wardrobe2.png
rm -f wardrobe2.svg  && cp -f wardrobe.svg    wardrobe2.svg
