<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.openhab.addons.itests</groupId>
    <artifactId>org.openhab.addons.reactor.itests</artifactId>
    <version>5.3.0-SNAPSHOT</version>
  </parent>

  <artifactId>org.openhab.io.yamlcomposer.tests</artifactId>

  <name>openHAB Add-ons :: Integration Tests :: YAML Composer IO Tests</name>

  <dependencies>
    <dependency>
      <groupId>org.openhab.addons.bundles</groupId>
      <artifactId>org.openhab.io.yamlcomposer</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.snakeyaml</groupId>
      <artifactId>snakeyaml-engine</artifactId>
      <version>3.0.1</version>
    </dependency>
    <dependency>
      <groupId>org.openhab.osgiify</groupId>
      <artifactId>com.hubspot.jinjava.jinjava</artifactId>
      <version>2.8.3</version>
    </dependency>
    <dependency>
      <groupId>ch.obermuhlner</groupId>
      <artifactId>big-math</artifactId>
      <version>2.3.2</version>
    </dependency>
    <dependency>
      <groupId>org.openhab.osgiify</groupId>
      <artifactId>com.google.re2j.re2j</artifactId>
      <version>1.2</version>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.datatype</groupId>
      <artifactId>jackson-datatype-jdk8</artifactId>
      <version>${jackson.version}</version>
    </dependency>
  </dependencies>

</project>
