/*
 * Copyright (c) 2010-2025 Contributors to the openHAB project
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 */

package org.openhab.binding.jellyfin.internal.api.version.current.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.openhab.binding.jellyfin.internal.api.version.current.model.ActivityLogEntry;
import org.openhab.binding.jellyfin.internal.api.version.current.model.SessionMessageType;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Activity log created message.
 */
@JsonPropertyOrder({
  ActivityLogEntryMessage.JSON_PROPERTY_DATA,
  ActivityLogEntryMessage.JSON_PROPERTY_MESSAGE_ID,
  ActivityLogEntryMessage.JSON_PROPERTY_MESSAGE_TYPE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class ActivityLogEntryMessage {
  public static final String JSON_PROPERTY_DATA = "Data";
  @javax.annotation.Nullable
  private JsonNullable<List<ActivityLogEntry>> data = JsonNullable.<List<ActivityLogEntry>>undefined();

  public static final String JSON_PROPERTY_MESSAGE_ID = "MessageId";
  @javax.annotation.Nullable
  private UUID messageId;

  public static final String JSON_PROPERTY_MESSAGE_TYPE = "MessageType";
  @javax.annotation.Nullable
  private SessionMessageType messageType = SessionMessageType.ACTIVITY_LOG_ENTRY;

  public ActivityLogEntryMessage() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public ActivityLogEntryMessage(
    @JsonProperty(JSON_PROPERTY_MESSAGE_TYPE) SessionMessageType messageType
  ) {
    this();
    this.messageType = messageType;
  }

  public ActivityLogEntryMessage data(@javax.annotation.Nullable List<ActivityLogEntry> data) {
    this.data = JsonNullable.<List<ActivityLogEntry>>of(data);
    
    return this;
  }

  public ActivityLogEntryMessage addDataItem(ActivityLogEntry dataItem) {
    if (this.data == null || !this.data.isPresent()) {
      this.data = JsonNullable.<List<ActivityLogEntry>>of(new ArrayList<>());
    }
    try {
      this.data.get().add(dataItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Gets or sets the data.
   * @return data
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public List<ActivityLogEntry> getData() {
        return data.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<ActivityLogEntry>> getData_JsonNullable() {
    return data;
  }
  
  @JsonProperty(JSON_PROPERTY_DATA)
  public void setData_JsonNullable(JsonNullable<List<ActivityLogEntry>> data) {
    this.data = data;
  }

  public void setData(@javax.annotation.Nullable List<ActivityLogEntry> data) {
    this.data = JsonNullable.<List<ActivityLogEntry>>of(data);
  }

  public ActivityLogEntryMessage messageId(@javax.annotation.Nullable UUID messageId) {
    
    this.messageId = messageId;
    return this;
  }

  /**
   * Gets or sets the message id.
   * @return messageId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MESSAGE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getMessageId() {
    return messageId;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessageId(@javax.annotation.Nullable UUID messageId) {
    this.messageId = messageId;
  }

  /**
   * The different kinds of messages that are used in the WebSocket api.
   * @return messageType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MESSAGE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SessionMessageType getMessageType() {
    return messageType;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActivityLogEntryMessage activityLogEntryMessage = (ActivityLogEntryMessage) o;
    return equalsNullable(this.data, activityLogEntryMessage.data) &&
        Objects.equals(this.messageId, activityLogEntryMessage.messageId) &&
        Objects.equals(this.messageType, activityLogEntryMessage.messageType);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(data), messageId, messageType);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActivityLogEntryMessage {\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    messageId: ").append(toIndentedString(messageId)).append("\n");
    sb.append("    messageType: ").append(toIndentedString(messageType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ActivityLogEntryMessage instance;

    public Builder() {
      this(new ActivityLogEntryMessage());
    }

    protected Builder(ActivityLogEntryMessage instance) {
      this.instance = instance;
    }

    public ActivityLogEntryMessage.Builder data(List<ActivityLogEntry> data) {
      this.instance.data = JsonNullable.<List<ActivityLogEntry>>of(data);
      return this;
    }
    public ActivityLogEntryMessage.Builder data(JsonNullable<List<ActivityLogEntry>> data) {
      this.instance.data = data;
      return this;
    }
    public ActivityLogEntryMessage.Builder messageId(UUID messageId) {
      this.instance.messageId = messageId;
      return this;
    }
    public ActivityLogEntryMessage.Builder messageType(SessionMessageType messageType) {
      this.instance.messageType = messageType;
      return this;
    }


    /**
    * returns a built ActivityLogEntryMessage instance.
    *
    * The builder is not reusable.
    */
    public ActivityLogEntryMessage build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ActivityLogEntryMessage.Builder builder() {
    return new ActivityLogEntryMessage.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ActivityLogEntryMessage.Builder toBuilder() {
    return new ActivityLogEntryMessage.Builder()
      .data(getData())
      .messageId(getMessageId())
      .messageType(getMessageType());
  }


}

