/*
 * Copyright (c) 2010-2025 Contributors to the openHAB project
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 */

package org.openhab.binding.jellyfin.internal.api.version.current.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * A class representing an authentication result.
 */
@JsonPropertyOrder({ AuthenticationResult.JSON_PROPERTY_USER, AuthenticationResult.JSON_PROPERTY_SESSION_INFO,
        AuthenticationResult.JSON_PROPERTY_ACCESS_TOKEN, AuthenticationResult.JSON_PROPERTY_SERVER_ID })
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class AuthenticationResult {
    public static final String JSON_PROPERTY_USER = "User";
    @javax.annotation.Nullable
    private UserDto user;

    public static final String JSON_PROPERTY_SESSION_INFO = "SessionInfo";
    @javax.annotation.Nullable
    private SessionInfoDto sessionInfo;

    public static final String JSON_PROPERTY_ACCESS_TOKEN = "AccessToken";
    @javax.annotation.Nullable
    private String accessToken;

    public static final String JSON_PROPERTY_SERVER_ID = "ServerId";
    @javax.annotation.Nullable
    private String serverId;

    public AuthenticationResult() {
    }

    public AuthenticationResult user(@javax.annotation.Nullable UserDto user) {

        this.user = user;
        return this;
    }

    /**
     * Gets or sets the user.
     * 
     * @return user
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_USER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public UserDto getUser() {
        return user;
    }

    @JsonProperty(JSON_PROPERTY_USER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setUser(@javax.annotation.Nullable UserDto user) {
        this.user = user;
    }

    public AuthenticationResult sessionInfo(@javax.annotation.Nullable SessionInfoDto sessionInfo) {

        this.sessionInfo = sessionInfo;
        return this;
    }

    /**
     * Gets or sets the session info.
     * 
     * @return sessionInfo
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_SESSION_INFO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public SessionInfoDto getSessionInfo() {
        return sessionInfo;
    }

    @JsonProperty(JSON_PROPERTY_SESSION_INFO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSessionInfo(@javax.annotation.Nullable SessionInfoDto sessionInfo) {
        this.sessionInfo = sessionInfo;
    }

    public AuthenticationResult accessToken(@javax.annotation.Nullable String accessToken) {

        this.accessToken = accessToken;
        return this;
    }

    /**
     * Gets or sets the access token.
     * 
     * @return accessToken
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ACCESS_TOKEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getAccessToken() {
        return accessToken;
    }

    @JsonProperty(JSON_PROPERTY_ACCESS_TOKEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAccessToken(@javax.annotation.Nullable String accessToken) {
        this.accessToken = accessToken;
    }

    public AuthenticationResult serverId(@javax.annotation.Nullable String serverId) {

        this.serverId = serverId;
        return this;
    }

    /**
     * Gets or sets the server id.
     * 
     * @return serverId
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_SERVER_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getServerId() {
        return serverId;
    }

    @JsonProperty(JSON_PROPERTY_SERVER_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setServerId(@javax.annotation.Nullable String serverId) {
        this.serverId = serverId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AuthenticationResult authenticationResult = (AuthenticationResult) o;
        return Objects.equals(this.user, authenticationResult.user)
                && Objects.equals(this.sessionInfo, authenticationResult.sessionInfo)
                && Objects.equals(this.accessToken, authenticationResult.accessToken)
                && Objects.equals(this.serverId, authenticationResult.serverId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(user, sessionInfo, accessToken, serverId);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AuthenticationResult {\n");
        sb.append("    user: ").append(toIndentedString(user)).append("\n");
        sb.append("    sessionInfo: ").append(toIndentedString(sessionInfo)).append("\n");
        sb.append("    accessToken: ").append(toIndentedString(accessToken)).append("\n");
        sb.append("    serverId: ").append(toIndentedString(serverId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static class Builder {

        private AuthenticationResult instance;

        public Builder() {
            this(new AuthenticationResult());
        }

        protected Builder(AuthenticationResult instance) {
            this.instance = instance;
        }

        public AuthenticationResult.Builder user(UserDto user) {
            this.instance.user = user;
            return this;
        }

        public AuthenticationResult.Builder sessionInfo(SessionInfoDto sessionInfo) {
            this.instance.sessionInfo = sessionInfo;
            return this;
        }

        public AuthenticationResult.Builder accessToken(String accessToken) {
            this.instance.accessToken = accessToken;
            return this;
        }

        public AuthenticationResult.Builder serverId(String serverId) {
            this.instance.serverId = serverId;
            return this;
        }

        /**
         * returns a built AuthenticationResult instance.
         *
         * The builder is not reusable.
         */
        public AuthenticationResult build() {
            try {
                return this.instance;
            } finally {
                // ensure that this.instance is not reused
                this.instance = null;
            }
        }

        @Override
        public String toString() {
            return getClass() + "=(" + instance + ")";
        }
    }

    /**
     * Create a builder with no initialized field.
     */
    public static AuthenticationResult.Builder builder() {
        return new AuthenticationResult.Builder();
    }

    /**
     * Create a builder with a shallow copy of this instance.
     */
    public AuthenticationResult.Builder toBuilder() {
        return new AuthenticationResult.Builder().user(getUser()).sessionInfo(getSessionInfo())
                .accessToken(getAccessToken()).serverId(getServerId());
    }
}
