/*
 * Copyright (c) 2010-2025 Contributors to the openHAB project
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 */

package org.openhab.binding.jellyfin.internal.api.version.current.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.jackson.nullable.JsonNullable;
import org.openhab.binding.jellyfin.internal.api.version.current.model.ActivityLogEntryStartMessage;
import org.openhab.binding.jellyfin.internal.api.version.current.model.ActivityLogEntryStopMessage;
import org.openhab.binding.jellyfin.internal.api.version.current.model.InboundKeepAliveMessage;
import org.openhab.binding.jellyfin.internal.api.version.current.model.ScheduledTasksInfoStartMessage;
import org.openhab.binding.jellyfin.internal.api.version.current.model.ScheduledTasksInfoStopMessage;
import org.openhab.binding.jellyfin.internal.api.version.current.model.SessionMessageType;
import org.openhab.binding.jellyfin.internal.api.version.current.model.SessionsStartMessage;
import org.openhab.binding.jellyfin.internal.api.version.current.model.SessionsStopMessage;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Represents the list of possible inbound websocket types
 */
@JsonPropertyOrder({
  InboundWebSocketMessage.JSON_PROPERTY_DATA,
  InboundWebSocketMessage.JSON_PROPERTY_MESSAGE_TYPE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
@JsonIgnoreProperties(
  value = "MessageType", // ignore manually set MessageType, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the MessageType to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "MessageType", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = ActivityLogEntryStartMessage.class, name = "ActivityLogEntryStart"),
  @JsonSubTypes.Type(value = ActivityLogEntryStopMessage.class, name = "ActivityLogEntryStop"),
  @JsonSubTypes.Type(value = InboundKeepAliveMessage.class, name = "KeepAlive"),
  @JsonSubTypes.Type(value = ScheduledTasksInfoStartMessage.class, name = "ScheduledTasksInfoStart"),
  @JsonSubTypes.Type(value = ScheduledTasksInfoStopMessage.class, name = "ScheduledTasksInfoStop"),
  @JsonSubTypes.Type(value = SessionsStartMessage.class, name = "SessionsStart"),
  @JsonSubTypes.Type(value = SessionsStopMessage.class, name = "SessionsStop"),
  @JsonSubTypes.Type(value = ActivityLogEntryStartMessage.class, name = "ActivityLogEntryStartMessage"),
  @JsonSubTypes.Type(value = ActivityLogEntryStopMessage.class, name = "ActivityLogEntryStopMessage"),
  @JsonSubTypes.Type(value = InboundKeepAliveMessage.class, name = "InboundKeepAliveMessage"),
  @JsonSubTypes.Type(value = ScheduledTasksInfoStartMessage.class, name = "ScheduledTasksInfoStartMessage"),
  @JsonSubTypes.Type(value = ScheduledTasksInfoStopMessage.class, name = "ScheduledTasksInfoStopMessage"),
  @JsonSubTypes.Type(value = SessionsStartMessage.class, name = "SessionsStartMessage"),
  @JsonSubTypes.Type(value = SessionsStopMessage.class, name = "SessionsStopMessage"),
})

public class InboundWebSocketMessage {
  public static final String JSON_PROPERTY_DATA = "Data";
  @javax.annotation.Nullable
  private JsonNullable<String> data = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_MESSAGE_TYPE = "MessageType";
  @javax.annotation.Nullable
  private SessionMessageType messageType = SessionMessageType.SESSIONS_STOP;

  public InboundWebSocketMessage() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public InboundWebSocketMessage(
    @JsonProperty(JSON_PROPERTY_MESSAGE_TYPE) SessionMessageType messageType
  ) {
    this();
    this.messageType = messageType;
  }

  public InboundWebSocketMessage data(@javax.annotation.Nullable String data) {
    this.data = JsonNullable.<String>of(data);
    
    return this;
  }

  /**
   * Gets or sets the data.
   * @return data
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getData() {
        return data.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getData_JsonNullable() {
    return data;
  }
  
  @JsonProperty(JSON_PROPERTY_DATA)
  public void setData_JsonNullable(JsonNullable<String> data) {
    this.data = data;
  }

  public void setData(@javax.annotation.Nullable String data) {
    this.data = JsonNullable.<String>of(data);
  }

  /**
   * The different kinds of messages that are used in the WebSocket api.
   * @return messageType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MESSAGE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SessionMessageType getMessageType() {
    return messageType;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InboundWebSocketMessage inboundWebSocketMessage = (InboundWebSocketMessage) o;
    return equalsNullable(this.data, inboundWebSocketMessage.data) &&
        Objects.equals(this.messageType, inboundWebSocketMessage.messageType);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(data), messageType);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InboundWebSocketMessage {\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    messageType: ").append(toIndentedString(messageType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private InboundWebSocketMessage instance;

    public Builder() {
      this(new InboundWebSocketMessage());
    }

    protected Builder(InboundWebSocketMessage instance) {
      this.instance = instance;
    }

    public InboundWebSocketMessage.Builder data(String data) {
      this.instance.data = JsonNullable.<String>of(data);
      return this;
    }
    public InboundWebSocketMessage.Builder data(JsonNullable<String> data) {
      this.instance.data = data;
      return this;
    }
    public InboundWebSocketMessage.Builder messageType(SessionMessageType messageType) {
      this.instance.messageType = messageType;
      return this;
    }


    /**
    * returns a built InboundWebSocketMessage instance.
    *
    * The builder is not reusable.
    */
    public InboundWebSocketMessage build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static InboundWebSocketMessage.Builder builder() {
    return new InboundWebSocketMessage.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public InboundWebSocketMessage.Builder toBuilder() {
    return new InboundWebSocketMessage.Builder()
      .data(getData())
      .messageType(getMessageType());
  }


}

