/*
 * Copyright (c) 2010-2025 Contributors to the openHAB project
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 */

package org.openhab.binding.jellyfin.internal.api.version.current.model;

import java.util.Arrays;
import java.util.Objects;
import java.util.StringJoiner;
import java.util.UUID;

import org.openapitools.jackson.nullable.JsonNullable;
import org.openhab.binding.jellyfin.internal.api.version.ApiClient;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * MovieInfoRemoteSearchQuery
 */
@JsonPropertyOrder({ MovieInfoRemoteSearchQuery.JSON_PROPERTY_SEARCH_INFO,
        MovieInfoRemoteSearchQuery.JSON_PROPERTY_ITEM_ID, MovieInfoRemoteSearchQuery.JSON_PROPERTY_SEARCH_PROVIDER_NAME,
        MovieInfoRemoteSearchQuery.JSON_PROPERTY_INCLUDE_DISABLED_PROVIDERS })
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class MovieInfoRemoteSearchQuery {
    public static final String JSON_PROPERTY_SEARCH_INFO = "SearchInfo";
    private JsonNullable<MovieInfo> searchInfo = JsonNullable.<MovieInfo> undefined();

    public static final String JSON_PROPERTY_ITEM_ID = "ItemId";
    @javax.annotation.Nullable
    private UUID itemId;

    public static final String JSON_PROPERTY_SEARCH_PROVIDER_NAME = "SearchProviderName";
    private JsonNullable<String> searchProviderName = JsonNullable.<String> undefined();

    public static final String JSON_PROPERTY_INCLUDE_DISABLED_PROVIDERS = "IncludeDisabledProviders";
    @javax.annotation.Nullable
    private Boolean includeDisabledProviders;

    public MovieInfoRemoteSearchQuery() {
    }

    public MovieInfoRemoteSearchQuery searchInfo(@javax.annotation.Nullable MovieInfo searchInfo) {
        this.searchInfo = JsonNullable.<MovieInfo> of(searchInfo);
        return this;
    }

    /**
     * Get searchInfo
     * 
     * @return searchInfo
     */
    @javax.annotation.Nullable
    @JsonIgnore
    public MovieInfo getSearchInfo() {
        return searchInfo.orElse(null);
    }

    @JsonProperty(JSON_PROPERTY_SEARCH_INFO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public JsonNullable<MovieInfo> getSearchInfo_JsonNullable() {
        return searchInfo;
    }

    @JsonProperty(JSON_PROPERTY_SEARCH_INFO)
    public void setSearchInfo_JsonNullable(JsonNullable<MovieInfo> searchInfo) {
        this.searchInfo = searchInfo;
    }

    public void setSearchInfo(@javax.annotation.Nullable MovieInfo searchInfo) {
        this.searchInfo = JsonNullable.<MovieInfo> of(searchInfo);
    }

    public MovieInfoRemoteSearchQuery itemId(@javax.annotation.Nullable UUID itemId) {
        this.itemId = itemId;
        return this;
    }

    /**
     * Get itemId
     * 
     * @return itemId
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ITEM_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public UUID getItemId() {
        return itemId;
    }

    @JsonProperty(JSON_PROPERTY_ITEM_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setItemId(@javax.annotation.Nullable UUID itemId) {
        this.itemId = itemId;
    }

    public MovieInfoRemoteSearchQuery searchProviderName(@javax.annotation.Nullable String searchProviderName) {
        this.searchProviderName = JsonNullable.<String> of(searchProviderName);
        return this;
    }

    /**
     * Gets or sets the provider name to search within if set.
     * 
     * @return searchProviderName
     */
    @javax.annotation.Nullable
    @JsonIgnore
    public String getSearchProviderName() {
        return searchProviderName.orElse(null);
    }

    @JsonProperty(JSON_PROPERTY_SEARCH_PROVIDER_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public JsonNullable<String> getSearchProviderName_JsonNullable() {
        return searchProviderName;
    }

    @JsonProperty(JSON_PROPERTY_SEARCH_PROVIDER_NAME)
    public void setSearchProviderName_JsonNullable(JsonNullable<String> searchProviderName) {
        this.searchProviderName = searchProviderName;
    }

    public void setSearchProviderName(@javax.annotation.Nullable String searchProviderName) {
        this.searchProviderName = JsonNullable.<String> of(searchProviderName);
    }

    public MovieInfoRemoteSearchQuery includeDisabledProviders(
            @javax.annotation.Nullable Boolean includeDisabledProviders) {
        this.includeDisabledProviders = includeDisabledProviders;
        return this;
    }

    /**
     * Gets or sets a value indicating whether disabled providers should be included.
     * 
     * @return includeDisabledProviders
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_INCLUDE_DISABLED_PROVIDERS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Boolean getIncludeDisabledProviders() {
        return includeDisabledProviders;
    }

    @JsonProperty(JSON_PROPERTY_INCLUDE_DISABLED_PROVIDERS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setIncludeDisabledProviders(@javax.annotation.Nullable Boolean includeDisabledProviders) {
        this.includeDisabledProviders = includeDisabledProviders;
    }

    /**
     * Return true if this MovieInfoRemoteSearchQuery object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MovieInfoRemoteSearchQuery movieInfoRemoteSearchQuery = (MovieInfoRemoteSearchQuery) o;
        return equalsNullable(this.searchInfo, movieInfoRemoteSearchQuery.searchInfo)
                && Objects.equals(this.itemId, movieInfoRemoteSearchQuery.itemId)
                && equalsNullable(this.searchProviderName, movieInfoRemoteSearchQuery.searchProviderName)
                && Objects.equals(this.includeDisabledProviders, movieInfoRemoteSearchQuery.includeDisabledProviders);
    }

    private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
        return a == b
                || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
    }

    @Override
    public int hashCode() {
        return Objects.hash(hashCodeNullable(searchInfo), itemId, hashCodeNullable(searchProviderName),
                includeDisabledProviders);
    }

    private static <T> int hashCodeNullable(JsonNullable<T> a) {
        if (a == null) {
            return 1;
        }
        return a.isPresent() ? Arrays.deepHashCode(new Object[] { a.get() }) : 31;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MovieInfoRemoteSearchQuery {\n");
        sb.append("    searchInfo: ").append(toIndentedString(searchInfo)).append("\n");
        sb.append("    itemId: ").append(toIndentedString(itemId)).append("\n");
        sb.append("    searchProviderName: ").append(toIndentedString(searchProviderName)).append("\n");
        sb.append("    includeDisabledProviders: ").append(toIndentedString(includeDisabledProviders)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `SearchInfo` to the URL query string
        if (getSearchInfo() != null) {
            joiner.add(getSearchInfo().toUrlQueryString(prefix + "SearchInfo" + suffix));
        }

        // add `ItemId` to the URL query string
        if (getItemId() != null) {
            joiner.add(String.format("%sItemId%s=%s", prefix, suffix,
                    ApiClient.urlEncode(ApiClient.valueToString(getItemId()))));
        }

        // add `SearchProviderName` to the URL query string
        if (getSearchProviderName() != null) {
            joiner.add(String.format("%sSearchProviderName%s=%s", prefix, suffix,
                    ApiClient.urlEncode(ApiClient.valueToString(getSearchProviderName()))));
        }

        // add `IncludeDisabledProviders` to the URL query string
        if (getIncludeDisabledProviders() != null) {
            joiner.add(String.format("%sIncludeDisabledProviders%s=%s", prefix, suffix,
                    ApiClient.urlEncode(ApiClient.valueToString(getIncludeDisabledProviders()))));
        }

        return joiner.toString();
    }

    public static class Builder {

        private MovieInfoRemoteSearchQuery instance;

        public Builder() {
            this(new MovieInfoRemoteSearchQuery());
        }

        protected Builder(MovieInfoRemoteSearchQuery instance) {
            this.instance = instance;
        }

        public MovieInfoRemoteSearchQuery.Builder searchInfo(MovieInfo searchInfo) {
            this.instance.searchInfo = JsonNullable.<MovieInfo> of(searchInfo);
            return this;
        }

        public MovieInfoRemoteSearchQuery.Builder searchInfo(JsonNullable<MovieInfo> searchInfo) {
            this.instance.searchInfo = searchInfo;
            return this;
        }

        public MovieInfoRemoteSearchQuery.Builder itemId(UUID itemId) {
            this.instance.itemId = itemId;
            return this;
        }

        public MovieInfoRemoteSearchQuery.Builder searchProviderName(String searchProviderName) {
            this.instance.searchProviderName = JsonNullable.<String> of(searchProviderName);
            return this;
        }

        public MovieInfoRemoteSearchQuery.Builder searchProviderName(JsonNullable<String> searchProviderName) {
            this.instance.searchProviderName = searchProviderName;
            return this;
        }

        public MovieInfoRemoteSearchQuery.Builder includeDisabledProviders(Boolean includeDisabledProviders) {
            this.instance.includeDisabledProviders = includeDisabledProviders;
            return this;
        }

        /**
         * returns a built MovieInfoRemoteSearchQuery instance.
         *
         * The builder is not reusable.
         */
        public MovieInfoRemoteSearchQuery build() {
            try {
                return this.instance;
            } finally {
                // ensure that this.instance is not reused
                this.instance = null;
            }
        }

        @Override
        public String toString() {
            return getClass() + "=(" + instance + ")";
        }
    }

    /**
     * Create a builder with no initialized field.
     */
    public static MovieInfoRemoteSearchQuery.Builder builder() {
        return new MovieInfoRemoteSearchQuery.Builder();
    }

    /**
     * Create a builder with a shallow copy of this instance.
     */
    public MovieInfoRemoteSearchQuery.Builder toBuilder() {
        return new MovieInfoRemoteSearchQuery.Builder().searchInfo(getSearchInfo()).itemId(getItemId())
                .searchProviderName(getSearchProviderName()).includeDisabledProviders(getIncludeDisabledProviders());
    }
}
