/*
 * Copyright (c) 2010-2025 Contributors to the openHAB project
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 */

package org.openhab.binding.jellyfin.internal.api.version.current.model;

import java.time.OffsetDateTime;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * RemoteSubtitleInfo
 */
@JsonPropertyOrder({ RemoteSubtitleInfo.JSON_PROPERTY_THREE_LETTER_I_S_O_LANGUAGE_NAME,
        RemoteSubtitleInfo.JSON_PROPERTY_ID, RemoteSubtitleInfo.JSON_PROPERTY_PROVIDER_NAME,
        RemoteSubtitleInfo.JSON_PROPERTY_NAME, RemoteSubtitleInfo.JSON_PROPERTY_FORMAT,
        RemoteSubtitleInfo.JSON_PROPERTY_AUTHOR, RemoteSubtitleInfo.JSON_PROPERTY_COMMENT,
        RemoteSubtitleInfo.JSON_PROPERTY_DATE_CREATED, RemoteSubtitleInfo.JSON_PROPERTY_COMMUNITY_RATING,
        RemoteSubtitleInfo.JSON_PROPERTY_FRAME_RATE, RemoteSubtitleInfo.JSON_PROPERTY_DOWNLOAD_COUNT,
        RemoteSubtitleInfo.JSON_PROPERTY_IS_HASH_MATCH, RemoteSubtitleInfo.JSON_PROPERTY_AI_TRANSLATED,
        RemoteSubtitleInfo.JSON_PROPERTY_MACHINE_TRANSLATED, RemoteSubtitleInfo.JSON_PROPERTY_FORCED,
        RemoteSubtitleInfo.JSON_PROPERTY_HEARING_IMPAIRED })
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class RemoteSubtitleInfo {
    public static final String JSON_PROPERTY_THREE_LETTER_I_S_O_LANGUAGE_NAME = "ThreeLetterISOLanguageName";
    @javax.annotation.Nullable
    private String threeLetterISOLanguageName;

    public static final String JSON_PROPERTY_ID = "Id";
    @javax.annotation.Nullable
    private String id;

    public static final String JSON_PROPERTY_PROVIDER_NAME = "ProviderName";
    @javax.annotation.Nullable
    private String providerName;

    public static final String JSON_PROPERTY_NAME = "Name";
    @javax.annotation.Nullable
    private String name;

    public static final String JSON_PROPERTY_FORMAT = "Format";
    @javax.annotation.Nullable
    private String format;

    public static final String JSON_PROPERTY_AUTHOR = "Author";
    @javax.annotation.Nullable
    private String author;

    public static final String JSON_PROPERTY_COMMENT = "Comment";
    @javax.annotation.Nullable
    private String comment;

    public static final String JSON_PROPERTY_DATE_CREATED = "DateCreated";
    @javax.annotation.Nullable
    private OffsetDateTime dateCreated;

    public static final String JSON_PROPERTY_COMMUNITY_RATING = "CommunityRating";
    @javax.annotation.Nullable
    private Float communityRating;

    public static final String JSON_PROPERTY_FRAME_RATE = "FrameRate";
    @javax.annotation.Nullable
    private Float frameRate;

    public static final String JSON_PROPERTY_DOWNLOAD_COUNT = "DownloadCount";
    @javax.annotation.Nullable
    private Integer downloadCount;

    public static final String JSON_PROPERTY_IS_HASH_MATCH = "IsHashMatch";
    @javax.annotation.Nullable
    private Boolean isHashMatch;

    public static final String JSON_PROPERTY_AI_TRANSLATED = "AiTranslated";
    @javax.annotation.Nullable
    private Boolean aiTranslated;

    public static final String JSON_PROPERTY_MACHINE_TRANSLATED = "MachineTranslated";
    @javax.annotation.Nullable
    private Boolean machineTranslated;

    public static final String JSON_PROPERTY_FORCED = "Forced";
    @javax.annotation.Nullable
    private Boolean forced;

    public static final String JSON_PROPERTY_HEARING_IMPAIRED = "HearingImpaired";
    @javax.annotation.Nullable
    private Boolean hearingImpaired;

    public RemoteSubtitleInfo() {
    }

    public RemoteSubtitleInfo threeLetterISOLanguageName(@javax.annotation.Nullable String threeLetterISOLanguageName) {

        this.threeLetterISOLanguageName = threeLetterISOLanguageName;
        return this;
    }

    /**
     * Get threeLetterISOLanguageName
     * 
     * @return threeLetterISOLanguageName
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_THREE_LETTER_I_S_O_LANGUAGE_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getThreeLetterISOLanguageName() {
        return threeLetterISOLanguageName;
    }

    @JsonProperty(JSON_PROPERTY_THREE_LETTER_I_S_O_LANGUAGE_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setThreeLetterISOLanguageName(@javax.annotation.Nullable String threeLetterISOLanguageName) {
        this.threeLetterISOLanguageName = threeLetterISOLanguageName;
    }

    public RemoteSubtitleInfo id(@javax.annotation.Nullable String id) {

        this.id = id;
        return this;
    }

    /**
     * Get id
     * 
     * @return id
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getId() {
        return id;
    }

    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setId(@javax.annotation.Nullable String id) {
        this.id = id;
    }

    public RemoteSubtitleInfo providerName(@javax.annotation.Nullable String providerName) {

        this.providerName = providerName;
        return this;
    }

    /**
     * Get providerName
     * 
     * @return providerName
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PROVIDER_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getProviderName() {
        return providerName;
    }

    @JsonProperty(JSON_PROPERTY_PROVIDER_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setProviderName(@javax.annotation.Nullable String providerName) {
        this.providerName = providerName;
    }

    public RemoteSubtitleInfo name(@javax.annotation.Nullable String name) {

        this.name = name;
        return this;
    }

    /**
     * Get name
     * 
     * @return name
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getName() {
        return name;
    }

    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setName(@javax.annotation.Nullable String name) {
        this.name = name;
    }

    public RemoteSubtitleInfo format(@javax.annotation.Nullable String format) {

        this.format = format;
        return this;
    }

    /**
     * Get format
     * 
     * @return format
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_FORMAT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getFormat() {
        return format;
    }

    @JsonProperty(JSON_PROPERTY_FORMAT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setFormat(@javax.annotation.Nullable String format) {
        this.format = format;
    }

    public RemoteSubtitleInfo author(@javax.annotation.Nullable String author) {

        this.author = author;
        return this;
    }

    /**
     * Get author
     * 
     * @return author
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_AUTHOR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getAuthor() {
        return author;
    }

    @JsonProperty(JSON_PROPERTY_AUTHOR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAuthor(@javax.annotation.Nullable String author) {
        this.author = author;
    }

    public RemoteSubtitleInfo comment(@javax.annotation.Nullable String comment) {

        this.comment = comment;
        return this;
    }

    /**
     * Get comment
     * 
     * @return comment
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_COMMENT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getComment() {
        return comment;
    }

    @JsonProperty(JSON_PROPERTY_COMMENT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setComment(@javax.annotation.Nullable String comment) {
        this.comment = comment;
    }

    public RemoteSubtitleInfo dateCreated(@javax.annotation.Nullable OffsetDateTime dateCreated) {

        this.dateCreated = dateCreated;
        return this;
    }

    /**
     * Get dateCreated
     * 
     * @return dateCreated
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DATE_CREATED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public OffsetDateTime getDateCreated() {
        return dateCreated;
    }

    @JsonProperty(JSON_PROPERTY_DATE_CREATED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDateCreated(@javax.annotation.Nullable OffsetDateTime dateCreated) {
        this.dateCreated = dateCreated;
    }

    public RemoteSubtitleInfo communityRating(@javax.annotation.Nullable Float communityRating) {

        this.communityRating = communityRating;
        return this;
    }

    /**
     * Get communityRating
     * 
     * @return communityRating
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_COMMUNITY_RATING)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Float getCommunityRating() {
        return communityRating;
    }

    @JsonProperty(JSON_PROPERTY_COMMUNITY_RATING)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCommunityRating(@javax.annotation.Nullable Float communityRating) {
        this.communityRating = communityRating;
    }

    public RemoteSubtitleInfo frameRate(@javax.annotation.Nullable Float frameRate) {

        this.frameRate = frameRate;
        return this;
    }

    /**
     * Get frameRate
     * 
     * @return frameRate
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_FRAME_RATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Float getFrameRate() {
        return frameRate;
    }

    @JsonProperty(JSON_PROPERTY_FRAME_RATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setFrameRate(@javax.annotation.Nullable Float frameRate) {
        this.frameRate = frameRate;
    }

    public RemoteSubtitleInfo downloadCount(@javax.annotation.Nullable Integer downloadCount) {

        this.downloadCount = downloadCount;
        return this;
    }

    /**
     * Get downloadCount
     * 
     * @return downloadCount
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DOWNLOAD_COUNT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getDownloadCount() {
        return downloadCount;
    }

    @JsonProperty(JSON_PROPERTY_DOWNLOAD_COUNT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDownloadCount(@javax.annotation.Nullable Integer downloadCount) {
        this.downloadCount = downloadCount;
    }

    public RemoteSubtitleInfo isHashMatch(@javax.annotation.Nullable Boolean isHashMatch) {

        this.isHashMatch = isHashMatch;
        return this;
    }

    /**
     * Get isHashMatch
     * 
     * @return isHashMatch
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_IS_HASH_MATCH)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getIsHashMatch() {
        return isHashMatch;
    }

    @JsonProperty(JSON_PROPERTY_IS_HASH_MATCH)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setIsHashMatch(@javax.annotation.Nullable Boolean isHashMatch) {
        this.isHashMatch = isHashMatch;
    }

    public RemoteSubtitleInfo aiTranslated(@javax.annotation.Nullable Boolean aiTranslated) {

        this.aiTranslated = aiTranslated;
        return this;
    }

    /**
     * Get aiTranslated
     * 
     * @return aiTranslated
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_AI_TRANSLATED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getAiTranslated() {
        return aiTranslated;
    }

    @JsonProperty(JSON_PROPERTY_AI_TRANSLATED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAiTranslated(@javax.annotation.Nullable Boolean aiTranslated) {
        this.aiTranslated = aiTranslated;
    }

    public RemoteSubtitleInfo machineTranslated(@javax.annotation.Nullable Boolean machineTranslated) {

        this.machineTranslated = machineTranslated;
        return this;
    }

    /**
     * Get machineTranslated
     * 
     * @return machineTranslated
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_MACHINE_TRANSLATED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getMachineTranslated() {
        return machineTranslated;
    }

    @JsonProperty(JSON_PROPERTY_MACHINE_TRANSLATED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMachineTranslated(@javax.annotation.Nullable Boolean machineTranslated) {
        this.machineTranslated = machineTranslated;
    }

    public RemoteSubtitleInfo forced(@javax.annotation.Nullable Boolean forced) {

        this.forced = forced;
        return this;
    }

    /**
     * Get forced
     * 
     * @return forced
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_FORCED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getForced() {
        return forced;
    }

    @JsonProperty(JSON_PROPERTY_FORCED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setForced(@javax.annotation.Nullable Boolean forced) {
        this.forced = forced;
    }

    public RemoteSubtitleInfo hearingImpaired(@javax.annotation.Nullable Boolean hearingImpaired) {

        this.hearingImpaired = hearingImpaired;
        return this;
    }

    /**
     * Get hearingImpaired
     * 
     * @return hearingImpaired
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_HEARING_IMPAIRED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getHearingImpaired() {
        return hearingImpaired;
    }

    @JsonProperty(JSON_PROPERTY_HEARING_IMPAIRED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setHearingImpaired(@javax.annotation.Nullable Boolean hearingImpaired) {
        this.hearingImpaired = hearingImpaired;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RemoteSubtitleInfo remoteSubtitleInfo = (RemoteSubtitleInfo) o;
        return Objects.equals(this.threeLetterISOLanguageName, remoteSubtitleInfo.threeLetterISOLanguageName)
                && Objects.equals(this.id, remoteSubtitleInfo.id)
                && Objects.equals(this.providerName, remoteSubtitleInfo.providerName)
                && Objects.equals(this.name, remoteSubtitleInfo.name)
                && Objects.equals(this.format, remoteSubtitleInfo.format)
                && Objects.equals(this.author, remoteSubtitleInfo.author)
                && Objects.equals(this.comment, remoteSubtitleInfo.comment)
                && Objects.equals(this.dateCreated, remoteSubtitleInfo.dateCreated)
                && Objects.equals(this.communityRating, remoteSubtitleInfo.communityRating)
                && Objects.equals(this.frameRate, remoteSubtitleInfo.frameRate)
                && Objects.equals(this.downloadCount, remoteSubtitleInfo.downloadCount)
                && Objects.equals(this.isHashMatch, remoteSubtitleInfo.isHashMatch)
                && Objects.equals(this.aiTranslated, remoteSubtitleInfo.aiTranslated)
                && Objects.equals(this.machineTranslated, remoteSubtitleInfo.machineTranslated)
                && Objects.equals(this.forced, remoteSubtitleInfo.forced)
                && Objects.equals(this.hearingImpaired, remoteSubtitleInfo.hearingImpaired);
    }

    @Override
    public int hashCode() {
        return Objects.hash(threeLetterISOLanguageName, id, providerName, name, format, author, comment, dateCreated,
                communityRating, frameRate, downloadCount, isHashMatch, aiTranslated, machineTranslated, forced,
                hearingImpaired);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class RemoteSubtitleInfo {\n");
        sb.append("    threeLetterISOLanguageName: ").append(toIndentedString(threeLetterISOLanguageName)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    providerName: ").append(toIndentedString(providerName)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    format: ").append(toIndentedString(format)).append("\n");
        sb.append("    author: ").append(toIndentedString(author)).append("\n");
        sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
        sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
        sb.append("    communityRating: ").append(toIndentedString(communityRating)).append("\n");
        sb.append("    frameRate: ").append(toIndentedString(frameRate)).append("\n");
        sb.append("    downloadCount: ").append(toIndentedString(downloadCount)).append("\n");
        sb.append("    isHashMatch: ").append(toIndentedString(isHashMatch)).append("\n");
        sb.append("    aiTranslated: ").append(toIndentedString(aiTranslated)).append("\n");
        sb.append("    machineTranslated: ").append(toIndentedString(machineTranslated)).append("\n");
        sb.append("    forced: ").append(toIndentedString(forced)).append("\n");
        sb.append("    hearingImpaired: ").append(toIndentedString(hearingImpaired)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static class Builder {

        private RemoteSubtitleInfo instance;

        public Builder() {
            this(new RemoteSubtitleInfo());
        }

        protected Builder(RemoteSubtitleInfo instance) {
            this.instance = instance;
        }

        public RemoteSubtitleInfo.Builder threeLetterISOLanguageName(String threeLetterISOLanguageName) {
            this.instance.threeLetterISOLanguageName = threeLetterISOLanguageName;
            return this;
        }

        public RemoteSubtitleInfo.Builder id(String id) {
            this.instance.id = id;
            return this;
        }

        public RemoteSubtitleInfo.Builder providerName(String providerName) {
            this.instance.providerName = providerName;
            return this;
        }

        public RemoteSubtitleInfo.Builder name(String name) {
            this.instance.name = name;
            return this;
        }

        public RemoteSubtitleInfo.Builder format(String format) {
            this.instance.format = format;
            return this;
        }

        public RemoteSubtitleInfo.Builder author(String author) {
            this.instance.author = author;
            return this;
        }

        public RemoteSubtitleInfo.Builder comment(String comment) {
            this.instance.comment = comment;
            return this;
        }

        public RemoteSubtitleInfo.Builder dateCreated(OffsetDateTime dateCreated) {
            this.instance.dateCreated = dateCreated;
            return this;
        }

        public RemoteSubtitleInfo.Builder communityRating(Float communityRating) {
            this.instance.communityRating = communityRating;
            return this;
        }

        public RemoteSubtitleInfo.Builder frameRate(Float frameRate) {
            this.instance.frameRate = frameRate;
            return this;
        }

        public RemoteSubtitleInfo.Builder downloadCount(Integer downloadCount) {
            this.instance.downloadCount = downloadCount;
            return this;
        }

        public RemoteSubtitleInfo.Builder isHashMatch(Boolean isHashMatch) {
            this.instance.isHashMatch = isHashMatch;
            return this;
        }

        public RemoteSubtitleInfo.Builder aiTranslated(Boolean aiTranslated) {
            this.instance.aiTranslated = aiTranslated;
            return this;
        }

        public RemoteSubtitleInfo.Builder machineTranslated(Boolean machineTranslated) {
            this.instance.machineTranslated = machineTranslated;
            return this;
        }

        public RemoteSubtitleInfo.Builder forced(Boolean forced) {
            this.instance.forced = forced;
            return this;
        }

        public RemoteSubtitleInfo.Builder hearingImpaired(Boolean hearingImpaired) {
            this.instance.hearingImpaired = hearingImpaired;
            return this;
        }

        /**
         * returns a built RemoteSubtitleInfo instance.
         *
         * The builder is not reusable.
         */
        public RemoteSubtitleInfo build() {
            try {
                return this.instance;
            } finally {
                // ensure that this.instance is not reused
                this.instance = null;
            }
        }

        @Override
        public String toString() {
            return getClass() + "=(" + instance + ")";
        }
    }

    /**
     * Create a builder with no initialized field.
     */
    public static RemoteSubtitleInfo.Builder builder() {
        return new RemoteSubtitleInfo.Builder();
    }

    /**
     * Create a builder with a shallow copy of this instance.
     */
    public RemoteSubtitleInfo.Builder toBuilder() {
        return new RemoteSubtitleInfo.Builder().threeLetterISOLanguageName(getThreeLetterISOLanguageName()).id(getId())
                .providerName(getProviderName()).name(getName()).format(getFormat()).author(getAuthor())
                .comment(getComment()).dateCreated(getDateCreated()).communityRating(getCommunityRating())
                .frameRate(getFrameRate()).downloadCount(getDownloadCount()).isHashMatch(getIsHashMatch())
                .aiTranslated(getAiTranslated()).machineTranslated(getMachineTranslated()).forced(getForced())
                .hearingImpaired(getHearingImpaired());
    }
}
