/*
 * Copyright (c) 2010-2025 Contributors to the openHAB project
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 */

package org.openhab.binding.jellyfin.internal.api.version.current.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * A class for subtitle profile information.
 */
@JsonPropertyOrder({ SubtitleProfile.JSON_PROPERTY_FORMAT, SubtitleProfile.JSON_PROPERTY_METHOD,
        SubtitleProfile.JSON_PROPERTY_DIDL_MODE, SubtitleProfile.JSON_PROPERTY_LANGUAGE,
        SubtitleProfile.JSON_PROPERTY_CONTAINER })
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class SubtitleProfile {
    public static final String JSON_PROPERTY_FORMAT = "Format";
    @javax.annotation.Nullable
    private String format;

    public static final String JSON_PROPERTY_METHOD = "Method";
    @javax.annotation.Nullable
    private SubtitleDeliveryMethod method;

    public static final String JSON_PROPERTY_DIDL_MODE = "DidlMode";
    @javax.annotation.Nullable
    private String didlMode;

    public static final String JSON_PROPERTY_LANGUAGE = "Language";
    @javax.annotation.Nullable
    private String language;

    public static final String JSON_PROPERTY_CONTAINER = "Container";
    @javax.annotation.Nullable
    private String container;

    public SubtitleProfile() {
    }

    public SubtitleProfile format(@javax.annotation.Nullable String format) {

        this.format = format;
        return this;
    }

    /**
     * Gets or sets the format.
     * 
     * @return format
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_FORMAT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getFormat() {
        return format;
    }

    @JsonProperty(JSON_PROPERTY_FORMAT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setFormat(@javax.annotation.Nullable String format) {
        this.format = format;
    }

    public SubtitleProfile method(@javax.annotation.Nullable SubtitleDeliveryMethod method) {

        this.method = method;
        return this;
    }

    /**
     * Gets or sets the delivery method.
     * 
     * @return method
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_METHOD)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public SubtitleDeliveryMethod getMethod() {
        return method;
    }

    @JsonProperty(JSON_PROPERTY_METHOD)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMethod(@javax.annotation.Nullable SubtitleDeliveryMethod method) {
        this.method = method;
    }

    public SubtitleProfile didlMode(@javax.annotation.Nullable String didlMode) {

        this.didlMode = didlMode;
        return this;
    }

    /**
     * Gets or sets the DIDL mode.
     * 
     * @return didlMode
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DIDL_MODE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getDidlMode() {
        return didlMode;
    }

    @JsonProperty(JSON_PROPERTY_DIDL_MODE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDidlMode(@javax.annotation.Nullable String didlMode) {
        this.didlMode = didlMode;
    }

    public SubtitleProfile language(@javax.annotation.Nullable String language) {

        this.language = language;
        return this;
    }

    /**
     * Gets or sets the language.
     * 
     * @return language
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_LANGUAGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getLanguage() {
        return language;
    }

    @JsonProperty(JSON_PROPERTY_LANGUAGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLanguage(@javax.annotation.Nullable String language) {
        this.language = language;
    }

    public SubtitleProfile container(@javax.annotation.Nullable String container) {

        this.container = container;
        return this;
    }

    /**
     * Gets or sets the container.
     * 
     * @return container
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CONTAINER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getContainer() {
        return container;
    }

    @JsonProperty(JSON_PROPERTY_CONTAINER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setContainer(@javax.annotation.Nullable String container) {
        this.container = container;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SubtitleProfile subtitleProfile = (SubtitleProfile) o;
        return Objects.equals(this.format, subtitleProfile.format)
                && Objects.equals(this.method, subtitleProfile.method)
                && Objects.equals(this.didlMode, subtitleProfile.didlMode)
                && Objects.equals(this.language, subtitleProfile.language)
                && Objects.equals(this.container, subtitleProfile.container);
    }

    @Override
    public int hashCode() {
        return Objects.hash(format, method, didlMode, language, container);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SubtitleProfile {\n");
        sb.append("    format: ").append(toIndentedString(format)).append("\n");
        sb.append("    method: ").append(toIndentedString(method)).append("\n");
        sb.append("    didlMode: ").append(toIndentedString(didlMode)).append("\n");
        sb.append("    language: ").append(toIndentedString(language)).append("\n");
        sb.append("    container: ").append(toIndentedString(container)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static class Builder {

        private SubtitleProfile instance;

        public Builder() {
            this(new SubtitleProfile());
        }

        protected Builder(SubtitleProfile instance) {
            this.instance = instance;
        }

        public SubtitleProfile.Builder format(String format) {
            this.instance.format = format;
            return this;
        }

        public SubtitleProfile.Builder method(SubtitleDeliveryMethod method) {
            this.instance.method = method;
            return this;
        }

        public SubtitleProfile.Builder didlMode(String didlMode) {
            this.instance.didlMode = didlMode;
            return this;
        }

        public SubtitleProfile.Builder language(String language) {
            this.instance.language = language;
            return this;
        }

        public SubtitleProfile.Builder container(String container) {
            this.instance.container = container;
            return this;
        }

        /**
         * returns a built SubtitleProfile instance.
         *
         * The builder is not reusable.
         */
        public SubtitleProfile build() {
            try {
                return this.instance;
            } finally {
                // ensure that this.instance is not reused
                this.instance = null;
            }
        }

        @Override
        public String toString() {
            return getClass() + "=(" + instance + ")";
        }
    }

    /**
     * Create a builder with no initialized field.
     */
    public static SubtitleProfile.Builder builder() {
        return new SubtitleProfile.Builder();
    }

    /**
     * Create a builder with a shallow copy of this instance.
     */
    public SubtitleProfile.Builder toBuilder() {
        return new SubtitleProfile.Builder().format(getFormat()).method(getMethod()).didlMode(getDidlMode())
                .language(getLanguage()).container(getContainer());
    }
}
