#!/bin/bash

BUILD_LOG=build.log
SHARD_SUMMARY=target/shard-summary.md

ARGUMENTS="clean install -B -T 1.5C -U"
if [ $# -ge 1 ]; then
    ARGUMENTS=$@
fi

function write_shard_summary() {
    local mode="$1"
    local scope="$2"
    local addon_count="$3"
    local range="$4"

    mkdir -p "$(dirname "$SHARD_SUMMARY")"

    {
        echo "### Build Shard"
        echo "- Shard: ${MAVEN_BUILD_PART:-1}/${MAVEN_BUILD_PARTS:-1}"
        echo "- Mode: $mode"
        echo "- Scope: $scope"
        if [ -n "$addon_count" ]; then
            echo "- Add-ons: $addon_count"
        fi
        if [ -n "$range" ]; then
            echo "- Alphabetical range: $range"
        fi
    } > "$SHARD_SUMMARY"
}

function print_reactor_summary() {
    local start_end=$(grep -anE "\[INFO\] \\-{70,}" "$BUILD_LOG" | tail -n4 | cut -f1 -d: | sed -e 1b -e '$!d' | xargs)
    local start=$(awk '{print $1}' <<< $start_end)
    local end=$(awk '{print $2}' <<< $start_end)
    cat "$BUILD_LOG" | sed -n "${start},${end}p" | sed 's/\[INFO\] //'
}

function mvnp() {
    set -o pipefail # exit build with error when pipes fail
    local reactor_size=$(find -name "pom.xml" | grep -vE '/src/|/target/' | wc -l)
    local padding=$(bc -l <<< "scale=0;2*(l($reactor_size)/l(10)+1)")
    local command=(./mvnw $@)
    exec "${command[@]}" 2>&1 | # execute, redirect stderr to stdout
        tee "$BUILD_LOG" | # write output to log
        stdbuf -oL grep -aE '^\[INFO\] Building .+ \[.+\]$' | # filter progress
        stdbuf -o0 sed -uE 's/^\[INFO\] Building (.*[^ ])[ ]+\[([0-9]+\/[0-9]+)\]$/\2| \1/' | # prefix project name with progress
        stdbuf -o0 sed -e :a -e "s/^.\{1,${padding}\}|/ &/;ta" # right align progress with padding
}

function build_all() {
    echo
    echo "Building all projects"
    echo
    echo "+ ./mvnw $ARGUMENTS"
    echo

    write_shard_summary "full-build" "all projects" "" ""

    mvnp $ARGUMENTS

    status=$?
    echo

    if [ $status -eq 0 ]; then
        print_reactor_summary
    else
        tail -n 2000 "$BUILD_LOG"
    fi

    exit $status
}

function addon_projects() {
    local addon="$1"

    # include add-on projects
    local projects=":$(find . -mindepth 2 -maxdepth 2 -type d -regextype egrep -regex "./(bundles|itests)/$addon(\..*)?$" | sort | sed -E 's#./(bundles|itests)/##g' | xargs | sed 's# #,:#g')"

    # include BOMs
    projects="$projects,:org.openhab.addons.bom.openhab-core-index,:org.openhab.addons.bom.runtime-index,:org.openhab.addons.bom.test-index"

    # exclude features
    projects="$projects,-:org.openhab.addons.reactor.features.karaf,-:org.openhab.addons.features.karaf.openhab-addons,-:org.openhab.addons.features.karaf.openhab-addons-external"

    echo $projects
}

function build_addon() {
    local addon="$1"
    local command="./mvnw $ARGUMENTS -am -amd -pl $(addon_projects $addon)"

    echo
    echo "Building add-on: $addon"
    echo
    echo "+ $command"
    echo

    write_shard_summary "single-addon" "$addon" "1" "$addon"

    set -o pipefail # exit build with error when pipes fail
    $command 2>&1 | tee "$BUILD_LOG"
    exit $?
}

function build_addon_shard() {
    local addons="${MAVEN_SHARD_ADDONS:-}"
    local part="${MAVEN_BUILD_PART:-1}"
    local parts="${MAVEN_BUILD_PARTS:-1}"

    if [ -z "$addons" ]; then
        write_shard_summary "empty-shard" "no assigned add-ons" "0" ""
        echo "No add-ons assigned to shard $part/$parts" | tee "$BUILD_LOG"
        exit 0
    fi

    local first_addon=$(echo "$addons" | awk '{print $1}')
    local last_addon=$(echo "$addons" | awk '{print $NF}')
    local addon_total=$(echo "$addons" | wc -w)

    local projects=$(for addon in $addons; do addon_projects "$addon"; done | tr ',' '\n' | sed '/^$/d' | grep -Ev '^-:org\.openhab\.addons\.reactor\.features\.karaf$|^-:org\.openhab\.addons\.features\.karaf\.openhab-addons$|^-:org\.openhab\.addons\.features\.karaf\.openhab-addons-external$' | awk '!seen[$0]++' | paste -sd, -)

    local command="./mvnw $ARGUMENTS -am -pl $projects"

    write_shard_summary "alphabetical-shard" "assigned add-ons" "$addon_total" "$first_addon .. $last_addon"

    echo
    echo "Building add-on shard: $part/$parts ($addon_total add-ons)"
    echo "Alphabetical range: $first_addon .. $last_addon"
    echo
    echo "+ $command"
    echo

    set -o pipefail # exit build with error when pipes fail
    $command 2>&1 | tee "$BUILD_LOG"
    exit $?
}

function build_features() {
    local projects=":org.openhab.addons.reactor.features.karaf,:org.openhab.addons.features.karaf.openhab-addons,:org.openhab.addons.features.karaf.openhab-addons-external"
    local command="./mvnw $ARGUMENTS -pl $projects"

    echo
    echo "Building features"
    echo
    echo "+ $command"
    echo

    write_shard_summary "features" "feature modules" "" ""

    set -o pipefail
    $command 2>&1 | tee "$BUILD_LOG"
    exit $?
}

function build_based_on_changes() {
    if [ -n "${MAVEN_BUILD_ADDON:-}" ]; then
        build_addon "${MAVEN_BUILD_ADDON}"
    elif [ -n "${MAVEN_BUILD_FEATURES:-}" ]; then
        build_features
    elif [ -n "${MAVEN_SHARD_ADDONS:-}" ]; then
        build_addon_shard
    else
        build_all
    fi
}

bash ./mvnw -v
rm -f shard-summary.md
build_based_on_changes
