/*
 * Copyright (c) 2010-2026 Contributors to the openHAB project
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */
package org.openhab.io.yamlcomposer.internal;

import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.StringReader;
import java.net.URLDecoder;
import java.net.URLEncoder;
import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.time.ZonedDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.IdentityHashMap;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;

import org.eclipse.jdt.annotation.NonNullByDefault;
import org.eclipse.jdt.annotation.Nullable;
import org.openhab.core.OpenHAB;
import org.openhab.io.yamlcomposer.internal.constructors.ModelConstructor;
import org.snakeyaml.engine.v2.api.Dump;
import org.snakeyaml.engine.v2.api.DumpSettings;
import org.snakeyaml.engine.v2.api.Load;
import org.snakeyaml.engine.v2.api.LoadSettings;
import org.snakeyaml.engine.v2.resolver.ScalarResolver;
import org.snakeyaml.engine.v2.schema.CoreSchema;
import org.snakeyaml.engine.v2.schema.Schema;

/**
 * Pure utility functions for YAML loading and output.
 *
 * @author Jimmy Tanagra - Initial contribution
 */
@NonNullByDefault
final class ComposerUtils {
    private static final String GENERATED_HEADER = """
            # ==============================================================================
            # Generated by openHAB %s (%s) YAML Composer, DO NOT EDIT
            # Source:    %s
            # Generated: %s
            # Env-Deps:  %s
            # Env-Hash:  %s
            # ==============================================================================

                            """;

    private static final String HEADER_MARKER = GENERATED_HEADER.lines().iterator().next();

    private ComposerUtils() {
        // Static utility class
    }

    /**
     * Removes top-level keys that start with a dot from the given map.
     *
     * @param dataMap the map to process
     */
    static void removeHiddenKeys(Map<?, ?> dataMap) {
        dataMap.keySet().removeIf(key -> key instanceof String keyStr && keyStr.startsWith("."));
    }

    /**
     * Writes the fully processed YAML representation to a compiled output file using the system environment.
     * <p>
     * To prevent unnecessary disk write operations and avoid triggering downstream file-reload events in openHAB,
     * this method checks if the target file already exists and compares its YAML body (ignoring header
     * metadata such as generation timestamps) against the proposed content. If the compiled body and tracked
     * environment hashes are identical, the write is skipped.
     *
     * @param dataMap the resulting data map to dump
     * @param sourcePath the absolute path of the source file being processed
     * @param outputPath the absolute path of the compiled output file
     * @param trackedEnvVars the set of environment variables referenced during composition
     * @return {@code true} if the file was written to disk; {@code false} if the write was skipped
     *         because the existing output body and environment state are identical
     * @throws IOException if writing to the file fails
     */
    static boolean writeCompiledOutput(Object dataMap, Path sourcePath, Path outputPath, Set<String> trackedEnvVars)
            throws IOException {
        return writeCompiledOutput(dataMap, sourcePath, outputPath, trackedEnvVars, System.getenv(),
                YamlOutputConfig.defaultConfig());
    }

    static boolean writeCompiledOutput(Object dataMap, Path sourcePath, Path outputPath, Set<String> trackedEnvVars,
            YamlOutputConfig outputConfig) throws IOException {
        return writeCompiledOutput(dataMap, sourcePath, outputPath, trackedEnvVars, System.getenv(), outputConfig);
    }

    static boolean writeCompiledOutput(Object dataMap, Path sourcePath, Path outputPath, Set<String> trackedEnvVars,
            Map<String, String> envMap) throws IOException {
        return writeCompiledOutput(dataMap, sourcePath, outputPath, trackedEnvVars, envMap,
                YamlOutputConfig.defaultConfig());
    }

    /**
     * Writes the fully processed YAML representation to a compiled output file using the provided environment map.
     * <p>
     * Used by tests to simulate different environment variable values without modifying the system environment.
     * <p>
     * To prevent unnecessary disk write operations and avoid triggering downstream file-reload events in openHAB,
     * this method checks if the target file already exists and compares its YAML body (ignoring header
     * metadata such as generation timestamps) against the proposed content. If the compiled body and tracked
     * environment hashes are identical, the write is skipped.
     *
     * @param dataMap the resulting data map to dump
     * @param sourcePath the absolute path of the source file being processed
     * @param outputPath the absolute path of the compiled output file
     * @param trackedEnvVars the set of environment variables referenced during composition
     * @param envMap the environment variable map to compute the initial hash against
     * @param outputConfig the YAML output configuration to use for dumping
     * @return {@code true} if the file was written to disk; {@code false} if the write was skipped
     *         because the existing output body and environment state are identical
     * @throws IOException if writing to the file fails
     */
    static boolean writeCompiledOutput(Object dataMap, Path sourcePath, Path outputPath, Set<String> trackedEnvVars,
            Map<String, String> envMap, YamlOutputConfig outputConfig) throws IOException {
        Path outputDir = outputPath.getParent();
        if (outputDir != null) {
            Files.createDirectories(outputDir);
        }

        DumpSettings dumpSettings = DumpSettings.builder() //
                .setDefaultFlowStyle(YamlOutputConfig.DEFAULT_FLOW_STYLE) //
                .setDefaultScalarStyle(YamlOutputConfig.DEFAULT_SCALAR_STYLE) //
                .setIndent(YamlOutputConfig.DEFAULT_INDENT) //
                .setIndicatorIndent(YamlOutputConfig.DEFAULT_INDICATOR_INDENT) //
                .setIndentWithIndicator(YamlOutputConfig.DEFAULT_INDENT_WITH_INDICATOR) //
                .setWidth(outputConfig.maxLineWidth()) //
                .setSplitLines(outputConfig.splitLines()) //
                .setExplicitStart(false) //
                .setExplicitEnd(false) //
                .setMultiLineFlow(true) //
                .build();

        Dump yaml = new Dump(dumpSettings);
        Object unaliasedData = breakAliases(dataMap);
        String compiledYamlBody = yaml.dumpToString(unaliasedData);

        if (outputConfig.sectionSpacing() > 0) {
            compiledYamlBody = formatYamlSpacing(compiledYamlBody, outputConfig.sectionSpacing());
        }

        Path sourcePathRelative = ComposerConfig.configRoot().relativize(sourcePath);

        if (Files.exists(outputPath)) {
            String existingContent = Files.readString(outputPath, StandardCharsets.UTF_8);
            String existingBody = extractBody(existingContent);

            if (existingBody.equals(compiledYamlBody)
                    && !isEnvironmentChanged(existingContent, trackedEnvVars, envMap)) {
                return false;
            }
        }

        TreeSet<String> sortedEnvVars = new TreeSet<>(trackedEnvVars);
        String envDepsFormatted = formatEnvDeps(sortedEnvVars);
        String envHashStr = computeEnvHash(sortedEnvVars, envMap);

        String finalHeader = GENERATED_HEADER.formatted(OpenHAB.getVersion(), OpenHAB.buildString(), sourcePathRelative,
                ZonedDateTime.now(), envDepsFormatted, envHashStr);

        Files.writeString(outputPath, finalHeader + compiledYamlBody, StandardCharsets.UTF_8);
        return true;
    }

    /**
     * Checks if any environment variables tracked in the provided output file content have changed
     * relative to the system environment.
     *
     * @param content the raw string content of the generated file
     * @param trackedEnvVars the current set of tracked environment variables from composition
     * @return true if environment values changed or header is legacy/unreadable, false otherwise
     */
    static boolean isEnvironmentChanged(String content, Set<String> trackedEnvVars) {
        return isEnvironmentChanged(content, trackedEnvVars, System.getenv());
    }

    /**
     * Checks if any environment variables tracked in the provided output file content have changed
     * relative to the provided environment map.
     * <p>
     * Used by tests to simulate different environment variable values without modifying the system environment.
     *
     * @param content the raw string content of the generated file
     * @param trackedEnvVars the current set of tracked environment variables from composition
     * @param envMap the environment variable map to check against
     * @return true if environment values changed or header is legacy/unreadable, false otherwise
     */
    static boolean isEnvironmentChanged(String content, Set<String> trackedEnvVars, Map<String, String> envMap) {
        try (BufferedReader reader = new BufferedReader(new StringReader(content))) {
            String line;
            Set<String> envVars = new HashSet<>();
            String envHashLine = null;
            boolean collectingEnvDeps = false;
            boolean headerStarted = false;

            while ((line = reader.readLine()) != null) {
                if (line.startsWith("# ===")) {
                    if (headerStarted) {
                        break;
                    }
                    headerStarted = true;
                    continue;
                }

                if (!headerStarted) {
                    continue;
                }

                if (line.startsWith("# Env-Deps:")) {
                    collectingEnvDeps = true;
                    String headerVal = line.substring("# Env-Deps:".length()).trim();
                    envVars.addAll(parseEnvVars(headerVal));
                } else if (line.startsWith("# Env-Hash:")) {
                    collectingEnvDeps = false;
                    envHashLine = line.substring("# Env-Hash:".length()).trim();
                } else if (collectingEnvDeps) {
                    if (line.startsWith("#")) {
                        String headerVal = line.substring(1).trim();
                        envVars.addAll(parseEnvVars(headerVal));
                    } else {
                        collectingEnvDeps = false;
                    }
                }

                if (envHashLine != null && !collectingEnvDeps) {
                    break;
                }
            }

            // If header markers are missing (legacy file), trigger regeneration
            if (envHashLine == null) {
                return true;
            }

            if (!envVars.equals(trackedEnvVars)) {
                return true;
            }

            String currentHash = computeEnvHash(new TreeSet<>(trackedEnvVars), envMap);
            return !currentHash.equals(envHashLine);
        } catch (IOException e) {
            return true;
        }
    }

    /**
     * Extracts the core YAML content body from a full document string by stripping the generated header block.
     * <p>
     * Header boundaries are identified by the opening and closing comment markers derived directly from
     * {@link #GENERATED_HEADER}. If no header block markers are found, the raw content string is returned with
     * leading whitespace stripped.
     *
     * @param fullYamlContent the complete file content including optional header
     * @return the content body stripped of its header section
     */
    private static String extractBody(String fullYamlContent) {
        if (!HEADER_MARKER.isEmpty()) {
            int firstMarker = fullYamlContent.indexOf(HEADER_MARKER);
            if (firstMarker != -1) {
                int secondMarker = fullYamlContent.indexOf(HEADER_MARKER, firstMarker + HEADER_MARKER.length());
                if (secondMarker != -1) {
                    return fullYamlContent.substring(secondMarker + HEADER_MARKER.length()).stripLeading();
                }
            }
        }
        return fullYamlContent.stripLeading();
    }

    private static List<String> parseEnvVars(String content) {
        if (content.isEmpty()) {
            return List.of();
        }
        return Arrays.stream(content.split(",")) //
                .map(String::trim) //
                .filter(s -> !s.isEmpty()) //
                .map(token -> URLDecoder.decode(token, StandardCharsets.UTF_8)) //
                .toList();
    }

    /**
     * Formats the list of environment variable names into a multi-line string for inclusion in the generated file
     * header.
     *
     * @param envVars the list of environment variable names
     * @return a formatted multi-line string suitable for inclusion in the file header
     */
    private static String formatEnvDeps(Set<String> envVars) {
        if (envVars.isEmpty()) {
            return "";
        }

        List<String> encodedVars = envVars.stream() //
                .map(v -> URLEncoder.encode(v, StandardCharsets.UTF_8)) //
                .toList();

        List<String> lines = new ArrayList<>();
        StringBuilder currentLine = new StringBuilder();
        int maxContentLength = 75;

        for (int i = 0; i < encodedVars.size(); i++) {
            String item = encodedVars.get(i) + (i < encodedVars.size() - 1 ? ", " : "");

            if (currentLine.length() + item.length() > maxContentLength && currentLine.length() > 0) {
                lines.add(currentLine.toString().stripTrailing());
                currentLine = new StringBuilder();
            }
            currentLine.append(item);
        }
        if (currentLine.length() > 0) {
            lines.add(currentLine.toString().stripTrailing());
        }

        return String.join("\n#            ", lines);
    }

    private static String computeEnvHash(TreeSet<String> envVars, Map<String, String> envMap) {
        if (envVars.isEmpty()) {
            return "";
        }
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            for (String varName : envVars) {
                byte[] nameBytes = varName.getBytes(StandardCharsets.UTF_8);
                digest.update(ByteBuffer.allocate(Integer.BYTES).putInt(nameBytes.length).array());
                digest.update(nameBytes);

                String val = envMap.get(varName);
                if (val == null) {
                    // Explicit presence marker for unset/absent variable
                    digest.update((byte) 0x00);
                } else {
                    // Explicit presence marker for present variable, followed by length and value bytes
                    digest.update((byte) 0x01);
                    byte[] valBytes = val.getBytes(StandardCharsets.UTF_8);
                    digest.update(ByteBuffer.allocate(Integer.BYTES).putInt(valBytes.length).array());
                    digest.update(valBytes);
                }
            }
            byte[] hashBytes = digest.digest();
            StringBuilder sb = new StringBuilder();
            for (byte b : hashBytes) {
                sb.append(String.format("%02x", b));
            }
            return sb.toString();
        } catch (NoSuchAlgorithmException e) {
            return "";
        }
    }

    /**
     * Creates a new SnakeYAML Engine load instance with the custom composer constructor and resolver.
     *
     * @param sourcePath the source path of the YAML file for error reporting in the constructor
     * @return a new Load instance
     */
    private static Load createYamlLoader(String sourcePath) {
        Schema schema = new CoreSchema() {
            @Override
            public ScalarResolver getScalarResolver() {
                return new ModelResolver();
            }
        };

        LoadSettings loadSettings = LoadSettings.builder() //
                .setLabel(sourcePath) //
                .setAllowDuplicateKeys(false) //
                .setUseMarks(true) //
                .setSchema(schema) //
                .build();
        return new Load(loadSettings, new ModelConstructor(loadSettings, sourcePath));
    }

    /**
     * Loads YAML content from the given byte array using a Yaml instance configured with the custom constructor.
     *
     * @param fileBytes the YAML content as a byte array
     * @param sourcePath the source path of the YAML file for error reporting in the constructor
     * @return the loaded YAML object
     * @throws IOException if an I/O error occurs
     */
    static @Nullable Object loadYaml(byte[] fileBytes, Path sourcePath) throws IOException {
        Load loader = createYamlLoader(sourcePath.toString());
        return loader.loadFromInputStream(new ByteArrayInputStream(fileBytes));
    }

    /**
     * Produces a deep-copy of the common YAML structure objects (maps, lists, sets)
     * such that no container instance is shared more than once in the resulting
     * graph. This removes object identity sharing that SnakeYAML would otherwise
     * emit as anchors/aliases when dumping.
     *
     * @param root the loaded YAML object (may be Map, List, Set, scalar, or custom)
     * @return a deep-copied object graph with sharing broken
     */
    private static @Nullable Object breakAliases(@Nullable Object root) {
        if (root == null) {
            return null;
        }
        return cloneNode(root, new IdentityHashMap<>());
    }

    /**
     * Post-processes a YAML string to inject empty lines for improved readability.
     *
     * <p>
     * This method applies two specific spacing rules:
     * <ul>
     * <li><strong>Level 0:</strong> Inserts a newline before every top-level key (except the first line).</li>
     * <li><strong>Level 2:</strong> Inserts a newline between sibling nodes indented by exactly two spaces.</li>
     * </ul>
     *
     * <p>
     * The logic ensures that the first child of a section remains "glued" to its parent header,
     * and it safely handles both Map keys (e.g., {@code   Key:}) and List items (e.g., {@code   - Item}).
     *
     * @param yaml The raw YAML string to be formatted.
     * @param spacingLines The number of blank lines to insert between sections or sibling nodes.
     * @return A formatted YAML string with injected "breathing room."
     */
    private static @Nullable String formatYamlSpacing(@Nullable String yaml, int spacingLines) {
        if (yaml == null || yaml.isEmpty()) {
            return yaml;
        }

        String padding = "\n".repeat(spacingLines);
        String[] lines = yaml.split("\n");
        StringBuilder sb = new StringBuilder();

        boolean hasSeenLevel0 = false;
        boolean hasSeenLevel2 = false;

        for (String line : lines) {
            // --- Level 0 Logic (Sections) ---
            // Matches lines starting with a character (not space, not comment)
            if (!line.startsWith(" ") && !line.startsWith("#")) {
                if (hasSeenLevel0) {
                    sb.append(padding);
                }
                hasSeenLevel0 = true;
                hasSeenLevel2 = false; // Reset level 2 tracker for the new section
            }

            // --- Level 2 Logic (Items or List Elements) ---
            // Matches exactly 2 spaces followed by a non-whitespace character.
            // This targets siblings within a top-level section.
            else if (line.matches("^ {2}[^ \\t\\-].*")) {
                if (hasSeenLevel2) {
                    sb.append(padding);
                }
                hasSeenLevel2 = true;
            }

            sb.append(line).append("\n");
        }

        return sb.toString().trim();
    }

    /**
     * Recursively clones a YAML node, breaking object identity to prevent SnakeYAML from emitting anchors/aliases.
     *
     * @param node The YAML node to clone.
     * @param stack The recursion stack used to handle cycles.
     * @return A deep-cloned YAML node with object identity broken.
     */
    private static @Nullable Object cloneNode(@Nullable Object node, IdentityHashMap<Object, Object> stack) {
        if (node == null) {
            return null;
        }
        // Scalars and non-container objects are returned as-is
        if (!(node instanceof Map) && !(node instanceof List) && !(node instanceof Set)) {
            return node;
        }

        // If the node is already on the current recursion stack, return the
        // partially-built copy to handle cycles. We do NOT reuse completed
        // copies for separate occurrences — that would preserve sharing and
        // produce aliases.
        if (stack.containsKey(node)) {
            return stack.get(node);
        }

        if (node instanceof Map) {
            @SuppressWarnings("unchecked")
            Map<@Nullable Object, @Nullable Object> original = (Map<@Nullable Object, @Nullable Object>) node;
            Map<@Nullable Object, @Nullable Object> copy = new LinkedHashMap<>(original.size());
            stack.put(node, copy);
            for (Map.Entry<@Nullable Object, @Nullable Object> e : original.entrySet()) {
                Object k = e.getKey();
                Object v = e.getValue();
                Object newKey = cloneNode(k, stack);
                Object newVal = cloneNode(v, stack);
                copy.put(newKey, newVal);
            }
            // Remove from stack so later separate occurrences are cloned again
            stack.remove(node);
            return copy;
        }

        if (node instanceof List) {
            @SuppressWarnings("unchecked")
            List<@Nullable Object> original = (List<@Nullable Object>) node;
            List<@Nullable Object> copy = new ArrayList<>(original.size());
            stack.put(node, copy);
            for (@Nullable
            Object item : original) {
                copy.add(cloneNode(item, stack));
            }
            stack.remove(node);
            return copy;
        }

        // Set (preserve insertion order if possible)
        if (node instanceof Set) {
            @SuppressWarnings("unchecked")
            Set<@Nullable Object> original = (Set<@Nullable Object>) node;
            Set<@Nullable Object> copy = new LinkedHashSet<>(original.size());
            stack.put(node, copy);
            for (Object item : original) {
                copy.add(cloneNode(item, stack));
            }
            stack.remove(node);
            return copy;
        }

        // Fallback: return node as-is
        return node;
    }
}
