<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.openhab.addons.bundles</groupId>
    <artifactId>org.openhab.addons.reactor.bundles</artifactId>
    <version>5.3.0-SNAPSHOT</version>
  </parent>
  <artifactId>org.openhab.binding.caldav</artifactId>
  <name>openHAB Add-ons :: Bundles :: CalDAV Binding</name>
  <properties>
    <!-- Preserve biweekly's optional Jackson imports for its unused jCal support when embedding the library. -->
    <bnd.importpackage>com.fasterxml.jackson.*;resolution:=optional;version="[2.12,3)"</bnd.importpackage>
  </properties>
  <dependencies>
    <dependency>
      <groupId>net.sf.biweekly</groupId>
      <artifactId>biweekly</artifactId>
      <version>0.6.6</version>
      <exclusions>
        <exclusion>
          <groupId>com.fasterxml.jackson.core</groupId>
          <artifactId>jackson-core</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.fasterxml.jackson.core</groupId>
          <artifactId>jackson-databind</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>com.github.mangstadt</groupId>
      <artifactId>vinnie</artifactId>
      <version>2.0.2</version>
    </dependency>
  </dependencies>
</project>
