---
swagger: '2.0'

################################################################################
#                              API Information                                 #
################################################################################
info:
  version: v2
  title: tado° API

################################################################################
#                  Host, Base Path, Schemes and Content Types                  #
################################################################################
host: my.tado.com
basePath: /api/v2
schemes:
  - https
################################################################################
#                                   Tags                                       #
################################################################################
tags:
 - name: PUBLIC
   description: |
     Operations that are part of the tado° API.

################################################################################
#                                  Security                                    #
################################################################################
securityDefinitions:
  oauth:
    type: oauth2
    flow: accessCode
    authorizationUrl: https://auth.tado.com/oauth/authorize
    tokenUrl: https://auth.tado.com/oauth/token
    scopes:
      identity:read: read the identity
      home.details:read:  read home details
      home.operation:read: read home operation
      home.operation.overlay:read: read home overlay
      home.operation.overlay:write: write home overlay

################################################################################
#                                           Paths                              #
################################################################################
paths:
    /me:
      get:
        operationId: showUser
        summary: Details about the currently logged in user
        tags:
        - PUBLIC
        security:
        - oauth:
          - identity:read
        description: |
          This will return details about the currently logged in user.
    /homes/{home_id}:
      get:
        operationId: showHome
        summary: Details about a specific home.
        tags:
        - PUBLIC
        security:
        - oauth:
          - home.details:read
        description: |
          This will return the details of the specified home.
    /homes/{home_id}/zones:
      get:
        operationId: listZones
        summary: List all zones of a home.
        tags:
        - PUBLIC
        security:
        - oauth:
          - home.details:read
        description: |
          This will return a list of zones that are associated with a home.
    /homes/{home_id}/zones/{zone_id}/state:
      get:
        operationId: showZoneState
        summary: State of a zone.
        tags:
        - PUBLIC
        security:
        - oauth:
          - home.operation:read
        description: |
          This will return the current state of the specified zone.
    /homes/{home_id}/zones/{zone_id}/details:
      get:
        operationId: showZoneDetails
        summary: Details of a zone.
        tags:
        - PUBLIC
        security:
        - oauth:
          - home.operation:read
    /homes/{home_id}/zones/{zone_id}/defaultOverlay:
      get:
        operationId: showZoneDefaultOverlay
        summary: Preferences for default overlay. If an overlay is created without a termination condition (e.g through the device UI), the given termination condition is taken for this overlay.
        tags:
        - PUBLIC
        security:
        - oauth:
          - home.operation:read
    /homes/{home_id}/zones/{zone_id}/overlay:
      get:
        operationId: showZoneOverlay
        summary: Overlay of a zone
        tags:
        - PUBLIC
        security:
        - oauth:
          - home.operation.overlay:read
        description: |
          This will return the current overlay of the specified zone.
      put:
        operationId: updateZoneOverlay
        summary: Set a new overlay
        tags:
        - PUBLIC
        security:
        - oauth:
          - home.operation.overlay:write
        description: |
          This will set the overlay for the specified zone of a home.
      delete:
        operationId: deleteZoneOverlay
        summary: Delete an overlay
        tags:
        - PUBLIC
        security:
        - oauth:
          - home.operation.overlay:write
        description: |
          This will delete the overlay for the specified zone of a home.
    /homes/{home_id}/zones/{zone_id}/capabilities:
      get:
        operationId: showZoneCapabilities
        summary: Capabilities of a zone
        tags:
        - PUBLIC
        security:
        - oauth:
          - home.details:read
        description: |
          This will return the capabilities of the specified zone.
    /homes/{home_id}/mobileDevices:
      get:
        operationId: listMobileDevices
        summary: List all mobile devices associated with this home.
        tags:
        - PUBLIC
        security:
        - oauth:
          - home.details:read
################################################################################
#                                 Definitions                                  #
################################################################################
################################################################################
#                                 Path Parameters                              #
################################################################################