/**
 * Copyright (c) 2010-2024 Contributors to the openHAB project
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */
package org.openhab.binding.siemenshvac.internal.type;

import org.eclipse.jdt.annotation.NonNullByDefault;
import org.eclipse.jdt.annotation.Nullable;
import org.openhab.core.thing.type.ChannelGroupType;
import org.openhab.core.thing.type.ChannelGroupTypeProvider;
import org.openhab.core.thing.type.ChannelGroupTypeUID;

/**
 * Extends the ChannelGroupTypeProvider to manually add a ChannelGroupType.
 *
 * @author Laurent Arnal - Initial contribution
 */
@NonNullByDefault
public interface SiemensHvacChannelGroupTypeProvider extends ChannelGroupTypeProvider {

    /**
     * Adds the ChannelGroupType to this provider.
     */
    void addChannelGroupType(ChannelGroupType channelGroupType);

    /**
     * Use this method to lookup a ChannelGroupType which was generated by the siemensHvac binding.
     */
    @Nullable
    ChannelGroupType getInternalChannelGroupType(ChannelGroupTypeUID channelGroupTypeUID);

    void invalidate();
}
