/**
 * Copyright (c) 2010-2019 Contributors to the openHAB project
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */
package org.openhab.binding.nadreceiver.internal.protocol;

/**
 * Enum class listing all possible commands, received or to be sent
 *
 * @author Marc Chételat - Initial contribution
 *
 */
public enum NadReceiverCommandType {

    AudysseyDistanceBackLeft("Audyssey.Distance.BackLeft"), // =Unknown
    AudysseyDistanceBackRight("Audyssey.Distance.BackRight"), // =Unknown
    AudysseyDistanceCenter("Audyssey.Distance.Center"), // =Unknown
    AudysseyDistanceLeft("Audyssey.Distance.Left"), // =Unknown
    AudysseyDistanceRight("Audyssey.Distance.Right"), // =Unknown
    AudysseyDistanceSub("Audyssey.Distance.Sub"), // =Unknown
    AudysseyDistanceSurroundLeft("Audyssey.Distance.SurroundLeft"), // =Unknown
    AudysseyDistanceSurroundRight("Audyssey.Distance.SurroundRight"), // =Unknown
    AudysseyDistanceUser1Left("Audyssey.Distance.User1Left"), // =Unknown
    AudysseyDistanceUser1Right("Audyssey.Distance.User1Right"), // =Unknown
    AudysseyDistanceUser2Left("Audyssey.Distance.User2Left"), // =Unknown
    AudysseyDistanceUser2Right("Audyssey.Distance.User2Right"), // =Unknown
    AudysseyEnabled("Audyssey.Enabled"), // =No
    /*
     * Audyssey.Level.BackLeft=Unknown
     * Audyssey.Level.BackRight=Unknown
     * Audyssey.Level.Center=Unknown
     * Audyssey.Level.Left=Unknown
     * Audyssey.Level.Right=Unknown
     * Audyssey.Level.Sub=Unknown
     * Audyssey.Level.SurroundLeft=Unknown
     * Audyssey.Level.SurroundRight=Unknown
     * Audyssey.Level.User1Left=Unknown
     * Audyssey.Level.User1Right=Unknown
     * Audyssey.Level.User2Left=Unknown
     * Audyssey.Level.User2Right=Unknown
     * Audyssey.Speaker.Back.Config=Unknown
     * Audyssey.Speaker.Back.Frequency=Unknown
     * Audyssey.Speaker.Back.Mode=Unknown
     * Audyssey.Speaker.Center.Config=Unknown
     * Audyssey.Speaker.Center.Frequency=Unknown
     * Audyssey.Speaker.Front.Config=Unknown
     * Audyssey.Speaker.Front.Frequency=Unknown
     * Audyssey.Speaker.Sub=Unknown
     * Audyssey.Speaker.Surround.Config=Unknown
     * Audyssey.Speaker.Surround.Frequency=Unknown
     * Audyssey.Speaker.User1.Config=Unknown
     * Audyssey.Speaker.User1.Frequency=Unknown
     * Audyssey.Speaker.User1.Mode=Unknown
     * Audyssey.Speaker.User2.Config=Unknown
     * Audyssey.Speaker.User2.Frequency=Unknown
     * Audyssey.Speaker.User2.Mode=Unknown
     */

    BluOSIP("BluOS.IP"), // =192.168.1.103
    BluOSOSDAPI("BluOS.OSDAPI"), // =5
    BluOSVersion("BluOS.Version"), // =v3.2.10
    DSPVersion("DSP.Version"), // =v1.10

    /*
     * Dirac.Level.BackLeft=0
     * Dirac.Level.BackRight=0
     * Dirac.Level.Center=0
     * Dirac.Level.Left=3
     * Dirac.Level.Right=3
     * Dirac.Level.Sub=0
     * Dirac.Level.SurroundLeft=3
     * Dirac.Level.SurroundRight=3
     * Dirac.Level.User1Left=0
     * Dirac.Level.User1Right=0
     * Dirac.Level.User2Left=0
     * Dirac.Level.User2Right=0
     * Dirac1.Distance.BackLeft=0.0
     * Dirac1.Distance.BackRight=0.0
     * Dirac1.Distance.Center=0.0
     * Dirac1.Distance.Left=0.0
     * Dirac1.Distance.Right=0.7
     * Dirac1.Distance.Sub=0.0
     * Dirac1.Distance.SurroundLeft=6.7
     * Dirac1.Distance.SurroundRight=9.8
     * Dirac1.Distance.UOM=ms
     * Dirac1.Distance.User1Left=0.0
     * Dirac1.Distance.User1Right=0.0
     * Dirac1.Distance.User2Left=0.0
     * Dirac1.Distance.User2Right=0.0
     * Dirac1.EnhancedBass=Off
     * Dirac1.Level.BackLeft=0
     * Dirac1.Level.BackRight=0
     * Dirac1.Level.Center=0
     * Dirac1.Level.Left=1
     * Dirac1.Level.Right=-1
     * Dirac1.Level.Sub=0
     * Dirac1.Level.SurroundLeft=-1
     * Dirac1.Level.SurroundRight=-2
     * Dirac1.Level.User1Left=0
     * Dirac1.Level.User1Right=0
     * Dirac1.Level.User2Left=0
     * Dirac1.Level.User2Right=0
     * Dirac1.Name=DiracProject_1
     * Dirac1.Speaker.Back.Config=Off
     * Dirac1.Speaker.Back.Frequency=100
     * Dirac1.Speaker.Back.Mode=Stereo
     * Dirac1.Speaker.Center.Config=Off
     * Dirac1.Speaker.Center.Frequency=80
     * Dirac1.Speaker.Front.Config=Large
     * Dirac1.Speaker.Front.Frequency=80
     * Dirac1.Speaker.Sub=Off
     * Dirac1.Speaker.Surround.Config=Small
     * Dirac1.Speaker.Surround.Frequency=50
     * Dirac1.Speaker.User1.Config=Off
     * Dirac1.Speaker.User1.Frequency=80
     * Dirac1.Speaker.User1.Mode=DolbyFront
     * Dirac1.Speaker.User2.Config=Off
     * Dirac1.Speaker.User2.Frequency=80
     * Dirac1.Speaker.User2.Mode=DolbyFront
     * Dirac1.State=EnabledExact
     * Dirac2.Distance.BackLeft=0.0
     * Dirac2.Distance.BackRight=0.0
     * Dirac2.Distance.Center=0.0
     * Dirac2.Distance.Left=0.0
     * Dirac2.Distance.Right=1.2
     * Dirac2.Distance.Sub=0.0
     * Dirac2.Distance.SurroundLeft=5.7
     * Dirac2.Distance.SurroundRight=6.7
     * Dirac2.Distance.UOM=ms
     * Dirac2.Distance.User1Left=0.0
     * Dirac2.Distance.User1Right=0.0
     * Dirac2.Distance.User2Left=0.0
     * Dirac2.Distance.User2Right=0.0
     * Dirac2.EnhancedBass=Off
     * Dirac2.Level.BackLeft=0
     * Dirac2.Level.BackRight=0
     * Dirac2.Level.Center=0
     * Dirac2.Level.Left=3
     * Dirac2.Level.Right=1
     * Dirac2.Level.Sub=0
     * Dirac2.Level.SurroundLeft=-4
     * Dirac2.Level.SurroundRight=-4
     * Dirac2.Level.User1Left=0
     * Dirac2.Level.User1Right=0
     * Dirac2.Level.User2Left=0
     * Dirac2.Level.User2Right=0
     * Dirac2.Name=DiracProject_2
     * Dirac2.Speaker.Back.Config=Off
     * Dirac2.Speaker.Back.Frequency=100
     * Dirac2.Speaker.Back.Mode=Stereo
     * Dirac2.Speaker.Center.Config=Off
     * Dirac2.Speaker.Center.Frequency=80
     * Dirac2.Speaker.Front.Config=Large
     * Dirac2.Speaker.Front.Frequency=80
     * Dirac2.Speaker.Sub=Off
     * Dirac2.Speaker.Surround.Config=Small
     * Dirac2.Speaker.Surround.Frequency=50
     * Dirac2.Speaker.User1.Config=Off
     * Dirac2.Speaker.User1.Frequency=80
     * Dirac2.Speaker.User1.Mode=DolbyFront
     * Dirac2.Speaker.User2.Config=Off
     * Dirac2.Speaker.User2.Frequency=80
     * Dirac2.Speaker.User2.Mode=DolbyFront
     * Dirac2.State=EnabledExact
     * Dirac3.Distance.BackLeft=0.0
     * Dirac3.Distance.BackRight=0.0
     * Dirac3.Distance.Center=0.0
     * Dirac3.Distance.Left=0.0
     * Dirac3.Distance.Right=0.0
     * Dirac3.Distance.Sub=0.0
     * Dirac3.Distance.SurroundLeft=5.9
     * Dirac3.Distance.SurroundRight=5.7
     * Dirac3.Distance.UOM=ms
     * Dirac3.Distance.User1Left=0.0
     * Dirac3.Distance.User1Right=0.0
     * Dirac3.Distance.User2Left=0.0
     * Dirac3.Distance.User2Right=0.0
     * Dirac3.EnhancedBass=Off
     * Dirac3.Level.BackLeft=0
     * Dirac3.Level.BackRight=0
     * Dirac3.Level.Center=0
     * Dirac3.Level.Left=3
     * Dirac3.Level.Right=1
     * Dirac3.Level.Sub=0
     * Dirac3.Level.SurroundLeft=-3
     * Dirac3.Level.SurroundRight=-3
     * Dirac3.Level.User1Left=0
     * Dirac3.Level.User1Right=0
     * Dirac3.Level.User2Left=0
     * Dirac3.Level.User2Right=0
     * Dirac3.Name=DractLive2_Dec18
     * Dirac3.Speaker.Back.Config=Off
     * Dirac3.Speaker.Back.Frequency=100
     * Dirac3.Speaker.Back.Mode=Stereo
     * Dirac3.Speaker.Center.Config=Off
     * Dirac3.Speaker.Center.Frequency=80
     * Dirac3.Speaker.Front.Config=Large
     * Dirac3.Speaker.Front.Frequency=80
     * Dirac3.Speaker.Sub=Off
     * Dirac3.Speaker.Surround.Config=Small
     * Dirac3.Speaker.Surround.Frequency=50
     * Dirac3.Speaker.User1.Config=Off
     * Dirac3.Speaker.User1.Frequency=80
     * Dirac3.Speaker.User1.Mode=DolbyFront
     * Dirac3.Speaker.User2.Config=Off
     * Dirac3.Speaker.User2.Frequency=80
     * Dirac3.Speaker.User2.Mode=DolbyFront
     * Dirac3.State=EnabledExact
     * Internal.Audyssey.Distance.Restore=No
     * Internal.Audyssey.Level.Restore=No
     * Internal.Audyssey.Speaker.Restore=No
     * Internal.Preset.Index=1
     * Internal.Source.Index=1
     * Internal.Upgrade.DisplayStatus=
     * Internal.Upgrade.Status=NotAvailable
     */

    MainAction("Main.Action"), // =MenuClose
    MainAmpBack("Main.Amp.Back"), // =Back
    MainAudioCODEC("Main.Audio.CODEC"), // =PCM
    MainAudioChannels("Main.Audio.Channels"), // =2/0.0
    MainAudioLock("Main.Audio.Lock"), // =No
    MainAudioRate("Main.Audio.Rate"), // =44.1
    MainAudyssey("Main.Audyssey"), // =Off
    MainAudysseyADV("Main.Audyssey.ADV"), // =Off
    MainAudysseyDEQ("Main.Audyssey.DEQ"), // =Off
    MainAudysseyOffset("Main.Audyssey.Offset"), // =0
    MainAutoStandby("Main.AutoStandby"), // =On
    MainBass("Main.Bass"), // =8
    MainBuild("Main.Build"), // =T758_PG536M_NONE

    /*
     * Main.CEC.ARC=Off
     * Main.CEC.Audio=On
     * Main.CEC.Power=Off
     * Main.CEC.Switch=Off
     * Main.ControlStandby=On
     * Main.DTS.CenterGain=0.5
     * Main.DTS.DRC=100
     * Main.Dimmer=On
     * Main.Dirac=0
     * Main.Distance.BackLeft=0
     * Main.Distance.BackRight=0
     * Main.Distance.Center=0
     * Main.Distance.Left=17
     * Main.Distance.Right=17
     * Main.Distance.Sub=0
     * Main.Distance.SurroundLeft=5
     * Main.Distance.SurroundRight=5
     * Main.Distance.UOM=Meters
     * Main.Distance.User1Left=0
     * Main.Distance.User1Right=0
     * Main.Distance.User2Left=0
     * Main.Distance.User2Right=0
     * Main.Dolby.CenterSpread=On
     * Main.Dolby.CenterWidth=3
     * Main.Dolby.DRC=Auto
     * Main.Dolby.Dimension=0
     * Main.Dolby.Panorama=Off
     * Main.EnhancedBass=Off
     * Main.EnhancedStereo.Back=On
     * Main.EnhancedStereo.Center=On
     * Main.EnhancedStereo.Front=On
     * Main.EnhancedStereo.Surround=On
     * Main.EnhancedStereo.User1=On
     * Main.EnhancedStereo.User2=On
     * Main.IR.Channel=0
     * Main.Language=English
     * Main.Level.BackLeft=0
     * Main.Level.BackRight=0
     * Main.Level.Center=0
     * Main.Level.Left=8
     * Main.Level.Right=8
     * Main.Level.Sub=0
     * Main.Level.SurroundLeft=-12
     * Main.Level.SurroundRight=-12
     * Main.Level.User1Left=0
     * Main.Level.User1Right=0
     * Main.Level.User2Left=0
     * Main.Level.User2Right=0
     * Main.LipSyncDelay=0
     * Main.ListeningMode=None
     * Main.ListeningMode.Analog=None
     * Main.ListeningMode.DTS.Stereo=NEO6Music
     * Main.ListeningMode.DTS.Surround=NEO6Cinema
     * Main.ListeningMode.Dolby.Stereo=DolbySurround
     * Main.ListeningMode.Dolby.Surround=DolbySurround
     * Main.ListeningMode.PCM.Stereo=None
     * Main.ListeningMode.PCM.Surround=None
     */

    MainModel("Main.Model"), // =T758
    MainMute("Main.Mute"), // =Off
    MainOSDTempDisplay("Main.OSD.TempDisplay"), // =On
    MainPower("Main.Power"), // =Off
    MainSerial("Main.Serial"), // =A77T75812386
    MainSleep("Main.Sleep"), // =0
    MainSource("Main.Source"), // =4
    /*
     * Main.Speaker.Back.Config=Off
     * Main.Speaker.Back.Frequency=100
     * Main.Speaker.Back.Mode=Stereo
     * Main.Speaker.Center.Config=Off
     * Main.Speaker.Center.Frequency=80
     * Main.Speaker.Front.Config=Large
     * Main.Speaker.Front.Frequency=80
     * Main.Speaker.Sub=Off
     * Main.Speaker.Surround.Config=Small
     * Main.Speaker.Surround.Frequency=50
     * Main.Speaker.User1.Config=Off
     * Main.Speaker.User1.Frequency=80
     * Main.Speaker.User1.Mode=DolbyFront
     * Main.Speaker.User2.Config=Off
     * Main.Speaker.User2.Frequency=80
     * Main.Speaker.User2.Mode=DolbyFront
     * Main.ToneDefeat=On
     * Main.Treble=4
     * Main.Trigger1.Delay=0
     * Main.Trigger1.Out=Main
     * Main.Trim.Center=0
     * Main.Trim.Sub=0
     * Main.Trim.Surround=0
     * Main.VFD.Display=Temp
     * Main.VFD.Line1=MainSource
     * Main.VFD.Line2=AudioCodec
     * Main.VFD.TempLine=2
     * Main.Version=v2.12
     * Main.Video.3D=No
     * Main.Video.ARC=No
     * Main.Video.Bits=
     * Main.Video.Color=
     * Main.Video.HDR=No
     * Main.Video.Lock=No
     * Main.Video.Resolution=
     * Main.VideoMode=NTSC
     */

    MainVolume("Main.Volume"), // =-99

    SourceNUM("Source#"),
    SourceNUMAnalogAudioFormat("Source#.AnalogAudioFormat"), // =Off
    SourceNUMAnalogAudioInput("Source#.AnalogAudioInput"), // =5
    SourceNUMAnalogGain("Source#.AnalogGain"), // =0
    SourceNUMDigitalAudioFormat("Source#.DigitalAudioFormat"), // =Optical
    SourceNUMDigitalAudioInput("Source#.DigitalAudioInput"), // =2
    SourceNUMEnabled("Source#.Enabled"), // =Yes
    SourceNUMName("Source#.Name"), // =SmartTV
    SourceNUMPreset("Source#.Preset"), // =0
    SourceNUMTriggerOut("Source#.TriggerOut"), // =0
    SourceNUMVideoFormat("Source#.VideoFormat"), // =Off
    SourceNUMVideoInput("Source#.VideoInput"), // =3

    /*
     * Preset1.Audyssey=Off
     * Preset1.Audyssey.ADV=Off
     * Preset1.Audyssey.DEQ=Off
     * Preset1.Audyssey.Offset=0
     * Preset1.Bass=0
     * Preset1.DTS.CenterGain=0.2
     * Preset1.DTS.DRC=100
     * Preset1.Dimmer=Off
     * Preset1.Dirac=0
     * Preset1.Distance.BackLeft=0
     * Preset1.Distance.BackRight=0
     * Preset1.Distance.Center=0
     * Preset1.Distance.Left=0
     * Preset1.Distance.Right=0
     * Preset1.Distance.Sub=0
     * Preset1.Distance.SurroundLeft=0
     * Preset1.Distance.SurroundRight=0
     * Preset1.Distance.UOM=Feet
     * Preset1.Distance.User1Left=0
     * Preset1.Distance.User1Right=0
     * Preset1.Distance.User2Left=0
     * Preset1.Distance.User2Right=0
     * Preset1.Dolby.CenterSpread=On
     * Preset1.Dolby.CenterWidth=3
     * Preset1.Dolby.DRC=Auto
     * Preset1.Dolby.Dimension=0
     * Preset1.Dolby.Panorama=Off
     * Preset1.EnhancedBass=Off
     * Preset1.EnhancedStereo.Back=On
     * Preset1.EnhancedStereo.Center=On
     * Preset1.EnhancedStereo.Front=On
     * Preset1.EnhancedStereo.Surround=On
     * Preset1.EnhancedStereo.User1=On
     * Preset1.EnhancedStereo.User2=On
     * Preset1.Level.BackLeft=0
     * Preset1.Level.BackRight=0
     * Preset1.Level.Center=0
     * Preset1.Level.Left=0
     * Preset1.Level.Right=0
     * Preset1.Level.Sub=0
     * Preset1.Level.SurroundLeft=0
     * Preset1.Level.SurroundRight=0
     * Preset1.Level.User1Left=0
     * Preset1.Level.User1Right=0
     * Preset1.Level.User2Left=0
     * Preset1.Level.User2Right=0
     * Preset1.LipSyncDelay=0
     * Preset1.ListeningMode=None
     * Preset1.ListeningMode.Analog=None
     * Preset1.ListeningMode.DTS.Stereo=NEO6Music
     * Preset1.ListeningMode.DTS.Surround=NEO6Cinema
     * Preset1.ListeningMode.Dolby.Stereo=PLIIMusic
     * Preset1.ListeningMode.Dolby.Surround=PLIIMovie
     * Preset1.ListeningMode.PCM.Stereo=None
     * Preset1.ListeningMode.PCM.Surround=None
     * Preset1.Name=Preset 1
     * Preset1.OSD.TempDisplay=On
     * Preset1.Setup.DSPOptions=Yes
     * Preset1.Setup.Display=No
     * Preset1.Setup.ListeningMode=Yes
     * Preset1.Setup.PictureControls=No
     * Preset1.Setup.Speaker=No
     * Preset1.Setup.ToneControls=Yes
     * Preset1.Setup.Video=No
     * Preset1.Speaker.Back.Config=Small
     * Preset1.Speaker.Back.Frequency=80
     * Preset1.Speaker.Back.Mode=Stereo
     * Preset1.Speaker.Center.Config=Small
     * Preset1.Speaker.Center.Frequency=80
     * Preset1.Speaker.Front.Config=Small
     * Preset1.Speaker.Front.Frequency=80
     * Preset1.Speaker.Sub=On
     * Preset1.Speaker.Surround.Config=Small
     * Preset1.Speaker.Surround.Frequency=80
     * Preset1.Speaker.User1.Config=Off
     * Preset1.Speaker.User1.Frequency=80
     * Preset1.Speaker.User1.Mode=DolbyFront
     * Preset1.Speaker.User2.Config=Off
     * Preset1.Speaker.User2.Frequency=80
     * Preset1.Speaker.User2.Mode=DolbyFront
     * Preset1.ToneDefeat=Off
     * Preset1.Treble=0
     * Preset1.VFD.Display=On
     * Preset1.VFD.Line1=MainSource
     * Preset1.VFD.Line2=AudioCodec
     * Preset1.VFD.TempLine=2
     * Preset2.Audyssey=Off
     * Preset2.Audyssey.ADV=Off
     * Preset2.Audyssey.DEQ=Off
     * Preset2.Audyssey.Offset=0
     * Preset2.Bass=0
     * Preset2.DTS.CenterGain=0.2
     * Preset2.DTS.DRC=100
     * Preset2.Dimmer=Off
     * Preset2.Dirac=0
     * Preset2.Distance.BackLeft=0
     * Preset2.Distance.BackRight=0
     * Preset2.Distance.Center=0
     * Preset2.Distance.Left=0
     * Preset2.Distance.Right=0
     * Preset2.Distance.Sub=0
     * Preset2.Distance.SurroundLeft=0
     * Preset2.Distance.SurroundRight=0
     * Preset2.Distance.UOM=Feet
     * Preset2.Distance.User1Left=0
     * Preset2.Distance.User1Right=0
     * Preset2.Distance.User2Left=0
     * Preset2.Distance.User2Right=0
     * Preset2.Dolby.CenterSpread=On
     * Preset2.Dolby.CenterWidth=3
     * Preset2.Dolby.DRC=Auto
     * Preset2.Dolby.Dimension=0
     * Preset2.Dolby.Panorama=Off
     * Preset2.EnhancedBass=Off
     * Preset2.EnhancedStereo.Back=On
     * Preset2.EnhancedStereo.Center=On
     * Preset2.EnhancedStereo.Front=On
     * Preset2.EnhancedStereo.Surround=On
     * Preset2.EnhancedStereo.User1=On
     * Preset2.EnhancedStereo.User2=On
     * Preset2.Level.BackLeft=0
     * Preset2.Level.BackRight=0
     * Preset2.Level.Center=0
     * Preset2.Level.Left=0
     * Preset2.Level.Right=0
     * Preset2.Level.Sub=0
     * Preset2.Level.SurroundLeft=0
     * Preset2.Level.SurroundRight=0
     * Preset2.Level.User1Left=0
     * Preset2.Level.User1Right=0
     * Preset2.Level.User2Left=0
     * Preset2.Level.User2Right=0
     * Preset2.LipSyncDelay=0
     * Preset2.ListeningMode=None
     * Preset2.ListeningMode.Analog=None
     * Preset2.ListeningMode.DTS.Stereo=NEO6Music
     * Preset2.ListeningMode.DTS.Surround=NEO6Cinema
     * Preset2.ListeningMode.Dolby.Stereo=PLIIMusic
     * Preset2.ListeningMode.Dolby.Surround=PLIIMovie
     * Preset2.ListeningMode.PCM.Stereo=None
     * Preset2.ListeningMode.PCM.Surround=None
     * Preset2.Name=Preset 2
     * Preset2.OSD.TempDisplay=On
     * Preset2.Setup.DSPOptions=Yes
     * Preset2.Setup.Display=No
     * Preset2.Setup.ListeningMode=Yes
     * Preset2.Setup.PictureControls=No
     * Preset2.Setup.Speaker=No
     * Preset2.Setup.ToneControls=Yes
     * Preset2.Setup.Video=No
     * Preset2.Speaker.Back.Config=Small
     * Preset2.Speaker.Back.Frequency=80
     * Preset2.Speaker.Back.Mode=Stereo
     * Preset2.Speaker.Center.Config=Small
     * Preset2.Speaker.Center.Frequency=80
     * Preset2.Speaker.Front.Config=Small
     * Preset2.Speaker.Front.Frequency=80
     * Preset2.Speaker.Sub=On
     * Preset2.Speaker.Surround.Config=Small
     * Preset2.Speaker.Surround.Frequency=80
     * Preset2.Speaker.User1.Config=Off
     * Preset2.Speaker.User1.Frequency=80
     * Preset2.Speaker.User1.Mode=DolbyFront
     * Preset2.Speaker.User2.Config=Off
     * Preset2.Speaker.User2.Frequency=80
     * Preset2.Speaker.User2.Mode=DolbyFront
     * Preset2.ToneDefeat=Off
     * Preset2.Treble=0
     * Preset2.VFD.Display=On
     * Preset2.VFD.Line1=MainSource
     * Preset2.VFD.Line2=AudioCodec
     * Preset2.VFD.TempLine=2
     * Preset3.Audyssey=Off
     * Preset3.Audyssey.ADV=Off
     * Preset3.Audyssey.DEQ=Off
     * Preset3.Audyssey.Offset=0
     * Preset3.Bass=0
     * Preset3.DTS.CenterGain=0.2
     * Preset3.DTS.DRC=100
     * Preset3.Dimmer=Off
     * Preset3.Dirac=0
     * Preset3.Distance.BackLeft=0
     * Preset3.Distance.BackRight=0
     * Preset3.Distance.Center=0
     * Preset3.Distance.Left=0
     * Preset3.Distance.Right=0
     * Preset3.Distance.Sub=0
     * Preset3.Distance.SurroundLeft=0
     * Preset3.Distance.SurroundRight=0
     * Preset3.Distance.UOM=Feet
     * Preset3.Distance.User1Left=0
     * Preset3.Distance.User1Right=0
     * Preset3.Distance.User2Left=0
     * Preset3.Distance.User2Right=0
     * Preset3.Dolby.CenterSpread=On
     * Preset3.Dolby.CenterWidth=3
     * Preset3.Dolby.DRC=Auto
     * Preset3.Dolby.Dimension=0
     * Preset3.Dolby.Panorama=Off
     * Preset3.EnhancedBass=Off
     * Preset3.EnhancedStereo.Back=On
     * Preset3.EnhancedStereo.Center=On
     * Preset3.EnhancedStereo.Front=On
     * Preset3.EnhancedStereo.Surround=On
     * Preset3.EnhancedStereo.User1=On
     * Preset3.EnhancedStereo.User2=On
     * Preset3.Level.BackLeft=0
     * Preset3.Level.BackRight=0
     * Preset3.Level.Center=0
     * Preset3.Level.Left=0
     * Preset3.Level.Right=0
     * Preset3.Level.Sub=0
     * Preset3.Level.SurroundLeft=0
     * Preset3.Level.SurroundRight=0
     * Preset3.Level.User1Left=0
     * Preset3.Level.User1Right=0
     * Preset3.Level.User2Left=0
     * Preset3.Level.User2Right=0
     * Preset3.LipSyncDelay=0
     * Preset3.ListeningMode=None
     * Preset3.ListeningMode.Analog=None
     * Preset3.ListeningMode.DTS.Stereo=NEO6Music
     * Preset3.ListeningMode.DTS.Surround=NEO6Cinema
     * Preset3.ListeningMode.Dolby.Stereo=PLIIMusic
     * Preset3.ListeningMode.Dolby.Surround=PLIIMovie
     * Preset3.ListeningMode.PCM.Stereo=None
     * Preset3.ListeningMode.PCM.Surround=None
     * Preset3.Name=Preset 3
     * Preset3.OSD.TempDisplay=On
     * Preset3.Setup.DSPOptions=Yes
     * Preset3.Setup.Display=No
     * Preset3.Setup.ListeningMode=Yes
     * Preset3.Setup.PictureControls=No
     * Preset3.Setup.Speaker=No
     * Preset3.Setup.ToneControls=Yes
     * Preset3.Setup.Video=No
     * Preset3.Speaker.Back.Config=Small
     * Preset3.Speaker.Back.Frequency=80
     * Preset3.Speaker.Back.Mode=Stereo
     * Preset3.Speaker.Center.Config=Small
     * Preset3.Speaker.Center.Frequency=80
     * Preset3.Speaker.Front.Config=Small
     * Preset3.Speaker.Front.Frequency=80
     * Preset3.Speaker.Sub=On
     * Preset3.Speaker.Surround.Config=Small
     * Preset3.Speaker.Surround.Frequency=80
     * Preset3.Speaker.User1.Config=Off
     * Preset3.Speaker.User1.Frequency=80
     * Preset3.Speaker.User1.Mode=DolbyFront
     * Preset3.Speaker.User2.Config=Off
     * Preset3.Speaker.User2.Frequency=80
     * Preset3.Speaker.User2.Mode=DolbyFront
     * Preset3.ToneDefeat=Off
     * Preset3.Treble=0
     * Preset3.VFD.Display=On
     * Preset3.VFD.Line1=MainSource
     * Preset3.VFD.Line2=AudioCodec
     * Preset3.VFD.TempLine=2
     * Preset4.Audyssey=Off
     * Preset4.Audyssey.ADV=Off
     * Preset4.Audyssey.DEQ=Off
     * Preset4.Audyssey.Offset=0
     * Preset4.Bass=0
     * Preset4.DTS.CenterGain=0.2
     * Preset4.DTS.DRC=100
     * Preset4.Dimmer=Off
     * Preset4.Dirac=0
     * Preset4.Distance.BackLeft=0
     * Preset4.Distance.BackRight=0
     * Preset4.Distance.Center=0
     * Preset4.Distance.Left=0
     * Preset4.Distance.Right=0
     * Preset4.Distance.Sub=0
     * Preset4.Distance.SurroundLeft=0
     * Preset4.Distance.SurroundRight=0
     * Preset4.Distance.UOM=Feet
     * Preset4.Distance.User1Left=0
     * Preset4.Distance.User1Right=0
     * Preset4.Distance.User2Left=0
     * Preset4.Distance.User2Right=0
     * Preset4.Dolby.CenterSpread=On
     * Preset4.Dolby.CenterWidth=3
     * Preset4.Dolby.DRC=Auto
     * Preset4.Dolby.Dimension=0
     * Preset4.Dolby.Panorama=Off
     * Preset4.EnhancedBass=Off
     * Preset4.EnhancedStereo.Back=On
     * Preset4.EnhancedStereo.Center=On
     * Preset4.EnhancedStereo.Front=On
     * Preset4.EnhancedStereo.Surround=On
     * Preset4.EnhancedStereo.User1=On
     * Preset4.EnhancedStereo.User2=On
     * Preset4.Level.BackLeft=0
     * Preset4.Level.BackRight=0
     * Preset4.Level.Center=0
     * Preset4.Level.Left=0
     * Preset4.Level.Right=0
     * Preset4.Level.Sub=0
     * Preset4.Level.SurroundLeft=0
     * Preset4.Level.SurroundRight=0
     * Preset4.Level.User1Left=0
     * Preset4.Level.User1Right=0
     * Preset4.Level.User2Left=0
     * Preset4.Level.User2Right=0
     * Preset4.LipSyncDelay=0
     * Preset4.ListeningMode=None
     * Preset4.ListeningMode.Analog=None
     * Preset4.ListeningMode.DTS.Stereo=NEO6Music
     * Preset4.ListeningMode.DTS.Surround=NEO6Cinema
     * Preset4.ListeningMode.Dolby.Stereo=PLIIMusic
     * Preset4.ListeningMode.Dolby.Surround=PLIIMovie
     * Preset4.ListeningMode.PCM.Stereo=None
     * Preset4.ListeningMode.PCM.Surround=None
     * Preset4.Name=Preset 4
     * Preset4.OSD.TempDisplay=On
     * Preset4.Setup.DSPOptions=Yes
     * Preset4.Setup.Display=No
     * Preset4.Setup.ListeningMode=Yes
     * Preset4.Setup.PictureControls=No
     * Preset4.Setup.Speaker=No
     * Preset4.Setup.ToneControls=Yes
     * Preset4.Setup.Video=No
     * Preset4.Speaker.Back.Config=Small
     * Preset4.Speaker.Back.Frequency=80
     * Preset4.Speaker.Back.Mode=Stereo
     * Preset4.Speaker.Center.Config=Small
     * Preset4.Speaker.Center.Frequency=80
     * Preset4.Speaker.Front.Config=Small
     * Preset4.Speaker.Front.Frequency=80
     * Preset4.Speaker.Sub=On
     * Preset4.Speaker.Surround.Config=Small
     * Preset4.Speaker.Surround.Frequency=80
     * Preset4.Speaker.User1.Config=Off
     * Preset4.Speaker.User1.Frequency=80
     * Preset4.Speaker.User1.Mode=DolbyFront
     * Preset4.Speaker.User2.Config=Off
     * Preset4.Speaker.User2.Frequency=80
     * Preset4.Speaker.User2.Mode=DolbyFront
     * Preset4.ToneDefeat=Off
     * Preset4.Treble=0
     * Preset4.VFD.Display=On
     * Preset4.VFD.Line1=MainSource
     * Preset4.VFD.Line2=AudioCodec
     * Preset4.VFD.TempLine=2
     * Preset5.Audyssey=Off
     * Preset5.Audyssey.ADV=Off
     * Preset5.Audyssey.DEQ=Off
     * Preset5.Audyssey.Offset=0
     * Preset5.Bass=0
     * Preset5.DTS.CenterGain=0.2
     * Preset5.DTS.DRC=100
     * Preset5.Dimmer=Off
     * Preset5.Dirac=0
     * Preset5.Distance.BackLeft=0
     * Preset5.Distance.BackRight=0
     * Preset5.Distance.Center=0
     * Preset5.Distance.Left=0
     * Preset5.Distance.Right=0
     * Preset5.Distance.Sub=0
     * Preset5.Distance.SurroundLeft=0
     * Preset5.Distance.SurroundRight=0
     * Preset5.Distance.UOM=Feet
     * Preset5.Distance.User1Left=0
     * Preset5.Distance.User1Right=0
     * Preset5.Distance.User2Left=0
     * Preset5.Distance.User2Right=0
     * Preset5.Dolby.CenterSpread=On
     * Preset5.Dolby.CenterWidth=3
     * Preset5.Dolby.DRC=Auto
     * Preset5.Dolby.Dimension=0
     * Preset5.Dolby.Panorama=Off
     * Preset5.EnhancedBass=Off
     * Preset5.EnhancedStereo.Back=On
     * Preset5.EnhancedStereo.Center=On
     * Preset5.EnhancedStereo.Front=On
     * Preset5.EnhancedStereo.Surround=On
     * Preset5.EnhancedStereo.User1=On
     * Preset5.EnhancedStereo.User2=On
     * Preset5.Level.BackLeft=0
     * Preset5.Level.BackRight=0
     * Preset5.Level.Center=0
     * Preset5.Level.Left=0
     * Preset5.Level.Right=0
     * Preset5.Level.Sub=0
     * Preset5.Level.SurroundLeft=0
     * Preset5.Level.SurroundRight=0
     * Preset5.Level.User1Left=0
     * Preset5.Level.User1Right=0
     * Preset5.Level.User2Left=0
     * Preset5.Level.User2Right=0
     * Preset5.LipSyncDelay=0
     * Preset5.ListeningMode=None
     * Preset5.ListeningMode.Analog=None
     * Preset5.ListeningMode.DTS.Stereo=NEO6Music
     * Preset5.ListeningMode.DTS.Surround=NEO6Cinema
     * Preset5.ListeningMode.Dolby.Stereo=PLIIMusic
     * Preset5.ListeningMode.Dolby.Surround=PLIIMovie
     * Preset5.ListeningMode.PCM.Stereo=None
     * Preset5.ListeningMode.PCM.Surround=None
     * Preset5.Name=Preset 5
     * Preset5.OSD.TempDisplay=On
     * Preset5.Setup.DSPOptions=Yes
     * Preset5.Setup.Display=No
     * Preset5.Setup.ListeningMode=Yes
     * Preset5.Setup.PictureControls=No
     * Preset5.Setup.Speaker=No
     * Preset5.Setup.ToneControls=Yes
     * Preset5.Setup.Video=No
     * Preset5.Speaker.Back.Config=Small
     * Preset5.Speaker.Back.Frequency=80
     * Preset5.Speaker.Back.Mode=Stereo
     * Preset5.Speaker.Center.Config=Small
     * Preset5.Speaker.Center.Frequency=80
     * Preset5.Speaker.Front.Config=Small
     * Preset5.Speaker.Front.Frequency=80
     * Preset5.Speaker.Sub=On
     * Preset5.Speaker.Surround.Config=Small
     * Preset5.Speaker.Surround.Frequency=80
     * Preset5.Speaker.User1.Config=Off
     * Preset5.Speaker.User1.Frequency=80
     * Preset5.Speaker.User1.Mode=DolbyFront
     * Preset5.Speaker.User2.Config=Off
     * Preset5.Speaker.User2.Frequency=80
     * Preset5.Speaker.User2.Mode=DolbyFront
     * Preset5.ToneDefeat=Off
     * Preset5.Treble=0
     * Preset5.VFD.Display=On
     * Preset5.VFD.Line1=MainSource
     * Preset5.VFD.Line2=AudioCodec
     * Preset5.VFD.TempLine=2
     * Source1.AnalogAudioFormat=Off
     * Source1.AnalogAudioInput=1
     * Source1.AnalogGain=0
     * Source1.DigitalAudioFormat=Optical
     * Source1.DigitalAudioInput=1
     * Source1.Enabled=Yes
     * Source1.Name=SwisscomTV
     * Source1.Preset=0
     * Source1.TriggerOut=0
     * Source1.VideoFormat=HDMI
     * Source1.VideoInput=1
     * Source10.AnalogAudioFormat=Stereo
     * Source10.AnalogAudioInput=6
     * Source10.AnalogGain=0
     * Source10.DigitalAudioFormat=Off
     * Source10.DigitalAudioInput=1
     * Source10.Enabled=No
     * Source10.Name=Tuner
     * Source10.Preset=0
     * Source10.TriggerOut=0
     * Source10.VideoFormat=Off
     * Source10.VideoInput=1
     * Source11.Name=Local
     * Source2.AnalogAudioFormat=Off
     * Source2.AnalogAudioInput=5
     * Source2.AnalogGain=0
     * Source2.DigitalAudioFormat=Optical
     * Source2.DigitalAudioInput=2
     * Source2.Enabled=Yes
     * Source2.Name=SmartTV
     * Source2.Preset=0
     * Source2.TriggerOut=0
     * Source2.VideoFormat=Off
     * Source2.VideoInput=3
     * Source3.AnalogAudioFormat=Off
     * Source3.AnalogAudioInput=5
     * Source3.AnalogGain=0
     * Source3.DigitalAudioFormat=HDMI
     * Source3.DigitalAudioInput=2
     * Source3.Enabled=Yes
     * Source3.Name=Bluray
     * Source3.Preset=0
     * Source3.TriggerOut=0
     * Source3.VideoFormat=HDMI
     * Source3.VideoInput=2
     * Source4.AnalogAudioFormat=Off
     * Source4.AnalogAudioInput=1
     * Source4.AnalogGain=0
     * Source4.DigitalAudioFormat=Coaxial
     * Source4.DigitalAudioInput=1
     * Source4.Enabled=Yes
     * Source4.Name=CD
     * Source4.Preset=0
     * Source4.TriggerOut=0
     * Source4.VideoFormat=Off
     * Source4.VideoInput=1
     * Source5.AnalogAudioFormat=Off
     * Source5.AnalogAudioInput=1
     * Source5.AnalogGain=0
     * Source5.DigitalAudioFormat=HDMI
     * Source5.DigitalAudioInput=3
     * Source5.Enabled=No
     * Source5.Name=PS3
     * Source5.Preset=0
     * Source5.TriggerOut=0
     * Source5.VideoFormat=HDMI
     * Source5.VideoInput=3
     * Source6.AnalogAudioFormat=Off
     * Source6.AnalogAudioInput=1
     * Source6.AnalogGain=0
     * Source6.DigitalAudioFormat=BluOS
     * Source6.DigitalAudioInput=1
     * Source6.Enabled=Yes
     * Source6.Name=BluOS
     * Source6.Preset=0
     * Source6.TriggerOut=0
     * Source6.VideoFormat=BluOS
     * Source6.VideoInput=1
     * Source7.AnalogAudioFormat=Off
     * Source7.AnalogAudioInput=1
     * Source7.AnalogGain=0
     * Source7.DigitalAudioFormat=Optical
     * Source7.DigitalAudioInput=1
     * Source7.Enabled=Yes
     * Source7.Name=ChromeCV
     * Source7.Preset=0
     * Source7.TriggerOut=0
     * Source7.VideoFormat=Previous
     * Source7.VideoInput=3
     * Source8.AnalogAudioFormat=Stereo
     * Source8.AnalogAudioInput=4
     * Source8.AnalogGain=0
     * Source8.DigitalAudioFormat=Optical
     * Source8.DigitalAudioInput=3
     * Source8.Enabled=No
     * Source8.Name=Front Input
     * Source8.Preset=0
     * Source8.TriggerOut=0
     * Source8.VideoFormat=Off
     * Source8.VideoInput=8
     * Source9.AnalogAudioFormat=Stereo
     * Source9.AnalogAudioInput=5
     * Source9.AnalogGain=0
     * Source9.DigitalAudioFormat=Off
     * Source9.DigitalAudioInput=1
     * Source9.Enabled=No
     * Source9.Name=Media Player
     * Source9.Preset=0
     * Source9.TriggerOut=0
     * Source9.VideoFormat=Off
     * Source9.VideoInput=1
     * Video.Config=30100001
     * Video.Version=v1.09
     */
    ZoneNUM("Zone#"),
    ZoneNUMMute("Zone#.Mute"), // =On
    ZoneNUMPower("Zone#.Power"), // =Off
    ZoneNUMSource("Zone#.Source"), // =11
    ZoneNUMVolume("Zone#.Volume"), // =0
    ZoneNUMVolumeControl("Zone2.VolumeControl"), // =Fixed
    ZoneNUMVolumeFixed("Zone2.VolumeFixed"); // =0

    private final String command;

    private NadReceiverCommandType(String command) {
        this.command = command;
    }

    public static NadReceiverCommandType fromString(String text) {
        if (text == null) {
            new IllegalArgumentException("text cannot be null");
        }
        String genericText = null;

        if (text != null && text.matches(".*\\d+.*")) {
            String extractedValue = text.replaceAll("\\D+", "");
            genericText = text.replace(extractedValue, "#");
        } else {
            genericText = text;
        }

        for (NadReceiverCommandType t : NadReceiverCommandType.values()) {
            if (t.toString().equalsIgnoreCase(genericText)) {
                return t;
            }
        }

        throw new IllegalArgumentException("No NadReceiverCommandType found from text: " + text);
    }

    /**
     *
     */
    @Override
    public String toString() {
        return this.command;
    }
}
