<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.openhab.addons.bundles</groupId>
    <artifactId>org.openhab.addons.reactor.bundles</artifactId>
    <version>5.3.0-SNAPSHOT</version>
  </parent>

  <artifactId>org.openhab.automation.jrubyscripting</artifactId>
  <name>openHAB Add-ons :: Bundles :: Automation :: JRuby Scripting</name>

  <properties>
    <jruby.version>10.1.1.0</jruby.version>

    <bnd.importpackage><![CDATA[org.crac;resolution:=optional,\
  com.dylibso.chicory.annotations;resolution:=optional,\
  org.joda.convert;resolution:=optional,\
  com.sun.nio.*;resolution:=optional,\
  com.sun.security.*;resolution:=optional,\
  org.apache.tools.ant.*;resolution:=optional,\
  org.bouncycastle.*;resolution:=optional,\
  sun.management.*;resolution:=optional,\
  sun.nio.*;resolution:=optional,\
  android.os;resolution:=optional,\
  jakarta.annotation;resolution:=optional,\
  jdk.crac.management;resolution:=optional]]></bnd.importpackage>

  </properties>

  <dependencies>
    <dependency>
      <groupId>org.jruby</groupId>
      <artifactId>jruby</artifactId>
      <version>${jruby.version}</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>embed-dependencies</id>
            <configuration>
              <!-- jruby isn't a flat jar. We want its transitive dependencies -->
              <excludeTransitive>false</excludeTransitive>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>
