

const locationSemantic = ["Apartment",
    "Attic",
    "Basement",
    "Bathroom",
    "Bedroom",
    "BoilerRoom",
    "Building",
    "Carport",
    "Cellar",
    "Corridor",
    "DiningRoom",
    "Driveway",
    "Entry",
    "FamilyRoom",
    "FirstFloor",
    "Floor",
    "Garage",
    "Garden",
    "GroundFloor",
    "GuestRoom",
    "House",
    "Indoor",
    "Kitchen",
    "LaundryRoom",
    "LivingRoom",
    "Location",
    "Office",
    "Outdoor",
    "Patio",
    "Porch",
    "Room",
    "SecondFloor",
    "Shed",
    "SummerHouse",
    "Terrace",
    "ThirdFloor",
    "Veranda",];

const equipmentSemantic = [
    "AlarmSystem",
    "BackDoor",
    "Battery",
    "Blinds",
    "Boiler",
    "Camera",
    "Car",
    "CeilingFan",
    "CellarDoor",
    "CleaningRobot",
    "Dishwasher",
    "Door",
    "Doorbell",
    "Dryer",
    "Equipment",
    "Fan",
    "Freezer",
    "FrontDoor",
    "GarageDoor",
    "Gate",
    "HVAC",
    "InnerDoor",
    "Inverter",
    "KitchenHood",
    "LawnMower",
    "Lightbulb",
    "LightStripe",
    "Lock",
    "MotionDetector",
    "NetworkAppliance",
    "Oven",
    "PowerOutlet",
    "Projector",
    "Pump",
    "RadiatorControl",
    "Receiver",
    "Refrigerator",
    "RemoteControl",
    "Screen",
    "Sensor",
    "SideDoor",
    "Siren",
    "Smartphone",
    "SmokeDetector",
    "Speaker",
    "Television",
    "Valve",
    "VoiceAssistant",
    "WallSwitch",
    "WashingMachine",
    "WeatherService",
    "WebService",
    "WhiteGood",
    "Window",
];

const pointSemantic = [
    "Alarm",
    "Control",
    "LowBattery",
    "Measurement",
    "OpenLevel",
    "OpenState",
    "Point",
    "Setpoint",
    "Status",
    "Switch",
    "Tampered",
    "Tilt",
];


export const Semantics = {
    Location: locationSemantic,
    Equipment: equipmentSemantic,
    Point: pointSemantic
};
export const ItemTypes = [
    "Call",
    "Color",
    "Contact",
    "DateTime",
    "Dimmer",
    "Image",
    "Location",
    "Number",
    "Player",
    "Rollershutter",
    "String",
    "Switch",
    "Group",
];