/*
 * Copyright (c) 2010-2025 Contributors to the openHAB project
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */
package org.openhab.binding.matter.internal.util;

import java.util.Map;

import org.eclipse.jdt.annotation.NonNullByDefault;

/**
 * Utility class for the vendor IDs for Matter devices.
 * 
 * @author Dan Cunningham - Initial contribution
 */
@NonNullByDefault
public class MatterVendorIDs {

    /**
     * This list generated from https://github.com/ioBroker/ioBroker.matter/blob/main/src-admin/src/utils/vendorIDs.ts
     */
    public static final Map<Integer, String> VENDOR_IDS = Map.ofEntries(Map.entry(0x0005, "Freescale (RF4CE)"),
            Map.entry(0x0006, "Oki Semiconductors (RF4CE)"), Map.entry(0x0007, "Texas Instruments"),
            Map.entry(0x1000, "Cirronet"), Map.entry(0x1001, "Chipcon"), Map.entry(0x1002, "Ember"),
            Map.entry(0x1003, "NTS"), Map.entry(0x1004, "Freescale"), Map.entry(0x1005, "IP Com"),
            Map.entry(0x1006, "San Juan Software"), Map.entry(0x1007, "TUV"), Map.entry(0x1008, "Integration"),
            Map.entry(0x1009, "BM SpA"), Map.entry(0x100a, "AwarePoint"), Map.entry(0x100b, "Signify Netherlands B.V."),
            Map.entry(0x100c, "Luxoft"), Map.entry(0x100d, "Korwin"), Map.entry(0x100e, "One RF Technology"),
            Map.entry(0x100f, "Software Technologies Group"), Map.entry(0x1010, "Telegesis"),
            Map.entry(0x1011, "Visonic"), Map.entry(0x1012, "Insta"), Map.entry(0x1013, "Atalum"),
            Map.entry(0x1014, "Atmel"), Map.entry(0x1015, "Develco"), Map.entry(0x1016, "Honeywell"),
            Map.entry(0x1017, "RadioPulse"), Map.entry(0x1018, "Renesas"), Map.entry(0x1019, "Xanadu Wireless"),
            Map.entry(0x101a, "NEC Engineering"), Map.entry(0x101b, "Yamatake Corporation"),
            Map.entry(0x101c, "Tendril Networks"), Map.entry(0x101d, "Assa Abloy"), Map.entry(0x101e, "MaxStream"),
            Map.entry(0x101f, "Neurocom"), Map.entry(0x1020, "Institute for Information Industry"),
            Map.entry(0x1021, "Legrand Group"), Map.entry(0x1022, "iControl"), Map.entry(0x1023, "Raymarine"),
            Map.entry(0x1024, "LS Research"), Map.entry(0x1025, "Onity Inc."), Map.entry(0x1026, "Mono Products"),
            Map.entry(0x1027, "RF Technologies"), Map.entry(0x1028, "Itron"), Map.entry(0x1029, "Tritech"),
            Map.entry(0x102a, "Embedit A/S"), Map.entry(0x102b, "S3C"), Map.entry(0x102c, "Siemens"),
            Map.entry(0x102d, "Mindtech"), Map.entry(0x102e, "LG Electronics"),
            Map.entry(0x102f, "Mitsubishi Electric Corp."), Map.entry(0x1030, "Johnson Controls"),
            Map.entry(0x1031, "Secure Meters (UK) Ltd"), Map.entry(0x1032, "Knick"), Map.entry(0x1033, "Viconics"),
            Map.entry(0x1034, "Flexipanel"), Map.entry(0x1035, "Piasim Corporation Pte., Ltd."),
            Map.entry(0x1036, "Trane"), Map.entry(0x1037, "NXP Semiconductors"),
            Map.entry(0x1038, "Living Independently Group"), Map.entry(0x1039, "AlertMe.com"),
            Map.entry(0x103a, "Daintree"), Map.entry(0x103b, "Aiji System"), Map.entry(0x103c, "Telecom Italia"),
            Map.entry(0x103d, "Mikrokrets AS"), Map.entry(0x103e, "Oki Semiconductor"),
            Map.entry(0x103f, "Newport Electonics"), Map.entry(0x1040, "Control 4"),
            Map.entry(0x1041, "STMicroelectronics"), Map.entry(0x1042, "Ad-Sol Nissin Corp"), Map.entry(0x1043, "DCSI"),
            Map.entry(0x1044, "France Telecom"), Map.entry(0x1045, "muNet"), Map.entry(0x1046, "Autani Corporation"),
            Map.entry(0x1047, "Colorado vNet"), Map.entry(0x1048, "Aerocomm, Inc."),
            Map.entry(0x1049, "Silicon Laboratories"), Map.entry(0x104a, "Inncom International Inc."),
            Map.entry(0x104b, "Cooper Power Systems"), Map.entry(0x104c, "Synapse"),
            Map.entry(0x104d, "Fisher Pierce/Sunrise"), Map.entry(0x104e, "CentraLite Systems, Inc."),
            Map.entry(0x104f, "Crane Wireless Monitoring Solutions"), Map.entry(0x1050, "Mobilarm Limited"),
            Map.entry(0x1051, "iMonitor Research Ltd."), Map.entry(0x1052, "Bartech"), Map.entry(0x1053, "MeshNetics"),
            Map.entry(0x1054, "LS Industrial Systems Co. Ltd."), Map.entry(0x1055, "Cason Engineering plc"),
            Map.entry(0x1056, "Wireless Glue Networks Inc."), Map.entry(0x1057, "Elster"),
            Map.entry(0x1058, "SMS Tecnologia Eletr&#xF4;nica"), Map.entry(0x1059, "Onset Computer Corporation"),
            Map.entry(0x105a, "Riga Development"), Map.entry(0x105b, "Energate"), Map.entry(0x105c, "ConMed Linvatec"),
            Map.entry(0x105d, "PowerMand"), Map.entry(0x105e, "Schneider Electric"),
            Map.entry(0x105f, "Eaton Corporation"), Map.entry(0x1060, "Telular Corporation"),
            Map.entry(0x1061, "Delphi Medical Systems"), Map.entry(0x1062, "EpiSensor Limited"),
            Map.entry(0x1063, "Landis+Gyr"), Map.entry(0x1064, "Kaba Group"), Map.entry(0x1065, "Shure Incorporated"),
            Map.entry(0x1066, "Comverge, Inc."), Map.entry(0x1067, "DBS Lodging Technologies, LLC."),
            Map.entry(0x1068, "Energy Aware Technology Inc."), Map.entry(0x1069, "Hidalgo Limited"),
            Map.entry(0x106a, "Air2App"), Map.entry(0x106b, "AMX"), Map.entry(0x106c, "EDMI Pty Ltd"),
            Map.entry(0x106d, "Cyan Ltd"), Map.entry(0x106e, "System SPA"), Map.entry(0x106f, "Telit"),
            Map.entry(0x1070, "Kaga Electronics"), Map.entry(0x1071, "Astrel Group SRL"), Map.entry(0x1072, "Certicom"),
            Map.entry(0x1073, "Gridpoint"), Map.entry(0x1074, "Profile Systems LLC"),
            Map.entry(0x1075, "Compacta International Ltd"), Map.entry(0x1076, "Freestyle Technology Pty Ltd."),
            Map.entry(0x1077, "Alektrona"), Map.entry(0x1078, "Computime"),
            Map.entry(0x1079, "Remote Technologies, Inc."), Map.entry(0x107a, "Wavecom S.A."),
            Map.entry(0x107b, "Energy Optimizers Ltd."), Map.entry(0x107c, "GE"), Map.entry(0x107d, "Jetlun"),
            Map.entry(0x107e, "Cipher Systems"), Map.entry(0x107f, "Corporate Systems Engineering"),
            Map.entry(0x1080, "ecobee"), Map.entry(0x1081, "SMK"), Map.entry(0x1082, "Meshworks Wireless Oy"),
            Map.entry(0x1083, "Ellips B.V."), Map.entry(0x1084, "Secure electrans"), Map.entry(0x1085, "CEDO"),
            Map.entry(0x1086, "Toshiba"), Map.entry(0x1087, "Digi International"), Map.entry(0x1088, "Ubilogix"),
            Map.entry(0x1089, "Echelon"), Map.entry(0x1090, "Green Energy Options"),
            Map.entry(0x1091, "Silver Spring Networks"), Map.entry(0x1092, "Black &amp; Decker"),
            Map.entry(0x1093, "Aztech Associates Inc."), Map.entry(0x1094, "A&amp;D Co., Ltd."),
            Map.entry(0x1095, "Rainforest Automation"), Map.entry(0x1096, "Carrier Electronics"),
            Map.entry(0x1097, "SyChip/Murata"), Map.entry(0x1098, "OpenPeak"), Map.entry(0x1099, "PassiveSystems"),
            Map.entry(0x109a, "MMB Research"), Map.entry(0x109b, "Leviton Manufacturing Company"),
            Map.entry(0x109c, "Korea Electric Power Data Network Co., Ltd."), Map.entry(0x109d, "Comcast"),
            Map.entry(0x109e, "NEC Electronics"), Map.entry(0x109f, "Netvox"), Map.entry(0x10a0, "U-Control"),
            Map.entry(0x10a1, "Embedia Technologies Corp"), Map.entry(0x10a2, "Sensus"),
            Map.entry(0x10a3, "Sunrise Technologies"), Map.entry(0x10a4, "Memtech Corp"), Map.entry(0x10a5, "Freebox"),
            Map.entry(0x10a6, "M2 Labs Ltd."), Map.entry(0x10a7, "British Gas"), Map.entry(0x10a8, "Sentec Ltd."),
            Map.entry(0x10a9, "Navetas"), Map.entry(0x10aa, "Lightspeed Technologies"),
            Map.entry(0x10ab, "Oki Electric Industry Co., Ltd."),
            Map.entry(0x10ac, "S I - Sistemas Inteligentes Eletr&#xF4;nicos Ltda"), Map.entry(0x10ad, "Dometic"),
            Map.entry(0x10ae, "Alps"), Map.entry(0x10af, "EnergyHub"), Map.entry(0x10b0, "Kamstrup"),
            Map.entry(0x10b1, "EchoStar"), Map.entry(0x10b2, "EnerNOC"), Map.entry(0x10b3, "Eltav"),
            Map.entry(0x10b4, "Belkin"), Map.entry(0x10b5, "XStreamHD - Wireless Ventures"),
            Map.entry(0x10b6, "Saturn South Pty Ltd"), Map.entry(0x10b7, "GreenTrapOnline A/S"),
            Map.entry(0x10b8, "SmartSynch, Inc."), Map.entry(0x10b9, "Nyce Control, Inc."),
            Map.entry(0x10ba, "ICM Controls Corp"), Map.entry(0x10bb, "Millennium Electronics, PTY Ltd."),
            Map.entry(0x10bc, "Motorola, Inc"), Map.entry(0x10bd, "Emerson White-Rodgers"),
            Map.entry(0x10be, "Radio Thermostat Company of America"), Map.entry(0x10bf, "OMRON Corporation"),
            Map.entry(0x10c0, "GiiNii Global Limited"), Map.entry(0x10c1, "Fujitsu General Limited"),
            Map.entry(0x10c2, "Peel Technologies, Inc."), Map.entry(0x10c3, "Accent S.p.A."),
            Map.entry(0x10c4, "ByteSnap Design Ltd."), Map.entry(0x10c5, "NEC TOKIN Corporation"),
            Map.entry(0x10c6, "G4S Justice Services"), Map.entry(0x10c7, "Trilliant Networks, Inc."),
            Map.entry(0x10c8, "Electrolux Italia S.p.A"), Map.entry(0x10c9, "Onzo Ltd"),
            Map.entry(0x10ca, "EnTek Systems"), Map.entry(0x10cb, "Philips"),
            Map.entry(0x10cc, "Mainstream Engineering"), Map.entry(0x10cd, "Indesit Company"),
            Map.entry(0x10ce, "THINKECO, INC."), Map.entry(0x10cf, "2D2C, Inc."), Map.entry(0x10d0, "Qorvo"),
            Map.entry(0x10d1, "InterCEL"), Map.entry(0x10d2, "LG Electronics"),
            Map.entry(0x10d3, "Mitsumi Electric Co.,Ltd."), Map.entry(0x10d4, "Mitsumi Electric Co.,Ltd."),
            Map.entry(0x10d5, "Zentrum Mikroelektronik Dresden AG (ZMDI)"), Map.entry(0x10d6, "Nest Labs, Inc."),
            Map.entry(0x10d7, "Exegin Technologies, Ltd."), Map.entry(0x10d8, "Honeywell"),
            Map.entry(0x10d9, "Takahata Precision Co. Ltd."), Map.entry(0x10da, "SUMITOMO ELECTRIC NETWORKS, INC."),
            Map.entry(0x10db, "GE Energy"), Map.entry(0x10dc, "GE Appliances"), Map.entry(0x10dd, "Radiocrafts AS"),
            Map.entry(0x10de, "Ceiva"), Map.entry(0x10df, "TEC&amp;CO Co., Ltd"),
            Map.entry(0x10e0, "Chameleon Technology (UK) Ltd"), Map.entry(0x10e1, "Samsung"),
            Map.entry(0x10e2, "ruwido austria gmbh"), Map.entry(0x10e3, "Huawei Technologies Co., Ltd."),
            Map.entry(0x10e4, "Huawei Technologies Co., Ltd."), Map.entry(0x10e5, "Greenwave Reality"),
            Map.entry(0x10e6, "BGlobal Metering Ltd"), Map.entry(0x10e7, "Mindteck"),
            Map.entry(0x10e8, "Ingersoll-Rand"), Map.entry(0x10e9, "Dius Computing Pty Ltd"),
            Map.entry(0x10ea, "Embedded Automation, Inc."), Map.entry(0x10eb, "ABB"), Map.entry(0x10ec, "Sony"),
            Map.entry(0x10ed, "Genus Power Infrastructures Limited"), Map.entry(0x10ee, "Universal Electronics, Inc."),
            Map.entry(0x10ef, "Universal Electronics, Inc."), Map.entry(0x10f0, "Metrum Technologies, LLC"),
            Map.entry(0x10f1, "Cisco"), Map.entry(0x10f2, "Ubisys technologies GmbH"), Map.entry(0x10f3, "Consert"),
            Map.entry(0x10f4, "Crestron Electronics"), Map.entry(0x10f5, "Enphase Energy"),
            Map.entry(0x10f6, "Invensys Controls"), Map.entry(0x10f7, "Mueller Systems, LLC"),
            Map.entry(0x10f8, "AAC Technologies Holding"), Map.entry(0x10f9, "U-NEXT Co., Ltd"),
            Map.entry(0x10fa, "Steelcase Inc."), Map.entry(0x10fb, "Telematics Wireless"),
            Map.entry(0x10fc, "Samil Power Co., Ltd"), Map.entry(0x10fd, "Pace Plc"),
            Map.entry(0x10fe, "Osborne Coinage Co."), Map.entry(0x10ff, "Powerwatch"),
            Map.entry(0x1100, "CANDELED GmbH"), Map.entry(0x1101, "FlexGrid S.R.L"), Map.entry(0x1102, "Humax"),
            Map.entry(0x1103, "Universal Devices"), Map.entry(0x1104, "Advanced Energy"),
            Map.entry(0x1105, "BEGA Gantenbrink-Leuchten"), Map.entry(0x1106, "Brunel University"),
            Map.entry(0x1107, "Panasonic R&amp;D Center Singapore"), Map.entry(0x1108, "eSystems Research"),
            Map.entry(0x1109, "Panamax"), Map.entry(0x110a, "SmartThings, Inc."), Map.entry(0x110b, "EM-Lite Ltd."),
            Map.entry(0x110c, "Osram Sylvania"), Map.entry(0x110d, "2 Save Energy Ltd."),
            Map.entry(0x110e, "Planet Innovation Products Pty Ltd"), Map.entry(0x110f, "Ambient Devices, Inc."),
            Map.entry(0x1110, "Profalux"), Map.entry(0x1111, "Billion Electric Company (BEC)"),
            Map.entry(0x1112, "Embertec Pty Ltd"), Map.entry(0x1113, "IT Watchdogs"), Map.entry(0x1114, "Reloc"),
            Map.entry(0x1115, "Intel Corporation"), Map.entry(0x1116, "Trend Electronics Limited"),
            Map.entry(0x1117, "Moxa"), Map.entry(0x1118, "QEES"), Map.entry(0x1119, "SAYME Wireless Sensor Networks"),
            Map.entry(0x111a, "Pentair Aquatic Systems"), Map.entry(0x111b, "Orbit Irrigation"),
            Map.entry(0x111c, "California Eastern Laboratories"), Map.entry(0x111d, "Comcast"),
            Map.entry(0x111e, "IDT Technology Limited"), Map.entry(0x111f, "Pixela Corporation"),
            Map.entry(0x1120, "TiVo, Inc."), Map.entry(0x1121, "Fidure Corp."),
            Map.entry(0x1122, "Marvell Semiconductor, Inc."), Map.entry(0x1123, "Wasion Group Limited"),
            Map.entry(0x1124, "Jasco Products Company"),
            Map.entry(0x1125, "Shenzhen Kaifa Technology (Chengdu) Co., Ltd."),
            Map.entry(0x1126, "Netcomm Wireless Limited"), Map.entry(0x1127, "Define Instruments Limited"),
            Map.entry(0x1128, "In Home Displays Ltd."), Map.entry(0x1129, "Miele &amp; Cie. KG"),
            Map.entry(0x112a, "Televes S.A."), Map.entry(0x112b, "Labelec"),
            Map.entry(0x112c, "China Electronics Standardization Institute"), Map.entry(0x112d, "Vectorform, LLC"),
            Map.entry(0x112e, "Busch-Jaeger Elektro"), Map.entry(0x112f, "Redpine Signals, Inc."),
            Map.entry(0x1130, "Bridges Electronic Technology Pty Ltd."), Map.entry(0x1131, "Sercomm"),
            Map.entry(0x1132, "WSH GmbH wirsindheller"), Map.entry(0x1133, "Bosch Security Systems, Inc."),
            Map.entry(0x1134, "eZEX Corporation"), Map.entry(0x1135, "Dresden Elektronik Ingenieurtechnik GmbH"),
            Map.entry(0x1136, "MEAZON S.A."), Map.entry(0x1137, "Crow Electronic Engineering Ltd."),
            Map.entry(0x1138, "Harvard Engineering Plc"), Map.entry(0x1139, "Andson(Beijing) Technology CO.,Ltd"),
            Map.entry(0x113a, "Adhoco AG"), Map.entry(0x113b, "Waxman Consumer Products Group, Inc."),
            Map.entry(0x113c, "Owon Technology, Inc."), Map.entry(0x113d, "Hitron Technologies, Inc."),
            Map.entry(0x113e, "Scemtec Hard - und Software f&#xFC;r Mess - und Steuerungstechnik GmbH"),
            Map.entry(0x113f, "Webee LLC"), Map.entry(0x1140, "Grid2Home Inc"), Map.entry(0x1141, "Telink Micro"),
            Map.entry(0x1142, "Jasmine Systems, Inc."), Map.entry(0x1143, "Bidgely"), Map.entry(0x1144, "Lutron"),
            Map.entry(0x1145, "IJENKO"), Map.entry(0x1146, "Starfield Electronic Ltd."), Map.entry(0x1147, "TCP, Inc."),
            Map.entry(0x1148, "Rogers Communications Partnership"), Map.entry(0x1149, "Cree, Inc."),
            Map.entry(0x114a, "Robert Bosch LLC"), Map.entry(0x114b, "Ibis Networks, Inc."),
            Map.entry(0x114c, "Quirky, Inc."), Map.entry(0x114d, "Efergy Technologies Limited"),
            Map.entry(0x114e, "SmartLabs, Inc."), Map.entry(0x114f, "Everspring Industry Co., Ltd."),
            Map.entry(0x1150, "Swann Communications Ptl Ltd."), Map.entry(0x1151, "Soneter"),
            Map.entry(0x1152, "Samsung SDS"), Map.entry(0x1153, "Uniband Electronic Corporation"),
            Map.entry(0x1154, "Accton Technology Corporation"), Map.entry(0x1155, "Bosch Thermotechnik GmbH"),
            Map.entry(0x1156, "Wincor Nixdorf Inc."), Map.entry(0x1157, "Ohsung Electronics"),
            Map.entry(0x1158, "Zen Within, Inc."), Map.entry(0x1159, "Tech4home, Lda."), Map.entry(0x115a, "Nanoleaf"),
            Map.entry(0x115b, "Keen Home, Inc."), Map.entry(0x115c, "Poly-Control APS"),
            Map.entry(0x115d, "Eastfield Lighting Co., Ltd Shenzhen"), Map.entry(0x115e, "IP Datatel, Inc."),
            Map.entry(0x115f, "Lumi United Techology, Ltd Shenzhen"), Map.entry(0x1160, "Sengled Co., Ltd."),
            Map.entry(0x1161, "Remote Solution Co., Ltd."),
            Map.entry(0x1162, "ABB Genway Xiamen Electrical Equipment Co., Ltd."),
            Map.entry(0x1163, "Zhejiang Rexense Tech"), Map.entry(0x1164, "ForEE Technology"),
            Map.entry(0x1165, "Open Access Technology Int&#x2019;l."), Map.entry(0x1166, "INNR Lighting BV"),
            Map.entry(0x1167, "Techworld Industries"), Map.entry(0x1168, "Leedarson Lighting Co., Ltd."),
            Map.entry(0x1169, "Arzel Zoning"), Map.entry(0x116a, "Holley Technology"),
            Map.entry(0x116b, "Beldon Technologies"), Map.entry(0x116c, "Flextronics"),
            Map.entry(0x116d, "Shenzhen Meian"), Map.entry(0x116e, "Lowe&#x2019;s"),
            Map.entry(0x116f, "Sigma Connectivity"), Map.entry(0x1171, "Wulian"), Map.entry(0x1172, "Plugwise B.V."),
            Map.entry(0x1173, "Titan Products"), Map.entry(0x1174, "Ecospectral"), Map.entry(0x1175, "D-Link"),
            Map.entry(0x1176, "Technicolor Home USA"), Map.entry(0x1177, "Opple Lighting"),
            Map.entry(0x1178, "Wistron NeWeb Corp."), Map.entry(0x1179, "QMotion Shades"),
            Map.entry(0x117a, "Insta GmbH"), Map.entry(0x117b, "Shanghai Vancount"),
            Map.entry(0x117c, "Ikea of Sweden"), Map.entry(0x117d, "RT-RK"), Map.entry(0x117e, "Shenzhen Feibit"),
            Map.entry(0x117f, "EuControls"), Map.entry(0x1180, "Telkonet"),
            Map.entry(0x1181, "Thermal Solution Resources"), Map.entry(0x1182, "PomCube"),
            Map.entry(0x1183, "Ei Electronics"), Map.entry(0x1184, "Optoga"), Map.entry(0x1185, "Stelpro"),
            Map.entry(0x1186, "Lynxus Technologies Corp."), Map.entry(0x1187, "Semiconductor Components"),
            Map.entry(0x1188, "TP-Link"), Map.entry(0x1189, "Ledvance GmbH"), Map.entry(0x118a, "Nortek"),
            Map.entry(0x118b, "iRevo/Assa Abbloy Korea"), Map.entry(0x118c, "Midea"),
            Map.entry(0x118d, "ZF Friedrichshafen"), Map.entry(0x118e, "Checkit"), Map.entry(0x118f, "Aclara"),
            Map.entry(0x1190, "Nokia"), Map.entry(0x1191, "Goldcard High-tech Co., Ltd."),
            Map.entry(0x1192, "George Wilson Industries Ltd."), Map.entry(0x1193, "EASY SAVER CO.,INC"),
            Map.entry(0x1194, "ZTE Corporation"), Map.entry(0x1195, "ARRIS"), Map.entry(0x1196, "Reliance BIG TV"),
            Map.entry(0x1197, "Insight Energy Ventures/Powerley"),
            Map.entry(0x1198, "Thomas Research Products (Hubbell Lighting Inc.)"),
            Map.entry(0x1199, "Li Seng Technology"), Map.entry(0x119a, "System Level Solutions Inc."),
            Map.entry(0x119b, "Matrix Labs"), Map.entry(0x119c, "Sinope Technologies"),
            Map.entry(0x119d, "Jiuzhou Greeble"), Map.entry(0x119e, "Guangzhou Lanvee Tech. Co. Ltd."),
            Map.entry(0x119f, "Venstar"), Map.entry(0x1200, "SLV"), Map.entry(0x1201, "Halo Smart Labs"),
            Map.entry(0x1202, "Scout Security Inc."), Map.entry(0x1203, "Alibaba China Inc."),
            Map.entry(0x1204, "Resolution Products, Inc."), Map.entry(0x1205, "Smartlok Inc."),
            Map.entry(0x1206, "Lux Products Corp."), Map.entry(0x1207, "Vimar SpA"),
            Map.entry(0x1208, "Universal Lighting Technologies"), Map.entry(0x1209, "Robert Bosch, GmbH"),
            Map.entry(0x120a, "Accenture"), Map.entry(0x120b, "Heiman Technology Co., Ltd."),
            Map.entry(0x120c, "Shenzhen HOMA Technology Co., Ltd."), Map.entry(0x120d, "Vision-Electronics Technology"),
            Map.entry(0x120e, "Lenovo"), Map.entry(0x120f, "Presciense R&amp;D"),
            Map.entry(0x1210, "Shenzhen Seastar Intelligence Co., Ltd."), Map.entry(0x1211, "Sensative AB"),
            Map.entry(0x1212, "SolarEdge"), Map.entry(0x1213, "Zipato"),
            Map.entry(0x1214, "China Fire &amp; Security Sensing Manufacturing (iHorn)"), Map.entry(0x1215, "Quby BV"),
            Map.entry(0x1216, "Hangzhou Roombanker Technology Co., Ltd."), Map.entry(0x1217, "Amazon Lab126"),
            Map.entry(0x1218, "Paulmann Licht GmbH"), Map.entry(0x1219, "Shenzhen Orvibo Electronics Co. Ltd."),
            Map.entry(0x121a, "TCI Telecommunications"), Map.entry(0x121b, "Mueller-Licht International Inc."),
            Map.entry(0x121c, "Aurora Limited"), Map.entry(0x121d, "SmartDCC"),
            Map.entry(0x121e, "Shanghai UMEinfo Co. Ltd."), Map.entry(0x121f, "carbonTRACK"),
            Map.entry(0x1220, "Somfy"), Map.entry(0x1221, "Viessmann Elektronik GmbH"),
            Map.entry(0x1222, "Hildebrand Technology Ltd"), Map.entry(0x1223, "Onkyo Technology Corporation"),
            Map.entry(0x1224, "Shenzhen Sunricher Technology Ltd."), Map.entry(0x1225, "Xiu Xiu Technology Co., Ltd"),
            Map.entry(0x1226, "Zumtobel Group"), Map.entry(0x1227, "Shenzhen Kaadas Intelligent Technology Co. Ltd"),
            Map.entry(0x1228, "Shanghai Xiaoyan Technology Co. Ltd"), Map.entry(0x1229, "Cypress Semiconductor"),
            Map.entry(0x122a, "XAL GmbH"), Map.entry(0x122b, "Inergy Systems LLC"),
            Map.entry(0x122c, "Alfred Karcher GmbH &amp; Co KG"), Map.entry(0x122d, "Adurolight Manufacturing"),
            Map.entry(0x122e, "Groupe Muller"), Map.entry(0x122f, "V-Mark Enterprises Inc."),
            Map.entry(0x1230, "Lead Energy AG"), Map.entry(0x1231, "Ultimate IOT (Henan) Technology Ltd."),
            Map.entry(0x1232, "Axxess Industries Inc."), Map.entry(0x1233, "Third Reality Inc."),
            Map.entry(0x1234, "DSR Corporation"), Map.entry(0x1235, "Guangzhou Vensi Intelligent Technology Co. Ltd."),
            Map.entry(0x1236, "Schlage Lock (Allegion)"), Map.entry(0x1237, "Net2Grid"),
            Map.entry(0x1238, "Airam Electric Oy Ab"), Map.entry(0x1239, "IMMAX WPB CZ"),
            Map.entry(0x123a, "ZIV Automation"), Map.entry(0x123b, "HangZhou iMagicTechnology Co., Ltd"),
            Map.entry(0x123c, "Xiamen Leelen Technology Co. Ltd."), Map.entry(0x123d, "Overkiz SAS"),
            Map.entry(0x123e, "Flonidan A/S"), Map.entry(0x123f, "HDL Automation Co., Ltd."),
            Map.entry(0x1240, "Ardomus Networks Corporation"), Map.entry(0x1241, "Samjin Co., Ltd."),
            Map.entry(0x1242, "FireAngel Safety Technology plc"), Map.entry(0x1243, "Indra Sistemas, S.A."),
            Map.entry(0x1244, "Shenzhen JBT Smart Lighting Co., Ltd."), Map.entry(0x1245, "GE Lighting &amp; Current"),
            Map.entry(0x1246, "Danfoss A/S"), Map.entry(0x1247, "NIVISS PHP Sp. z o.o. Sp.k."),
            Map.entry(0x1248, "Shenzhen Fengliyuan Energy Conservating Technology Co. Ltd"),
            Map.entry(0x1249, "NEXELEC"), Map.entry(0x124a, "Sichuan Behome Prominent Technology Co., Ltd"),
            Map.entry(0x124b, "Fujian Star-net Communication Co., Ltd."),
            Map.entry(0x124c, "Toshiba Visual Solutions Corporation"), Map.entry(0x124d, "Latchable, Inc."),
            Map.entry(0x124e, "L&amp;S Deutschland GmbH"), Map.entry(0x124f, "Gledopto Co., Ltd."),
            Map.entry(0x1250, "The Home Depot"), Map.entry(0x1251, "Neonlite Distribution Limited"),
            Map.entry(0x1252, "Arlo Technologies, Inc."), Map.entry(0x1253, "Xingluo Technology Co., Ltd."),
            Map.entry(0x1254, "Simon Electric (China) Co., Ltd."),
            Map.entry(0x1255, "Hangzhou Greatstar Industrial Co., Ltd."),
            Map.entry(0x1256, "Sequentric Energy Systems, LLC"), Map.entry(0x1257, "Solum Co., Ltd."),
            Map.entry(0x1258, "Eaglerise Electric &amp; Electronic (China) Co., Ltd."),
            Map.entry(0x1259, "Fantem Technologies (Shenzhen) Co., Ltd."),
            Map.entry(0x125a, "Yunding Network Technology (Beijing) Co., Ltd."), Map.entry(0x125b, "Atlantic Group"),
            Map.entry(0x125c, "Xiamen Intretech, Inc."), Map.entry(0x125d, "Tuya Global Inc."),
            Map.entry(0x125e, "Dnake (Xiamen) Intelligent Technology Co., Ltd."), Map.entry(0x125f, "Niko nv"),
            Map.entry(0x1260, "Emporia Energy"), Map.entry(0x1261, "Sikom AS"), Map.entry(0x1262, "AXIS Labs, Inc."),
            Map.entry(0x1263, "Current Products Corporation"), Map.entry(0x1264, "MeteRSit SRL"),
            Map.entry(0x1265, "HORNBACH Baumarkt AG"), Map.entry(0x1266, "DiCEworld s.r.l. a socio unico"),
            Map.entry(0x1267, "ARC Technology Co., Ltd"),
            Map.entry(0x1268, "Hangzhou Konke Information Technology Co., Ltd."),
            Map.entry(0x1269, "SALTO Systems S.L."), Map.entry(0x126a, "Shenzhen Shyugj Technology Co., Ltd"),
            Map.entry(0x126b, "Brayden Automation Corporation"), Map.entry(0x126c, "Environexus Pty. Ltd."),
            Map.entry(0x126d, "Eltra nv/sa"), Map.entry(0x126e, "Xiaomi Communications Co., Ltd."),
            Map.entry(0x126f, "Shanghai Shuncom Electronic Technology Co., Ltd."), Map.entry(0x1270, "Voltalis S.A"),
            Map.entry(0x1271, "FEELUX Co., Ltd."), Map.entry(0x1272, "SmartPlus Inc."),
            Map.entry(0x1273, "Halemeier GmbH"), Map.entry(0x1274, "Trust International BV"),
            Map.entry(0x1275, "Duke Energy Business Services LLC"), Map.entry(0x1276, "Calix, Inc."),
            Map.entry(0x1277, "ADEO"), Map.entry(0x1278, "Connected Response Limited"),
            Map.entry(0x1279, "StroyEnergoKom, Ltd."), Map.entry(0x127a, "Lumitech Lighting Solution GmbH"),
            Map.entry(0x127b, "Verdant Environmental Technologies"), Map.entry(0x127c, "Alfred International Inc."),
            Map.entry(0x127d, "Sansi LED Lighting co., LTD."), Map.entry(0x127e, "Mindtree Limited"),
            Map.entry(0x127f, "Nordic Semiconductor ASA"), Map.entry(0x1280, "Siterwell Electronics Co., Limited"),
            Map.entry(0x1281, "Briloner Leuchten GmbH &amp; Co. KG"),
            Map.entry(0x1282, "Shenzhen SEI Technology Co., Ltd."), Map.entry(0x1283, "Copper Labs, Inc."),
            Map.entry(0x1284, "Delta Dore"), Map.entry(0x1285, "Hager Group"),
            Map.entry(0x1286, "Shenzhen CoolKit Technology Co., Ltd"),
            Map.entry(0x1287, "Hangzhou Sky-Lighting Co., Ltd."), Map.entry(0x1288, "E.ON SE"),
            Map.entry(0x1289, "Lidl Stiftung &amp; Co. KG"),
            Map.entry(0x128a, "Sichuan Changhong Network Technologies Co., Ltd."), Map.entry(0x128b, "NodOn"),
            Map.entry(0x128c, "Jiangxi Innotech Technology Co., Ltd."), Map.entry(0x128d, "Mercator Pty Ltd"),
            Map.entry(0x128e, "Beijing Ruying Tech Limited"), Map.entry(0x128f, "EGLO Leuchten GmbH"),
            Map.entry(0x1290, "Pietro Fiorentini S.p.A"), Map.entry(0x1291, "Zehnder Group Vaux-Andigny"),
            Map.entry(0x1292, "BRK Brands, Inc."), Map.entry(0x1293, "Askey Computer Corp."),
            Map.entry(0x1294, "PassiveBolt, Inc."),
            Map.entry(0x1295, "AVM Audiovisuelles Marketing und Computersysteme Berlin"),
            Map.entry(0x1296, "Ningbo Suntech Lighting Technology Co., Ltd"),
            Map.entry(0x1297, "Société en Commandite Stello"), Map.entry(0x1298, "Vivint Smart Home"),
            Map.entry(0x1299, "Namron AS"), Map.entry(0x129a, "RADEMACHER Geraete-Elektronik GmbH"),
            Map.entry(0x129b, "OMO Systems LTD"), Map.entry(0x129c, "Siglis AG"), Map.entry(0x129d, "IMHOTEP CREATION"),
            Map.entry(0x129e, "icasa"), Map.entry(0x129f, "Level Home, Inc."), Map.entry(0x1300, "TIS Control Limited"),
            Map.entry(0x1301, "Radisys India Pvt. Ltd."), Map.entry(0x1302, "Veea Inc."),
            Map.entry(0x1303, "FELL Technology AS"), Map.entry(0x1304, "Sowilo Design Services, Ltd."),
            Map.entry(0x1305, "Lexi Devices, Inc."), Map.entry(0x1306, "Lifi Labs INC. dba LIFX"),
            Map.entry(0x1307, "GRUNDFOS Holding A/S"), Map.entry(0x1308, "SOURCING &amp; CREATION"),
            Map.entry(0x1309, "Kraken Technologies Ltd"), Map.entry(0x130a, "EVE SYSTEMS"),
            Map.entry(0x130b, "LITE-ON TECHNOLOGY CORPORATION"), Map.entry(0x130c, "Focalcrest Limited"),
            Map.entry(0x130d, "Bouffalo Lab (Nanjing) Co., Ltd."), Map.entry(0x130e, "Wyze Labs, Inc."),
            Map.entry(0x130f, "Z-Wave Europe GmbH"), Map.entry(0x1310, "AEOTEC LIMITED"),
            Map.entry(0x1311, "NGSTB Company Limited"),
            Map.entry(0x1312, "Qingdao Yeelink Information Technology Co., Ltd."),
            Map.entry(0x1313, "E-Smart Home Automation Systems Limited"), Map.entry(0x1314, "Fibar Group S.A."),
            Map.entry(0x1315, "Prolitech GmbH"), Map.entry(0x1316, "PanKore Integrated Circuit Technology Co. Ltd."),
            Map.entry(0x1317, "Logitech"), Map.entry(0x1318, "Piaro, Inc."),
            Map.entry(0x1319, "Mitsubishi Electric US, Inc."), Map.entry(0x131a, "Resideo Technologies, Inc."),
            Map.entry(0x131b, "Espressif Systems (Shanghai) Co., Ltd."),
            Map.entry(0x131c, "HELLA Sonnen- und Wetterschutztechnik GmbH"),
            Map.entry(0x131d, "Geberit International AG"), Map.entry(0x131e, "CAME S.p.A."),
            Map.entry(0x131f, "Guangzhou Elite Education &amp; Technology Co., Ltd."),
            Map.entry(0x1320, "Phyplus Microelectronics Limited"),
            Map.entry(0x1321, "Shenzhen Sonoff Technologies Co., Ltd."), Map.entry(0x1322, "Safe4 Security Group"),
            Map.entry(0x1323, "Shanghai MXCHIP Information Technology Co., Ltd."), Map.entry(0x1324, "HDC I-Controls"),
            Map.entry(0x1325, "Zuma Array Limited"), Map.entry(0x1326, "DECELECT"),
            Map.entry(0x1327, "Mill International AS"), Map.entry(0x1328, "HomeWizard BV"),
            Map.entry(0x1329, "Shenzhen Topband Co., Ltd"), Map.entry(0x132a, "Pressac Communications Ltd"),
            Map.entry(0x132b, "Origin Wireless, Inc."), Map.entry(0x132c, "Connecte AS"), Map.entry(0x132d, "YOKIS"),
            Map.entry(0x132e, "Xiamen Yankon Energetic Lighting Co., Ltd."), Map.entry(0x132f, "Yandex LLC"),
            Map.entry(0x1330, "Critical Software S.A."), Map.entry(0x1331, "Nortek Control"),
            Map.entry(0x1332, "BrightAI"), Map.entry(0x1333, "Becker-Antriebe GmbH"),
            Map.entry(0x1334, "Shenzhen TCL New Technology Company Limited"),
            Map.entry(0x1335, "Dexatek Technology Ltd"), Map.entry(0x1336, "Elelabs International Limited"),
            Map.entry(0x1337, "Datek Wireless AS"), Map.entry(0x1338, "ALDES"), Map.entry(0x1339, "Savant Company"),
            Map.entry(0x133a, "Ariston Thermo Group"), Map.entry(0x133b, "WAREMA Renkhoff SE"),
            Map.entry(0x133c, "VTech Holdings Limited"), Map.entry(0x133d, "Futurehome AS"),
            Map.entry(0x133e, "Cognitive Systems Corp."),
            Map.entry(0x133f, "ASR Microelectronics (Shenzhen) Co., Ltd."), Map.entry(0x1340, "Airios"),
            Map.entry(0x1341, "Guangdong OPPO Mobile Telecommunications Corp., Ltd."),
            Map.entry(0x1342, "Beken Corporation"), Map.entry(0x1343, "Corsair"), Map.entry(0x1344, "Eltako GmbH"),
            Map.entry(0x1345, "Chengdu Meross Technology Co., Ltd."),
            Map.entry(0x1346, "Rafael Microelectronics, Inc."), Map.entry(0x1347, "Aug. Winkhuas GmbH &amp; Co. KG"),
            Map.entry(0x1348, "Qingdao Haier Technology Co., Ltd."), Map.entry(0x1349, "Apple Inc."),
            Map.entry(0x134a, "Rollease Acmeda"), Map.entry(0x134b, "Nabu Casa, Inc."),
            Map.entry(0x134c, "Simon Holding"), Map.entry(0x134d, "KD Navien"), Map.entry(0x134e, "tado GmbH"),
            Map.entry(0x134f, "Mediola Connected Living AG"), Map.entry(0x1350, "Polynhome"),
            Map.entry(0x1351, "HooRii Technology Co., Ltd."), Map.entry(0x1352, "Häfele SE &amp; Co KG"),
            Map.entry(0x1353, "KIMIN Electronics Co., Ltd."), Map.entry(0x1354, "Zyax AB"),
            Map.entry(0x1355, "Baracoda SA"), Map.entry(0x1356, "Lennox International, Inc"),
            Map.entry(0x1357, "Teledatics Incorporated"), Map.entry(0x1358, "Top Victory Investments Limited"),
            Map.entry(0x1359, "GOQUAL Inc."), Map.entry(0x135a, "Siegenia Aubi KG"),
            Map.entry(0x135b, "Virtual Connected Controlling System (Singapore) Pte. Ltd."),
            Map.entry(0x135c, "Gigaset Communications GmbH"), Map.entry(0x135d, "Nuki Home Solutions GmbH"),
            Map.entry(0x135e, "Devicebook, Inc."), Map.entry(0x135f, "Consumer 2.0 Inc. (Rently)"),
            Map.entry(0x1360, "Edison Labs, Inc. (dba Orro)"), Map.entry(0x1361, "Inovelli"),
            Map.entry(0x1362, "deveritec GmbH"), Map.entry(0x1363, "Charter Communications"),
            Map.entry(0x1364, "Monolithic Power Systems, Inc."),
            Map.entry(0x1365, "Ningbo Dooya Mechanic &amp; Electronic Technology Co., Ltd"),
            Map.entry(0x1366, "Shenzhen SDMC Technology Co., Ltd."), Map.entry(0x1367, "HP Inc."),
            Map.entry(0x1368, "mui Lab, Inc."), Map.entry(0x1369, "BHtronics S.r.l."),
            Map.entry(0x136a, "Akuvox (Xiamen) Networks Co., Ltd."), Map.entry(0x136b, "nami"),
            Map.entry(0x136c, "Kee Tat Manufactory Holdings Limited"), Map.entry(0x136d, "Iton Technology Corp."),
            Map.entry(0x136e, "Ambi Labs Limited"), Map.entry(0x136f, "Corporación Empresarial Altra S.L."),
            Map.entry(0x1370, "Coway Co., Ltd."), Map.entry(0x1371, "Tridonic GmbH &amp; Co KG"),
            Map.entry(0x1372, "innovation matters iot GmbH"), Map.entry(0x1373, "MediaTek Inc."),
            Map.entry(0x1374, "Fresco"), Map.entry(0x1375, "Hangzhou Yaguan Technology Co., Ltd."),
            Map.entry(0x1376, "Guardian Glass, LLC"), Map.entry(0x1377, "Night Owl SP, LLC"),
            Map.entry(0x1378, "Je Woo Corporation Ltd."), Map.entry(0x1379, "Earda Technologies Co., Ltd."),
            Map.entry(0x137a, "Alexa Connect Kit (ACK)"), Map.entry(0x137b, "Amazon Basics"),
            Map.entry(0x137c, "Morse Micro Inc."), Map.entry(0x137d, "Shanghai Xiaodu Technology Limited"),
            Map.entry(0x137e, "Nubert electronic GmbH"), Map.entry(0x137f, "Shenzhen NEO Electronics Co. Ltd."),
            Map.entry(0x1380, "Grimsholm Products AB"), Map.entry(0x1381, "Amazon Prime Video"),
            Map.entry(0x1382, "ION INDUSTRIES B.V."), Map.entry(0x1383, "Ayla Networks"),
            Map.entry(0x1384, "Apple Keychain"), Map.entry(0x1385, "Lightning Semiconductor"),
            Map.entry(0x1386, "Skylux NV"), Map.entry(0x1387, "Shenzhen Qianyan Technology Ltd."),
            Map.entry(0x1388, "Infineon Technologies AG"), Map.entry(0x1389, "Shenzhen Jingxun Technology Co., Ltd."),
            Map.entry(0x138a, "Nature Inc."), Map.entry(0x138b, "WiFigarden Inc."),
            Map.entry(0x138c, "Hisense Group Co. Ltd., USA"),
            Map.entry(0x138d, "Nanjing Easthouse Electrical Co., Ltd."), Map.entry(0x138e, "Ledworks SRL"),
            Map.entry(0x138f, "Shina System Co., Ltd."), Map.entry(0x1390, "Qualcomm Technologies Inc."),
            Map.entry(0x1391, "Kasa (Big Field Global PTE. Ltd.)"),
            Map.entry(0x1392, "Tapo (Big Field Global PTE. Ltd.)"),
            Map.entry(0x1393, "Shanghai High-Flying Electronics Technology Co., Ltd."),
            Map.entry(0x1394, "SigmaStar Technology Ltd."), Map.entry(0x1395, "HOOBS Inc."),
            Map.entry(0x1396, "AiDot Inc."), Map.entry(0x1397, "Woan Technology (Shenzhen) Co., Ltd."),
            Map.entry(0x1398, "Meizu Technology Co., Ltd."), Map.entry(0x1399, "Yukai Engineering Inc."),
            Map.entry(0x139a, "Qrio, Inc."), Map.entry(0x139b, "ITIUS GmbH"),
            Map.entry(0x139c, "Zemismart Technology Limited"), Map.entry(0x139d, "LED Linear GmbH"),
            Map.entry(0x139e, "Dyson Technology Limited"), Map.entry(0x139f, "Razer Inc."),
            Map.entry(0x1400, "Uascent Technology Company Limited"), Map.entry(0x1401, "Bose Corporation"),
            Map.entry(0x1402, "GOLDTek Technology Co., Ltd."), Map.entry(0x1403, "Arlec Australia Pty. Ltd."),
            Map.entry(0x1404, "Shenzhen Phaten Technology Co., Ltd."), Map.entry(0x1405, "Ecovacs Robotics Co., Ltd."),
            Map.entry(0x1406, "Luxshare-ICT Co., Ltd."), Map.entry(0x1407, "Jiangshu Shushi Technology Co., Ltd."),
            Map.entry(0x1408, "Velux A/S"), Map.entry(0x1409, "Shenzhen Hidin Technology Co., Ltd."),
            Map.entry(0x140a, "Intertech Services AG"), Map.entry(0x140b, "70mai Co., Ltd."),
            Map.entry(0x140c, "Beijing ESWIN Computing Technology CO.,Ltd."),
            Map.entry(0x140d, "Photon Sail Technologies Pte. Ltd."), Map.entry(0x140e, "WiDom SRL"),
            Map.entry(0x140f, "Sagemcom SAS"), Map.entry(0x1410, "Quectel Wireless Solutions Co., Ltd."),
            Map.entry(0x1411, "Freedompro S.r.l."), Map.entry(0x1412, "Disign Incorporated"),
            Map.entry(0x1413, "1Home Solutions GmbH"), Map.entry(0x1414, "StreamUnlimited Engineering GmbH"),
            Map.entry(0x1415, "Caveman (Nanoleaf)"), Map.entry(0x1416, "Umbra (Nanoleaf)"),
            Map.entry(0x1417, "Konnected Inc."), Map.entry(0x1418, "KLite (Signify)"),
            Map.entry(0x1419, "Lorex Technology Inc."), Map.entry(0x141a, "RATOC Systems, Inc"),
            Map.entry(0x141b, "Rang Dong Light Source &amp; VacuumFlask Joint Stock Company"),
            Map.entry(0x141c, "Shenzhen Sibo Zhilian Technology Co., Ltd."), Map.entry(0x141d, "Secuyou APS"),
            Map.entry(0x141e, "TUO Accessories LLC"), Map.entry(0x141f, "DUCTECH Co., Ltd"),
            Map.entry(0x1420, "EcoFlow Inc."), Map.entry(0x1421, "Kwikset"),
            Map.entry(0x1422, "Zhuhai HiVi Technology Co., Ltd."), Map.entry(0x1423, "Feit Electric Company, Inc."),
            Map.entry(0x1424, "Alarm.com Incorporated"), Map.entry(0x1425, "Hangzhou BroadLink Technology Co., Ltd."),
            Map.entry(0x1426, "ELE (Group) Co., Ltd."), Map.entry(0x1427, "Hama GmbH &amp; Co. KG"),
            Map.entry(0x1428, "Shenzhen Aimore .Co .,Ltd"), Map.entry(0x1429, "Albrecht Jung GmbH &amp; Co. KG"),
            Map.entry(0x142a, "Hitachi Global Life Solutions, Inc."),
            Map.entry(0x142b, "Beijing Renhejia Technology Co., Ltd"),
            Map.entry(0x142c, "vivo Mobile Communication Co., Ltd."),
            Map.entry(0x142d, "Zhongshan QIHANG Electronic Technology Co."),
            Map.entry(0x142e, "Shenzhen Sowye Technology CO.,Ltd"),
            Map.entry(0x142f, "Shenzhen QIACHIP Wireless Ecommerce Co."), Map.entry(0x1430, "L-TRADE GROUP SP z.o.o."),
            Map.entry(0x1431, "Daikin Industries, Ltd."), Map.entry(0x1432, "ELKO EP, s.r.o."),
            Map.entry(0x1433, "MOMAX Technology (Hong Kong) Limited"),
            Map.entry(0x1434, "Hangzhou Ezviz Network Co., Ltd."), Map.entry(0x1435, "Granite River Labs"),
            Map.entry(0x1436, "SinuxSoft Inc."), Map.entry(0x1437, "ACCEL LAB Ltd."),
            Map.entry(0x1438, "Xiamen Topstar Lighting Co.,Ltd"), Map.entry(0x1439, "Vaillant Group"),
            Map.entry(0x143a, "YoSmart Inc."), Map.entry(0x143b, "Amina Charging AS"), Map.entry(0x143c, "Athom B.V."),
            Map.entry(0x143d, "Shenzhen Champon Technology Co., Ltd"), Map.entry(0x143e, "Acer Inc."),
            Map.entry(0x143f, "Vestel Elektronik Sanayi ve Ticaret A.S."), Map.entry(0x1440, "VerLuce"),
            Map.entry(0x1441, "Shenzhen Snowball Technology Co., Ltd."), Map.entry(0x1442, "REHAU Group"),
            Map.entry(0x1443, "GoodsiQ"), Map.entry(0x1444, "Last lock Inc."), Map.entry(0x1445, "Finesse Decor"),
            Map.entry(0x1446, "Take As Global, SL"), Map.entry(0x1447, "Honor Device Co., Ltd."),
            Map.entry(0x1448, "LivingStyle Enterprises Limited"), Map.entry(0x1449, "ZUTTO TECHNOLOGIES"),
            Map.entry(0x144a, "Sensibo Ltd."), Map.entry(0x144b, "Kohler Company"),
            Map.entry(0x144c, "TrustAsia Technologies, Inc."), Map.entry(0x144d, "Atios AG"),
            Map.entry(0x144e, "Sense Labs, Inc."), Map.entry(0x144f, "Assa Abloy AB"),
            Map.entry(0x1450, "GM Global Technology Operations LLC"), Map.entry(0x1451, "JetHome"),
            Map.entry(0x1452, "Big Ass Fans"), Map.entry(0x1453, "Gumax BV"), Map.entry(0x1454, "Yardi Systems Inc."),
            Map.entry(0x1455, "Deutsche Telekom AG"), Map.entry(0x1456, "Sensirion AG"),
            Map.entry(0x1457, "Hangzhou Wistar Mechanical &amp; Electric Technology Co., Ltd"),
            Map.entry(0x1458, "Wilhelm Koch GmbH "), Map.entry(0x1459, "Shenzhen iComm Semiconductor Co., Ltd."),
            Map.entry(0x145a, "British Telecommunications plc"), Map.entry(0x145b, "Remotec Technology Ltd."),
            Map.entry(0x145c, "Pin Genie, Inc. DBA Lockly"), Map.entry(0x145d, "Hosiden Corporation"),
            Map.entry(0x145e, "Deako, Inc."), Map.entry(0x145f, "Good Way Technology Co., Ltd."),
            Map.entry(0x1460, "Zhuhai Ruran Intelligent Technology Co., LTD (Meizu)"),
            Map.entry(0x1461, "Xinda Asset Management (Shenzhen) Co.,Ltd."),
            Map.entry(0x1462, "Chengdu Energy Magic Cube Technology Co., Ltd"),
            Map.entry(0x1463, "Eberle Controls GmbH"), Map.entry(0x1464, "Opulinks Technology"),
            Map.entry(0x1465, "Hunter Douglas Group"), Map.entry(0x1466, "Hangzhou Hemos Lighting Company Limited"),
            Map.entry(0x1467, "OTODO SAS"), Map.entry(0x1468, "Anona Security Technology Limited"),
            Map.entry(0x1469, "Loxone Electronics GmbH"), Map.entry(0x146a, "Intecular LLC"),
            Map.entry(0x146b, "Aixlink Ltd."), Map.entry(0x146c, "Shenzhen Jinjie Technology Co.,Ltd."),
            Map.entry(0x146d, "Polyaire Pty Ltd"), Map.entry(0x146e, "Shenzhen PINXUAN Trading Co."),
            Map.entry(0x146f, "SmartWing Home LLC"), Map.entry(0x1470, "Shenzhen Hope Microelectronics Co., Ltd."),
            Map.entry(0x1471, "Commax"), Map.entry(0x1472, "Zhejiang Jiecang Linear Motion Technology Co.,Ltd"),
            Map.entry(0x1473, "Shenzhen Lelight technology Co.lt"),
            Map.entry(0x1474, "Shenzhen Ruomu Zhilian Technology Co., Ltd."),
            Map.entry(0x1475, "Cable Television Laboratories, Inc. dba CableLabs"),
            Map.entry(0x1476, "Harman International"), Map.entry(0x1477, "Shenzhen Multi IR Technology Co.,Ltd"),
            Map.entry(0x1478, "APYNOV"), Map.entry(0x1479, "Browan Communications Inc."),
            Map.entry(0x147a, "Shenzhen Realwe Innovation Technology Co., Ltd."), Map.entry(0x147b, "Lumiflow INC"),
            Map.entry(0x147c, "SHENZHEN SHENAN YANGGUANG ELECTRONICS CO., LTD."),
            Map.entry(0x147d, "Wenzhou Morning Electronics Co., Ltd."), Map.entry(0x147e, "MIWA Lock Co., Ltd."),
            Map.entry(0x147f, "U-tec Group Inc."), Map.entry(0x1480, "Beijing Roborock Technology Co., Ltd."),
            Map.entry(0x1481, "Shenzhen Xenon Industrial Ltd"),
            Map.entry(0x1482, "Guangzhou Lingqu Electronic Technology Co., Ltd"),
            Map.entry(0x1483, "Shenzhen Jijia Intelligent Technology Co., Ltd."),
            Map.entry(0x1484, "CANDY HOUSE, Inc."), Map.entry(0x1485, "ELIT Scandinavia ApS"),
            Map.entry(0x1486, "Infibrite Inc"), Map.entry(0x1487, "Whirlpool Corp."),
            Map.entry(0x1488, "Shortcut Labs (Flic)"), Map.entry(0x1489, "INTEREL BUILDING AUTOMATION"),
            Map.entry(0x148a, "Occhio GmbH"), Map.entry(0x148b, "Samraj Technologies Limited"),
            Map.entry(0x1994, "Gewiss S.p.A."), Map.entry(0x2794, "Climax Technology Co., Ltd."),
            Map.entry(0x6006, "Google LLC"), Map.entry(0xc5a0, "Connectivity Standards Alliance"),
            Map.entry(0xc5a1, "Connectivity Standards Alliance"), Map.entry(0xc5a2, "Connectivity Standards Alliance"),
            Map.entry(0xc5a3, "Connectivity Standards Alliance"), Map.entry(0xc5a4, "Connectivity Standards Alliance"),
            Map.entry(0xc5a5, "Connectivity Standards Alliance"), Map.entry(0xc5a6, "Connectivity Standards Alliance"),
            Map.entry(0xc5a7, "Connectivity Standards Alliance"), Map.entry(0xc5a8, "Connectivity Standards Alliance"),
            Map.entry(0xc5a9, "Connectivity Standards Alliance"), Map.entry(0xc5aa, "Connectivity Standards Alliance"),
            Map.entry(0xc5ab, "Connectivity Standards Alliance"), Map.entry(0xc5ac, "Connectivity Standards Alliance"),
            Map.entry(0xc5ad, "Connectivity Standards Alliance"), Map.entry(0xc5ae, "Connectivity Standards Alliance"),
            Map.entry(0xc5af, "Connectivity Standards Alliance"), Map.entry(0xfff1, "[Test vendor #1]"),
            Map.entry(0xfff2, "[Test vendor #2]"), Map.entry(0xfff3, "[Test vendor #3]"),
            Map.entry(0xfff4, "[Test vendor #4]"), Map.entry(0xfff5, "[Reserved]"), Map.entry(0xfff6, "[Reserved]"),
            Map.entry(0xfff7, "[Reserved]"), Map.entry(0xfff8, "[Reserved]"), Map.entry(0xfff9, "[Reserved]"),
            Map.entry(0xfffa, "[Reserved]"), Map.entry(0xfffb, "[Reserved]"), Map.entry(0xfffc, "[Reserved]"),
            Map.entry(0xfffd, "[Reserved]"), Map.entry(0xfffe, "[Reserved]"), Map.entry(0xffff, "[Reserved]"));
}
