/*
 * Copyright (c) 2010-2025 Contributors to the openHAB project
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */
package org.openhab.binding.matter.internal.util;

import java.util.HashMap;
import java.util.Map;

import org.eclipse.jdt.annotation.NonNullByDefault;

/**
 * 
 * @author Dan Cunningham - Initial contribution
 */
@NonNullByDefault
public class MatterVendorIDs {

    /**
     * This list generated from https://github.com/ioBroker/ioBroker.matter/blob/main/src-admin/src/utils/vendorIDs.ts
     */
    public static final Map<Integer, String> VENDOR_IDS = new HashMap<>() {
        static final long serialVersionUID = 1L;
        {
            put(0x0005, "Freescale (RF4CE)");
            put(0x0006, "Oki Semiconductors (RF4CE)");
            put(0x0007, "Texas Instruments");
            put(0x1000, "Cirronet");
            put(0x1001, "Chipcon");
            put(0x1002, "Ember");
            put(0x1003, "NTS");
            put(0x1004, "Freescale");
            put(0x1005, "IP Com");
            put(0x1006, "San Juan Software");
            put(0x1007, "TUV");
            put(0x1008, "Integration");
            put(0x1009, "BM SpA");
            put(0x100a, "AwarePoint");
            put(0x100b, "Signify Netherlands B.V.");
            put(0x100c, "Luxoft");
            put(0x100d, "Korwin");
            put(0x100e, "One RF Technology");
            put(0x100f, "Software Technologies Group");
            put(0x1010, "Telegesis");
            put(0x1011, "Visonic");
            put(0x1012, "Insta");
            put(0x1013, "Atalum");
            put(0x1014, "Atmel");
            put(0x1015, "Develco");
            put(0x1016, "Honeywell");
            put(0x1017, "RadioPulse");
            put(0x1018, "Renesas");
            put(0x1019, "Xanadu Wireless");
            put(0x101a, "NEC Engineering");
            put(0x101b, "Yamatake Corporation");
            put(0x101c, "Tendril Networks");
            put(0x101d, "Assa Abloy");
            put(0x101e, "MaxStream");
            put(0x101f, "Neurocom");
            put(0x1020, "Institute for Information Industry");
            put(0x1021, "Legrand Group");
            put(0x1022, "iControl");
            put(0x1023, "Raymarine");
            put(0x1024, "LS Research");
            put(0x1025, "Onity Inc.");
            put(0x1026, "Mono Products");
            put(0x1027, "RF Technologies");
            put(0x1028, "Itron");
            put(0x1029, "Tritech");
            put(0x102a, "Embedit A/S");
            put(0x102b, "S3C");
            put(0x102c, "Siemens");
            put(0x102d, "Mindtech");
            put(0x102e, "LG Electronics");
            put(0x102f, "Mitsubishi Electric Corp.");
            put(0x1030, "Johnson Controls");
            put(0x1031, "Secure Meters (UK) Ltd");
            put(0x1032, "Knick");
            put(0x1033, "Viconics");
            put(0x1034, "Flexipanel");
            put(0x1035, "Piasim Corporation Pte., Ltd.");
            put(0x1036, "Trane");
            put(0x1037, "NXP Semiconductors");
            put(0x1038, "Living Independently Group");
            put(0x1039, "AlertMe.com");
            put(0x103a, "Daintree");
            put(0x103b, "Aiji System");
            put(0x103c, "Telecom Italia");
            put(0x103d, "Mikrokrets AS");
            put(0x103e, "Oki Semiconductor");
            put(0x103f, "Newport Electonics");
            put(0x1040, "Control 4");
            put(0x1041, "STMicroelectronics");
            put(0x1042, "Ad-Sol Nissin Corp");
            put(0x1043, "DCSI");
            put(0x1044, "France Telecom");
            put(0x1045, "muNet");
            put(0x1046, "Autani Corporation");
            put(0x1047, "Colorado vNet");
            put(0x1048, "Aerocomm, Inc.");
            put(0x1049, "Silicon Laboratories");
            put(0x104a, "Inncom International Inc.");
            put(0x104b, "Cooper Power Systems");
            put(0x104c, "Synapse");
            put(0x104d, "Fisher Pierce/Sunrise");
            put(0x104e, "CentraLite Systems, Inc.");
            put(0x104f, "Crane Wireless Monitoring Solutions");
            put(0x1050, "Mobilarm Limited");
            put(0x1051, "iMonitor Research Ltd.");
            put(0x1052, "Bartech");
            put(0x1053, "MeshNetics");
            put(0x1054, "LS Industrial Systems Co. Ltd.");
            put(0x1055, "Cason Engineering plc");
            put(0x1056, "Wireless Glue Networks Inc.");
            put(0x1057, "Elster");
            put(0x1058, "SMS Tecnologia Eletr&#xF4;nica");
            put(0x1059, "Onset Computer Corporation");
            put(0x105a, "Riga Development");
            put(0x105b, "Energate");
            put(0x105c, "ConMed Linvatec");
            put(0x105d, "PowerMand");
            put(0x105e, "Schneider Electric");
            put(0x105f, "Eaton Corporation");
            put(0x1060, "Telular Corporation");
            put(0x1061, "Delphi Medical Systems");
            put(0x1062, "EpiSensor Limited");
            put(0x1063, "Landis+Gyr");
            put(0x1064, "Kaba Group");
            put(0x1065, "Shure Incorporated");
            put(0x1066, "Comverge, Inc.");
            put(0x1067, "DBS Lodging Technologies, LLC.");
            put(0x1068, "Energy Aware Technology Inc.");
            put(0x1069, "Hidalgo Limited");
            put(0x106a, "Air2App");
            put(0x106b, "AMX");
            put(0x106c, "EDMI Pty Ltd");
            put(0x106d, "Cyan Ltd");
            put(0x106e, "System SPA");
            put(0x106f, "Telit");
            put(0x1070, "Kaga Electronics");
            put(0x1071, "Astrel Group SRL");
            put(0x1072, "Certicom");
            put(0x1073, "Gridpoint");
            put(0x1074, "Profile Systems LLC");
            put(0x1075, "Compacta International Ltd");
            put(0x1076, "Freestyle Technology Pty Ltd.");
            put(0x1077, "Alektrona");
            put(0x1078, "Computime");
            put(0x1079, "Remote Technologies, Inc.");
            put(0x107a, "Wavecom S.A.");
            put(0x107b, "Energy Optimizers Ltd.");
            put(0x107c, "GE");
            put(0x107d, "Jetlun");
            put(0x107e, "Cipher Systems");
            put(0x107f, "Corporate Systems Engineering");
            put(0x1080, "ecobee");
            put(0x1081, "SMK");
            put(0x1082, "Meshworks Wireless Oy");
            put(0x1083, "Ellips B.V.");
            put(0x1084, "Secure electrans");
            put(0x1085, "CEDO");
            put(0x1086, "Toshiba");
            put(0x1087, "Digi International");
            put(0x1088, "Ubilogix");
            put(0x1089, "Echelon");
            put(0x1090, "Green Energy Options");
            put(0x1091, "Silver Spring Networks");
            put(0x1092, "Black &amp; Decker");
            put(0x1093, "Aztech Associates Inc.");
            put(0x1094, "A&amp;D Co., Ltd.");
            put(0x1095, "Rainforest Automation");
            put(0x1096, "Carrier Electronics");
            put(0x1097, "SyChip/Murata");
            put(0x1098, "OpenPeak");
            put(0x1099, "PassiveSystems");
            put(0x109a, "MMB Research");
            put(0x109b, "Leviton Manufacturing Company");
            put(0x109c, "Korea Electric Power Data Network Co., Ltd.");
            put(0x109d, "Comcast");
            put(0x109e, "NEC Electronics");
            put(0x109f, "Netvox");
            put(0x10a0, "U-Control");
            put(0x10a1, "Embedia Technologies Corp");
            put(0x10a2, "Sensus");
            put(0x10a3, "Sunrise Technologies");
            put(0x10a4, "Memtech Corp");
            put(0x10a5, "Freebox");
            put(0x10a6, "M2 Labs Ltd.");
            put(0x10a7, "British Gas");
            put(0x10a8, "Sentec Ltd.");
            put(0x10a9, "Navetas");
            put(0x10aa, "Lightspeed Technologies");
            put(0x10ab, "Oki Electric Industry Co., Ltd.");
            put(0x10ac, "S I - Sistemas Inteligentes Eletr&#xF4;nicos Ltda");
            put(0x10ad, "Dometic");
            put(0x10ae, "Alps");
            put(0x10af, "EnergyHub");
            put(0x10b0, "Kamstrup");
            put(0x10b1, "EchoStar");
            put(0x10b2, "EnerNOC");
            put(0x10b3, "Eltav");
            put(0x10b4, "Belkin");
            put(0x10b5, "XStreamHD - Wireless Ventures");
            put(0x10b6, "Saturn South Pty Ltd");
            put(0x10b7, "GreenTrapOnline A/S");
            put(0x10b8, "SmartSynch, Inc.");
            put(0x10b9, "Nyce Control, Inc.");
            put(0x10ba, "ICM Controls Corp");
            put(0x10bb, "Millennium Electronics, PTY Ltd.");
            put(0x10bc, "Motorola, Inc");
            put(0x10bd, "Emerson White-Rodgers");
            put(0x10be, "Radio Thermostat Company of America");
            put(0x10bf, "OMRON Corporation");
            put(0x10c0, "GiiNii Global Limited");
            put(0x10c1, "Fujitsu General Limited");
            put(0x10c2, "Peel Technologies, Inc.");
            put(0x10c3, "Accent S.p.A.");
            put(0x10c4, "ByteSnap Design Ltd.");
            put(0x10c5, "NEC TOKIN Corporation");
            put(0x10c6, "G4S Justice Services");
            put(0x10c7, "Trilliant Networks, Inc.");
            put(0x10c8, "Electrolux Italia S.p.A");
            put(0x10c9, "Onzo Ltd");
            put(0x10ca, "EnTek Systems");
            put(0x10cb, "Philips");
            put(0x10cc, "Mainstream Engineering");
            put(0x10cd, "Indesit Company");
            put(0x10ce, "THINKECO, INC.");
            put(0x10cf, "2D2C, Inc.");
            put(0x10d0, "Qorvo");
            put(0x10d1, "InterCEL");
            put(0x10d2, "LG Electronics");
            put(0x10d3, "Mitsumi Electric Co.,Ltd.");
            put(0x10d4, "Mitsumi Electric Co.,Ltd.");
            put(0x10d5, "Zentrum Mikroelektronik Dresden AG (ZMDI)");
            put(0x10d6, "Nest Labs, Inc.");
            put(0x10d7, "Exegin Technologies, Ltd.");
            put(0x10d8, "Honeywell");
            put(0x10d9, "Takahata Precision Co. Ltd.");
            put(0x10da, "SUMITOMO ELECTRIC NETWORKS, INC.");
            put(0x10db, "GE Energy");
            put(0x10dc, "GE Appliances");
            put(0x10dd, "Radiocrafts AS");
            put(0x10de, "Ceiva");
            put(0x10df, "TEC&amp;CO Co., Ltd");
            put(0x10e0, "Chameleon Technology (UK) Ltd");
            put(0x10e1, "Samsung");
            put(0x10e2, "ruwido austria gmbh");
            put(0x10e3, "Huawei Technologies Co., Ltd.");
            put(0x10e4, "Huawei Technologies Co., Ltd.");
            put(0x10e5, "Greenwave Reality");
            put(0x10e6, "BGlobal Metering Ltd");
            put(0x10e7, "Mindteck");
            put(0x10e8, "Ingersoll-Rand");
            put(0x10e9, "Dius Computing Pty Ltd");
            put(0x10ea, "Embedded Automation, Inc.");
            put(0x10eb, "ABB");
            put(0x10ec, "Sony");
            put(0x10ed, "Genus Power Infrastructures Limited");
            put(0x10ee, "Universal Electronics, Inc.");
            put(0x10ef, "Universal Electronics, Inc.");
            put(0x10f0, "Metrum Technologies, LLC");
            put(0x10f1, "Cisco");
            put(0x10f2, "Ubisys technologies GmbH");
            put(0x10f3, "Consert");
            put(0x10f4, "Crestron Electronics");
            put(0x10f5, "Enphase Energy");
            put(0x10f6, "Invensys Controls");
            put(0x10f7, "Mueller Systems, LLC");
            put(0x10f8, "AAC Technologies Holding");
            put(0x10f9, "U-NEXT Co., Ltd");
            put(0x10fa, "Steelcase Inc.");
            put(0x10fb, "Telematics Wireless");
            put(0x10fc, "Samil Power Co., Ltd");
            put(0x10fd, "Pace Plc");
            put(0x10fe, "Osborne Coinage Co.");
            put(0x10ff, "Powerwatch");
            put(0x1100, "CANDELED GmbH");
            put(0x1101, "FlexGrid S.R.L");
            put(0x1102, "Humax");
            put(0x1103, "Universal Devices");
            put(0x1104, "Advanced Energy");
            put(0x1105, "BEGA Gantenbrink-Leuchten");
            put(0x1106, "Brunel University");
            put(0x1107, "Panasonic R&amp;D Center Singapore");
            put(0x1108, "eSystems Research");
            put(0x1109, "Panamax");
            put(0x110a, "SmartThings, Inc.");
            put(0x110b, "EM-Lite Ltd.");
            put(0x110c, "Osram Sylvania");
            put(0x110d, "2 Save Energy Ltd.");
            put(0x110e, "Planet Innovation Products Pty Ltd");
            put(0x110f, "Ambient Devices, Inc.");
            put(0x1110, "Profalux");
            put(0x1111, "Billion Electric Company (BEC)");
            put(0x1112, "Embertec Pty Ltd");
            put(0x1113, "IT Watchdogs");
            put(0x1114, "Reloc");
            put(0x1115, "Intel Corporation");
            put(0x1116, "Trend Electronics Limited");
            put(0x1117, "Moxa");
            put(0x1118, "QEES");
            put(0x1119, "SAYME Wireless Sensor Networks");
            put(0x111a, "Pentair Aquatic Systems");
            put(0x111b, "Orbit Irrigation");
            put(0x111c, "California Eastern Laboratories");
            put(0x111d, "Comcast");
            put(0x111e, "IDT Technology Limited");
            put(0x111f, "Pixela Corporation");
            put(0x1120, "TiVo, Inc.");
            put(0x1121, "Fidure Corp.");
            put(0x1122, "Marvell Semiconductor, Inc.");
            put(0x1123, "Wasion Group Limited");
            put(0x1124, "Jasco Products Company");
            put(0x1125, "Shenzhen Kaifa Technology (Chengdu) Co., Ltd.");
            put(0x1126, "Netcomm Wireless Limited");
            put(0x1127, "Define Instruments Limited");
            put(0x1128, "In Home Displays Ltd.");
            put(0x1129, "Miele &amp; Cie. KG");
            put(0x112a, "Televes S.A.");
            put(0x112b, "Labelec");
            put(0x112c, "China Electronics Standardization Institute");
            put(0x112d, "Vectorform, LLC");
            put(0x112e, "Busch-Jaeger Elektro");
            put(0x112f, "Redpine Signals, Inc.");
            put(0x1130, "Bridges Electronic Technology Pty Ltd.");
            put(0x1131, "Sercomm");
            put(0x1132, "WSH GmbH wirsindheller");
            put(0x1133, "Bosch Security Systems, Inc.");
            put(0x1134, "eZEX Corporation");
            put(0x1135, "Dresden Elektronik Ingenieurtechnik GmbH");
            put(0x1136, "MEAZON S.A.");
            put(0x1137, "Crow Electronic Engineering Ltd.");
            put(0x1138, "Harvard Engineering Plc");
            put(0x1139, "Andson(Beijing) Technology CO.,Ltd");
            put(0x113a, "Adhoco AG");
            put(0x113b, "Waxman Consumer Products Group, Inc.");
            put(0x113c, "Owon Technology, Inc.");
            put(0x113d, "Hitron Technologies, Inc.");
            put(0x113e, "Scemtec Hard - und Software f&#xFC;r Mess - und Steuerungstechnik GmbH");
            put(0x113f, "Webee LLC");
            put(0x1140, "Grid2Home Inc");
            put(0x1141, "Telink Micro");
            put(0x1142, "Jasmine Systems, Inc.");
            put(0x1143, "Bidgely");
            put(0x1144, "Lutron");
            put(0x1145, "IJENKO");
            put(0x1146, "Starfield Electronic Ltd.");
            put(0x1147, "TCP, Inc.");
            put(0x1148, "Rogers Communications Partnership");
            put(0x1149, "Cree, Inc.");
            put(0x114a, "Robert Bosch LLC");
            put(0x114b, "Ibis Networks, Inc.");
            put(0x114c, "Quirky, Inc.");
            put(0x114d, "Efergy Technologies Limited");
            put(0x114e, "SmartLabs, Inc.");
            put(0x114f, "Everspring Industry Co., Ltd.");
            put(0x1150, "Swann Communications Ptl Ltd.");
            put(0x1151, "Soneter");
            put(0x1152, "Samsung SDS");
            put(0x1153, "Uniband Electronic Corporation");
            put(0x1154, "Accton Technology Corporation");
            put(0x1155, "Bosch Thermotechnik GmbH");
            put(0x1156, "Wincor Nixdorf Inc.");
            put(0x1157, "Ohsung Electronics");
            put(0x1158, "Zen Within, Inc.");
            put(0x1159, "Tech4home, Lda.");
            put(0x115a, "Nanoleaf");
            put(0x115b, "Keen Home, Inc.");
            put(0x115c, "Poly-Control APS");
            put(0x115d, "Eastfield Lighting Co., Ltd Shenzhen");
            put(0x115e, "IP Datatel, Inc.");
            put(0x115f, "Lumi United Techology, Ltd Shenzhen");
            put(0x1160, "Sengled Co., Ltd.");
            put(0x1161, "Remote Solution Co., Ltd.");
            put(0x1162, "ABB Genway Xiamen Electrical Equipment Co., Ltd.");
            put(0x1163, "Zhejiang Rexense Tech");
            put(0x1164, "ForEE Technology");
            put(0x1165, "Open Access Technology Int&#x2019;l.");
            put(0x1166, "INNR Lighting BV");
            put(0x1167, "Techworld Industries");
            put(0x1168, "Leedarson Lighting Co., Ltd.");
            put(0x1169, "Arzel Zoning");
            put(0x116a, "Holley Technology");
            put(0x116b, "Beldon Technologies");
            put(0x116c, "Flextronics");
            put(0x116d, "Shenzhen Meian");
            put(0x116e, "Lowe&#x2019;s");
            put(0x116f, "Sigma Connectivity");
            put(0x1171, "Wulian");
            put(0x1172, "Plugwise B.V.");
            put(0x1173, "Titan Products");
            put(0x1174, "Ecospectral");
            put(0x1175, "D-Link");
            put(0x1176, "Technicolor Home USA");
            put(0x1177, "Opple Lighting");
            put(0x1178, "Wistron NeWeb Corp.");
            put(0x1179, "QMotion Shades");
            put(0x117a, "Insta GmbH");
            put(0x117b, "Shanghai Vancount");
            put(0x117c, "Ikea of Sweden");
            put(0x117d, "RT-RK");
            put(0x117e, "Shenzhen Feibit");
            put(0x117f, "EuControls");
            put(0x1180, "Telkonet");
            put(0x1181, "Thermal Solution Resources");
            put(0x1182, "PomCube");
            put(0x1183, "Ei Electronics");
            put(0x1184, "Optoga");
            put(0x1185, "Stelpro");
            put(0x1186, "Lynxus Technologies Corp.");
            put(0x1187, "Semiconductor Components");
            put(0x1188, "TP-Link");
            put(0x1189, "Ledvance GmbH");
            put(0x118a, "Nortek");
            put(0x118b, "iRevo/Assa Abbloy Korea");
            put(0x118c, "Midea");
            put(0x118d, "ZF Friedrichshafen");
            put(0x118e, "Checkit");
            put(0x118f, "Aclara");
            put(0x1190, "Nokia");
            put(0x1191, "Goldcard High-tech Co., Ltd.");
            put(0x1192, "George Wilson Industries Ltd.");
            put(0x1193, "EASY SAVER CO.,INC");
            put(0x1194, "ZTE Corporation");
            put(0x1195, "ARRIS");
            put(0x1196, "Reliance BIG TV");
            put(0x1197, "Insight Energy Ventures/Powerley");
            put(0x1198, "Thomas Research Products (Hubbell Lighting Inc.)");
            put(0x1199, "Li Seng Technology");
            put(0x119a, "System Level Solutions Inc.");
            put(0x119b, "Matrix Labs");
            put(0x119c, "Sinope Technologies");
            put(0x119d, "Jiuzhou Greeble");
            put(0x119e, "Guangzhou Lanvee Tech. Co. Ltd.");
            put(0x119f, "Venstar");
            put(0x1200, "SLV");
            put(0x1201, "Halo Smart Labs");
            put(0x1202, "Scout Security Inc.");
            put(0x1203, "Alibaba China Inc.");
            put(0x1204, "Resolution Products, Inc.");
            put(0x1205, "Smartlok Inc.");
            put(0x1206, "Lux Products Corp.");
            put(0x1207, "Vimar SpA");
            put(0x1208, "Universal Lighting Technologies");
            put(0x1209, "Robert Bosch, GmbH");
            put(0x120a, "Accenture");
            put(0x120b, "Heiman Technology Co., Ltd.");
            put(0x120c, "Shenzhen HOMA Technology Co., Ltd.");
            put(0x120d, "Vision-Electronics Technology");
            put(0x120e, "Lenovo");
            put(0x120f, "Presciense R&amp;D");
            put(0x1210, "Shenzhen Seastar Intelligence Co., Ltd.");
            put(0x1211, "Sensative AB");
            put(0x1212, "SolarEdge");
            put(0x1213, "Zipato");
            put(0x1214, "China Fire &amp; Security Sensing Manufacturing (iHorn)");
            put(0x1215, "Quby BV");
            put(0x1216, "Hangzhou Roombanker Technology Co., Ltd.");
            put(0x1217, "Amazon Lab126");
            put(0x1218, "Paulmann Licht GmbH");
            put(0x1219, "Shenzhen Orvibo Electronics Co. Ltd.");
            put(0x121a, "TCI Telecommunications");
            put(0x121b, "Mueller-Licht International Inc.");
            put(0x121c, "Aurora Limited");
            put(0x121d, "SmartDCC");
            put(0x121e, "Shanghai UMEinfo Co. Ltd.");
            put(0x121f, "carbonTRACK");
            put(0x1220, "Somfy");
            put(0x1221, "Viessmann Elektronik GmbH");
            put(0x1222, "Hildebrand Technology Ltd");
            put(0x1223, "Onkyo Technology Corporation");
            put(0x1224, "Shenzhen Sunricher Technology Ltd.");
            put(0x1225, "Xiu Xiu Technology Co., Ltd");
            put(0x1226, "Zumtobel Group");
            put(0x1227, "Shenzhen Kaadas Intelligent Technology Co. Ltd");
            put(0x1228, "Shanghai Xiaoyan Technology Co. Ltd");
            put(0x1229, "Cypress Semiconductor");
            put(0x122a, "XAL GmbH");
            put(0x122b, "Inergy Systems LLC");
            put(0x122c, "Alfred Karcher GmbH &amp; Co KG");
            put(0x122d, "Adurolight Manufacturing");
            put(0x122e, "Groupe Muller");
            put(0x122f, "V-Mark Enterprises Inc.");
            put(0x1230, "Lead Energy AG");
            put(0x1231, "Ultimate IOT (Henan) Technology Ltd.");
            put(0x1232, "Axxess Industries Inc.");
            put(0x1233, "Third Reality Inc.");
            put(0x1234, "DSR Corporation");
            put(0x1235, "Guangzhou Vensi Intelligent Technology Co. Ltd.");
            put(0x1236, "Schlage Lock (Allegion)");
            put(0x1237, "Net2Grid");
            put(0x1238, "Airam Electric Oy Ab");
            put(0x1239, "IMMAX WPB CZ");
            put(0x123a, "ZIV Automation");
            put(0x123b, "HangZhou iMagicTechnology Co., Ltd");
            put(0x123c, "Xiamen Leelen Technology Co. Ltd.");
            put(0x123d, "Overkiz SAS");
            put(0x123e, "Flonidan A/S");
            put(0x123f, "HDL Automation Co., Ltd.");
            put(0x1240, "Ardomus Networks Corporation");
            put(0x1241, "Samjin Co., Ltd.");
            put(0x1242, "FireAngel Safety Technology plc");
            put(0x1243, "Indra Sistemas, S.A.");
            put(0x1244, "Shenzhen JBT Smart Lighting Co., Ltd.");
            put(0x1245, "GE Lighting &amp; Current");
            put(0x1246, "Danfoss A/S");
            put(0x1247, "NIVISS PHP Sp. z o.o. Sp.k.");
            put(0x1248, "Shenzhen Fengliyuan Energy Conservating Technology Co. Ltd");
            put(0x1249, "NEXELEC");
            put(0x124a, "Sichuan Behome Prominent Technology Co., Ltd");
            put(0x124b, "Fujian Star-net Communication Co., Ltd.");
            put(0x124c, "Toshiba Visual Solutions Corporation");
            put(0x124d, "Latchable, Inc.");
            put(0x124e, "L&amp;S Deutschland GmbH");
            put(0x124f, "Gledopto Co., Ltd.");
            put(0x1250, "The Home Depot");
            put(0x1251, "Neonlite Distribution Limited");
            put(0x1252, "Arlo Technologies, Inc.");
            put(0x1253, "Xingluo Technology Co., Ltd.");
            put(0x1254, "Simon Electric (China) Co., Ltd.");
            put(0x1255, "Hangzhou Greatstar Industrial Co., Ltd.");
            put(0x1256, "Sequentric Energy Systems, LLC");
            put(0x1257, "Solum Co., Ltd.");
            put(0x1258, "Eaglerise Electric &amp; Electronic (China) Co., Ltd.");
            put(0x1259, "Fantem Technologies (Shenzhen) Co., Ltd.");
            put(0x125a, "Yunding Network Technology (Beijing) Co., Ltd.");
            put(0x125b, "Atlantic Group");
            put(0x125c, "Xiamen Intretech, Inc.");
            put(0x125d, "Tuya Global Inc.");
            put(0x125e, "Dnake (Xiamen) Intelligent Technology Co., Ltd.");
            put(0x125f, "Niko nv");
            put(0x1260, "Emporia Energy");
            put(0x1261, "Sikom AS");
            put(0x1262, "AXIS Labs, Inc.");
            put(0x1263, "Current Products Corporation");
            put(0x1264, "MeteRSit SRL");
            put(0x1265, "HORNBACH Baumarkt AG");
            put(0x1266, "DiCEworld s.r.l. a socio unico");
            put(0x1267, "ARC Technology Co., Ltd");
            put(0x1268, "Hangzhou Konke Information Technology Co., Ltd.");
            put(0x1269, "SALTO Systems S.L.");
            put(0x126a, "Shenzhen Shyugj Technology Co., Ltd");
            put(0x126b, "Brayden Automation Corporation");
            put(0x126c, "Environexus Pty. Ltd.");
            put(0x126d, "Eltra nv/sa");
            put(0x126e, "Xiaomi Communications Co., Ltd.");
            put(0x126f, "Shanghai Shuncom Electronic Technology Co., Ltd.");
            put(0x1270, "Voltalis S.A");
            put(0x1271, "FEELUX Co., Ltd.");
            put(0x1272, "SmartPlus Inc.");
            put(0x1273, "Halemeier GmbH");
            put(0x1274, "Trust International BV");
            put(0x1275, "Duke Energy Business Services LLC");
            put(0x1276, "Calix, Inc.");
            put(0x1277, "ADEO");
            put(0x1278, "Connected Response Limited");
            put(0x1279, "StroyEnergoKom, Ltd.");
            put(0x127a, "Lumitech Lighting Solution GmbH");
            put(0x127b, "Verdant Environmental Technologies");
            put(0x127c, "Alfred International Inc.");
            put(0x127d, "Sansi LED Lighting co., LTD.");
            put(0x127e, "Mindtree Limited");
            put(0x127f, "Nordic Semiconductor ASA");
            put(0x1280, "Siterwell Electronics Co., Limited");
            put(0x1281, "Briloner Leuchten GmbH &amp; Co. KG");
            put(0x1282, "Shenzhen SEI Technology Co., Ltd.");
            put(0x1283, "Copper Labs, Inc.");
            put(0x1284, "Delta Dore");
            put(0x1285, "Hager Group");
            put(0x1286, "Shenzhen CoolKit Technology Co., Ltd");
            put(0x1287, "Hangzhou Sky-Lighting Co., Ltd.");
            put(0x1288, "E.ON SE");
            put(0x1289, "Lidl Stiftung &amp; Co. KG");
            put(0x128a, "Sichuan Changhong Network Technologies Co., Ltd.");
            put(0x128b, "NodOn");
            put(0x128c, "Jiangxi Innotech Technology Co., Ltd.");
            put(0x128d, "Mercator Pty Ltd");
            put(0x128e, "Beijing Ruying Tech Limited");
            put(0x128f, "EGLO Leuchten GmbH");
            put(0x1290, "Pietro Fiorentini S.p.A");
            put(0x1291, "Zehnder Group Vaux-Andigny");
            put(0x1292, "BRK Brands, Inc.");
            put(0x1293, "Askey Computer Corp.");
            put(0x1294, "PassiveBolt, Inc.");
            put(0x1295, "AVM Audiovisuelles Marketing und Computersysteme Berlin");
            put(0x1296, "Ningbo Suntech Lighting Technology Co., Ltd");
            put(0x1297, "Société en Commandite Stello");
            put(0x1298, "Vivint Smart Home");
            put(0x1299, "Namron AS");
            put(0x129a, "RADEMACHER Geraete-Elektronik GmbH");
            put(0x129b, "OMO Systems LTD");
            put(0x129c, "Siglis AG");
            put(0x129d, "IMHOTEP CREATION");
            put(0x129e, "icasa");
            put(0x129f, "Level Home, Inc.");
            put(0x1300, "TIS Control Limited");
            put(0x1301, "Radisys India Pvt. Ltd.");
            put(0x1302, "Veea Inc.");
            put(0x1303, "FELL Technology AS");
            put(0x1304, "Sowilo Design Services, Ltd.");
            put(0x1305, "Lexi Devices, Inc.");
            put(0x1306, "Lifi Labs INC. dba LIFX");
            put(0x1307, "GRUNDFOS Holding A/S");
            put(0x1308, "SOURCING &amp; CREATION");
            put(0x1309, "Kraken Technologies Ltd");
            put(0x130a, "EVE SYSTEMS");
            put(0x130b, "LITE-ON TECHNOLOGY CORPORATION");
            put(0x130c, "Focalcrest Limited");
            put(0x130d, "Bouffalo Lab (Nanjing) Co., Ltd.");
            put(0x130e, "Wyze Labs, Inc.");
            put(0x130f, "Z-Wave Europe GmbH");
            put(0x1310, "AEOTEC LIMITED");
            put(0x1311, "NGSTB Company Limited");
            put(0x1312, "Qingdao Yeelink Information Technology Co., Ltd.");
            put(0x1313, "E-Smart Home Automation Systems Limited");
            put(0x1314, "Fibar Group S.A.");
            put(0x1315, "Prolitech GmbH");
            put(0x1316, "PanKore Integrated Circuit Technology Co. Ltd.");
            put(0x1317, "Logitech");
            put(0x1318, "Piaro, Inc.");
            put(0x1319, "Mitsubishi Electric US, Inc.");
            put(0x131a, "Resideo Technologies, Inc.");
            put(0x131b, "Espressif Systems (Shanghai) Co., Ltd.");
            put(0x131c, "HELLA Sonnen- und Wetterschutztechnik GmbH");
            put(0x131d, "Geberit International AG");
            put(0x131e, "CAME S.p.A.");
            put(0x131f, "Guangzhou Elite Education &amp; Technology Co., Ltd.");
            put(0x1320, "Phyplus Microelectronics Limited");
            put(0x1321, "Shenzhen Sonoff Technologies Co., Ltd.");
            put(0x1322, "Safe4 Security Group");
            put(0x1323, "Shanghai MXCHIP Information Technology Co., Ltd.");
            put(0x1324, "HDC I-Controls");
            put(0x1325, "Zuma Array Limited");
            put(0x1326, "DECELECT");
            put(0x1327, "Mill International AS");
            put(0x1328, "HomeWizard BV");
            put(0x1329, "Shenzhen Topband Co., Ltd");
            put(0x132a, "Pressac Communications Ltd");
            put(0x132b, "Origin Wireless, Inc.");
            put(0x132c, "Connecte AS");
            put(0x132d, "YOKIS");
            put(0x132e, "Xiamen Yankon Energetic Lighting Co., Ltd.");
            put(0x132f, "Yandex LLC");
            put(0x1330, "Critical Software S.A.");
            put(0x1331, "Nortek Control");
            put(0x1332, "BrightAI");
            put(0x1333, "Becker-Antriebe GmbH");
            put(0x1334, "Shenzhen TCL New Technology Company Limited");
            put(0x1335, "Dexatek Technology Ltd");
            put(0x1336, "Elelabs International Limited");
            put(0x1337, "Datek Wireless AS");
            put(0x1338, "ALDES");
            put(0x1339, "Savant Company");
            put(0x133a, "Ariston Thermo Group");
            put(0x133b, "WAREMA Renkhoff SE");
            put(0x133c, "VTech Holdings Limited");
            put(0x133d, "Futurehome AS");
            put(0x133e, "Cognitive Systems Corp.");
            put(0x133f, "ASR Microelectronics (Shenzhen) Co., Ltd.");
            put(0x1340, "Airios");
            put(0x1341, "Guangdong OPPO Mobile Telecommunications Corp., Ltd.");
            put(0x1342, "Beken Corporation");
            put(0x1343, "Corsair");
            put(0x1344, "Eltako GmbH");
            put(0x1345, "Chengdu Meross Technology Co., Ltd.");
            put(0x1346, "Rafael Microelectronics, Inc.");
            put(0x1347, "Aug. Winkhuas GmbH &amp; Co. KG");
            put(0x1348, "Qingdao Haier Technology Co., Ltd.");
            put(0x1349, "Apple Inc.");
            put(0x134a, "Rollease Acmeda");
            put(0x134b, "Nabu Casa, Inc.");
            put(0x134c, "Simon Holding");
            put(0x134d, "KD Navien");
            put(0x134e, "tado GmbH");
            put(0x134f, "Mediola Connected Living AG");
            put(0x1350, "Polynhome");
            put(0x1351, "HooRii Technology Co., Ltd.");
            put(0x1352, "Häfele SE &amp; Co KG");
            put(0x1353, "KIMIN Electronics Co., Ltd.");
            put(0x1354, "Zyax AB");
            put(0x1355, "Baracoda SA");
            put(0x1356, "Lennox International, Inc");
            put(0x1357, "Teledatics Incorporated");
            put(0x1358, "Top Victory Investments Limited");
            put(0x1359, "GOQUAL Inc.");
            put(0x135a, "Siegenia Aubi KG");
            put(0x135b, "Virtual Connected Controlling System (Singapore) Pte. Ltd.");
            put(0x135c, "Gigaset Communications GmbH");
            put(0x135d, "Nuki Home Solutions GmbH");
            put(0x135e, "Devicebook, Inc.");
            put(0x135f, "Consumer 2.0 Inc. (Rently)");
            put(0x1360, "Edison Labs, Inc. (dba Orro)");
            put(0x1361, "Inovelli");
            put(0x1362, "deveritec GmbH");
            put(0x1363, "Charter Communications");
            put(0x1364, "Monolithic Power Systems, Inc.");
            put(0x1365, "Ningbo Dooya Mechanic &amp; Electronic Technology Co., Ltd");
            put(0x1366, "Shenzhen SDMC Technology Co., Ltd.");
            put(0x1367, "HP Inc.");
            put(0x1368, "mui Lab, Inc.");
            put(0x1369, "BHtronics S.r.l.");
            put(0x136a, "Akuvox (Xiamen) Networks Co., Ltd.");
            put(0x136b, "nami");
            put(0x136c, "Kee Tat Manufactory Holdings Limited");
            put(0x136d, "Iton Technology Corp.");
            put(0x136e, "Ambi Labs Limited");
            put(0x136f, "Corporación Empresarial Altra S.L.");
            put(0x1370, "Coway Co., Ltd.");
            put(0x1371, "Tridonic GmbH &amp; Co KG");
            put(0x1372, "innovation matters iot GmbH");
            put(0x1373, "MediaTek Inc.");
            put(0x1374, "Fresco");
            put(0x1375, "Hangzhou Yaguan Technology Co., Ltd.");
            put(0x1376, "Guardian Glass, LLC");
            put(0x1377, "Night Owl SP, LLC");
            put(0x1378, "Je Woo Corporation Ltd.");
            put(0x1379, "Earda Technologies Co., Ltd.");
            put(0x137a, "Alexa Connect Kit (ACK)");
            put(0x137b, "Amazon Basics");
            put(0x137c, "Morse Micro Inc.");
            put(0x137d, "Shanghai Xiaodu Technology Limited");
            put(0x137e, "Nubert electronic GmbH");
            put(0x137f, "Shenzhen NEO Electronics Co. Ltd.");
            put(0x1380, "Grimsholm Products AB");
            put(0x1381, "Amazon Prime Video");
            put(0x1382, "ION INDUSTRIES B.V.");
            put(0x1383, "Ayla Networks");
            put(0x1384, "Apple Keychain");
            put(0x1385, "Lightning Semiconductor");
            put(0x1386, "Skylux NV");
            put(0x1387, "Shenzhen Qianyan Technology Ltd.");
            put(0x1388, "Infineon Technologies AG");
            put(0x1389, "Shenzhen Jingxun Technology Co., Ltd.");
            put(0x138a, "Nature Inc.");
            put(0x138b, "WiFigarden Inc.");
            put(0x138c, "Hisense Group Co. Ltd., USA");
            put(0x138d, "Nanjing Easthouse Electrical Co., Ltd.");
            put(0x138e, "Ledworks SRL");
            put(0x138f, "Shina System Co., Ltd.");
            put(0x1390, "Qualcomm Technologies Inc.");
            put(0x1391, "Kasa (Big Field Global PTE. Ltd.)");
            put(0x1392, "Tapo (Big Field Global PTE. Ltd.)");
            put(0x1393, "Shanghai High-Flying Electronics Technology Co., Ltd.");
            put(0x1394, "SigmaStar Technology Ltd.");
            put(0x1395, "HOOBS Inc.");
            put(0x1396, "AiDot Inc.");
            put(0x1397, "Woan Technology (Shenzhen) Co., Ltd.");
            put(0x1398, "Meizu Technology Co., Ltd.");
            put(0x1399, "Yukai Engineering Inc.");
            put(0x139a, "Qrio, Inc.");
            put(0x139b, "ITIUS GmbH");
            put(0x139c, "Zemismart Technology Limited");
            put(0x139d, "LED Linear GmbH");
            put(0x139e, "Dyson Technology Limited");
            put(0x139f, "Razer Inc.");
            put(0x1400, "Uascent Technology Company Limited");
            put(0x1401, "Bose Corporation");
            put(0x1402, "GOLDTek Technology Co., Ltd.");
            put(0x1403, "Arlec Australia Pty. Ltd.");
            put(0x1404, "Shenzhen Phaten Technology Co., Ltd.");
            put(0x1405, "Ecovacs Robotics Co., Ltd.");
            put(0x1406, "Luxshare-ICT Co., Ltd.");
            put(0x1407, "Jiangshu Shushi Technology Co., Ltd.");
            put(0x1408, "Velux A/S");
            put(0x1409, "Shenzhen Hidin Technology Co., Ltd.");
            put(0x140a, "Intertech Services AG");
            put(0x140b, "70mai Co., Ltd.");
            put(0x140c, "Beijing ESWIN Computing Technology CO.,Ltd.");
            put(0x140d, "Photon Sail Technologies Pte. Ltd.");
            put(0x140e, "WiDom SRL");
            put(0x140f, "Sagemcom SAS");
            put(0x1410, "Quectel Wireless Solutions Co., Ltd.");
            put(0x1411, "Freedompro S.r.l.");
            put(0x1412, "Disign Incorporated");
            put(0x1413, "1Home Solutions GmbH");
            put(0x1414, "StreamUnlimited Engineering GmbH");
            put(0x1415, "Caveman (Nanoleaf)");
            put(0x1416, "Umbra (Nanoleaf)");
            put(0x1417, "Konnected Inc.");
            put(0x1418, "KLite (Signify)");
            put(0x1419, "Lorex Technology Inc.");
            put(0x141a, "RATOC Systems, Inc");
            put(0x141b, "Rang Dong Light Source &amp; VacuumFlask Joint Stock Company");
            put(0x141c, "Shenzhen Sibo Zhilian Technology Co., Ltd.");
            put(0x141d, "Secuyou APS");
            put(0x141e, "TUO Accessories LLC");
            put(0x141f, "DUCTECH Co., Ltd");
            put(0x1420, "EcoFlow Inc.");
            put(0x1421, "Kwikset");
            put(0x1422, "Zhuhai HiVi Technology Co., Ltd.");
            put(0x1423, "Feit Electric Company, Inc.");
            put(0x1424, "Alarm.com Incorporated");
            put(0x1425, "Hangzhou BroadLink Technology Co., Ltd.");
            put(0x1426, "ELE (Group) Co., Ltd.");
            put(0x1427, "Hama GmbH &amp; Co. KG");
            put(0x1428, "Shenzhen Aimore .Co .,Ltd");
            put(0x1429, "Albrecht Jung GmbH &amp; Co. KG");
            put(0x142a, "Hitachi Global Life Solutions, Inc.");
            put(0x142b, "Beijing Renhejia Technology Co., Ltd");
            put(0x142c, "vivo Mobile Communication Co., Ltd.");
            put(0x142d, "Zhongshan QIHANG Electronic Technology Co.");
            put(0x142e, "Shenzhen Sowye Technology CO.,Ltd");
            put(0x142f, "Shenzhen QIACHIP Wireless Ecommerce Co.");
            put(0x1430, "L-TRADE GROUP SP z.o.o.");
            put(0x1431, "Daikin Industries, Ltd.");
            put(0x1432, "ELKO EP, s.r.o.");
            put(0x1433, "MOMAX Technology (Hong Kong) Limited");
            put(0x1434, "Hangzhou Ezviz Network Co., Ltd.");
            put(0x1435, "Granite River Labs");
            put(0x1436, "SinuxSoft Inc.");
            put(0x1437, "ACCEL LAB Ltd.");
            put(0x1438, "Xiamen Topstar Lighting Co.,Ltd");
            put(0x1439, "Vaillant Group");
            put(0x143a, "YoSmart Inc.");
            put(0x143b, "Amina Charging AS");
            put(0x143c, "Athom B.V.");
            put(0x143d, "Shenzhen Champon Technology Co., Ltd");
            put(0x143e, "Acer Inc.");
            put(0x143f, "Vestel Elektronik Sanayi ve Ticaret A.S.");
            put(0x1440, "VerLuce");
            put(0x1441, "Shenzhen Snowball Technology Co., Ltd.");
            put(0x1442, "REHAU Group");
            put(0x1443, "GoodsiQ");
            put(0x1444, "Last lock Inc.");
            put(0x1445, "Finesse Decor");
            put(0x1446, "Take As Global, SL");
            put(0x1447, "Honor Device Co., Ltd.");
            put(0x1448, "LivingStyle Enterprises Limited");
            put(0x1449, "ZUTTO TECHNOLOGIES");
            put(0x144a, "Sensibo Ltd.");
            put(0x144b, "Kohler Company");
            put(0x144c, "TrustAsia Technologies, Inc.");
            put(0x144d, "Atios AG");
            put(0x144e, "Sense Labs, Inc.");
            put(0x144f, "Assa Abloy AB");
            put(0x1450, "GM Global Technology Operations LLC");
            put(0x1451, "JetHome");
            put(0x1452, "Big Ass Fans");
            put(0x1453, "Gumax BV");
            put(0x1454, "Yardi Systems Inc.");
            put(0x1455, "Deutsche Telekom AG");
            put(0x1456, "Sensirion AG");
            put(0x1457, "Hangzhou Wistar Mechanical &amp; Electric Technology Co., Ltd");
            put(0x1458, "Wilhelm Koch GmbH ");
            put(0x1459, "Shenzhen iComm Semiconductor Co., Ltd.");
            put(0x145a, "British Telecommunications plc");
            put(0x145b, "Remotec Technology Ltd.");
            put(0x145c, "Pin Genie, Inc. DBA Lockly");
            put(0x145d, "Hosiden Corporation");
            put(0x145e, "Deako, Inc.");
            put(0x145f, "Good Way Technology Co., Ltd.");
            put(0x1460, "Zhuhai Ruran Intelligent Technology Co., LTD (Meizu)");
            put(0x1461, "Xinda Asset Management (Shenzhen) Co.,Ltd.");
            put(0x1462, "Chengdu Energy Magic Cube Technology Co., Ltd");
            put(0x1463, "Eberle Controls GmbH");
            put(0x1464, "Opulinks Technology");
            put(0x1465, "Hunter Douglas Group");
            put(0x1466, "Hangzhou Hemos Lighting Company Limited");
            put(0x1467, "OTODO SAS");
            put(0x1468, "Anona Security Technology Limited");
            put(0x1469, "Loxone Electronics GmbH");
            put(0x146a, "Intecular LLC");
            put(0x146b, "Aixlink Ltd.");
            put(0x146c, "Shenzhen Jinjie Technology Co.,Ltd.");
            put(0x146d, "Polyaire Pty Ltd");
            put(0x146e, "Shenzhen PINXUAN Trading Co.");
            put(0x146f, "SmartWing Home LLC");
            put(0x1470, "Shenzhen Hope Microelectronics Co., Ltd.");
            put(0x1471, "Commax");
            put(0x1472, "Zhejiang Jiecang Linear Motion Technology Co.,Ltd");
            put(0x1473, "Shenzhen Lelight technology Co.lt");
            put(0x1474, "Shenzhen Ruomu Zhilian Technology Co., Ltd.");
            put(0x1475, "Cable Television Laboratories, Inc. dba CableLabs");
            put(0x1476, "Harman International");
            put(0x1477, "Shenzhen Multi IR Technology Co.,Ltd");
            put(0x1478, "APYNOV");
            put(0x1479, "Browan Communications Inc.");
            put(0x147a, "Shenzhen Realwe Innovation Technology Co., Ltd.");
            put(0x147b, "Lumiflow INC");
            put(0x147c, "SHENZHEN SHENAN YANGGUANG ELECTRONICS CO., LTD.");
            put(0x147d, "Wenzhou Morning Electronics Co., Ltd.");
            put(0x147e, "MIWA Lock Co., Ltd.");
            put(0x147f, "U-tec Group Inc.");
            put(0x1480, "Beijing Roborock Technology Co., Ltd.");
            put(0x1481, "Shenzhen Xenon Industrial Ltd");
            put(0x1482, "Guangzhou Lingqu Electronic Technology Co., Ltd");
            put(0x1483, "Shenzhen Jijia Intelligent Technology Co., Ltd.");
            put(0x1484, "CANDY HOUSE, Inc.");
            put(0x1485, "ELIT Scandinavia ApS");
            put(0x1486, "Infibrite Inc");
            put(0x1487, "Whirlpool Corp.");
            put(0x1488, "Shortcut Labs (Flic)");
            put(0x1489, "INTEREL BUILDING AUTOMATION");
            put(0x148a, "Occhio GmbH");
            put(0x148b, "Samraj Technologies Limited");
            put(0x1994, "Gewiss S.p.A.");
            put(0x2794, "Climax Technology Co., Ltd.");
            put(0x6006, "Google LLC");
            put(0xc5a0, "Connectivity Standards Alliance");
            put(0xc5a1, "Connectivity Standards Alliance");
            put(0xc5a2, "Connectivity Standards Alliance");
            put(0xc5a3, "Connectivity Standards Alliance");
            put(0xc5a4, "Connectivity Standards Alliance");
            put(0xc5a5, "Connectivity Standards Alliance");
            put(0xc5a6, "Connectivity Standards Alliance");
            put(0xc5a7, "Connectivity Standards Alliance");
            put(0xc5a8, "Connectivity Standards Alliance");
            put(0xc5a9, "Connectivity Standards Alliance");
            put(0xc5aa, "Connectivity Standards Alliance");
            put(0xc5ab, "Connectivity Standards Alliance");
            put(0xc5ac, "Connectivity Standards Alliance");
            put(0xc5ad, "Connectivity Standards Alliance");
            put(0xc5ae, "Connectivity Standards Alliance");
            put(0xc5af, "Connectivity Standards Alliance");
            put(0xfff1, "[Test vendor #1]");
            put(0xfff2, "[Test vendor #2]");
            put(0xfff3, "[Test vendor #3]");
            put(0xfff4, "[Test vendor #4]");
            put(0xfff5, "[Reserved]");
            put(0xfff6, "[Reserved]");
            put(0xfff7, "[Reserved]");
            put(0xfff8, "[Reserved]");
            put(0xfff9, "[Reserved]");
            put(0xfffa, "[Reserved]");
            put(0xfffb, "[Reserved]");
            put(0xfffc, "[Reserved]");
            put(0xfffd, "[Reserved]");
            put(0xfffe, "[Reserved]");
            put(0xffff, "[Reserved]");
        }
    };
}
