/**
 * Copyright (c) 2014-2016 by the respective copyright holders.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
package org.openhab.binding.zwave.internal.protocol;

import static org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveCommandClass.CommandClass.*;

import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveCommandClass.CommandClass;

/**
 * Z-Wave Plus device type class. Defines the zwave plus device types and the mandatory command classes.
 *
 * @author Jorg de Jong
 */
public class ZWavePlusDeviceClass {
    private static Map<Integer, ZWavePlusInfo> zwavePlusDeviceTypes = new HashMap<>();

    public enum ZWavePlusDeviceType {
        UNKNOWN_TYPE(0x0000),
        CENTRAL_CONTROLLER(0x0100),
        DISPLAY_SIMPLE(0x0200),
        DOOR_LOCK_KEYPAD(0x0300),
        FAN_SWITCH(0x0400),
        GATEWAY(0x0500),
        LIGHT_DIMMER_SWITCH(0x0600),
        ON_OFF_POWER_SWITCH(0x0700),
        POWER_STRIP(0x0800),
        REMOTE_CONTROL_AV(0x0900),
        REMOTE_CONTROL_MULTI_PURPOSE(0x0a00),
        REMOTE_CONTROL_SIMPLE(0x0b00),
        KEY_FOB(0x0b01),
        SENSOR_NOTIFICATION(0x0c00),
        SMOKE_ALARM_SENSOR(0x0c01),
        CO_ALARM_SENSOR(0x0c02),
        CO2_ALARM_SENSOR(0x0c03),
        HEAT_ALARM_SENSOR(0x0c04),
        WATER_ALARM_SENSOR(0x0c05),
        ACCESS_CONTROL_SENSOR(0x0c06),
        HOME_SECURITY_SENSOR(0x0c07),
        POWER_MANAGEMENT_SENSOR(0x0c08),
        SYSTEM_SENSOR(0x0c09),
        EMERGENCY_ALARM_SENSOR(0x0c0a),
        CLOCK_SENSOR(0x0c0b),
        MULTIDEVICE_NOTIFICATION_SENSOR(0x0cff),
        MULTILEVEL_SENSOR(0x0d00),
        AIR_TEMPERATURE_SENSOR(0x0d01),
        GENERAL_PURPOSE_SENSOR(0x0d02),
        LUMINANCE_SENSOR(0x0d03),
        POWER_SENSOR(0x0d04),
        HUMIDITY_SENSOR(0x0d05),
        VELOCITY_SENSOR(0x0d06),
        DIRECTION_SENSOR(0x0d07),
        ATMOSPHERIC_PRESSURE_SENSOR(0x0d08),
        BAROMETRIC_PRESSURE_SENSOR(0x0d09),
        SOLAR_RADIATION_SENSOR(0x0d0a),
        DEW_POINT_SENSOR(0x0d0b),
        RAIN_RATE_SENSOR(0x0d0c),
        TIDE_LEVEL_SENSOR(0x0d0d),
        WEIGHT_SENSOR(0x0d0e),
        VOLTAGE_SENSOR(0x0d0f),
        CURRENT_SENSOR(0x0d10),
        CO2_LEVEL_SENSOR(0x0d11),
        AIR_FLOW_SENSOR(0x0d12),
        TANK_CAPACITY_SENSOR(0x0d13),
        DISTANCE_SENSOR(0x0d14),
        ANGLE_POSTITION_SENSOR(0x0d15),
        ROTATION_SENSOR(0x0d16),
        WATER_TEMPERATURE_SENSOR(0x0d17),
        SOIL_TEMPERATURE_SENSOR(0x0d18),
        SEISMIC_INTENSITY_SENSOR(0x0d19),
        SEISMIC_MAGNITUDE_SENSOR(0x0d1a),
        ULTRAVIOLET_SENSOR(0x0d1b),
        ELECTRICAL_RESISTIVITY_SENSOR(0x0d1c),
        ELECTRICAL_CONDUCTIVITY_SENSOR(0x0b1d),
        LOUDNESS_SENSOR(0x0b1e),
        MOISTURE_SENSOR(0x0b1f),
        FREQUENCY_SENSOR(0x0b20),
        TIME_SENSOR(0x0b21),
        TARGET_TEMPERATURE_SENSOR(0x0b22),
        MULTIDEVICE_SENSOR(0x0bff),
        SET_TOP_BOX(0x0e00),
        SIREN(0x0f00),
        SUB_ENERGY_METER(0x1000),
        SUB_SYSTEM_CONTROLLER(0x1100),
        THERMOSTAT_HVAC(0x1200),
        THERMOSTAT_SETBACK(0x1300),
        TV(0x1400),
        VALVE_OPEN_CLOSE(0x1500),
        WALL_CONTROLLER(0x1600),
        WHOLE_HOME_METER_SIMPLE(0x1700),
        WINDOW_COVERING_NO_POSITION_ENDPOINT(0x1800),
        WINDOW_COVERING_ENDPOINT_AWARE(0x1900),
        WINDOW_COVERING_POSITION_ENDPOINT_AWARE(0x1a00);

        private int key;

        ZWavePlusDeviceType(int key) {
            this.key = key;
        }

        public int getKey() {
            return key;
        }
    }

    private static void setup() {
        // @formatter:off
        List<ZWavePlusInfo> initdata = Arrays.asList(
            new ZWavePlusInfo(ZWavePlusDeviceType.UNKNOWN_TYPE),
            new ZWavePlusInfo(ZWavePlusDeviceType.CENTRAL_CONTROLLER, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, CRC_16_ENCAP, APPLICATION_STATUS),
            new ZWavePlusInfo(ZWavePlusDeviceType.DISPLAY_SIMPLE, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION),
            new ZWavePlusInfo(ZWavePlusDeviceType.DOOR_LOCK_KEYPAD, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, DOOR_LOCK, USER_CODE, BATTERY),
            new ZWavePlusInfo(ZWavePlusDeviceType.FAN_SWITCH, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SWITCH_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.GATEWAY, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, CRC_16_ENCAP, MULTI_INSTANCE, MULTI_INSTANCE_ASSOCIATION, WAKE_UP,APPLICATION_STATUS),
            new ZWavePlusInfo(ZWavePlusDeviceType.LIGHT_DIMMER_SWITCH, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SWITCH_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.ON_OFF_POWER_SWITCH, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SWITCH_BINARY),
            new ZWavePlusInfo(ZWavePlusDeviceType.POWER_STRIP, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, MULTI_INSTANCE, MULTI_INSTANCE_ASSOCIATION, SWITCH_BINARY),
            new ZWavePlusInfo(ZWavePlusDeviceType.REMOTE_CONTROL_AV, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION),
            new ZWavePlusInfo(ZWavePlusDeviceType.REMOTE_CONTROL_MULTI_PURPOSE, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION,WAKE_UP),
            new ZWavePlusInfo(ZWavePlusDeviceType.REMOTE_CONTROL_SIMPLE, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, CENTRAL_SCENE),
            new ZWavePlusInfo(ZWavePlusDeviceType.KEY_FOB, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, CENTRAL_SCENE),
            new ZWavePlusInfo(ZWavePlusDeviceType.SENSOR_NOTIFICATION, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY),
            new ZWavePlusInfo(ZWavePlusDeviceType.SMOKE_ALARM_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY),
            new ZWavePlusInfo(ZWavePlusDeviceType.CO_ALARM_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY),
            new ZWavePlusInfo(ZWavePlusDeviceType.CO2_ALARM_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY),
            new ZWavePlusInfo(ZWavePlusDeviceType.HEAT_ALARM_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY),
            new ZWavePlusInfo(ZWavePlusDeviceType.WATER_ALARM_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY),
            new ZWavePlusInfo(ZWavePlusDeviceType.ACCESS_CONTROL_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY),
            new ZWavePlusInfo(ZWavePlusDeviceType.HOME_SECURITY_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY),
            new ZWavePlusInfo(ZWavePlusDeviceType.POWER_MANAGEMENT_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY),
            new ZWavePlusInfo(ZWavePlusDeviceType.SYSTEM_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY),
            new ZWavePlusInfo(ZWavePlusDeviceType.EMERGENCY_ALARM_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY),
            new ZWavePlusInfo(ZWavePlusDeviceType.CLOCK_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY),
            new ZWavePlusInfo(ZWavePlusDeviceType.MULTIDEVICE_NOTIFICATION_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY),
            new ZWavePlusInfo(ZWavePlusDeviceType.MULTILEVEL_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.AIR_TEMPERATURE_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.GENERAL_PURPOSE_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.LUMINANCE_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.POWER_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.HUMIDITY_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.VELOCITY_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.DIRECTION_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.ATMOSPHERIC_PRESSURE_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.BAROMETRIC_PRESSURE_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.SOLAR_RADIATION_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.DEW_POINT_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.RAIN_RATE_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.TIDE_LEVEL_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.WEIGHT_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.VOLTAGE_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.CURRENT_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.CO2_LEVEL_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.AIR_FLOW_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.TANK_CAPACITY_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.DISTANCE_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.ANGLE_POSTITION_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.ROTATION_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.WATER_TEMPERATURE_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.SOIL_TEMPERATURE_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.SEISMIC_INTENSITY_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.SEISMIC_MAGNITUDE_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.ULTRAVIOLET_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.ELECTRICAL_RESISTIVITY_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.ELECTRICAL_CONDUCTIVITY_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.LOUDNESS_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.MOISTURE_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.FREQUENCY_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.TIME_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.TARGET_TEMPERATURE_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.MULTIDEVICE_SENSOR, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(ZWavePlusDeviceType.SET_TOP_BOX, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, CRC_16_ENCAP, MULTI_INSTANCE, MULTI_INSTANCE_ASSOCIATION, WAKE_UP, APPLICATION_STATUS),
            new ZWavePlusInfo(ZWavePlusDeviceType.SIREN, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION),
            new ZWavePlusInfo(ZWavePlusDeviceType.SUB_ENERGY_METER, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, CRC_16_ENCAP, METER),
            new ZWavePlusInfo(ZWavePlusDeviceType.SUB_SYSTEM_CONTROLLER, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, MULTI_INSTANCE, WAKE_UP, APPLICATION_STATUS),
            new ZWavePlusInfo(ZWavePlusDeviceType.THERMOSTAT_HVAC, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, THERMOSTAT_SETPOINT, THERMOSTAT_MODE),
            new ZWavePlusInfo(ZWavePlusDeviceType.THERMOSTAT_SETBACK, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, THERMOSTAT_SETPOINT),
            new ZWavePlusInfo(ZWavePlusDeviceType.TV, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, CRC_16_ENCAP, MULTI_INSTANCE, MULTI_INSTANCE_ASSOCIATION, WAKE_UP, APPLICATION_STATUS),
            new ZWavePlusInfo(ZWavePlusDeviceType.VALVE_OPEN_CLOSE, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SWITCH_MULTILEVEL, SWITCH_BINARY),
            new ZWavePlusInfo(ZWavePlusDeviceType.WALL_CONTROLLER, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, CENTRAL_SCENE),
            new ZWavePlusInfo(ZWavePlusDeviceType.WHOLE_HOME_METER_SIMPLE, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, CRC_16_ENCAP, METER),
            new ZWavePlusInfo(ZWavePlusDeviceType.WINDOW_COVERING_NO_POSITION_ENDPOINT, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION,VERSION, SWITCH_MULTILEVEL, SWITCH_BINARY),
            new ZWavePlusInfo(ZWavePlusDeviceType.WINDOW_COVERING_ENDPOINT_AWARE, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SWITCH_MULTILEVEL, SWITCH_BINARY),
            new ZWavePlusInfo(ZWavePlusDeviceType.WINDOW_COVERING_POSITION_ENDPOINT_AWARE, DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SWITCH_MULTILEVEL, SWITCH_BINARY));
        // @formatter:on
        for (ZWavePlusInfo c : initdata) {
            zwavePlusDeviceTypes.put(c.getType().getKey(), c);
        }
    }

    /**
     * Lookup the zwavePlus Device info.
     *
     * @param zwPlusDeviceType the device type
     * @return the device info if available
     */
    public static ZWavePlusInfo getZWavePlusInfo(int zwPlusDeviceType) {
        if (zwavePlusDeviceTypes.isEmpty()) {
            setup();
        }
        return zwavePlusDeviceTypes.get(zwPlusDeviceType);
    }

    /**
     * Contains the Zwave Plus Device type info.
     */
    public static class ZWavePlusInfo {
        private ZWavePlusDeviceType type;

        public ZWavePlusDeviceType getType() {
            return type;
        }

        private Set<CommandClass> mandatoryCommandClasses = new HashSet<>();

        ZWavePlusInfo(ZWavePlusDeviceType type, CommandClass... classes) {
            this.type = type;
            mandatoryCommandClasses.addAll(Arrays.asList(classes));
        }

        public Set<CommandClass> getMandatoryCommandClasses() {
            return mandatoryCommandClasses;
        }
    }
}
