/**
 * Copyright (c) 2014-2016 by the respective copyright holders.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
package org.openhab.binding.zwave.internal.protocol;

import static org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveCommandClass.CommandClass.*;

import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveCommandClass.CommandClass;

/**
 * Z-Wave Plus device type class. Defines the zwave plus device types and the mandatory command classes.
 *
 * @author Jorg de Jong
 */
public class ZWavePlusDeviceType {
    private static Map<Integer, ZWavePlusInfo> zwavePlusDeviceTypes = new HashMap<>();

    private static void setup() {
        // @formatter:off
        List<ZWavePlusInfo> initdata = Arrays.asList(new ZWavePlusInfo(0x0000, "Unknown Type"),
            new ZWavePlusInfo(0x0100, "Central Controller", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, CRC_16_ENCAP, APPLICATION_STATUS),
            new ZWavePlusInfo(0x0200, "Display Simple", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION),
            new ZWavePlusInfo(0x0300, "Door Lock Keypad", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, DOOR_LOCK, USER_CODE, BATTERY),
            new ZWavePlusInfo(0x0400, "Fan Switch", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SWITCH_MULTILEVEL),
            new ZWavePlusInfo(0x0500, "Gateway", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, CRC_16_ENCAP, MULTI_INSTANCE, MULTI_INSTANCE_ASSOCIATION, WAKE_UP,APPLICATION_STATUS),
            new ZWavePlusInfo(0x0600, "Light Dimmer Switch", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SWITCH_MULTILEVEL),
            new ZWavePlusInfo(0x0700, "On/Off Power Switch", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SWITCH_BINARY),
            new ZWavePlusInfo(0x0800, "Power Strip", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, MULTI_INSTANCE, MULTI_INSTANCE_ASSOCIATION, SWITCH_BINARY),
            new ZWavePlusInfo(0x0900, "Remote Control AV", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION),
            new ZWavePlusInfo(0x0a00, "Remote Control Multi Purpose", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION,WAKE_UP),
            new ZWavePlusInfo(0x0b00, "Remote Control Simple", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, CENTRAL_SCENE),
            new ZWavePlusInfo(0x0b01, "Key Fob", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, CENTRAL_SCENE),
            new ZWavePlusInfo(0x0c00, "Sensor Notification", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY),
            new ZWavePlusInfo(0x0c01, "Smoke Alarm Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY),
            new ZWavePlusInfo(0x0c02, "CO Alarm Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY),
            new ZWavePlusInfo(0x0c03, "CO2 Alarm Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY),
            new ZWavePlusInfo(0x0c04, "Heat Alarm Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY),
            new ZWavePlusInfo(0x0c05, "Water Alarm Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY),
            new ZWavePlusInfo(0x0c06, "Access Control Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY),
            new ZWavePlusInfo(0x0c07, "Home Security Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY),
            new ZWavePlusInfo(0x0c08, "Power Management Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY),
            new ZWavePlusInfo(0x0c09, "System Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY),
            new ZWavePlusInfo(0x0c0a, "Emergency Alarm Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY),
            new ZWavePlusInfo(0x0c0b, "Clock Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY),
            new ZWavePlusInfo(0x0cff, "MultiDevice Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY),
            new ZWavePlusInfo(0x0d00, "Multilevel Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(0x0d01, "Air Temperature Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(0x0d02, "General Purpose Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(0x0d03, "Luminance Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(0x0d04, "Power Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(0x0d05, "Humidity Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(0x0d06, "Velocity Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(0x0d07, "Direction Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(0x0d08, "Atmospheric Pressure Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(0x0d09, "Barometric Pressure Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(0x0d0a, "Solar Radiation Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(0x0d0b, "Dew Point Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(0x0d0c, "Rain Rate Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(0x0d0d, "Tide Level Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(0x0d0e, "Weight Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(0x0d0f, "Voltage Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(0x0d10, "Current Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(0x0d11, "CO2 Level Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(0x0d12, "Air Flow Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(0x0d13, "Tank Capacity Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(0x0d14, "Distance Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(0x0d15, "Angle Postition Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(0x0d16, "Rotation Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(0x0d17, "Water Temperature Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(0x0d18, "Soil Temperature Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(0x0d19, "Seismic Intensity Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(0x0d1a, "Seismic Magnitude Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(0x0d1b, "Ultraviolet Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(0x0d1c, "Electrical Resistivity Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(0x0b1d, "Electrical Conductivity Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(0x0b1e, "Loudness Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(0x0b1f, "Moisture Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(0x0b20, "Frequency Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(0x0b21, "Time Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(0x0b22, "Target Temperature Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(0x0bff, "MultiDevice Sensor", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SENSOR_BINARY, SENSOR_MULTILEVEL),
            new ZWavePlusInfo(0x0e00, "Set Top Box", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, CRC_16_ENCAP, MULTI_INSTANCE, MULTI_INSTANCE_ASSOCIATION, WAKE_UP, APPLICATION_STATUS),
            new ZWavePlusInfo(0x0f00, "Siren", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION),
            new ZWavePlusInfo(0x1000, "Sub Energy Meter", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, CRC_16_ENCAP, METER),
            new ZWavePlusInfo(0x1100, "Sub System Controller", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, MULTI_INSTANCE, WAKE_UP, APPLICATION_STATUS),
            new ZWavePlusInfo(0x1200, "Thermostat HVAC", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, THERMOSTAT_SETPOINT, THERMOSTAT_MODE),
            new ZWavePlusInfo(0x1300, "Thermostat Setback", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, THERMOSTAT_SETPOINT),
            new ZWavePlusInfo(0x1400, "TV", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, CRC_16_ENCAP, MULTI_INSTANCE, MULTI_INSTANCE_ASSOCIATION, WAKE_UP, APPLICATION_STATUS),
            new ZWavePlusInfo(0x1500, "Valve open/close", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SWITCH_MULTILEVEL, SWITCH_BINARY),
            new ZWavePlusInfo(0x1600, "Wall Controller", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, CENTRAL_SCENE),
            new ZWavePlusInfo(0x1700, "Whole Home Meter Simple", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, CRC_16_ENCAP, METER),
            new ZWavePlusInfo(0x1800, "Window Covering No Position/Endpoint", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION,VERSION, SWITCH_MULTILEVEL, SWITCH_BINARY),
            new ZWavePlusInfo(0x1900, "Window Covering Endpoint Aware", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SWITCH_MULTILEVEL, SWITCH_BINARY),
            new ZWavePlusInfo(0x1a00, "Window Covering Position/Endpoint Aware", DEVICE_RESET_LOCALLY, ZWAVE_PLUS_INFO, ASSOCIATION_GROUP_INFO, MANUFACTURER_SPECIFIC, POWERLEVEL, ASSOCIATION, VERSION, SWITCH_MULTILEVEL, SWITCH_BINARY));
        // @formatter:on
        for (ZWavePlusInfo c : initdata) {
            zwavePlusDeviceTypes.put(c.getKey(), c);
        }
    }

    /**
     * Lookup the zwavePlus Device info.
     *
     * @param zwPlusDeviceType the device type
     * @return the device info if available
     */
    public static ZWavePlusInfo getZWavePlusInfo(int zwPlusDeviceType) {
        if (zwavePlusDeviceTypes.isEmpty()) {
            setup();
        }
        return zwavePlusDeviceTypes.get(zwPlusDeviceType);
    }

    /**
     * Contains the Zwave Plus Device type info.
     */
    public static class ZWavePlusInfo {
        private int key;
        private String label;
        private Set<CommandClass> mandatoryCommandClasses = new HashSet<>();

        ZWavePlusInfo(int key, String label, CommandClass... classes) {
            this.key = key;
            this.label = label;
            mandatoryCommandClasses.addAll(Arrays.asList(classes));
        }

        public int getKey() {
            return key;
        }

        public String getLabel() {
            return label;
        }

        public Set<CommandClass> getMandatoryCommandClasses() {
            return mandatoryCommandClasses;
        }
    }
}
