/**
 * Copyright (c) 2010-2017 by the respective copyright holders.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
package org.openhab.binding.nibeuplink.internal.model;

/**
 * list of all available channels
 *
 * @author Alexander Friese - initial contribution
 *
 */
public enum F750Channels implements Channel {

    CH_32260("32260", "NIBE Inverter 216-state", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40004("40004", "BT1 Outdoor Temperature", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40005("40005", "EP23-BT2 Supply temp S4", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40006("40006", "EP22-BT2 Supply temp S3", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40007("40007", "EP21-BT2 Supply temp S2", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40008("40008", "BT2 Supply temp S1", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40012("40012", "EB100-EP14-BT3 Return temp", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40013("40013", "BT7 HW Top", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40014("40014", "BT6 HW Load", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40017("40017", "EB100-EP14-BT12 Condensor Out", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40018("40018", "EB100-EP14-BT14 Hot Gas Temp", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40019("40019", "EB100-EP14-BT15 Liquid Line", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40020("40020", "EB100-BT16 Evaporator temp", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40022("40022", "EB100-EP14-BT17 Suction", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40025("40025", "BT20 Exhaust air temp. 1", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40026("40026", "BT21 Vented air temp. 1", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40030("40030", "EP23-BT50 Room Temp S4", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40031("40031", "EP22-BT50 Room Temp S3", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40032("40032", "EP21-BT50 Room Temp S2", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40033("40033", "BT50 Room Temp S1", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40043("40043", "BT53 Solar Panel Temp", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40044("40044", "BT54 Solar Load Temp", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40047("40047", "EB100-BT61 Supply Radiator Temp", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40048("40048", "EB100-BT62 Return Radiator Temp", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40050("40050", "EB100-BS1 Air flow", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40051("40051", "EB100-BS1 Air flow unfiltered", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40054("40054", "EB100-FD1 Temperature limiter", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40067("40067", "BT1 Average", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40071("40071", "BT25 Ext. Supply", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40072("40072", "BF1 EP14 Flow", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40074("40074", "EB100-FR1 Anode Status", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40077("40077", "BT6 external water heater load temp.", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40078("40078", "BT7 external water heater top temp.", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40079("40079", "EB100-BE3 Current", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40081("40081", "EB100-BE2 Current", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40083("40083", "EB100-BE1 Current", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40122("40122", "BT52 external water heater load temp.", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40127("40127", "EP23-BT3 Return temp S4", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40128("40128", "EP22-BT3 Return temp S3", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40129("40129", "EP21-BT3 Return temp S2", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40141("40141", "AZ2-BT22 Supply air temp. SAM", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40142("40142", "AZ2-BT23 Outdoor temp. SAM", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40143("40143", "AZ2-BT68 Flow temp. SAM", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40144("40144", "AZ2-BT69 Return temp. SAM", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40157("40157", "EP30-BT53 Solar Panel Temp", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40158("40158", "EP30-BT54 Solar Load Temp", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40159("40159", "EP47-BT2 Supply temp S8", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40160("40160", "EP46-BT2 Supply temp S7", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40161("40161", "EP45-BT2 Supply temp S6", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40162("40162", "EP44-BT2 Supply temp S5", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40163("40163", "EP47-BT3 Return temp S8", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40164("40164", "EP46-BT3 Return temp S7", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40165("40165", "EP45-BT3 Return temp S6", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40166("40166", "EP44-BT3 Return temp S5", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40167("40167", "EP47-BT50 Room Temp S8", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40168("40168", "EP46-BT50 Room Temp S7", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40169("40169", "EP45-BT50 Room Temp S6", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40170("40170", "EP44-BT50 Room Temp S5", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40185("40185", "BT1 Average, 1h", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40188("40188", "EP47-BT50 Room Temp S8 Average", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40189("40189", "EP46-BT50 Room Temp S7 Average", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40190("40190", "EP45-BT50 Room Temp S6 Average", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40191("40191", "EP44-BT50 Room Temp S5 Average", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40192("40192", "EP23-BT50 Room Temp S4 Average", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40193("40193", "EP22-BT50 Room Temp S3 Average", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40194("40194", "EP21-BT50 Room Temp S2 Average", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40195("40195", "BT50 Room Temp S1 Average", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40212("40212", "BT74 Average", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40217("40217", "Calc. Supply S8", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40218("40218", "Calc. Supply S7", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40219("40219", "Calc. Supply S6", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40220("40220", "Calculated Supply S5", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40305("40305", "Mixing Valve State S8", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40306("40306", "Mixing Valve State S7", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40307("40307", "Mixing Valve State S6", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40308("40308", "Mixing Valve State S5", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40316("40316", "Inverter limit status", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40317("40317", "Inverter drive status", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40321("40321", "Compressor Frequency, Request", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40322("40322", "Max Compressor Frequency, Heating", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40323("40323", "Inverter alarm code", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40324("40324", "Inverter fault code", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40326("40326", "Inverter drive command", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40327("40327", "NIBE Inverter Pic version", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40328("40328", "NIBE Inverter 8051 version", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40329("40329", "NIBE Inverter Def. Wizard", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40330("40330", "NIBE Inverter Mce version", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40331("40331", "NIBE Inverter Hw version", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40332("40332", "NIBE Inverter Hw type", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40339("40339", "External adjustment activated via input S8", ChannelType.SENSOR, ChannelGroup.SENSOR,
            String.class),
    CH_40340("40340", "External adjustment activated via input S7", ChannelType.SENSOR, ChannelGroup.SENSOR,
            String.class),
    CH_40341("40341", "External adjustment activated via input S6", ChannelType.SENSOR, ChannelGroup.SENSOR,
            String.class),
    CH_40342("40342", "External adjustment activated via input S5", ChannelType.SENSOR, ChannelGroup.SENSOR,
            String.class),
    CH_40364("40364", "AHPS Docking blocked", ChannelType.SENSOR, ChannelGroup.SENSOR, String.class),
    CH_40365("40365", "Extra heating system pump S8", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40366("40366", "Extra heating system pump S7", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40367("40367", "Extra heating system pump S6", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40368("40368", "Extra heating system pump S5", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40370("40370", "AHPS Docking accessory relays", ChannelType.SENSOR, ChannelGroup.SENSOR, String.class),
    CH_40755("40755", "Tot. ext. HW add op.time", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40760("40760", "Hz unlimited", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40762("40762", "Reg. state AHPS Docking shunt", ChannelType.SENSOR, ChannelGroup.SENSOR, String.class),
    CH_40763("40763", "AHPS Docking calc. supply temp.", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40771("40771", "Heat Meter - Pool2 Cpr EP14", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40792("40792", "OPT state", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40793("40793", "OPT version", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40801("40801", "OPT rel. modulation level", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40802("40802", "OPT boiler temperature", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40806("40806", "OPT boiler op. time", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40868("40868", "+Adjust AUX Port", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40870("40870", "+Adjust OP mode", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40871("40871", "+Adjust Comfort mode", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40872("40872", "+Adjust Parallell adjustment", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40873("40873", "+Adjust Humidity", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40874("40874", "+Adjust Temp indoor", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40875("40875", "+Adjust Temp outdoor", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40876("40876", "+Adjust Version", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40877("40877", "+Adjust Activated", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40878("40878", "+Adjust Need", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40889("40889", "BT64 Average", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40918("40918", "EB100-FD3 Temperature limiter", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40933("40933", "Defrosting time", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40940("40940", "Degree Minutes (32 bit)", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_40993("40993", "Inverter min speed", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_40994("40994", "Inverter max speed", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_41026("41026", "EB100-Adjusted BS1 Air flow", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_41027("41027", "Humidity average", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_41186("41186", "Set point OPT boiler", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_41189("41189", "AA20-BE5 EME10 Current", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_41190("41190", "AA20-BE5 EME10 Average Current", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_41191("41191", "AA20 PV Panel State", ChannelType.SENSOR, ChannelGroup.SENSOR, String.class),
    CH_41214("41214", "OEK accessory block status", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_41256("41256", "Fan speed current", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_41257("41257", "Fan speed current", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_41258("41258", "Fan speed current", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_41265("41265", "Smart Home Mode", ChannelType.SENSOR, ChannelGroup.SENSOR, String.class),
    CH_41266("41266", "Offset to smart home system", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_41267("41267", "Smart Home ctrl syst 8", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_41268("41268", "Smart Home ctrl syst 7", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_41269("41269", "Smart Home ctrl syst 6", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_41270("41270", "Smart Home ctrl syst 5", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_41271("41271", "Smart Home ctrl syst 4", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_41272("41272", "Smart Home ctrl syst 3", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_41273("41273", "Smart Home ctrl syst 2", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_41274("41274", "Smart Home ctrl syst 1", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_41287("41287", "OPT boiler has priority hot water", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_41393("41393", "Smart energy source, energy source prio 7, start DM", ChannelType.SENSOR, ChannelGroup.SENSOR,
            Double.class),
    CH_41395("41395", "Smart energy source, energy source prio 6, start DM", ChannelType.SENSOR, ChannelGroup.SENSOR,
            Double.class),
    CH_41397("41397", "Smart energy source, energy source prio 5, start DM", ChannelType.SENSOR, ChannelGroup.SENSOR,
            Double.class),
    CH_41399("41399", "Smart energy source, energy source prio 4, start DM", ChannelType.SENSOR, ChannelGroup.SENSOR,
            Double.class),
    CH_41401("41401", "Smart energy source, energy source prio 3, start DM", ChannelType.SENSOR, ChannelGroup.SENSOR,
            Double.class),
    CH_41403("41403", "Smart energy source, energy source prio 2, start DM", ChannelType.SENSOR, ChannelGroup.SENSOR,
            Double.class),
    CH_41405("41405", "Smart energy source, energy source prio 1, start DM", ChannelType.SENSOR, ChannelGroup.SENSOR,
            Double.class),
    CH_41421("41421", "Smart energy source, degree minute min value", ChannelType.SENSOR, ChannelGroup.SENSOR,
            Double.class),
    CH_41424("41424", "Smart energy source, actual OPT10 addition price", ChannelType.SENSOR, ChannelGroup.SENSOR,
            Double.class),
    CH_41425("41425", "Smart energy source, actual shunt add price", ChannelType.SENSOR, ChannelGroup.SENSOR,
            Double.class),
    CH_41426("41426", "Smart energy source, actual ext. step add price", ChannelType.SENSOR, ChannelGroup.SENSOR,
            Double.class),
    CH_41427("41427", "Smart energy source, actual electricity price", ChannelType.SENSOR, ChannelGroup.SENSOR,
            Double.class),
    CH_41928("41928", "Smart Price Adaption Price", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_41929("41929", "Smart Price Adaption Price Level", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_41930("41930", "AA20-BE5 Power 10", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_42034("42034", "AA20 PV Panel Pool Offset", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43001("43001", "Software version", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43005("43005", "Degree Minutes (16 bit)", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_43006("43006", "Calc. Supply S4", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43007("43007", "Calc. Supply S3", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43008("43008", "Calc. Supply S2", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43009("43009", "Calc. Supply S1", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43013("43013", "Freeze Protection Status", ChannelType.SENSOR, ChannelGroup.SENSOR, String.class),
    CH_43061("43061", "t. after start timer", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43062("43062", "t. after mode change", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43064("43064", "Heat Medium Flow dT Set Point", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43065("43065", "Heat Medium Flow dT Actual", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43066("43066", "Defrosting time", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43081("43081", "Tot. op.time add.", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43084("43084", "Int. el.add. Power", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43086("43086", "Prio", ChannelType.SENSOR, ChannelGroup.SENSOR, String.class),
    CH_43091("43091", "Int. el.add. State", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43093("43093", "Mixing Valve State S4", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43094("43094", "Mixing Valve State S3", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43095("43095", "Mixing Valve State S2", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43096("43096", "Mixing Valve State S1", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43097("43097", "Status of the shunt controlled additional heat accessory", ChannelType.SENSOR,
            ChannelGroup.SENSOR, String.class),
    CH_43108("43108", "Fan speed current", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43122("43122", "Compr. current min.freq.", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43123("43123", "Compr. current max.freq.", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43124("43124", "Airflow ref.", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43132("43132", "Inverter com. timer", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43136("43136", "Compressor Frequency, Actual", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43140("43140", "Inverter Temperature", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43141("43141", "compr. in power", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43144("43144", "Compr. energy total", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43147("43147", "Compr. in current", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43158("43158", "External adjustment activated via input S4", ChannelType.SENSOR, ChannelGroup.SENSOR,
            String.class),
    CH_43159("43159", "External adjustment activated via input S3", ChannelType.SENSOR, ChannelGroup.SENSOR,
            String.class),
    CH_43160("43160", "External adjustment activated via input S2", ChannelType.SENSOR, ChannelGroup.SENSOR,
            String.class),
    CH_43161("43161", "External adjustment activated via input S1", ChannelType.SENSOR, ChannelGroup.SENSOR,
            String.class),
    CH_43180("43180", "HWC Pump Status GP11", ChannelType.SENSOR, ChannelGroup.SENSOR, String.class),
    CH_43181("43181", "Chargepump speed", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43182("43182", "Compressor Frequency, Target", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43239("43239", "Tot. HW op.time add.", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43305("43305", "Compr. energy HW", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43371("43371", "Hot gas limit status", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43372("43372", "Evaporater limit status", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43375("43375", "compr. in power mean", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43382("43382", "Inverter mem error code", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43416("43416", "Compressor starts EB100-EP14", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43420("43420", "Tot. op.time compr. EB100-EP14", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43424("43424", "Tot. HW op.time compr. EB100-EP14", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43427("43427", "Compressor State EP14", ChannelType.SENSOR, ChannelGroup.SENSOR, String.class),
    CH_43431("43431", "Supply Pump State EP14", ChannelType.SENSOR, ChannelGroup.SENSOR, String.class),
    CH_43435("43435", "Cpr Status EP14", ChannelType.SENSOR, ChannelGroup.SENSOR, String.class),
    CH_43437("43437", "Supply Pump Speed EP14", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43444("43444", "State OEK", ChannelType.SENSOR, ChannelGroup.SENSOR, String.class),
    CH_43514("43514", "EB100 PCA Base Relays EP14", ChannelType.SENSOR, ChannelGroup.SENSOR, String.class),
    CH_43516("43516", "PCA-Power Relays EP14", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43542("43542", "Calculated supply air temp.", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_43561("43561", "Pool 1 blocked", ChannelType.SENSOR, ChannelGroup.SENSOR, String.class),
    CH_44258("44258", "External supply air accessory relays", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_44298("44298", "Heat Meter - HW Cpr and Add EP14", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_44300("44300", "Heat Meter - Heat Cpr and Add EP14", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_44304("44304", "Heat Meter - Pool Cpr EP14", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_44306("44306", "Heat Meter - HW Cpr EP14", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_44308("44308", "Heat Meter - Heat Cpr EP14", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_44317("44317", "SCA accessory relays", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_44331("44331", "Software release", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_44744("44744", "Extra heating system pump S4", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_44745("44745", "Extra heating system pump S3", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_44746("44746", "Extra heating system pump S2", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_44755("44755", "DEW hot water valve", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_44757("44757", "SCA hot water valve", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_44874("44874", "State SG Ready", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_44878("44878", "SG Ready input A", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_44879("44879", "SG Ready input B", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_44896("44896", "Smart Price Adaption Heating Offset", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_44897("44897", "Smart Price Adaption HW Comfort Mode", ChannelType.SENSOR, ChannelGroup.SENSOR, String.class),
    CH_44898("44898", "Smart Price Adaption Pool Offset", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_44899("44899", "Smart Price Adaption Cool Offset", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_44908("44908", "State smart price adaption", ChannelType.SENSOR, ChannelGroup.SENSOR, String.class),
    CH_45001("45001", "Alarm", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_47062("47062", "HW charge offset", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47291("47291", "Floor drying timer", ChannelType.SENSOR, ChannelGroup.SENSOR, Double.class),
    CH_48206("48206", "Silent Mode Status", ChannelType.SENSOR, ChannelGroup.SENSOR, String.class),
    CH_40879("40879", "+Adjust Parallell factor", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_40880("40880", "+Adjust Max change", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_40881("40881", "+Adjust Affect system8", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_40882("40882", "+Adjust Affect system7", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_40883("40883", "+Adjust Affect system6", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_40884("40884", "+Adjust Affect system5", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_40885("40885", "+Adjust Affect system4", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_40886("40886", "+Adjust Affect system3", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_40887("40887", "+Adjust Affect system2", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_40888("40888", "+Adjust Affect system1", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_45171("45171", "Alarm Reset", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47004("47004", "Heat Curve S4", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47005("47005", "Heat Curve S3", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47006("47006", "Heat Curve S2", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47007("47007", "Heat Curve S1", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47008("47008", "Heat Offset S4", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47009("47009", "Heat Offset S3", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47010("47010", "Heat Offset S2", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47011("47011", "Heat Offset S1", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47012("47012", "Min Supply System 4", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47013("47013", "Min Supply System 3", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47014("47014", "Min Supply System 2", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47015("47015", "Min Supply System 1", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47016("47016", "Max Supply System 4", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47017("47017", "Max Supply System 3", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47018("47018", "Max Supply System 2", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47019("47019", "Max Supply System 1", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47020("47020", "Own Heating Curve P7", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47021("47021", "Own Heating Curve P6", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47022("47022", "Own Heating Curve P5", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47023("47023", "Own Heating Curve P4", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47024("47024", "Own Heating Curve P3", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47025("47025", "Own Heating Curve P2", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47026("47026", "Own Heating Curve P1", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47027("47027", "Point offset outdoor temp.", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47028("47028", "Point offset", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47029("47029", "External adjustment S4", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47030("47030", "External adjustment S3", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47031("47031", "External adjustment S2", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47032("47032", "External adjustment S1", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47033("47033", "External adjustment with room sensor S4", ChannelType.SETTING, ChannelGroup.SETTING,
            Double.class),
    CH_47034("47034", "External adjustment with room sensor S3", ChannelType.SETTING, ChannelGroup.SETTING,
            Double.class),
    CH_47035("47035", "External adjustment with room sensor S2", ChannelType.SETTING, ChannelGroup.SETTING,
            Double.class),
    CH_47036("47036", "External adjustment with room sensor S1", ChannelType.SETTING, ChannelGroup.SETTING,
            Double.class),
    CH_47041("47041", "Hot water mode", ChannelType.SETTING, ChannelGroup.SETTING, String.class),
    CH_47043("47043", "Start temperature HW Luxury", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47044("47044", "Start temperature HW Normal", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47045("47045", "Start temperature HW Economy", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47046("47046", "Stop temperature Periodic HW", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47047("47047", "Stop temperature HW Luxury", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47048("47048", "Stop temperature HW Normal", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47049("47049", "Stop temperature HW Economy", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47050("47050", "Periodic HW", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_47051("47051", "Periodic HW Interval", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47054("47054", "Run time HWC", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47055("47055", "Still time HWC", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47092("47092", "Manual compfreq HW", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47093("47093", "Manual compfreq speed HW", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47094("47094", "Sec per compfreq step", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47095("47095", "Max compfreq step", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47096("47096", "Manual compfreq Heating", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47097("47097", "Min speed after start", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47098("47098", "Min speed after HW", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47099("47099", "GMz", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47100("47100", "Max diff VBF-BerVBF", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47101("47101", "Comp freq reg P", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47102("47102", "Comp freq max delta F", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47103("47103", "Min comp freq", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47104("47104", "Max comp freq", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47105("47105", "Comp freq heating", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47131("47131", "Language", ChannelType.SETTING, ChannelGroup.SETTING, String.class),
    CH_47134("47134", "Period HW", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47135("47135", "Period Heat", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47137("47137", "Operational mode", ChannelType.SETTING, ChannelGroup.SETTING, String.class),
    CH_47138("47138", "Operational mode heat medium pump", ChannelType.SETTING, ChannelGroup.SETTING, String.class),
    CH_47206("47206", "DM start heating", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47209("47209", "DM between add. steps", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47210("47210", "DM start add. with shunt", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47212("47212", "Max int add. power", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47214("47214", "Fuse", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47261("47261", "Exhaust Fan speed 4", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47262("47262", "Exhaust Fan speed 3", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47263("47263", "Exhaust Fan speed 2", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47264("47264", "Exhaust Fan speed 1", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47265("47265", "Exhaust Fan speed normal", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47266("47266", "Supply Fan speed 4", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47267("47267", "Supply Fan speed 3", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47268("47268", "Supply Fan speed 2", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47269("47269", "Supply Fan speed 1", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47270("47270", "Supply Fan speed normal", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47271("47271", "Fan return time 4", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47272("47272", "Fan return time 3", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47273("47273", "Fan return time 2", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47274("47274", "Fan return time 1", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47275("47275", "Filter Reminder period", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47276("47276", "Floor drying", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_47277("47277", "Floor drying period 7", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47278("47278", "Floor drying period 6", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47279("47279", "Floor drying period 5", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47280("47280", "Floor drying period 4", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47281("47281", "Floor drying period 3", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47282("47282", "Floor drying period 2", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47283("47283", "Floor drying period 1", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47284("47284", "Floor drying temp. 7", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47285("47285", "Floor drying temp. 6", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47286("47286", "Floor drying temp. 5", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47287("47287", "Floor drying temp. 4", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47288("47288", "Floor drying temp. 3", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47289("47289", "Floor drying temp. 2", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47290("47290", "Floor drying temp. 1", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47294("47294", "Use airflow defrost", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47295("47295", "Airflow reduction trig", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47296("47296", "Airflow defrost done", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47299("47299", "Min time defrost", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47300("47300", "DOT", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47301("47301", "delta T at DOT", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47302("47302", "Climate system 2 accessory", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_47303("47303", "Climate system 3 accessory", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_47304("47304", "Climate system 4 accessory", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_47305("47305", "Climate system 4 mixing valve amp.", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47306("47306", "Climate system 3 mixing valve amp.", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47307("47307", "Climate system 2 mixing valve amp.", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47308("47308", "Climate system 4 shunt wait", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47309("47309", "Climate system 3 shunt wait", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47310("47310", "Climate system 2 shunt wait", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47317("47317", "Shunt controlled add. accessory", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_47318("47318", "Shunt controlled add. min. temp.", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47319("47319", "Shunt controlled add. min. runtime", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47320("47320", "Shunt controlled add. mixing valve amp.", ChannelType.SETTING, ChannelGroup.SETTING,
            Double.class),
    CH_47321("47321", "Shunt controlled add. mixing valve wait", ChannelType.SETTING, ChannelGroup.SETTING,
            Double.class),
    CH_47352("47352", "SMS40 accessory", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_47365("47365", "RMU System 1", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_47366("47366", "RMU System 2", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_47367("47367", "RMU System 3", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_47368("47368", "RMU System 4", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_47370("47370", "Allow Additive Heating", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_47371("47371", "Allow Heating", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_47374("47374", "Start Temperature Cooling", ChannelType.SETTING, ChannelGroup.SETTING, String.class),
    CH_47375("47375", "Stop Temperature Heating", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47376("47376", "Stop Temperature Additive", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47377("47377", "Outdoor Filter Time", ChannelType.SETTING, ChannelGroup.SETTING, String.class),
    CH_47378("47378", "Max diff. comp.", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47379("47379", "Max diff. add.", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47384("47384", "Date format", ChannelType.SETTING, ChannelGroup.SETTING, String.class),
    CH_47385("47385", "Time format", ChannelType.SETTING, ChannelGroup.SETTING, String.class),
    CH_47387("47387", "HW production", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_47388("47388", "Alarm lower room temp.", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_47389("47389", "Alarm lower HW temp.", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_47391("47391", "Use room sensor S4", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_47392("47392", "Use room sensor S3", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_47393("47393", "Use room sensor S2", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_47394("47394", "Use room sensor S1", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_47395("47395", "Room sensor setpoint S4", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47396("47396", "Room sensor setpoint S3", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47397("47397", "Room sensor setpoint S2", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47398("47398", "Room sensor setpoint S1", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47399("47399", "Room sensor factor S4", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47400("47400", "Room sensor factor S3", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47401("47401", "Room sensor factor S2", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47402("47402", "Room sensor factor S1", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47442("47442", "preset flow clim. sys.", ChannelType.SETTING, ChannelGroup.SETTING, String.class),
    CH_47473("47473", "Max time defrost", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47525("47525", "Heat Curve S8", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47537("47537", "Night cooling", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_47538("47538", "Start room temp. night cooling", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47539("47539", "Night Cooling Min. diff.", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_47555("47555", "DEW accessory", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_47567("47567", "Heat Curve S7", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48043("48043", "Holiday - Activated", ChannelType.SETTING, ChannelGroup.SETTING, String.class),
    CH_48072("48072", "DM diff start add.", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48132("48132", "Temporary Lux", ChannelType.SETTING, ChannelGroup.SETTING, String.class),
    CH_48139("48139", "DM startdiff add. with shunt", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48158("48158", "SAM supply air curve: outdoor temp T3", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48159("48159", "SAM supply air curve: outdoor temp T2", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48160("48160", "SAM supply air curve: outdoor temp T1", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48161("48161", "SAM supply air curve: supply air temp at T3", ChannelType.SETTING, ChannelGroup.SETTING,
            Double.class),
    CH_48162("48162", "SAM supply air curve: supply air temp at T2", ChannelType.SETTING, ChannelGroup.SETTING,
            Double.class),
    CH_48163("48163", "SAM supply air curve: supply air temp at T1", ChannelType.SETTING, ChannelGroup.SETTING,
            Double.class),
    CH_48201("48201", "SCA accessory", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48275("48275", "Max charge pump reg speed", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48282("48282", "SG Ready heating", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48283("48283", "SG Ready cooling", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48284("48284", "SG Ready hot water", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48285("48285", "SG Ready pool", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48452("48452", "Auto heat medium pump speed, hw", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48453("48453", "Auto heat medium pump speed, heat", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48454("48454", "Auto heat medium pump speed, pool", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48455("48455", "Auto heat medium pump speed, cool", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48488("48488", "Heat Curve S6", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48489("48489", "Heat Curve S5", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48491("48491", "Heat Offset S8", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48492("48492", "Heat Offset S7", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48493("48493", "Heat Offset S6", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48494("48494", "Heat Offset S5", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48495("48495", "Min Supply System 8", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48496("48496", "Min Supply System 7", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48497("48497", "Min Supply System 6", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48498("48498", "Min Supply System 5", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48499("48499", "Max Supply System 8", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48500("48500", "Max Supply System 7", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48501("48501", "Max Supply System 6", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48502("48502", "Max Supply System 5", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48503("48503", "External adjustment S8", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48504("48504", "External adjustment S7", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48505("48505", "External adjustment S6", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48506("48506", "External adjustment S5", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48507("48507", "External adjustment with room sensor S8", ChannelType.SETTING, ChannelGroup.SETTING,
            Double.class),
    CH_48508("48508", "External adjustment with room sensor S7", ChannelType.SETTING, ChannelGroup.SETTING,
            Double.class),
    CH_48509("48509", "External adjustment with room sensor S6", ChannelType.SETTING, ChannelGroup.SETTING,
            Double.class),
    CH_48510("48510", "External adjustment with room sensor S5", ChannelType.SETTING, ChannelGroup.SETTING,
            Double.class),
    CH_48567("48567", "Initiate inverter", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48568("48568", "Force inverter init", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48569("48569", "Climate system 5 accessory", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48570("48570", "Climate system 6 accessory", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48571("48571", "Climate system 7 accessory", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48572("48572", "Climate system 8 accessory", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48573("48573", "Climate system 8 mixing valve amp.", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48574("48574", "Climate system 7 mixing valve amp.", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48575("48575", "Climate system 6 mixing valve amp.", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48576("48576", "Climate system 5 mixing valve amp.", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48577("48577", "Climate system 8 shunt wait", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48578("48578", "Climate system 7 shunt wait", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48579("48579", "Climate system 6 shunt wait", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48580("48580", "Climate system 5 shunt wait", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48637("48637", "AHPS docking accessory", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48638("48638", "AHPS docking: solar heating", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48639("48639", "AHPS docking: prioritized add.", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48640("48640", "AHPS docking: ext. addition", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48641("48641", "AHPS docking: ext. hot water", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48659("48659", "Cut off frequency activated 2", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48660("48660", "Cut off frequency activated 1", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48661("48661", "Cut off frequency start 2", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48662("48662", "Cut off frequency start 1", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48663("48663", "Cut off frequency stop 2", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48664("48664", "Cut off frequency stop 1", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48675("48675", "Use room sensor S8", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48676("48676", "Use room sensor S7", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48677("48677", "Use room sensor S6", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48678("48678", "Use room sensor S5", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48680("48680", "Room sensor setpoint S8", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48681("48681", "Room sensor setpoint S7", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48682("48682", "Room sensor setpoint S6", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48683("48683", "Room sensor setpoint S5", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48685("48685", "Room sensor factor S8", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48686("48686", "Room sensor factor S7", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48687("48687", "Room sensor factor S6", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48688("48688", "Room sensor factor S5", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48732("48732", "Cool offset S8", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48733("48733", "Cool offset S7", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48734("48734", "Cool offset S6", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48735("48735", "Cool offset S5", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48736("48736", "Cool offset S4", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48737("48737", "Cool offset S3", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48738("48738", "Cool offset S2", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48739("48739", "Cool offset S1", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48743("48743", "Hot water high power mode", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48755("48755", "Transformer ratio", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48794("48794", "RH set value", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48810("48810", "Prevent humidity S8 ", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48811("48811", "Prevent humidity S7", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48812("48812", "Prevent humidity S6", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48813("48813", "Prevent humidity S5", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48814("48814", "Prevent humidity S4", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48815("48815", "Prevent humidity S3", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48816("48816", "Prevent humidity S2", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48817("48817", "Prevent humidity S1", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48828("48828", "OPT", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48889("48889", "MODBUS40 Disable LOG.SET", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48891("48891", "Setting up ventilation", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48908("48908", "Energy Meter Factor X23", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48909("48909", "Energy Meter Factor X22", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48910("48910", "Energy Meter X23", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48911("48911", "Energy Meter X22", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48914("48914", "Max int add. power, SG Ready", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48915("48915", "Real air flow", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48926("48926", "Humidity factor", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48927("48927", "Humidity cool factor", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48928("48928", "OPT Hystereses", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48930("48930", "EME10 Activated", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48931("48931", "EME PV Panel Affect Heating", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48932("48932", "EME PV Panel Affect Hot Water", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48969("48969", "AUX block OPT", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48970("48970", "Outdoor Air Mixing function", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48972("48972", "Outdoor air min. temp.", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48973("48973", "Reduced ventilation", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48975("48975", "OEK accessory", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48976("48976", "Smart home room control", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48979("48979", "Smart energy source", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48980("48980", "Smart energy source, ctrl method", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_48981("48981", "Smart energy source, electricity price source", ChannelType.SETTING, ChannelGroup.SETTING,
            String.class),
    CH_48982("48982", "Smart energy source, electricity price", ChannelType.SETTING, ChannelGroup.SETTING,
            Double.class),
    CH_48983("48983", "Smart energy source, fixed elec. price from", ChannelType.SETTING, ChannelGroup.SETTING,
            Boolean.class),
    CH_48984("48984", "Smart energy source, fixed part electricity price", ChannelType.SETTING, ChannelGroup.SETTING,
            Double.class),
    CH_48985("48985", "Smart energy source, shunt add price source", ChannelType.SETTING, ChannelGroup.SETTING,
            Boolean.class),
    CH_48986("48986", "Smart energy source, shunt add price", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48987("48987", "Smart energy source, ext step add price from", ChannelType.SETTING, ChannelGroup.SETTING,
            Boolean.class),
    CH_48988("48988", "Smart energy source, ext step add price", ChannelType.SETTING, ChannelGroup.SETTING,
            Double.class),
    CH_48989("48989", "Smart energy source, OPT10 price source", ChannelType.SETTING, ChannelGroup.SETTING,
            Boolean.class),
    CH_48990("48990", "Smart energy source, OPT10 price", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_48991("48991", "Smart energy source, primary factor elec.", ChannelType.SETTING, ChannelGroup.SETTING,
            Double.class),
    CH_48992("48992", "Smart energy source, primary factor shunted add.", ChannelType.SETTING, ChannelGroup.SETTING,
            Double.class),
    CH_48993("48993", "Smart energy source, primary factor ext step add", ChannelType.SETTING, ChannelGroup.SETTING,
            Double.class),
    CH_48994("48994", "Smart energy source, primary factor OPT10 add.", ChannelType.SETTING, ChannelGroup.SETTING,
            Double.class),
    CH_48995("48995", "Smart energy source, OPT10 high tariff price", ChannelType.SETTING, ChannelGroup.SETTING,
            Double.class),
    CH_48996("48996", "Smart energy source, OPT10 low tariff price", ChannelType.SETTING, ChannelGroup.SETTING,
            Double.class),
    CH_48997("48997", "Smart energy source, ext step add high tariff price", ChannelType.SETTING, ChannelGroup.SETTING,
            Double.class),
    CH_48998("48998", "Smart energy source, ext step add low tariff price", ChannelType.SETTING, ChannelGroup.SETTING,
            Double.class),
    CH_48999("48999", "Smart energy source, shunt add high tariff price", ChannelType.SETTING, ChannelGroup.SETTING,
            Double.class),
    CH_49000("49000", "Smart energy source, shunt add low tariff price", ChannelType.SETTING, ChannelGroup.SETTING,
            Double.class),
    CH_49001("49001", "Smart energy source, fixed elec. high tariff price", ChannelType.SETTING, ChannelGroup.SETTING,
            Double.class),
    CH_49002("49002", "Smart energy source, fixed elec. low tariff price", ChannelType.SETTING, ChannelGroup.SETTING,
            Double.class),
    CH_49003("49003", "Smart energy source, electricity high tariff price", ChannelType.SETTING, ChannelGroup.SETTING,
            Double.class),
    CH_49004("49004", "Smart energy source, electricity high low price", ChannelType.SETTING, ChannelGroup.SETTING,
            Double.class),
    CH_49005("49005", "Smart energy source, DM diff source prio 5", ChannelType.SETTING, ChannelGroup.SETTING,
            Double.class),
    CH_49006("49006", "Smart energy source, DM diff source prio 4", ChannelType.SETTING, ChannelGroup.SETTING,
            Double.class),
    CH_49007("49007", "Smart energy source, DM diff source prio 3", ChannelType.SETTING, ChannelGroup.SETTING,
            Double.class),
    CH_49008("49008", "Smart energy source, DM diff source prio 2", ChannelType.SETTING, ChannelGroup.SETTING,
            Double.class),
    CH_49009("49009", "Smart energy source, DM start source prio 1", ChannelType.SETTING, ChannelGroup.SETTING,
            Double.class),
    CH_49223("49223", "SCA solar heating", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_49224("49224", "SCA ext. hot water", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_49227("49227", "Block top frequencies", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_49281("49281", "SAM fan model", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_49282("49282", "Silent Mode Max Speed", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_49285("49285", "Energy Meter pulses per kWh X23", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_49286("49286", "Energy Meter pulses per kWh X22", ChannelType.SETTING, ChannelGroup.SETTING, Double.class),
    CH_49287("49287", "Energy Meter mode X23", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_49288("49288", "Energy Meter mode X22", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),
    CH_49289("49289", "Ground water pump speed control ", ChannelType.SETTING, ChannelGroup.SETTING, Boolean.class),

    /* END */
    ;

    private final String id;
    private final String name;
    private final ChannelType channelType;
    private final ChannelGroup channelGroup;
    private final Class<?> javaType;

    /**
     * Constructor
     *
     * @param id
     * @param name
     * @param type
     */
    F750Channels(String id, String name, ChannelType channelType, ChannelGroup channelGroup, Class<?> javaType) {
        this.id = id;
        this.name = name;
        this.channelType = channelType;
        this.channelGroup = channelGroup;
        this.javaType = javaType;
    }

    public static F750Channels fromId(String id) {
        for (F750Channels channel : F750Channels.values()) {
            if (channel.id.equals(id)) {
                return channel;
            }
        }
        return null;
    }

    @Override
    public final String getName() {
        return name;
    }

    @Override
    public final String getId() {
        return id;
    }

    @Override
    public final ChannelType getChannelType() {
        return channelType;
    }

    @Override
    public ChannelGroup getChannelGroup() {
        return channelGroup;
    }

    @Override
    public final Class<?> getJavaType() {
        return javaType;
    }

    @Override
    public String getFQName() {
        String fQName = getChannelGroup().toString().toLowerCase() + "#" + getId();
        return fQName;
    }

}
