/*
 * Copyright (c) 2010-2025 Contributors to the openHAB project
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 */

package org.openhab.binding.jellyfin.internal.api.version.legacy.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * The authenticate user by name request body.
 */
@JsonPropertyOrder({ AuthenticateUserByName.JSON_PROPERTY_USERNAME, AuthenticateUserByName.JSON_PROPERTY_PW,
        AuthenticateUserByName.JSON_PROPERTY_PASSWORD })
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class AuthenticateUserByName {
    public static final String JSON_PROPERTY_USERNAME = "Username";
    @javax.annotation.Nullable
    private String username;

    public static final String JSON_PROPERTY_PW = "Pw";
    @javax.annotation.Nullable
    private String pw;

    public static final String JSON_PROPERTY_PASSWORD = "Password";
    @javax.annotation.Nullable
    private String password;

    public AuthenticateUserByName() {
    }

    public AuthenticateUserByName username(@javax.annotation.Nullable String username) {

        this.username = username;
        return this;
    }

    /**
     * Gets or sets the username.
     * 
     * @return username
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_USERNAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getUsername() {
        return username;
    }

    @JsonProperty(JSON_PROPERTY_USERNAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setUsername(@javax.annotation.Nullable String username) {
        this.username = username;
    }

    public AuthenticateUserByName pw(@javax.annotation.Nullable String pw) {

        this.pw = pw;
        return this;
    }

    /**
     * Gets or sets the plain text password.
     * 
     * @return pw
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PW)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPw() {
        return pw;
    }

    @JsonProperty(JSON_PROPERTY_PW)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPw(@javax.annotation.Nullable String pw) {
        this.pw = pw;
    }

    public AuthenticateUserByName password(@javax.annotation.Nullable String password) {

        this.password = password;
        return this;
    }

    /**
     * Gets or sets the sha1-hashed password.
     * 
     * @return password
     * @deprecated
     */
    @Deprecated
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PASSWORD)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPassword() {
        return password;
    }

    @JsonProperty(JSON_PROPERTY_PASSWORD)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPassword(@javax.annotation.Nullable String password) {
        this.password = password;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AuthenticateUserByName authenticateUserByName = (AuthenticateUserByName) o;
        return Objects.equals(this.username, authenticateUserByName.username)
                && Objects.equals(this.pw, authenticateUserByName.pw)
                && Objects.equals(this.password, authenticateUserByName.password);
    }

    @Override
    public int hashCode() {
        return Objects.hash(username, pw, password);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AuthenticateUserByName {\n");
        sb.append("    username: ").append(toIndentedString(username)).append("\n");
        sb.append("    pw: ").append(toIndentedString(pw)).append("\n");
        sb.append("    password: ").append(toIndentedString(password)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static class Builder {

        private AuthenticateUserByName instance;

        public Builder() {
            this(new AuthenticateUserByName());
        }

        protected Builder(AuthenticateUserByName instance) {
            this.instance = instance;
        }

        public AuthenticateUserByName.Builder username(String username) {
            this.instance.username = username;
            return this;
        }

        public AuthenticateUserByName.Builder pw(String pw) {
            this.instance.pw = pw;
            return this;
        }

        public AuthenticateUserByName.Builder password(String password) {
            this.instance.password = password;
            return this;
        }

        /**
         * returns a built AuthenticateUserByName instance.
         *
         * The builder is not reusable.
         */
        public AuthenticateUserByName build() {
            try {
                return this.instance;
            } finally {
                // ensure that this.instance is not reused
                this.instance = null;
            }
        }

        @Override
        public String toString() {
            return getClass() + "=(" + instance + ")";
        }
    }

    /**
     * Create a builder with no initialized field.
     */
    public static AuthenticateUserByName.Builder builder() {
        return new AuthenticateUserByName.Builder();
    }

    /**
     * Create a builder with a shallow copy of this instance.
     */
    public AuthenticateUserByName.Builder toBuilder() {
        return new AuthenticateUserByName.Builder().username(getUsername()).pw(getPw()).password(getPassword());
    }
}
