/*
 * Copyright (c) 2010-2025 Contributors to the openHAB project
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 */

package org.openhab.binding.jellyfin.internal.api.version.legacy.model;

import java.time.OffsetDateTime;
import java.util.Objects;
import java.util.UUID;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * AuthenticationInfo
 */
@JsonPropertyOrder({ AuthenticationInfo.JSON_PROPERTY_ID, AuthenticationInfo.JSON_PROPERTY_ACCESS_TOKEN,
        AuthenticationInfo.JSON_PROPERTY_DEVICE_ID, AuthenticationInfo.JSON_PROPERTY_APP_NAME,
        AuthenticationInfo.JSON_PROPERTY_APP_VERSION, AuthenticationInfo.JSON_PROPERTY_DEVICE_NAME,
        AuthenticationInfo.JSON_PROPERTY_USER_ID, AuthenticationInfo.JSON_PROPERTY_IS_ACTIVE,
        AuthenticationInfo.JSON_PROPERTY_DATE_CREATED, AuthenticationInfo.JSON_PROPERTY_DATE_REVOKED,
        AuthenticationInfo.JSON_PROPERTY_DATE_LAST_ACTIVITY, AuthenticationInfo.JSON_PROPERTY_USER_NAME })
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class AuthenticationInfo {
    public static final String JSON_PROPERTY_ID = "Id";
    @javax.annotation.Nullable
    private Long id;

    public static final String JSON_PROPERTY_ACCESS_TOKEN = "AccessToken";
    @javax.annotation.Nullable
    private String accessToken;

    public static final String JSON_PROPERTY_DEVICE_ID = "DeviceId";
    @javax.annotation.Nullable
    private String deviceId;

    public static final String JSON_PROPERTY_APP_NAME = "AppName";
    @javax.annotation.Nullable
    private String appName;

    public static final String JSON_PROPERTY_APP_VERSION = "AppVersion";
    @javax.annotation.Nullable
    private String appVersion;

    public static final String JSON_PROPERTY_DEVICE_NAME = "DeviceName";
    @javax.annotation.Nullable
    private String deviceName;

    public static final String JSON_PROPERTY_USER_ID = "UserId";
    @javax.annotation.Nullable
    private UUID userId;

    public static final String JSON_PROPERTY_IS_ACTIVE = "IsActive";
    @javax.annotation.Nullable
    private Boolean isActive;

    public static final String JSON_PROPERTY_DATE_CREATED = "DateCreated";
    @javax.annotation.Nullable
    private OffsetDateTime dateCreated;

    public static final String JSON_PROPERTY_DATE_REVOKED = "DateRevoked";
    @javax.annotation.Nullable
    private OffsetDateTime dateRevoked;

    public static final String JSON_PROPERTY_DATE_LAST_ACTIVITY = "DateLastActivity";
    @javax.annotation.Nullable
    private OffsetDateTime dateLastActivity;

    public static final String JSON_PROPERTY_USER_NAME = "UserName";
    @javax.annotation.Nullable
    private String userName;

    public AuthenticationInfo() {
    }

    public AuthenticationInfo id(@javax.annotation.Nullable Long id) {

        this.id = id;
        return this;
    }

    /**
     * Gets or sets the identifier.
     * 
     * @return id
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Long getId() {
        return id;
    }

    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setId(@javax.annotation.Nullable Long id) {
        this.id = id;
    }

    public AuthenticationInfo accessToken(@javax.annotation.Nullable String accessToken) {

        this.accessToken = accessToken;
        return this;
    }

    /**
     * Gets or sets the access token.
     * 
     * @return accessToken
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ACCESS_TOKEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getAccessToken() {
        return accessToken;
    }

    @JsonProperty(JSON_PROPERTY_ACCESS_TOKEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAccessToken(@javax.annotation.Nullable String accessToken) {
        this.accessToken = accessToken;
    }

    public AuthenticationInfo deviceId(@javax.annotation.Nullable String deviceId) {

        this.deviceId = deviceId;
        return this;
    }

    /**
     * Gets or sets the device identifier.
     * 
     * @return deviceId
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DEVICE_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getDeviceId() {
        return deviceId;
    }

    @JsonProperty(JSON_PROPERTY_DEVICE_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDeviceId(@javax.annotation.Nullable String deviceId) {
        this.deviceId = deviceId;
    }

    public AuthenticationInfo appName(@javax.annotation.Nullable String appName) {

        this.appName = appName;
        return this;
    }

    /**
     * Gets or sets the name of the application.
     * 
     * @return appName
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_APP_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getAppName() {
        return appName;
    }

    @JsonProperty(JSON_PROPERTY_APP_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAppName(@javax.annotation.Nullable String appName) {
        this.appName = appName;
    }

    public AuthenticationInfo appVersion(@javax.annotation.Nullable String appVersion) {

        this.appVersion = appVersion;
        return this;
    }

    /**
     * Gets or sets the application version.
     * 
     * @return appVersion
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_APP_VERSION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getAppVersion() {
        return appVersion;
    }

    @JsonProperty(JSON_PROPERTY_APP_VERSION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAppVersion(@javax.annotation.Nullable String appVersion) {
        this.appVersion = appVersion;
    }

    public AuthenticationInfo deviceName(@javax.annotation.Nullable String deviceName) {

        this.deviceName = deviceName;
        return this;
    }

    /**
     * Gets or sets the name of the device.
     * 
     * @return deviceName
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DEVICE_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getDeviceName() {
        return deviceName;
    }

    @JsonProperty(JSON_PROPERTY_DEVICE_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDeviceName(@javax.annotation.Nullable String deviceName) {
        this.deviceName = deviceName;
    }

    public AuthenticationInfo userId(@javax.annotation.Nullable UUID userId) {

        this.userId = userId;
        return this;
    }

    /**
     * Gets or sets the user identifier.
     * 
     * @return userId
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_USER_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public UUID getUserId() {
        return userId;
    }

    @JsonProperty(JSON_PROPERTY_USER_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setUserId(@javax.annotation.Nullable UUID userId) {
        this.userId = userId;
    }

    public AuthenticationInfo isActive(@javax.annotation.Nullable Boolean isActive) {

        this.isActive = isActive;
        return this;
    }

    /**
     * Gets or sets a value indicating whether this instance is active.
     * 
     * @return isActive
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_IS_ACTIVE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getIsActive() {
        return isActive;
    }

    @JsonProperty(JSON_PROPERTY_IS_ACTIVE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setIsActive(@javax.annotation.Nullable Boolean isActive) {
        this.isActive = isActive;
    }

    public AuthenticationInfo dateCreated(@javax.annotation.Nullable OffsetDateTime dateCreated) {

        this.dateCreated = dateCreated;
        return this;
    }

    /**
     * Gets or sets the date created.
     * 
     * @return dateCreated
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DATE_CREATED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public OffsetDateTime getDateCreated() {
        return dateCreated;
    }

    @JsonProperty(JSON_PROPERTY_DATE_CREATED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDateCreated(@javax.annotation.Nullable OffsetDateTime dateCreated) {
        this.dateCreated = dateCreated;
    }

    public AuthenticationInfo dateRevoked(@javax.annotation.Nullable OffsetDateTime dateRevoked) {

        this.dateRevoked = dateRevoked;
        return this;
    }

    /**
     * Gets or sets the date revoked.
     * 
     * @return dateRevoked
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DATE_REVOKED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public OffsetDateTime getDateRevoked() {
        return dateRevoked;
    }

    @JsonProperty(JSON_PROPERTY_DATE_REVOKED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDateRevoked(@javax.annotation.Nullable OffsetDateTime dateRevoked) {
        this.dateRevoked = dateRevoked;
    }

    public AuthenticationInfo dateLastActivity(@javax.annotation.Nullable OffsetDateTime dateLastActivity) {

        this.dateLastActivity = dateLastActivity;
        return this;
    }

    /**
     * Get dateLastActivity
     * 
     * @return dateLastActivity
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DATE_LAST_ACTIVITY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public OffsetDateTime getDateLastActivity() {
        return dateLastActivity;
    }

    @JsonProperty(JSON_PROPERTY_DATE_LAST_ACTIVITY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDateLastActivity(@javax.annotation.Nullable OffsetDateTime dateLastActivity) {
        this.dateLastActivity = dateLastActivity;
    }

    public AuthenticationInfo userName(@javax.annotation.Nullable String userName) {

        this.userName = userName;
        return this;
    }

    /**
     * Get userName
     * 
     * @return userName
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_USER_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getUserName() {
        return userName;
    }

    @JsonProperty(JSON_PROPERTY_USER_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setUserName(@javax.annotation.Nullable String userName) {
        this.userName = userName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AuthenticationInfo authenticationInfo = (AuthenticationInfo) o;
        return Objects.equals(this.id, authenticationInfo.id)
                && Objects.equals(this.accessToken, authenticationInfo.accessToken)
                && Objects.equals(this.deviceId, authenticationInfo.deviceId)
                && Objects.equals(this.appName, authenticationInfo.appName)
                && Objects.equals(this.appVersion, authenticationInfo.appVersion)
                && Objects.equals(this.deviceName, authenticationInfo.deviceName)
                && Objects.equals(this.userId, authenticationInfo.userId)
                && Objects.equals(this.isActive, authenticationInfo.isActive)
                && Objects.equals(this.dateCreated, authenticationInfo.dateCreated)
                && Objects.equals(this.dateRevoked, authenticationInfo.dateRevoked)
                && Objects.equals(this.dateLastActivity, authenticationInfo.dateLastActivity)
                && Objects.equals(this.userName, authenticationInfo.userName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, accessToken, deviceId, appName, appVersion, deviceName, userId, isActive, dateCreated,
                dateRevoked, dateLastActivity, userName);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AuthenticationInfo {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    accessToken: ").append(toIndentedString(accessToken)).append("\n");
        sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
        sb.append("    appName: ").append(toIndentedString(appName)).append("\n");
        sb.append("    appVersion: ").append(toIndentedString(appVersion)).append("\n");
        sb.append("    deviceName: ").append(toIndentedString(deviceName)).append("\n");
        sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
        sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
        sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
        sb.append("    dateRevoked: ").append(toIndentedString(dateRevoked)).append("\n");
        sb.append("    dateLastActivity: ").append(toIndentedString(dateLastActivity)).append("\n");
        sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static class Builder {

        private AuthenticationInfo instance;

        public Builder() {
            this(new AuthenticationInfo());
        }

        protected Builder(AuthenticationInfo instance) {
            this.instance = instance;
        }

        public AuthenticationInfo.Builder id(Long id) {
            this.instance.id = id;
            return this;
        }

        public AuthenticationInfo.Builder accessToken(String accessToken) {
            this.instance.accessToken = accessToken;
            return this;
        }

        public AuthenticationInfo.Builder deviceId(String deviceId) {
            this.instance.deviceId = deviceId;
            return this;
        }

        public AuthenticationInfo.Builder appName(String appName) {
            this.instance.appName = appName;
            return this;
        }

        public AuthenticationInfo.Builder appVersion(String appVersion) {
            this.instance.appVersion = appVersion;
            return this;
        }

        public AuthenticationInfo.Builder deviceName(String deviceName) {
            this.instance.deviceName = deviceName;
            return this;
        }

        public AuthenticationInfo.Builder userId(UUID userId) {
            this.instance.userId = userId;
            return this;
        }

        public AuthenticationInfo.Builder isActive(Boolean isActive) {
            this.instance.isActive = isActive;
            return this;
        }

        public AuthenticationInfo.Builder dateCreated(OffsetDateTime dateCreated) {
            this.instance.dateCreated = dateCreated;
            return this;
        }

        public AuthenticationInfo.Builder dateRevoked(OffsetDateTime dateRevoked) {
            this.instance.dateRevoked = dateRevoked;
            return this;
        }

        public AuthenticationInfo.Builder dateLastActivity(OffsetDateTime dateLastActivity) {
            this.instance.dateLastActivity = dateLastActivity;
            return this;
        }

        public AuthenticationInfo.Builder userName(String userName) {
            this.instance.userName = userName;
            return this;
        }

        /**
         * returns a built AuthenticationInfo instance.
         *
         * The builder is not reusable.
         */
        public AuthenticationInfo build() {
            try {
                return this.instance;
            } finally {
                // ensure that this.instance is not reused
                this.instance = null;
            }
        }

        @Override
        public String toString() {
            return getClass() + "=(" + instance + ")";
        }
    }

    /**
     * Create a builder with no initialized field.
     */
    public static AuthenticationInfo.Builder builder() {
        return new AuthenticationInfo.Builder();
    }

    /**
     * Create a builder with a shallow copy of this instance.
     */
    public AuthenticationInfo.Builder toBuilder() {
        return new AuthenticationInfo.Builder().id(getId()).accessToken(getAccessToken()).deviceId(getDeviceId())
                .appName(getAppName()).appVersion(getAppVersion()).deviceName(getDeviceName()).userId(getUserId())
                .isActive(getIsActive()).dateCreated(getDateCreated()).dateRevoked(getDateRevoked())
                .dateLastActivity(getDateLastActivity()).userName(getUserName());
    }
}
