/*
 * Copyright (c) 2010-2025 Contributors to the openHAB project
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 */

package org.openhab.binding.jellyfin.internal.api.version.legacy.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.openhab.binding.jellyfin.internal.api.version.legacy.model.AuthenticationInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * AuthenticationInfoQueryResult
 */
@JsonPropertyOrder({
  AuthenticationInfoQueryResult.JSON_PROPERTY_ITEMS,
  AuthenticationInfoQueryResult.JSON_PROPERTY_TOTAL_RECORD_COUNT,
  AuthenticationInfoQueryResult.JSON_PROPERTY_START_INDEX
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class AuthenticationInfoQueryResult {
  public static final String JSON_PROPERTY_ITEMS = "Items";
  @javax.annotation.Nullable
  private JsonNullable<List<AuthenticationInfo>> items = JsonNullable.<List<AuthenticationInfo>>undefined();

  public static final String JSON_PROPERTY_TOTAL_RECORD_COUNT = "TotalRecordCount";
  @javax.annotation.Nullable
  private Integer totalRecordCount;

  public static final String JSON_PROPERTY_START_INDEX = "StartIndex";
  @javax.annotation.Nullable
  private Integer startIndex;

  public AuthenticationInfoQueryResult() {
  }

  public AuthenticationInfoQueryResult items(@javax.annotation.Nullable List<AuthenticationInfo> items) {
    this.items = JsonNullable.<List<AuthenticationInfo>>of(items);
    
    return this;
  }

  public AuthenticationInfoQueryResult addItemsItem(AuthenticationInfo itemsItem) {
    if (this.items == null || !this.items.isPresent()) {
      this.items = JsonNullable.<List<AuthenticationInfo>>of(new ArrayList<>());
    }
    try {
      this.items.get().add(itemsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Gets or sets the items.
   * @return items
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public List<AuthenticationInfo> getItems() {
        return items.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ITEMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<AuthenticationInfo>> getItems_JsonNullable() {
    return items;
  }
  
  @JsonProperty(JSON_PROPERTY_ITEMS)
  public void setItems_JsonNullable(JsonNullable<List<AuthenticationInfo>> items) {
    this.items = items;
  }

  public void setItems(@javax.annotation.Nullable List<AuthenticationInfo> items) {
    this.items = JsonNullable.<List<AuthenticationInfo>>of(items);
  }

  public AuthenticationInfoQueryResult totalRecordCount(@javax.annotation.Nullable Integer totalRecordCount) {
    
    this.totalRecordCount = totalRecordCount;
    return this;
  }

  /**
   * Gets or sets the total number of records available.
   * @return totalRecordCount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL_RECORD_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTotalRecordCount() {
    return totalRecordCount;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_RECORD_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalRecordCount(@javax.annotation.Nullable Integer totalRecordCount) {
    this.totalRecordCount = totalRecordCount;
  }

  public AuthenticationInfoQueryResult startIndex(@javax.annotation.Nullable Integer startIndex) {
    
    this.startIndex = startIndex;
    return this;
  }

  /**
   * Gets or sets the index of the first record in Items.
   * @return startIndex
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_START_INDEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getStartIndex() {
    return startIndex;
  }


  @JsonProperty(JSON_PROPERTY_START_INDEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartIndex(@javax.annotation.Nullable Integer startIndex) {
    this.startIndex = startIndex;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthenticationInfoQueryResult authenticationInfoQueryResult = (AuthenticationInfoQueryResult) o;
    return equalsNullable(this.items, authenticationInfoQueryResult.items) &&
        Objects.equals(this.totalRecordCount, authenticationInfoQueryResult.totalRecordCount) &&
        Objects.equals(this.startIndex, authenticationInfoQueryResult.startIndex);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(items), totalRecordCount, startIndex);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthenticationInfoQueryResult {\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    totalRecordCount: ").append(toIndentedString(totalRecordCount)).append("\n");
    sb.append("    startIndex: ").append(toIndentedString(startIndex)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private AuthenticationInfoQueryResult instance;

    public Builder() {
      this(new AuthenticationInfoQueryResult());
    }

    protected Builder(AuthenticationInfoQueryResult instance) {
      this.instance = instance;
    }

    public AuthenticationInfoQueryResult.Builder items(List<AuthenticationInfo> items) {
      this.instance.items = JsonNullable.<List<AuthenticationInfo>>of(items);
      return this;
    }
    public AuthenticationInfoQueryResult.Builder items(JsonNullable<List<AuthenticationInfo>> items) {
      this.instance.items = items;
      return this;
    }
    public AuthenticationInfoQueryResult.Builder totalRecordCount(Integer totalRecordCount) {
      this.instance.totalRecordCount = totalRecordCount;
      return this;
    }
    public AuthenticationInfoQueryResult.Builder startIndex(Integer startIndex) {
      this.instance.startIndex = startIndex;
      return this;
    }


    /**
    * returns a built AuthenticationInfoQueryResult instance.
    *
    * The builder is not reusable.
    */
    public AuthenticationInfoQueryResult build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static AuthenticationInfoQueryResult.Builder builder() {
    return new AuthenticationInfoQueryResult.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public AuthenticationInfoQueryResult.Builder toBuilder() {
    return new AuthenticationInfoQueryResult.Builder()
      .items(getItems())
      .totalRecordCount(getTotalRecordCount())
      .startIndex(getStartIndex());
  }


}

