/*
 * Copyright (c) 2010-2025 Contributors to the openHAB project
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 */

package org.openhab.binding.jellyfin.internal.api.version.legacy.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * The create user by name request body.
 */
@JsonPropertyOrder({ CreateUserByName.JSON_PROPERTY_NAME, CreateUserByName.JSON_PROPERTY_PASSWORD })
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class CreateUserByName {
    public static final String JSON_PROPERTY_NAME = "Name";
    @javax.annotation.Nullable
    private String name;

    public static final String JSON_PROPERTY_PASSWORD = "Password";
    @javax.annotation.Nullable
    private String password;

    public CreateUserByName() {
    }

    public CreateUserByName name(@javax.annotation.Nullable String name) {

        this.name = name;
        return this;
    }

    /**
     * Gets or sets the username.
     * 
     * @return name
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getName() {
        return name;
    }

    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setName(@javax.annotation.Nullable String name) {
        this.name = name;
    }

    public CreateUserByName password(@javax.annotation.Nullable String password) {

        this.password = password;
        return this;
    }

    /**
     * Gets or sets the password.
     * 
     * @return password
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PASSWORD)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPassword() {
        return password;
    }

    @JsonProperty(JSON_PROPERTY_PASSWORD)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPassword(@javax.annotation.Nullable String password) {
        this.password = password;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateUserByName createUserByName = (CreateUserByName) o;
        return Objects.equals(this.name, createUserByName.name)
                && Objects.equals(this.password, createUserByName.password);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, password);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CreateUserByName {\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    password: ").append(toIndentedString(password)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static class Builder {

        private CreateUserByName instance;

        public Builder() {
            this(new CreateUserByName());
        }

        protected Builder(CreateUserByName instance) {
            this.instance = instance;
        }

        public CreateUserByName.Builder name(String name) {
            this.instance.name = name;
            return this;
        }

        public CreateUserByName.Builder password(String password) {
            this.instance.password = password;
            return this;
        }

        /**
         * returns a built CreateUserByName instance.
         *
         * The builder is not reusable.
         */
        public CreateUserByName build() {
            try {
                return this.instance;
            } finally {
                // ensure that this.instance is not reused
                this.instance = null;
            }
        }

        @Override
        public String toString() {
            return getClass() + "=(" + instance + ")";
        }
    }

    /**
     * Create a builder with no initialized field.
     */
    public static CreateUserByName.Builder builder() {
        return new CreateUserByName.Builder();
    }

    /**
     * Create a builder with a shallow copy of this instance.
     */
    public CreateUserByName.Builder toBuilder() {
        return new CreateUserByName.Builder().name(getName()).password(getPassword());
    }
}
