/*
 * Copyright (c) 2010-2025 Contributors to the openHAB project
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 */

package org.openhab.binding.jellyfin.internal.api.version.legacy.model;

import java.util.Objects;
import java.util.UUID;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Class NextItemRequestDto.
 */
@JsonPropertyOrder({ NextItemRequestDto.JSON_PROPERTY_PLAYLIST_ITEM_ID })
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class NextItemRequestDto {
    public static final String JSON_PROPERTY_PLAYLIST_ITEM_ID = "PlaylistItemId";
    @javax.annotation.Nullable
    private UUID playlistItemId;

    public NextItemRequestDto() {
    }

    public NextItemRequestDto playlistItemId(@javax.annotation.Nullable UUID playlistItemId) {

        this.playlistItemId = playlistItemId;
        return this;
    }

    /**
     * Gets or sets the playing item identifier.
     * 
     * @return playlistItemId
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PLAYLIST_ITEM_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public UUID getPlaylistItemId() {
        return playlistItemId;
    }

    @JsonProperty(JSON_PROPERTY_PLAYLIST_ITEM_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPlaylistItemId(@javax.annotation.Nullable UUID playlistItemId) {
        this.playlistItemId = playlistItemId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        NextItemRequestDto nextItemRequestDto = (NextItemRequestDto) o;
        return Objects.equals(this.playlistItemId, nextItemRequestDto.playlistItemId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(playlistItemId);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class NextItemRequestDto {\n");
        sb.append("    playlistItemId: ").append(toIndentedString(playlistItemId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static class Builder {

        private NextItemRequestDto instance;

        public Builder() {
            this(new NextItemRequestDto());
        }

        protected Builder(NextItemRequestDto instance) {
            this.instance = instance;
        }

        public NextItemRequestDto.Builder playlistItemId(UUID playlistItemId) {
            this.instance.playlistItemId = playlistItemId;
            return this;
        }

        /**
         * returns a built NextItemRequestDto instance.
         *
         * The builder is not reusable.
         */
        public NextItemRequestDto build() {
            try {
                return this.instance;
            } finally {
                // ensure that this.instance is not reused
                this.instance = null;
            }
        }

        @Override
        public String toString() {
            return getClass() + "=(" + instance + ")";
        }
    }

    /**
     * Create a builder with no initialized field.
     */
    public static NextItemRequestDto.Builder builder() {
        return new NextItemRequestDto.Builder();
    }

    /**
     * Create a builder with a shallow copy of this instance.
     */
    public NextItemRequestDto.Builder toBuilder() {
        return new NextItemRequestDto.Builder().playlistItemId(getPlaylistItemId());
    }
}
