/*
 * Copyright (c) 2010-2025 Contributors to the openHAB project
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 */

package org.openhab.binding.jellyfin.internal.api.version.legacy.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.openhab.binding.jellyfin.internal.api.version.legacy.model.SendToUserType;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * NotificationOption
 */
@JsonPropertyOrder({
  NotificationOption.JSON_PROPERTY_TYPE,
  NotificationOption.JSON_PROPERTY_DISABLED_MONITOR_USERS,
  NotificationOption.JSON_PROPERTY_SEND_TO_USERS,
  NotificationOption.JSON_PROPERTY_ENABLED,
  NotificationOption.JSON_PROPERTY_DISABLED_SERVICES,
  NotificationOption.JSON_PROPERTY_SEND_TO_USER_MODE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class NotificationOption {
  public static final String JSON_PROPERTY_TYPE = "Type";
  @javax.annotation.Nullable
  private JsonNullable<String> type = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_DISABLED_MONITOR_USERS = "DisabledMonitorUsers";
  @javax.annotation.Nullable
  private List<String> disabledMonitorUsers = new ArrayList<>();

  public static final String JSON_PROPERTY_SEND_TO_USERS = "SendToUsers";
  @javax.annotation.Nullable
  private List<String> sendToUsers = new ArrayList<>();

  public static final String JSON_PROPERTY_ENABLED = "Enabled";
  @javax.annotation.Nullable
  private Boolean enabled;

  public static final String JSON_PROPERTY_DISABLED_SERVICES = "DisabledServices";
  @javax.annotation.Nullable
  private List<String> disabledServices = new ArrayList<>();

  public static final String JSON_PROPERTY_SEND_TO_USER_MODE = "SendToUserMode";
  @javax.annotation.Nullable
  private SendToUserType sendToUserMode;

  public NotificationOption() {
  }

  public NotificationOption type(@javax.annotation.Nullable String type) {
    this.type = JsonNullable.<String>of(type);
    
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getType() {
        return type.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getType_JsonNullable() {
    return type;
  }
  
  @JsonProperty(JSON_PROPERTY_TYPE)
  public void setType_JsonNullable(JsonNullable<String> type) {
    this.type = type;
  }

  public void setType(@javax.annotation.Nullable String type) {
    this.type = JsonNullable.<String>of(type);
  }

  public NotificationOption disabledMonitorUsers(@javax.annotation.Nullable List<String> disabledMonitorUsers) {
    
    this.disabledMonitorUsers = disabledMonitorUsers;
    return this;
  }

  public NotificationOption addDisabledMonitorUsersItem(String disabledMonitorUsersItem) {
    if (this.disabledMonitorUsers == null) {
      this.disabledMonitorUsers = new ArrayList<>();
    }
    this.disabledMonitorUsers.add(disabledMonitorUsersItem);
    return this;
  }

  /**
   * Gets or sets user Ids to not monitor (it&#39;s opt out).
   * @return disabledMonitorUsers
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISABLED_MONITOR_USERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getDisabledMonitorUsers() {
    return disabledMonitorUsers;
  }


  @JsonProperty(JSON_PROPERTY_DISABLED_MONITOR_USERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisabledMonitorUsers(@javax.annotation.Nullable List<String> disabledMonitorUsers) {
    this.disabledMonitorUsers = disabledMonitorUsers;
  }

  public NotificationOption sendToUsers(@javax.annotation.Nullable List<String> sendToUsers) {
    
    this.sendToUsers = sendToUsers;
    return this;
  }

  public NotificationOption addSendToUsersItem(String sendToUsersItem) {
    if (this.sendToUsers == null) {
      this.sendToUsers = new ArrayList<>();
    }
    this.sendToUsers.add(sendToUsersItem);
    return this;
  }

  /**
   * Gets or sets user Ids to send to (if SendToUserMode &#x3D;&#x3D; Custom).
   * @return sendToUsers
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEND_TO_USERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getSendToUsers() {
    return sendToUsers;
  }


  @JsonProperty(JSON_PROPERTY_SEND_TO_USERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSendToUsers(@javax.annotation.Nullable List<String> sendToUsers) {
    this.sendToUsers = sendToUsers;
  }

  public NotificationOption enabled(@javax.annotation.Nullable Boolean enabled) {
    
    this.enabled = enabled;
    return this;
  }

  /**
   * Gets or sets a value indicating whether this MediaBrowser.Model.Notifications.NotificationOption is enabled.
   * @return enabled
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEnabled() {
    return enabled;
  }


  @JsonProperty(JSON_PROPERTY_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnabled(@javax.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
  }

  public NotificationOption disabledServices(@javax.annotation.Nullable List<String> disabledServices) {
    
    this.disabledServices = disabledServices;
    return this;
  }

  public NotificationOption addDisabledServicesItem(String disabledServicesItem) {
    if (this.disabledServices == null) {
      this.disabledServices = new ArrayList<>();
    }
    this.disabledServices.add(disabledServicesItem);
    return this;
  }

  /**
   * Gets or sets the disabled services.
   * @return disabledServices
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISABLED_SERVICES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getDisabledServices() {
    return disabledServices;
  }


  @JsonProperty(JSON_PROPERTY_DISABLED_SERVICES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisabledServices(@javax.annotation.Nullable List<String> disabledServices) {
    this.disabledServices = disabledServices;
  }

  public NotificationOption sendToUserMode(@javax.annotation.Nullable SendToUserType sendToUserMode) {
    
    this.sendToUserMode = sendToUserMode;
    return this;
  }

  /**
   * Gets or sets the send to user mode.
   * @return sendToUserMode
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEND_TO_USER_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SendToUserType getSendToUserMode() {
    return sendToUserMode;
  }


  @JsonProperty(JSON_PROPERTY_SEND_TO_USER_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSendToUserMode(@javax.annotation.Nullable SendToUserType sendToUserMode) {
    this.sendToUserMode = sendToUserMode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NotificationOption notificationOption = (NotificationOption) o;
    return equalsNullable(this.type, notificationOption.type) &&
        Objects.equals(this.disabledMonitorUsers, notificationOption.disabledMonitorUsers) &&
        Objects.equals(this.sendToUsers, notificationOption.sendToUsers) &&
        Objects.equals(this.enabled, notificationOption.enabled) &&
        Objects.equals(this.disabledServices, notificationOption.disabledServices) &&
        Objects.equals(this.sendToUserMode, notificationOption.sendToUserMode);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(type), disabledMonitorUsers, sendToUsers, enabled, disabledServices, sendToUserMode);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NotificationOption {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    disabledMonitorUsers: ").append(toIndentedString(disabledMonitorUsers)).append("\n");
    sb.append("    sendToUsers: ").append(toIndentedString(sendToUsers)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    disabledServices: ").append(toIndentedString(disabledServices)).append("\n");
    sb.append("    sendToUserMode: ").append(toIndentedString(sendToUserMode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private NotificationOption instance;

    public Builder() {
      this(new NotificationOption());
    }

    protected Builder(NotificationOption instance) {
      this.instance = instance;
    }

    public NotificationOption.Builder type(String type) {
      this.instance.type = JsonNullable.<String>of(type);
      return this;
    }
    public NotificationOption.Builder type(JsonNullable<String> type) {
      this.instance.type = type;
      return this;
    }
    public NotificationOption.Builder disabledMonitorUsers(List<String> disabledMonitorUsers) {
      this.instance.disabledMonitorUsers = disabledMonitorUsers;
      return this;
    }
    public NotificationOption.Builder sendToUsers(List<String> sendToUsers) {
      this.instance.sendToUsers = sendToUsers;
      return this;
    }
    public NotificationOption.Builder enabled(Boolean enabled) {
      this.instance.enabled = enabled;
      return this;
    }
    public NotificationOption.Builder disabledServices(List<String> disabledServices) {
      this.instance.disabledServices = disabledServices;
      return this;
    }
    public NotificationOption.Builder sendToUserMode(SendToUserType sendToUserMode) {
      this.instance.sendToUserMode = sendToUserMode;
      return this;
    }


    /**
    * returns a built NotificationOption instance.
    *
    * The builder is not reusable.
    */
    public NotificationOption build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static NotificationOption.Builder builder() {
    return new NotificationOption.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public NotificationOption.Builder toBuilder() {
    return new NotificationOption.Builder()
      .type(getType())
      .disabledMonitorUsers(getDisabledMonitorUsers())
      .sendToUsers(getSendToUsers())
      .enabled(getEnabled())
      .disabledServices(getDisabledServices())
      .sendToUserMode(getSendToUserMode());
  }


}

