/*
 * Copyright (c) 2010-2025 Contributors to the openHAB project
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 */

package org.openhab.binding.jellyfin.internal.api.version.legacy.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Open live stream dto.
 */
@JsonPropertyOrder({ OpenLiveStreamDto.JSON_PROPERTY_OPEN_TOKEN, OpenLiveStreamDto.JSON_PROPERTY_USER_ID,
        OpenLiveStreamDto.JSON_PROPERTY_PLAY_SESSION_ID, OpenLiveStreamDto.JSON_PROPERTY_MAX_STREAMING_BITRATE,
        OpenLiveStreamDto.JSON_PROPERTY_START_TIME_TICKS, OpenLiveStreamDto.JSON_PROPERTY_AUDIO_STREAM_INDEX,
        OpenLiveStreamDto.JSON_PROPERTY_SUBTITLE_STREAM_INDEX, OpenLiveStreamDto.JSON_PROPERTY_MAX_AUDIO_CHANNELS,
        OpenLiveStreamDto.JSON_PROPERTY_ITEM_ID, OpenLiveStreamDto.JSON_PROPERTY_ENABLE_DIRECT_PLAY,
        OpenLiveStreamDto.JSON_PROPERTY_ENABLE_DIRECT_STREAM, OpenLiveStreamDto.JSON_PROPERTY_DEVICE_PROFILE,
        OpenLiveStreamDto.JSON_PROPERTY_DIRECT_PLAY_PROTOCOLS })
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class OpenLiveStreamDto {
    public static final String JSON_PROPERTY_OPEN_TOKEN = "OpenToken";
    @javax.annotation.Nullable
    private String openToken;

    public static final String JSON_PROPERTY_USER_ID = "UserId";
    @javax.annotation.Nullable
    private UUID userId;

    public static final String JSON_PROPERTY_PLAY_SESSION_ID = "PlaySessionId";
    @javax.annotation.Nullable
    private String playSessionId;

    public static final String JSON_PROPERTY_MAX_STREAMING_BITRATE = "MaxStreamingBitrate";
    @javax.annotation.Nullable
    private Integer maxStreamingBitrate;

    public static final String JSON_PROPERTY_START_TIME_TICKS = "StartTimeTicks";
    @javax.annotation.Nullable
    private Long startTimeTicks;

    public static final String JSON_PROPERTY_AUDIO_STREAM_INDEX = "AudioStreamIndex";
    @javax.annotation.Nullable
    private Integer audioStreamIndex;

    public static final String JSON_PROPERTY_SUBTITLE_STREAM_INDEX = "SubtitleStreamIndex";
    @javax.annotation.Nullable
    private Integer subtitleStreamIndex;

    public static final String JSON_PROPERTY_MAX_AUDIO_CHANNELS = "MaxAudioChannels";
    @javax.annotation.Nullable
    private Integer maxAudioChannels;

    public static final String JSON_PROPERTY_ITEM_ID = "ItemId";
    @javax.annotation.Nullable
    private UUID itemId;

    public static final String JSON_PROPERTY_ENABLE_DIRECT_PLAY = "EnableDirectPlay";
    @javax.annotation.Nullable
    private Boolean enableDirectPlay;

    public static final String JSON_PROPERTY_ENABLE_DIRECT_STREAM = "EnableDirectStream";
    @javax.annotation.Nullable
    private Boolean enableDirectStream;

    public static final String JSON_PROPERTY_DEVICE_PROFILE = "DeviceProfile";
    @javax.annotation.Nullable
    private DeviceProfile deviceProfile;

    public static final String JSON_PROPERTY_DIRECT_PLAY_PROTOCOLS = "DirectPlayProtocols";
    @javax.annotation.Nullable
    private List<MediaProtocol> directPlayProtocols = new ArrayList<>();

    public OpenLiveStreamDto() {
    }

    public OpenLiveStreamDto openToken(@javax.annotation.Nullable String openToken) {

        this.openToken = openToken;
        return this;
    }

    /**
     * Gets or sets the open token.
     * 
     * @return openToken
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_OPEN_TOKEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getOpenToken() {
        return openToken;
    }

    @JsonProperty(JSON_PROPERTY_OPEN_TOKEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setOpenToken(@javax.annotation.Nullable String openToken) {
        this.openToken = openToken;
    }

    public OpenLiveStreamDto userId(@javax.annotation.Nullable UUID userId) {

        this.userId = userId;
        return this;
    }

    /**
     * Gets or sets the user id.
     * 
     * @return userId
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_USER_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public UUID getUserId() {
        return userId;
    }

    @JsonProperty(JSON_PROPERTY_USER_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setUserId(@javax.annotation.Nullable UUID userId) {
        this.userId = userId;
    }

    public OpenLiveStreamDto playSessionId(@javax.annotation.Nullable String playSessionId) {

        this.playSessionId = playSessionId;
        return this;
    }

    /**
     * Gets or sets the play session id.
     * 
     * @return playSessionId
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PLAY_SESSION_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPlaySessionId() {
        return playSessionId;
    }

    @JsonProperty(JSON_PROPERTY_PLAY_SESSION_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPlaySessionId(@javax.annotation.Nullable String playSessionId) {
        this.playSessionId = playSessionId;
    }

    public OpenLiveStreamDto maxStreamingBitrate(@javax.annotation.Nullable Integer maxStreamingBitrate) {

        this.maxStreamingBitrate = maxStreamingBitrate;
        return this;
    }

    /**
     * Gets or sets the max streaming bitrate.
     * 
     * @return maxStreamingBitrate
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_MAX_STREAMING_BITRATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getMaxStreamingBitrate() {
        return maxStreamingBitrate;
    }

    @JsonProperty(JSON_PROPERTY_MAX_STREAMING_BITRATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMaxStreamingBitrate(@javax.annotation.Nullable Integer maxStreamingBitrate) {
        this.maxStreamingBitrate = maxStreamingBitrate;
    }

    public OpenLiveStreamDto startTimeTicks(@javax.annotation.Nullable Long startTimeTicks) {

        this.startTimeTicks = startTimeTicks;
        return this;
    }

    /**
     * Gets or sets the start time in ticks.
     * 
     * @return startTimeTicks
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_START_TIME_TICKS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Long getStartTimeTicks() {
        return startTimeTicks;
    }

    @JsonProperty(JSON_PROPERTY_START_TIME_TICKS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setStartTimeTicks(@javax.annotation.Nullable Long startTimeTicks) {
        this.startTimeTicks = startTimeTicks;
    }

    public OpenLiveStreamDto audioStreamIndex(@javax.annotation.Nullable Integer audioStreamIndex) {

        this.audioStreamIndex = audioStreamIndex;
        return this;
    }

    /**
     * Gets or sets the audio stream index.
     * 
     * @return audioStreamIndex
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_AUDIO_STREAM_INDEX)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getAudioStreamIndex() {
        return audioStreamIndex;
    }

    @JsonProperty(JSON_PROPERTY_AUDIO_STREAM_INDEX)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAudioStreamIndex(@javax.annotation.Nullable Integer audioStreamIndex) {
        this.audioStreamIndex = audioStreamIndex;
    }

    public OpenLiveStreamDto subtitleStreamIndex(@javax.annotation.Nullable Integer subtitleStreamIndex) {

        this.subtitleStreamIndex = subtitleStreamIndex;
        return this;
    }

    /**
     * Gets or sets the subtitle stream index.
     * 
     * @return subtitleStreamIndex
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_SUBTITLE_STREAM_INDEX)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getSubtitleStreamIndex() {
        return subtitleStreamIndex;
    }

    @JsonProperty(JSON_PROPERTY_SUBTITLE_STREAM_INDEX)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSubtitleStreamIndex(@javax.annotation.Nullable Integer subtitleStreamIndex) {
        this.subtitleStreamIndex = subtitleStreamIndex;
    }

    public OpenLiveStreamDto maxAudioChannels(@javax.annotation.Nullable Integer maxAudioChannels) {

        this.maxAudioChannels = maxAudioChannels;
        return this;
    }

    /**
     * Gets or sets the max audio channels.
     * 
     * @return maxAudioChannels
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_MAX_AUDIO_CHANNELS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getMaxAudioChannels() {
        return maxAudioChannels;
    }

    @JsonProperty(JSON_PROPERTY_MAX_AUDIO_CHANNELS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMaxAudioChannels(@javax.annotation.Nullable Integer maxAudioChannels) {
        this.maxAudioChannels = maxAudioChannels;
    }

    public OpenLiveStreamDto itemId(@javax.annotation.Nullable UUID itemId) {

        this.itemId = itemId;
        return this;
    }

    /**
     * Gets or sets the item id.
     * 
     * @return itemId
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ITEM_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public UUID getItemId() {
        return itemId;
    }

    @JsonProperty(JSON_PROPERTY_ITEM_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setItemId(@javax.annotation.Nullable UUID itemId) {
        this.itemId = itemId;
    }

    public OpenLiveStreamDto enableDirectPlay(@javax.annotation.Nullable Boolean enableDirectPlay) {

        this.enableDirectPlay = enableDirectPlay;
        return this;
    }

    /**
     * Gets or sets a value indicating whether to enable direct play.
     * 
     * @return enableDirectPlay
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ENABLE_DIRECT_PLAY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getEnableDirectPlay() {
        return enableDirectPlay;
    }

    @JsonProperty(JSON_PROPERTY_ENABLE_DIRECT_PLAY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setEnableDirectPlay(@javax.annotation.Nullable Boolean enableDirectPlay) {
        this.enableDirectPlay = enableDirectPlay;
    }

    public OpenLiveStreamDto enableDirectStream(@javax.annotation.Nullable Boolean enableDirectStream) {

        this.enableDirectStream = enableDirectStream;
        return this;
    }

    /**
     * Gets or sets a value indicating whether to enale direct stream.
     * 
     * @return enableDirectStream
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ENABLE_DIRECT_STREAM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getEnableDirectStream() {
        return enableDirectStream;
    }

    @JsonProperty(JSON_PROPERTY_ENABLE_DIRECT_STREAM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setEnableDirectStream(@javax.annotation.Nullable Boolean enableDirectStream) {
        this.enableDirectStream = enableDirectStream;
    }

    public OpenLiveStreamDto deviceProfile(@javax.annotation.Nullable DeviceProfile deviceProfile) {

        this.deviceProfile = deviceProfile;
        return this;
    }

    /**
     * A MediaBrowser.Model.Dlna.DeviceProfile represents a set of metadata which determines which content a certain
     * device is able to play. &lt;br /&gt; Specifically, it defines the supported &lt;see
     * cref&#x3D;\&quot;P:MediaBrowser.Model.Dlna.DeviceProfile.ContainerProfiles\&quot;&gt;containers&lt;/see&gt; and
     * &lt;see cref&#x3D;\&quot;P:MediaBrowser.Model.Dlna.DeviceProfile.CodecProfiles\&quot;&gt;codecs&lt;/see&gt;
     * (video and/or audio, including codec profiles and levels) the device is able to direct play (without transcoding
     * or remuxing), as well as which &lt;see
     * cref&#x3D;\&quot;P:MediaBrowser.Model.Dlna.DeviceProfile.TranscodingProfiles\&quot;&gt;containers/codecs to
     * transcode to&lt;/see&gt; in case it isn&#39;t.
     * 
     * @return deviceProfile
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DEVICE_PROFILE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public DeviceProfile getDeviceProfile() {
        return deviceProfile;
    }

    @JsonProperty(JSON_PROPERTY_DEVICE_PROFILE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDeviceProfile(@javax.annotation.Nullable DeviceProfile deviceProfile) {
        this.deviceProfile = deviceProfile;
    }

    public OpenLiveStreamDto directPlayProtocols(@javax.annotation.Nullable List<MediaProtocol> directPlayProtocols) {

        this.directPlayProtocols = directPlayProtocols;
        return this;
    }

    public OpenLiveStreamDto addDirectPlayProtocolsItem(MediaProtocol directPlayProtocolsItem) {
        if (this.directPlayProtocols == null) {
            this.directPlayProtocols = new ArrayList<>();
        }
        this.directPlayProtocols.add(directPlayProtocolsItem);
        return this;
    }

    /**
     * Gets or sets the device play protocols.
     * 
     * @return directPlayProtocols
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DIRECT_PLAY_PROTOCOLS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<MediaProtocol> getDirectPlayProtocols() {
        return directPlayProtocols;
    }

    @JsonProperty(JSON_PROPERTY_DIRECT_PLAY_PROTOCOLS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDirectPlayProtocols(@javax.annotation.Nullable List<MediaProtocol> directPlayProtocols) {
        this.directPlayProtocols = directPlayProtocols;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OpenLiveStreamDto openLiveStreamDto = (OpenLiveStreamDto) o;
        return Objects.equals(this.openToken, openLiveStreamDto.openToken)
                && Objects.equals(this.userId, openLiveStreamDto.userId)
                && Objects.equals(this.playSessionId, openLiveStreamDto.playSessionId)
                && Objects.equals(this.maxStreamingBitrate, openLiveStreamDto.maxStreamingBitrate)
                && Objects.equals(this.startTimeTicks, openLiveStreamDto.startTimeTicks)
                && Objects.equals(this.audioStreamIndex, openLiveStreamDto.audioStreamIndex)
                && Objects.equals(this.subtitleStreamIndex, openLiveStreamDto.subtitleStreamIndex)
                && Objects.equals(this.maxAudioChannels, openLiveStreamDto.maxAudioChannels)
                && Objects.equals(this.itemId, openLiveStreamDto.itemId)
                && Objects.equals(this.enableDirectPlay, openLiveStreamDto.enableDirectPlay)
                && Objects.equals(this.enableDirectStream, openLiveStreamDto.enableDirectStream)
                && Objects.equals(this.deviceProfile, openLiveStreamDto.deviceProfile)
                && Objects.equals(this.directPlayProtocols, openLiveStreamDto.directPlayProtocols);
    }

    @Override
    public int hashCode() {
        return Objects.hash(openToken, userId, playSessionId, maxStreamingBitrate, startTimeTicks, audioStreamIndex,
                subtitleStreamIndex, maxAudioChannels, itemId, enableDirectPlay, enableDirectStream, deviceProfile,
                directPlayProtocols);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OpenLiveStreamDto {\n");
        sb.append("    openToken: ").append(toIndentedString(openToken)).append("\n");
        sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
        sb.append("    playSessionId: ").append(toIndentedString(playSessionId)).append("\n");
        sb.append("    maxStreamingBitrate: ").append(toIndentedString(maxStreamingBitrate)).append("\n");
        sb.append("    startTimeTicks: ").append(toIndentedString(startTimeTicks)).append("\n");
        sb.append("    audioStreamIndex: ").append(toIndentedString(audioStreamIndex)).append("\n");
        sb.append("    subtitleStreamIndex: ").append(toIndentedString(subtitleStreamIndex)).append("\n");
        sb.append("    maxAudioChannels: ").append(toIndentedString(maxAudioChannels)).append("\n");
        sb.append("    itemId: ").append(toIndentedString(itemId)).append("\n");
        sb.append("    enableDirectPlay: ").append(toIndentedString(enableDirectPlay)).append("\n");
        sb.append("    enableDirectStream: ").append(toIndentedString(enableDirectStream)).append("\n");
        sb.append("    deviceProfile: ").append(toIndentedString(deviceProfile)).append("\n");
        sb.append("    directPlayProtocols: ").append(toIndentedString(directPlayProtocols)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static class Builder {

        private OpenLiveStreamDto instance;

        public Builder() {
            this(new OpenLiveStreamDto());
        }

        protected Builder(OpenLiveStreamDto instance) {
            this.instance = instance;
        }

        public OpenLiveStreamDto.Builder openToken(String openToken) {
            this.instance.openToken = openToken;
            return this;
        }

        public OpenLiveStreamDto.Builder userId(UUID userId) {
            this.instance.userId = userId;
            return this;
        }

        public OpenLiveStreamDto.Builder playSessionId(String playSessionId) {
            this.instance.playSessionId = playSessionId;
            return this;
        }

        public OpenLiveStreamDto.Builder maxStreamingBitrate(Integer maxStreamingBitrate) {
            this.instance.maxStreamingBitrate = maxStreamingBitrate;
            return this;
        }

        public OpenLiveStreamDto.Builder startTimeTicks(Long startTimeTicks) {
            this.instance.startTimeTicks = startTimeTicks;
            return this;
        }

        public OpenLiveStreamDto.Builder audioStreamIndex(Integer audioStreamIndex) {
            this.instance.audioStreamIndex = audioStreamIndex;
            return this;
        }

        public OpenLiveStreamDto.Builder subtitleStreamIndex(Integer subtitleStreamIndex) {
            this.instance.subtitleStreamIndex = subtitleStreamIndex;
            return this;
        }

        public OpenLiveStreamDto.Builder maxAudioChannels(Integer maxAudioChannels) {
            this.instance.maxAudioChannels = maxAudioChannels;
            return this;
        }

        public OpenLiveStreamDto.Builder itemId(UUID itemId) {
            this.instance.itemId = itemId;
            return this;
        }

        public OpenLiveStreamDto.Builder enableDirectPlay(Boolean enableDirectPlay) {
            this.instance.enableDirectPlay = enableDirectPlay;
            return this;
        }

        public OpenLiveStreamDto.Builder enableDirectStream(Boolean enableDirectStream) {
            this.instance.enableDirectStream = enableDirectStream;
            return this;
        }

        public OpenLiveStreamDto.Builder deviceProfile(DeviceProfile deviceProfile) {
            this.instance.deviceProfile = deviceProfile;
            return this;
        }

        public OpenLiveStreamDto.Builder directPlayProtocols(List<MediaProtocol> directPlayProtocols) {
            this.instance.directPlayProtocols = directPlayProtocols;
            return this;
        }

        /**
         * returns a built OpenLiveStreamDto instance.
         *
         * The builder is not reusable.
         */
        public OpenLiveStreamDto build() {
            try {
                return this.instance;
            } finally {
                // ensure that this.instance is not reused
                this.instance = null;
            }
        }

        @Override
        public String toString() {
            return getClass() + "=(" + instance + ")";
        }
    }

    /**
     * Create a builder with no initialized field.
     */
    public static OpenLiveStreamDto.Builder builder() {
        return new OpenLiveStreamDto.Builder();
    }

    /**
     * Create a builder with a shallow copy of this instance.
     */
    public OpenLiveStreamDto.Builder toBuilder() {
        return new OpenLiveStreamDto.Builder().openToken(getOpenToken()).userId(getUserId())
                .playSessionId(getPlaySessionId()).maxStreamingBitrate(getMaxStreamingBitrate())
                .startTimeTicks(getStartTimeTicks()).audioStreamIndex(getAudioStreamIndex())
                .subtitleStreamIndex(getSubtitleStreamIndex()).maxAudioChannels(getMaxAudioChannels())
                .itemId(getItemId()).enableDirectPlay(getEnableDirectPlay()).enableDirectStream(getEnableDirectStream())
                .deviceProfile(getDeviceProfile()).directPlayProtocols(getDirectPlayProtocols());
    }
}
