/*
 * Copyright (c) 2010-2025 Contributors to the openHAB project
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 */

package org.openhab.binding.jellyfin.internal.api.version.legacy.model;

import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * PersonLookupInfo
 */
@JsonPropertyOrder({ PersonLookupInfo.JSON_PROPERTY_NAME, PersonLookupInfo.JSON_PROPERTY_ORIGINAL_TITLE,
        PersonLookupInfo.JSON_PROPERTY_PATH, PersonLookupInfo.JSON_PROPERTY_METADATA_LANGUAGE,
        PersonLookupInfo.JSON_PROPERTY_METADATA_COUNTRY_CODE, PersonLookupInfo.JSON_PROPERTY_PROVIDER_IDS,
        PersonLookupInfo.JSON_PROPERTY_YEAR, PersonLookupInfo.JSON_PROPERTY_INDEX_NUMBER,
        PersonLookupInfo.JSON_PROPERTY_PARENT_INDEX_NUMBER, PersonLookupInfo.JSON_PROPERTY_PREMIERE_DATE,
        PersonLookupInfo.JSON_PROPERTY_IS_AUTOMATED })
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class PersonLookupInfo {
    public static final String JSON_PROPERTY_NAME = "Name";
    @javax.annotation.Nullable
    private String name;

    public static final String JSON_PROPERTY_ORIGINAL_TITLE = "OriginalTitle";
    @javax.annotation.Nullable
    private String originalTitle;

    public static final String JSON_PROPERTY_PATH = "Path";
    @javax.annotation.Nullable
    private String path;

    public static final String JSON_PROPERTY_METADATA_LANGUAGE = "MetadataLanguage";
    @javax.annotation.Nullable
    private String metadataLanguage;

    public static final String JSON_PROPERTY_METADATA_COUNTRY_CODE = "MetadataCountryCode";
    @javax.annotation.Nullable
    private String metadataCountryCode;

    public static final String JSON_PROPERTY_PROVIDER_IDS = "ProviderIds";
    @javax.annotation.Nullable
    private Map<String, String> providerIds;

    public static final String JSON_PROPERTY_YEAR = "Year";
    @javax.annotation.Nullable
    private Integer year;

    public static final String JSON_PROPERTY_INDEX_NUMBER = "IndexNumber";
    @javax.annotation.Nullable
    private Integer indexNumber;

    public static final String JSON_PROPERTY_PARENT_INDEX_NUMBER = "ParentIndexNumber";
    @javax.annotation.Nullable
    private Integer parentIndexNumber;

    public static final String JSON_PROPERTY_PREMIERE_DATE = "PremiereDate";
    @javax.annotation.Nullable
    private OffsetDateTime premiereDate;

    public static final String JSON_PROPERTY_IS_AUTOMATED = "IsAutomated";
    @javax.annotation.Nullable
    private Boolean isAutomated;

    public PersonLookupInfo() {
    }

    public PersonLookupInfo name(@javax.annotation.Nullable String name) {

        this.name = name;
        return this;
    }

    /**
     * Gets or sets the name.
     * 
     * @return name
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getName() {
        return name;
    }

    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setName(@javax.annotation.Nullable String name) {
        this.name = name;
    }

    public PersonLookupInfo originalTitle(@javax.annotation.Nullable String originalTitle) {

        this.originalTitle = originalTitle;
        return this;
    }

    /**
     * Gets or sets the original title.
     * 
     * @return originalTitle
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ORIGINAL_TITLE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getOriginalTitle() {
        return originalTitle;
    }

    @JsonProperty(JSON_PROPERTY_ORIGINAL_TITLE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setOriginalTitle(@javax.annotation.Nullable String originalTitle) {
        this.originalTitle = originalTitle;
    }

    public PersonLookupInfo path(@javax.annotation.Nullable String path) {

        this.path = path;
        return this;
    }

    /**
     * Gets or sets the path.
     * 
     * @return path
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PATH)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPath() {
        return path;
    }

    @JsonProperty(JSON_PROPERTY_PATH)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPath(@javax.annotation.Nullable String path) {
        this.path = path;
    }

    public PersonLookupInfo metadataLanguage(@javax.annotation.Nullable String metadataLanguage) {

        this.metadataLanguage = metadataLanguage;
        return this;
    }

    /**
     * Gets or sets the metadata language.
     * 
     * @return metadataLanguage
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_METADATA_LANGUAGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getMetadataLanguage() {
        return metadataLanguage;
    }

    @JsonProperty(JSON_PROPERTY_METADATA_LANGUAGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMetadataLanguage(@javax.annotation.Nullable String metadataLanguage) {
        this.metadataLanguage = metadataLanguage;
    }

    public PersonLookupInfo metadataCountryCode(@javax.annotation.Nullable String metadataCountryCode) {

        this.metadataCountryCode = metadataCountryCode;
        return this;
    }

    /**
     * Gets or sets the metadata country code.
     * 
     * @return metadataCountryCode
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_METADATA_COUNTRY_CODE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getMetadataCountryCode() {
        return metadataCountryCode;
    }

    @JsonProperty(JSON_PROPERTY_METADATA_COUNTRY_CODE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMetadataCountryCode(@javax.annotation.Nullable String metadataCountryCode) {
        this.metadataCountryCode = metadataCountryCode;
    }

    public PersonLookupInfo providerIds(@javax.annotation.Nullable Map<String, String> providerIds) {

        this.providerIds = providerIds;
        return this;
    }

    public PersonLookupInfo putProviderIdsItem(String key, String providerIdsItem) {
        if (this.providerIds == null) {
            this.providerIds = new HashMap<>();
        }
        this.providerIds.put(key, providerIdsItem);
        return this;
    }

    /**
     * Gets or sets the provider ids.
     * 
     * @return providerIds
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PROVIDER_IDS)
    @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

    public Map<String, String> getProviderIds() {
        return providerIds;
    }

    @JsonProperty(JSON_PROPERTY_PROVIDER_IDS)
    @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
    public void setProviderIds(@javax.annotation.Nullable Map<String, String> providerIds) {
        this.providerIds = providerIds;
    }

    public PersonLookupInfo year(@javax.annotation.Nullable Integer year) {

        this.year = year;
        return this;
    }

    /**
     * Gets or sets the year.
     * 
     * @return year
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_YEAR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getYear() {
        return year;
    }

    @JsonProperty(JSON_PROPERTY_YEAR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setYear(@javax.annotation.Nullable Integer year) {
        this.year = year;
    }

    public PersonLookupInfo indexNumber(@javax.annotation.Nullable Integer indexNumber) {

        this.indexNumber = indexNumber;
        return this;
    }

    /**
     * Get indexNumber
     * 
     * @return indexNumber
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_INDEX_NUMBER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getIndexNumber() {
        return indexNumber;
    }

    @JsonProperty(JSON_PROPERTY_INDEX_NUMBER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setIndexNumber(@javax.annotation.Nullable Integer indexNumber) {
        this.indexNumber = indexNumber;
    }

    public PersonLookupInfo parentIndexNumber(@javax.annotation.Nullable Integer parentIndexNumber) {

        this.parentIndexNumber = parentIndexNumber;
        return this;
    }

    /**
     * Get parentIndexNumber
     * 
     * @return parentIndexNumber
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PARENT_INDEX_NUMBER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getParentIndexNumber() {
        return parentIndexNumber;
    }

    @JsonProperty(JSON_PROPERTY_PARENT_INDEX_NUMBER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setParentIndexNumber(@javax.annotation.Nullable Integer parentIndexNumber) {
        this.parentIndexNumber = parentIndexNumber;
    }

    public PersonLookupInfo premiereDate(@javax.annotation.Nullable OffsetDateTime premiereDate) {

        this.premiereDate = premiereDate;
        return this;
    }

    /**
     * Get premiereDate
     * 
     * @return premiereDate
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PREMIERE_DATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public OffsetDateTime getPremiereDate() {
        return premiereDate;
    }

    @JsonProperty(JSON_PROPERTY_PREMIERE_DATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPremiereDate(@javax.annotation.Nullable OffsetDateTime premiereDate) {
        this.premiereDate = premiereDate;
    }

    public PersonLookupInfo isAutomated(@javax.annotation.Nullable Boolean isAutomated) {

        this.isAutomated = isAutomated;
        return this;
    }

    /**
     * Get isAutomated
     * 
     * @return isAutomated
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_IS_AUTOMATED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getIsAutomated() {
        return isAutomated;
    }

    @JsonProperty(JSON_PROPERTY_IS_AUTOMATED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setIsAutomated(@javax.annotation.Nullable Boolean isAutomated) {
        this.isAutomated = isAutomated;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PersonLookupInfo personLookupInfo = (PersonLookupInfo) o;
        return Objects.equals(this.name, personLookupInfo.name)
                && Objects.equals(this.originalTitle, personLookupInfo.originalTitle)
                && Objects.equals(this.path, personLookupInfo.path)
                && Objects.equals(this.metadataLanguage, personLookupInfo.metadataLanguage)
                && Objects.equals(this.metadataCountryCode, personLookupInfo.metadataCountryCode)
                && Objects.equals(this.providerIds, personLookupInfo.providerIds)
                && Objects.equals(this.year, personLookupInfo.year)
                && Objects.equals(this.indexNumber, personLookupInfo.indexNumber)
                && Objects.equals(this.parentIndexNumber, personLookupInfo.parentIndexNumber)
                && Objects.equals(this.premiereDate, personLookupInfo.premiereDate)
                && Objects.equals(this.isAutomated, personLookupInfo.isAutomated);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, originalTitle, path, metadataLanguage, metadataCountryCode, providerIds, year,
                indexNumber, parentIndexNumber, premiereDate, isAutomated);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PersonLookupInfo {\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    originalTitle: ").append(toIndentedString(originalTitle)).append("\n");
        sb.append("    path: ").append(toIndentedString(path)).append("\n");
        sb.append("    metadataLanguage: ").append(toIndentedString(metadataLanguage)).append("\n");
        sb.append("    metadataCountryCode: ").append(toIndentedString(metadataCountryCode)).append("\n");
        sb.append("    providerIds: ").append(toIndentedString(providerIds)).append("\n");
        sb.append("    year: ").append(toIndentedString(year)).append("\n");
        sb.append("    indexNumber: ").append(toIndentedString(indexNumber)).append("\n");
        sb.append("    parentIndexNumber: ").append(toIndentedString(parentIndexNumber)).append("\n");
        sb.append("    premiereDate: ").append(toIndentedString(premiereDate)).append("\n");
        sb.append("    isAutomated: ").append(toIndentedString(isAutomated)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static class Builder {

        private PersonLookupInfo instance;

        public Builder() {
            this(new PersonLookupInfo());
        }

        protected Builder(PersonLookupInfo instance) {
            this.instance = instance;
        }

        public PersonLookupInfo.Builder name(String name) {
            this.instance.name = name;
            return this;
        }

        public PersonLookupInfo.Builder originalTitle(String originalTitle) {
            this.instance.originalTitle = originalTitle;
            return this;
        }

        public PersonLookupInfo.Builder path(String path) {
            this.instance.path = path;
            return this;
        }

        public PersonLookupInfo.Builder metadataLanguage(String metadataLanguage) {
            this.instance.metadataLanguage = metadataLanguage;
            return this;
        }

        public PersonLookupInfo.Builder metadataCountryCode(String metadataCountryCode) {
            this.instance.metadataCountryCode = metadataCountryCode;
            return this;
        }

        public PersonLookupInfo.Builder providerIds(Map<String, String> providerIds) {
            this.instance.providerIds = providerIds;
            return this;
        }

        public PersonLookupInfo.Builder year(Integer year) {
            this.instance.year = year;
            return this;
        }

        public PersonLookupInfo.Builder indexNumber(Integer indexNumber) {
            this.instance.indexNumber = indexNumber;
            return this;
        }

        public PersonLookupInfo.Builder parentIndexNumber(Integer parentIndexNumber) {
            this.instance.parentIndexNumber = parentIndexNumber;
            return this;
        }

        public PersonLookupInfo.Builder premiereDate(OffsetDateTime premiereDate) {
            this.instance.premiereDate = premiereDate;
            return this;
        }

        public PersonLookupInfo.Builder isAutomated(Boolean isAutomated) {
            this.instance.isAutomated = isAutomated;
            return this;
        }

        /**
         * returns a built PersonLookupInfo instance.
         *
         * The builder is not reusable.
         */
        public PersonLookupInfo build() {
            try {
                return this.instance;
            } finally {
                // ensure that this.instance is not reused
                this.instance = null;
            }
        }

        @Override
        public String toString() {
            return getClass() + "=(" + instance + ")";
        }
    }

    /**
     * Create a builder with no initialized field.
     */
    public static PersonLookupInfo.Builder builder() {
        return new PersonLookupInfo.Builder();
    }

    /**
     * Create a builder with a shallow copy of this instance.
     */
    public PersonLookupInfo.Builder toBuilder() {
        return new PersonLookupInfo.Builder().name(getName()).originalTitle(getOriginalTitle()).path(getPath())
                .metadataLanguage(getMetadataLanguage()).metadataCountryCode(getMetadataCountryCode())
                .providerIds(getProviderIds()).year(getYear()).indexNumber(getIndexNumber())
                .parentIndexNumber(getParentIndexNumber()).premiereDate(getPremiereDate())
                .isAutomated(getIsAutomated());
    }
}
