/*
 * Copyright (c) 2010-2025 Contributors to the openHAB project
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 */

package org.openhab.binding.jellyfin.internal.api.version.legacy.model;

import java.util.Objects;
import java.util.UUID;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Plabyback info dto.
 */
@JsonPropertyOrder({ PlaybackInfoDto.JSON_PROPERTY_USER_ID, PlaybackInfoDto.JSON_PROPERTY_MAX_STREAMING_BITRATE,
        PlaybackInfoDto.JSON_PROPERTY_START_TIME_TICKS, PlaybackInfoDto.JSON_PROPERTY_AUDIO_STREAM_INDEX,
        PlaybackInfoDto.JSON_PROPERTY_SUBTITLE_STREAM_INDEX, PlaybackInfoDto.JSON_PROPERTY_MAX_AUDIO_CHANNELS,
        PlaybackInfoDto.JSON_PROPERTY_MEDIA_SOURCE_ID, PlaybackInfoDto.JSON_PROPERTY_LIVE_STREAM_ID,
        PlaybackInfoDto.JSON_PROPERTY_DEVICE_PROFILE, PlaybackInfoDto.JSON_PROPERTY_ENABLE_DIRECT_PLAY,
        PlaybackInfoDto.JSON_PROPERTY_ENABLE_DIRECT_STREAM, PlaybackInfoDto.JSON_PROPERTY_ENABLE_TRANSCODING,
        PlaybackInfoDto.JSON_PROPERTY_ALLOW_VIDEO_STREAM_COPY, PlaybackInfoDto.JSON_PROPERTY_ALLOW_AUDIO_STREAM_COPY,
        PlaybackInfoDto.JSON_PROPERTY_AUTO_OPEN_LIVE_STREAM })
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class PlaybackInfoDto {
    public static final String JSON_PROPERTY_USER_ID = "UserId";
    @javax.annotation.Nullable
    private UUID userId;

    public static final String JSON_PROPERTY_MAX_STREAMING_BITRATE = "MaxStreamingBitrate";
    @javax.annotation.Nullable
    private Integer maxStreamingBitrate;

    public static final String JSON_PROPERTY_START_TIME_TICKS = "StartTimeTicks";
    @javax.annotation.Nullable
    private Long startTimeTicks;

    public static final String JSON_PROPERTY_AUDIO_STREAM_INDEX = "AudioStreamIndex";
    @javax.annotation.Nullable
    private Integer audioStreamIndex;

    public static final String JSON_PROPERTY_SUBTITLE_STREAM_INDEX = "SubtitleStreamIndex";
    @javax.annotation.Nullable
    private Integer subtitleStreamIndex;

    public static final String JSON_PROPERTY_MAX_AUDIO_CHANNELS = "MaxAudioChannels";
    @javax.annotation.Nullable
    private Integer maxAudioChannels;

    public static final String JSON_PROPERTY_MEDIA_SOURCE_ID = "MediaSourceId";
    @javax.annotation.Nullable
    private String mediaSourceId;

    public static final String JSON_PROPERTY_LIVE_STREAM_ID = "LiveStreamId";
    @javax.annotation.Nullable
    private String liveStreamId;

    public static final String JSON_PROPERTY_DEVICE_PROFILE = "DeviceProfile";
    @javax.annotation.Nullable
    private DeviceProfile deviceProfile;

    public static final String JSON_PROPERTY_ENABLE_DIRECT_PLAY = "EnableDirectPlay";
    @javax.annotation.Nullable
    private Boolean enableDirectPlay;

    public static final String JSON_PROPERTY_ENABLE_DIRECT_STREAM = "EnableDirectStream";
    @javax.annotation.Nullable
    private Boolean enableDirectStream;

    public static final String JSON_PROPERTY_ENABLE_TRANSCODING = "EnableTranscoding";
    @javax.annotation.Nullable
    private Boolean enableTranscoding;

    public static final String JSON_PROPERTY_ALLOW_VIDEO_STREAM_COPY = "AllowVideoStreamCopy";
    @javax.annotation.Nullable
    private Boolean allowVideoStreamCopy;

    public static final String JSON_PROPERTY_ALLOW_AUDIO_STREAM_COPY = "AllowAudioStreamCopy";
    @javax.annotation.Nullable
    private Boolean allowAudioStreamCopy;

    public static final String JSON_PROPERTY_AUTO_OPEN_LIVE_STREAM = "AutoOpenLiveStream";
    @javax.annotation.Nullable
    private Boolean autoOpenLiveStream;

    public PlaybackInfoDto() {
    }

    public PlaybackInfoDto userId(@javax.annotation.Nullable UUID userId) {

        this.userId = userId;
        return this;
    }

    /**
     * Gets or sets the playback userId.
     * 
     * @return userId
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_USER_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public UUID getUserId() {
        return userId;
    }

    @JsonProperty(JSON_PROPERTY_USER_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setUserId(@javax.annotation.Nullable UUID userId) {
        this.userId = userId;
    }

    public PlaybackInfoDto maxStreamingBitrate(@javax.annotation.Nullable Integer maxStreamingBitrate) {

        this.maxStreamingBitrate = maxStreamingBitrate;
        return this;
    }

    /**
     * Gets or sets the max streaming bitrate.
     * 
     * @return maxStreamingBitrate
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_MAX_STREAMING_BITRATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getMaxStreamingBitrate() {
        return maxStreamingBitrate;
    }

    @JsonProperty(JSON_PROPERTY_MAX_STREAMING_BITRATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMaxStreamingBitrate(@javax.annotation.Nullable Integer maxStreamingBitrate) {
        this.maxStreamingBitrate = maxStreamingBitrate;
    }

    public PlaybackInfoDto startTimeTicks(@javax.annotation.Nullable Long startTimeTicks) {

        this.startTimeTicks = startTimeTicks;
        return this;
    }

    /**
     * Gets or sets the start time in ticks.
     * 
     * @return startTimeTicks
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_START_TIME_TICKS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Long getStartTimeTicks() {
        return startTimeTicks;
    }

    @JsonProperty(JSON_PROPERTY_START_TIME_TICKS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setStartTimeTicks(@javax.annotation.Nullable Long startTimeTicks) {
        this.startTimeTicks = startTimeTicks;
    }

    public PlaybackInfoDto audioStreamIndex(@javax.annotation.Nullable Integer audioStreamIndex) {

        this.audioStreamIndex = audioStreamIndex;
        return this;
    }

    /**
     * Gets or sets the audio stream index.
     * 
     * @return audioStreamIndex
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_AUDIO_STREAM_INDEX)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getAudioStreamIndex() {
        return audioStreamIndex;
    }

    @JsonProperty(JSON_PROPERTY_AUDIO_STREAM_INDEX)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAudioStreamIndex(@javax.annotation.Nullable Integer audioStreamIndex) {
        this.audioStreamIndex = audioStreamIndex;
    }

    public PlaybackInfoDto subtitleStreamIndex(@javax.annotation.Nullable Integer subtitleStreamIndex) {

        this.subtitleStreamIndex = subtitleStreamIndex;
        return this;
    }

    /**
     * Gets or sets the subtitle stream index.
     * 
     * @return subtitleStreamIndex
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_SUBTITLE_STREAM_INDEX)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getSubtitleStreamIndex() {
        return subtitleStreamIndex;
    }

    @JsonProperty(JSON_PROPERTY_SUBTITLE_STREAM_INDEX)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSubtitleStreamIndex(@javax.annotation.Nullable Integer subtitleStreamIndex) {
        this.subtitleStreamIndex = subtitleStreamIndex;
    }

    public PlaybackInfoDto maxAudioChannels(@javax.annotation.Nullable Integer maxAudioChannels) {

        this.maxAudioChannels = maxAudioChannels;
        return this;
    }

    /**
     * Gets or sets the max audio channels.
     * 
     * @return maxAudioChannels
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_MAX_AUDIO_CHANNELS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getMaxAudioChannels() {
        return maxAudioChannels;
    }

    @JsonProperty(JSON_PROPERTY_MAX_AUDIO_CHANNELS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMaxAudioChannels(@javax.annotation.Nullable Integer maxAudioChannels) {
        this.maxAudioChannels = maxAudioChannels;
    }

    public PlaybackInfoDto mediaSourceId(@javax.annotation.Nullable String mediaSourceId) {

        this.mediaSourceId = mediaSourceId;
        return this;
    }

    /**
     * Gets or sets the media source id.
     * 
     * @return mediaSourceId
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_MEDIA_SOURCE_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getMediaSourceId() {
        return mediaSourceId;
    }

    @JsonProperty(JSON_PROPERTY_MEDIA_SOURCE_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMediaSourceId(@javax.annotation.Nullable String mediaSourceId) {
        this.mediaSourceId = mediaSourceId;
    }

    public PlaybackInfoDto liveStreamId(@javax.annotation.Nullable String liveStreamId) {

        this.liveStreamId = liveStreamId;
        return this;
    }

    /**
     * Gets or sets the live stream id.
     * 
     * @return liveStreamId
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_LIVE_STREAM_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getLiveStreamId() {
        return liveStreamId;
    }

    @JsonProperty(JSON_PROPERTY_LIVE_STREAM_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLiveStreamId(@javax.annotation.Nullable String liveStreamId) {
        this.liveStreamId = liveStreamId;
    }

    public PlaybackInfoDto deviceProfile(@javax.annotation.Nullable DeviceProfile deviceProfile) {

        this.deviceProfile = deviceProfile;
        return this;
    }

    /**
     * A MediaBrowser.Model.Dlna.DeviceProfile represents a set of metadata which determines which content a certain
     * device is able to play. &lt;br /&gt; Specifically, it defines the supported &lt;see
     * cref&#x3D;\&quot;P:MediaBrowser.Model.Dlna.DeviceProfile.ContainerProfiles\&quot;&gt;containers&lt;/see&gt; and
     * &lt;see cref&#x3D;\&quot;P:MediaBrowser.Model.Dlna.DeviceProfile.CodecProfiles\&quot;&gt;codecs&lt;/see&gt;
     * (video and/or audio, including codec profiles and levels) the device is able to direct play (without transcoding
     * or remuxing), as well as which &lt;see
     * cref&#x3D;\&quot;P:MediaBrowser.Model.Dlna.DeviceProfile.TranscodingProfiles\&quot;&gt;containers/codecs to
     * transcode to&lt;/see&gt; in case it isn&#39;t.
     * 
     * @return deviceProfile
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DEVICE_PROFILE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public DeviceProfile getDeviceProfile() {
        return deviceProfile;
    }

    @JsonProperty(JSON_PROPERTY_DEVICE_PROFILE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDeviceProfile(@javax.annotation.Nullable DeviceProfile deviceProfile) {
        this.deviceProfile = deviceProfile;
    }

    public PlaybackInfoDto enableDirectPlay(@javax.annotation.Nullable Boolean enableDirectPlay) {

        this.enableDirectPlay = enableDirectPlay;
        return this;
    }

    /**
     * Gets or sets a value indicating whether to enable direct play.
     * 
     * @return enableDirectPlay
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ENABLE_DIRECT_PLAY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getEnableDirectPlay() {
        return enableDirectPlay;
    }

    @JsonProperty(JSON_PROPERTY_ENABLE_DIRECT_PLAY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setEnableDirectPlay(@javax.annotation.Nullable Boolean enableDirectPlay) {
        this.enableDirectPlay = enableDirectPlay;
    }

    public PlaybackInfoDto enableDirectStream(@javax.annotation.Nullable Boolean enableDirectStream) {

        this.enableDirectStream = enableDirectStream;
        return this;
    }

    /**
     * Gets or sets a value indicating whether to enable direct stream.
     * 
     * @return enableDirectStream
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ENABLE_DIRECT_STREAM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getEnableDirectStream() {
        return enableDirectStream;
    }

    @JsonProperty(JSON_PROPERTY_ENABLE_DIRECT_STREAM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setEnableDirectStream(@javax.annotation.Nullable Boolean enableDirectStream) {
        this.enableDirectStream = enableDirectStream;
    }

    public PlaybackInfoDto enableTranscoding(@javax.annotation.Nullable Boolean enableTranscoding) {

        this.enableTranscoding = enableTranscoding;
        return this;
    }

    /**
     * Gets or sets a value indicating whether to enable transcoding.
     * 
     * @return enableTranscoding
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ENABLE_TRANSCODING)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getEnableTranscoding() {
        return enableTranscoding;
    }

    @JsonProperty(JSON_PROPERTY_ENABLE_TRANSCODING)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setEnableTranscoding(@javax.annotation.Nullable Boolean enableTranscoding) {
        this.enableTranscoding = enableTranscoding;
    }

    public PlaybackInfoDto allowVideoStreamCopy(@javax.annotation.Nullable Boolean allowVideoStreamCopy) {

        this.allowVideoStreamCopy = allowVideoStreamCopy;
        return this;
    }

    /**
     * Gets or sets a value indicating whether to enable video stream copy.
     * 
     * @return allowVideoStreamCopy
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ALLOW_VIDEO_STREAM_COPY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getAllowVideoStreamCopy() {
        return allowVideoStreamCopy;
    }

    @JsonProperty(JSON_PROPERTY_ALLOW_VIDEO_STREAM_COPY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAllowVideoStreamCopy(@javax.annotation.Nullable Boolean allowVideoStreamCopy) {
        this.allowVideoStreamCopy = allowVideoStreamCopy;
    }

    public PlaybackInfoDto allowAudioStreamCopy(@javax.annotation.Nullable Boolean allowAudioStreamCopy) {

        this.allowAudioStreamCopy = allowAudioStreamCopy;
        return this;
    }

    /**
     * Gets or sets a value indicating whether to allow audio stream copy.
     * 
     * @return allowAudioStreamCopy
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ALLOW_AUDIO_STREAM_COPY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getAllowAudioStreamCopy() {
        return allowAudioStreamCopy;
    }

    @JsonProperty(JSON_PROPERTY_ALLOW_AUDIO_STREAM_COPY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAllowAudioStreamCopy(@javax.annotation.Nullable Boolean allowAudioStreamCopy) {
        this.allowAudioStreamCopy = allowAudioStreamCopy;
    }

    public PlaybackInfoDto autoOpenLiveStream(@javax.annotation.Nullable Boolean autoOpenLiveStream) {

        this.autoOpenLiveStream = autoOpenLiveStream;
        return this;
    }

    /**
     * Gets or sets a value indicating whether to auto open the live stream.
     * 
     * @return autoOpenLiveStream
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_AUTO_OPEN_LIVE_STREAM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getAutoOpenLiveStream() {
        return autoOpenLiveStream;
    }

    @JsonProperty(JSON_PROPERTY_AUTO_OPEN_LIVE_STREAM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAutoOpenLiveStream(@javax.annotation.Nullable Boolean autoOpenLiveStream) {
        this.autoOpenLiveStream = autoOpenLiveStream;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PlaybackInfoDto playbackInfoDto = (PlaybackInfoDto) o;
        return Objects.equals(this.userId, playbackInfoDto.userId)
                && Objects.equals(this.maxStreamingBitrate, playbackInfoDto.maxStreamingBitrate)
                && Objects.equals(this.startTimeTicks, playbackInfoDto.startTimeTicks)
                && Objects.equals(this.audioStreamIndex, playbackInfoDto.audioStreamIndex)
                && Objects.equals(this.subtitleStreamIndex, playbackInfoDto.subtitleStreamIndex)
                && Objects.equals(this.maxAudioChannels, playbackInfoDto.maxAudioChannels)
                && Objects.equals(this.mediaSourceId, playbackInfoDto.mediaSourceId)
                && Objects.equals(this.liveStreamId, playbackInfoDto.liveStreamId)
                && Objects.equals(this.deviceProfile, playbackInfoDto.deviceProfile)
                && Objects.equals(this.enableDirectPlay, playbackInfoDto.enableDirectPlay)
                && Objects.equals(this.enableDirectStream, playbackInfoDto.enableDirectStream)
                && Objects.equals(this.enableTranscoding, playbackInfoDto.enableTranscoding)
                && Objects.equals(this.allowVideoStreamCopy, playbackInfoDto.allowVideoStreamCopy)
                && Objects.equals(this.allowAudioStreamCopy, playbackInfoDto.allowAudioStreamCopy)
                && Objects.equals(this.autoOpenLiveStream, playbackInfoDto.autoOpenLiveStream);
    }

    @Override
    public int hashCode() {
        return Objects.hash(userId, maxStreamingBitrate, startTimeTicks, audioStreamIndex, subtitleStreamIndex,
                maxAudioChannels, mediaSourceId, liveStreamId, deviceProfile, enableDirectPlay, enableDirectStream,
                enableTranscoding, allowVideoStreamCopy, allowAudioStreamCopy, autoOpenLiveStream);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PlaybackInfoDto {\n");
        sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
        sb.append("    maxStreamingBitrate: ").append(toIndentedString(maxStreamingBitrate)).append("\n");
        sb.append("    startTimeTicks: ").append(toIndentedString(startTimeTicks)).append("\n");
        sb.append("    audioStreamIndex: ").append(toIndentedString(audioStreamIndex)).append("\n");
        sb.append("    subtitleStreamIndex: ").append(toIndentedString(subtitleStreamIndex)).append("\n");
        sb.append("    maxAudioChannels: ").append(toIndentedString(maxAudioChannels)).append("\n");
        sb.append("    mediaSourceId: ").append(toIndentedString(mediaSourceId)).append("\n");
        sb.append("    liveStreamId: ").append(toIndentedString(liveStreamId)).append("\n");
        sb.append("    deviceProfile: ").append(toIndentedString(deviceProfile)).append("\n");
        sb.append("    enableDirectPlay: ").append(toIndentedString(enableDirectPlay)).append("\n");
        sb.append("    enableDirectStream: ").append(toIndentedString(enableDirectStream)).append("\n");
        sb.append("    enableTranscoding: ").append(toIndentedString(enableTranscoding)).append("\n");
        sb.append("    allowVideoStreamCopy: ").append(toIndentedString(allowVideoStreamCopy)).append("\n");
        sb.append("    allowAudioStreamCopy: ").append(toIndentedString(allowAudioStreamCopy)).append("\n");
        sb.append("    autoOpenLiveStream: ").append(toIndentedString(autoOpenLiveStream)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static class Builder {

        private PlaybackInfoDto instance;

        public Builder() {
            this(new PlaybackInfoDto());
        }

        protected Builder(PlaybackInfoDto instance) {
            this.instance = instance;
        }

        public PlaybackInfoDto.Builder userId(UUID userId) {
            this.instance.userId = userId;
            return this;
        }

        public PlaybackInfoDto.Builder maxStreamingBitrate(Integer maxStreamingBitrate) {
            this.instance.maxStreamingBitrate = maxStreamingBitrate;
            return this;
        }

        public PlaybackInfoDto.Builder startTimeTicks(Long startTimeTicks) {
            this.instance.startTimeTicks = startTimeTicks;
            return this;
        }

        public PlaybackInfoDto.Builder audioStreamIndex(Integer audioStreamIndex) {
            this.instance.audioStreamIndex = audioStreamIndex;
            return this;
        }

        public PlaybackInfoDto.Builder subtitleStreamIndex(Integer subtitleStreamIndex) {
            this.instance.subtitleStreamIndex = subtitleStreamIndex;
            return this;
        }

        public PlaybackInfoDto.Builder maxAudioChannels(Integer maxAudioChannels) {
            this.instance.maxAudioChannels = maxAudioChannels;
            return this;
        }

        public PlaybackInfoDto.Builder mediaSourceId(String mediaSourceId) {
            this.instance.mediaSourceId = mediaSourceId;
            return this;
        }

        public PlaybackInfoDto.Builder liveStreamId(String liveStreamId) {
            this.instance.liveStreamId = liveStreamId;
            return this;
        }

        public PlaybackInfoDto.Builder deviceProfile(DeviceProfile deviceProfile) {
            this.instance.deviceProfile = deviceProfile;
            return this;
        }

        public PlaybackInfoDto.Builder enableDirectPlay(Boolean enableDirectPlay) {
            this.instance.enableDirectPlay = enableDirectPlay;
            return this;
        }

        public PlaybackInfoDto.Builder enableDirectStream(Boolean enableDirectStream) {
            this.instance.enableDirectStream = enableDirectStream;
            return this;
        }

        public PlaybackInfoDto.Builder enableTranscoding(Boolean enableTranscoding) {
            this.instance.enableTranscoding = enableTranscoding;
            return this;
        }

        public PlaybackInfoDto.Builder allowVideoStreamCopy(Boolean allowVideoStreamCopy) {
            this.instance.allowVideoStreamCopy = allowVideoStreamCopy;
            return this;
        }

        public PlaybackInfoDto.Builder allowAudioStreamCopy(Boolean allowAudioStreamCopy) {
            this.instance.allowAudioStreamCopy = allowAudioStreamCopy;
            return this;
        }

        public PlaybackInfoDto.Builder autoOpenLiveStream(Boolean autoOpenLiveStream) {
            this.instance.autoOpenLiveStream = autoOpenLiveStream;
            return this;
        }

        /**
         * returns a built PlaybackInfoDto instance.
         *
         * The builder is not reusable.
         */
        public PlaybackInfoDto build() {
            try {
                return this.instance;
            } finally {
                // ensure that this.instance is not reused
                this.instance = null;
            }
        }

        @Override
        public String toString() {
            return getClass() + "=(" + instance + ")";
        }
    }

    /**
     * Create a builder with no initialized field.
     */
    public static PlaybackInfoDto.Builder builder() {
        return new PlaybackInfoDto.Builder();
    }

    /**
     * Create a builder with a shallow copy of this instance.
     */
    public PlaybackInfoDto.Builder toBuilder() {
        return new PlaybackInfoDto.Builder().userId(getUserId()).maxStreamingBitrate(getMaxStreamingBitrate())
                .startTimeTicks(getStartTimeTicks()).audioStreamIndex(getAudioStreamIndex())
                .subtitleStreamIndex(getSubtitleStreamIndex()).maxAudioChannels(getMaxAudioChannels())
                .mediaSourceId(getMediaSourceId()).liveStreamId(getLiveStreamId()).deviceProfile(getDeviceProfile())
                .enableDirectPlay(getEnableDirectPlay()).enableDirectStream(getEnableDirectStream())
                .enableTranscoding(getEnableTranscoding()).allowVideoStreamCopy(getAllowVideoStreamCopy())
                .allowAudioStreamCopy(getAllowAudioStreamCopy()).autoOpenLiveStream(getAutoOpenLiveStream());
    }
}
