/*
 * Copyright (c) 2010-2025 Contributors to the openHAB project
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 */

package org.openhab.binding.jellyfin.internal.api.version.legacy.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * QueryFilters
 */
@JsonPropertyOrder({ QueryFilters.JSON_PROPERTY_GENRES, QueryFilters.JSON_PROPERTY_TAGS })
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class QueryFilters {
    public static final String JSON_PROPERTY_GENRES = "Genres";
    @javax.annotation.Nullable
    private List<NameGuidPair> genres;

    public static final String JSON_PROPERTY_TAGS = "Tags";
    @javax.annotation.Nullable
    private List<String> tags;

    public QueryFilters() {
    }

    public QueryFilters genres(@javax.annotation.Nullable List<NameGuidPair> genres) {

        this.genres = genres;
        return this;
    }

    public QueryFilters addGenresItem(NameGuidPair genresItem) {
        if (this.genres == null) {
            this.genres = new ArrayList<>();
        }
        this.genres.add(genresItem);
        return this;
    }

    /**
     * Get genres
     * 
     * @return genres
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_GENRES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<NameGuidPair> getGenres() {
        return genres;
    }

    @JsonProperty(JSON_PROPERTY_GENRES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setGenres(@javax.annotation.Nullable List<NameGuidPair> genres) {
        this.genres = genres;
    }

    public QueryFilters tags(@javax.annotation.Nullable List<String> tags) {

        this.tags = tags;
        return this;
    }

    public QueryFilters addTagsItem(String tagsItem) {
        if (this.tags == null) {
            this.tags = new ArrayList<>();
        }
        this.tags.add(tagsItem);
        return this;
    }

    /**
     * Get tags
     * 
     * @return tags
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TAGS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<String> getTags() {
        return tags;
    }

    @JsonProperty(JSON_PROPERTY_TAGS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTags(@javax.annotation.Nullable List<String> tags) {
        this.tags = tags;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        QueryFilters queryFilters = (QueryFilters) o;
        return Objects.equals(this.genres, queryFilters.genres) && Objects.equals(this.tags, queryFilters.tags);
    }

    @Override
    public int hashCode() {
        return Objects.hash(genres, tags);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class QueryFilters {\n");
        sb.append("    genres: ").append(toIndentedString(genres)).append("\n");
        sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static class Builder {

        private QueryFilters instance;

        public Builder() {
            this(new QueryFilters());
        }

        protected Builder(QueryFilters instance) {
            this.instance = instance;
        }

        public QueryFilters.Builder genres(List<NameGuidPair> genres) {
            this.instance.genres = genres;
            return this;
        }

        public QueryFilters.Builder tags(List<String> tags) {
            this.instance.tags = tags;
            return this;
        }

        /**
         * returns a built QueryFilters instance.
         *
         * The builder is not reusable.
         */
        public QueryFilters build() {
            try {
                return this.instance;
            } finally {
                // ensure that this.instance is not reused
                this.instance = null;
            }
        }

        @Override
        public String toString() {
            return getClass() + "=(" + instance + ")";
        }
    }

    /**
     * Create a builder with no initialized field.
     */
    public static QueryFilters.Builder builder() {
        return new QueryFilters.Builder();
    }

    /**
     * Create a builder with a shallow copy of this instance.
     */
    public QueryFilters.Builder toBuilder() {
        return new QueryFilters.Builder().genres(getGenres()).tags(getTags());
    }
}
