/*
 * Copyright (c) 2010-2025 Contributors to the openHAB project
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 */

package org.openhab.binding.jellyfin.internal.api.version.legacy.model;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Objects;

import org.openapitools.jackson.nullable.JsonNullable;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * RemoteSubtitleInfo
 */
@JsonPropertyOrder({ RemoteSubtitleInfo.JSON_PROPERTY_THREE_LETTER_I_S_O_LANGUAGE_NAME,
        RemoteSubtitleInfo.JSON_PROPERTY_ID, RemoteSubtitleInfo.JSON_PROPERTY_PROVIDER_NAME,
        RemoteSubtitleInfo.JSON_PROPERTY_NAME, RemoteSubtitleInfo.JSON_PROPERTY_FORMAT,
        RemoteSubtitleInfo.JSON_PROPERTY_AUTHOR, RemoteSubtitleInfo.JSON_PROPERTY_COMMENT,
        RemoteSubtitleInfo.JSON_PROPERTY_DATE_CREATED, RemoteSubtitleInfo.JSON_PROPERTY_COMMUNITY_RATING,
        RemoteSubtitleInfo.JSON_PROPERTY_DOWNLOAD_COUNT, RemoteSubtitleInfo.JSON_PROPERTY_IS_HASH_MATCH })
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class RemoteSubtitleInfo {
    public static final String JSON_PROPERTY_THREE_LETTER_I_S_O_LANGUAGE_NAME = "ThreeLetterISOLanguageName";
    @javax.annotation.Nullable
    private JsonNullable<String> threeLetterISOLanguageName = JsonNullable.<String> undefined();

    public static final String JSON_PROPERTY_ID = "Id";
    @javax.annotation.Nullable
    private JsonNullable<String> id = JsonNullable.<String> undefined();

    public static final String JSON_PROPERTY_PROVIDER_NAME = "ProviderName";
    @javax.annotation.Nullable
    private JsonNullable<String> providerName = JsonNullable.<String> undefined();

    public static final String JSON_PROPERTY_NAME = "Name";
    @javax.annotation.Nullable
    private JsonNullable<String> name = JsonNullable.<String> undefined();

    public static final String JSON_PROPERTY_FORMAT = "Format";
    @javax.annotation.Nullable
    private JsonNullable<String> format = JsonNullable.<String> undefined();

    public static final String JSON_PROPERTY_AUTHOR = "Author";
    @javax.annotation.Nullable
    private JsonNullable<String> author = JsonNullable.<String> undefined();

    public static final String JSON_PROPERTY_COMMENT = "Comment";
    @javax.annotation.Nullable
    private JsonNullable<String> comment = JsonNullable.<String> undefined();

    public static final String JSON_PROPERTY_DATE_CREATED = "DateCreated";
    @javax.annotation.Nullable
    private JsonNullable<OffsetDateTime> dateCreated = JsonNullable.<OffsetDateTime> undefined();

    public static final String JSON_PROPERTY_COMMUNITY_RATING = "CommunityRating";
    @javax.annotation.Nullable
    private JsonNullable<Float> communityRating = JsonNullable.<Float> undefined();

    public static final String JSON_PROPERTY_DOWNLOAD_COUNT = "DownloadCount";
    @javax.annotation.Nullable
    private JsonNullable<Integer> downloadCount = JsonNullable.<Integer> undefined();

    public static final String JSON_PROPERTY_IS_HASH_MATCH = "IsHashMatch";
    @javax.annotation.Nullable
    private JsonNullable<Boolean> isHashMatch = JsonNullable.<Boolean> undefined();

    public RemoteSubtitleInfo() {
    }

    public RemoteSubtitleInfo threeLetterISOLanguageName(@javax.annotation.Nullable String threeLetterISOLanguageName) {
        this.threeLetterISOLanguageName = JsonNullable.<String> of(threeLetterISOLanguageName);

        return this;
    }

    /**
     * Get threeLetterISOLanguageName
     * 
     * @return threeLetterISOLanguageName
     */
    @javax.annotation.Nullable
    @JsonIgnore

    public String getThreeLetterISOLanguageName() {
        return threeLetterISOLanguageName.orElse(null);
    }

    @JsonProperty(JSON_PROPERTY_THREE_LETTER_I_S_O_LANGUAGE_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public JsonNullable<String> getThreeLetterISOLanguageName_JsonNullable() {
        return threeLetterISOLanguageName;
    }

    @JsonProperty(JSON_PROPERTY_THREE_LETTER_I_S_O_LANGUAGE_NAME)
    public void setThreeLetterISOLanguageName_JsonNullable(JsonNullable<String> threeLetterISOLanguageName) {
        this.threeLetterISOLanguageName = threeLetterISOLanguageName;
    }

    public void setThreeLetterISOLanguageName(@javax.annotation.Nullable String threeLetterISOLanguageName) {
        this.threeLetterISOLanguageName = JsonNullable.<String> of(threeLetterISOLanguageName);
    }

    public RemoteSubtitleInfo id(@javax.annotation.Nullable String id) {
        this.id = JsonNullable.<String> of(id);

        return this;
    }

    /**
     * Get id
     * 
     * @return id
     */
    @javax.annotation.Nullable
    @JsonIgnore

    public String getId() {
        return id.orElse(null);
    }

    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public JsonNullable<String> getId_JsonNullable() {
        return id;
    }

    @JsonProperty(JSON_PROPERTY_ID)
    public void setId_JsonNullable(JsonNullable<String> id) {
        this.id = id;
    }

    public void setId(@javax.annotation.Nullable String id) {
        this.id = JsonNullable.<String> of(id);
    }

    public RemoteSubtitleInfo providerName(@javax.annotation.Nullable String providerName) {
        this.providerName = JsonNullable.<String> of(providerName);

        return this;
    }

    /**
     * Get providerName
     * 
     * @return providerName
     */
    @javax.annotation.Nullable
    @JsonIgnore

    public String getProviderName() {
        return providerName.orElse(null);
    }

    @JsonProperty(JSON_PROPERTY_PROVIDER_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public JsonNullable<String> getProviderName_JsonNullable() {
        return providerName;
    }

    @JsonProperty(JSON_PROPERTY_PROVIDER_NAME)
    public void setProviderName_JsonNullable(JsonNullable<String> providerName) {
        this.providerName = providerName;
    }

    public void setProviderName(@javax.annotation.Nullable String providerName) {
        this.providerName = JsonNullable.<String> of(providerName);
    }

    public RemoteSubtitleInfo name(@javax.annotation.Nullable String name) {
        this.name = JsonNullable.<String> of(name);

        return this;
    }

    /**
     * Get name
     * 
     * @return name
     */
    @javax.annotation.Nullable
    @JsonIgnore

    public String getName() {
        return name.orElse(null);
    }

    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public JsonNullable<String> getName_JsonNullable() {
        return name;
    }

    @JsonProperty(JSON_PROPERTY_NAME)
    public void setName_JsonNullable(JsonNullable<String> name) {
        this.name = name;
    }

    public void setName(@javax.annotation.Nullable String name) {
        this.name = JsonNullable.<String> of(name);
    }

    public RemoteSubtitleInfo format(@javax.annotation.Nullable String format) {
        this.format = JsonNullable.<String> of(format);

        return this;
    }

    /**
     * Get format
     * 
     * @return format
     */
    @javax.annotation.Nullable
    @JsonIgnore

    public String getFormat() {
        return format.orElse(null);
    }

    @JsonProperty(JSON_PROPERTY_FORMAT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public JsonNullable<String> getFormat_JsonNullable() {
        return format;
    }

    @JsonProperty(JSON_PROPERTY_FORMAT)
    public void setFormat_JsonNullable(JsonNullable<String> format) {
        this.format = format;
    }

    public void setFormat(@javax.annotation.Nullable String format) {
        this.format = JsonNullable.<String> of(format);
    }

    public RemoteSubtitleInfo author(@javax.annotation.Nullable String author) {
        this.author = JsonNullable.<String> of(author);

        return this;
    }

    /**
     * Get author
     * 
     * @return author
     */
    @javax.annotation.Nullable
    @JsonIgnore

    public String getAuthor() {
        return author.orElse(null);
    }

    @JsonProperty(JSON_PROPERTY_AUTHOR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public JsonNullable<String> getAuthor_JsonNullable() {
        return author;
    }

    @JsonProperty(JSON_PROPERTY_AUTHOR)
    public void setAuthor_JsonNullable(JsonNullable<String> author) {
        this.author = author;
    }

    public void setAuthor(@javax.annotation.Nullable String author) {
        this.author = JsonNullable.<String> of(author);
    }

    public RemoteSubtitleInfo comment(@javax.annotation.Nullable String comment) {
        this.comment = JsonNullable.<String> of(comment);

        return this;
    }

    /**
     * Get comment
     * 
     * @return comment
     */
    @javax.annotation.Nullable
    @JsonIgnore

    public String getComment() {
        return comment.orElse(null);
    }

    @JsonProperty(JSON_PROPERTY_COMMENT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public JsonNullable<String> getComment_JsonNullable() {
        return comment;
    }

    @JsonProperty(JSON_PROPERTY_COMMENT)
    public void setComment_JsonNullable(JsonNullable<String> comment) {
        this.comment = comment;
    }

    public void setComment(@javax.annotation.Nullable String comment) {
        this.comment = JsonNullable.<String> of(comment);
    }

    public RemoteSubtitleInfo dateCreated(@javax.annotation.Nullable OffsetDateTime dateCreated) {
        this.dateCreated = JsonNullable.<OffsetDateTime> of(dateCreated);

        return this;
    }

    /**
     * Get dateCreated
     * 
     * @return dateCreated
     */
    @javax.annotation.Nullable
    @JsonIgnore

    public OffsetDateTime getDateCreated() {
        return dateCreated.orElse(null);
    }

    @JsonProperty(JSON_PROPERTY_DATE_CREATED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public JsonNullable<OffsetDateTime> getDateCreated_JsonNullable() {
        return dateCreated;
    }

    @JsonProperty(JSON_PROPERTY_DATE_CREATED)
    public void setDateCreated_JsonNullable(JsonNullable<OffsetDateTime> dateCreated) {
        this.dateCreated = dateCreated;
    }

    public void setDateCreated(@javax.annotation.Nullable OffsetDateTime dateCreated) {
        this.dateCreated = JsonNullable.<OffsetDateTime> of(dateCreated);
    }

    public RemoteSubtitleInfo communityRating(@javax.annotation.Nullable Float communityRating) {
        this.communityRating = JsonNullable.<Float> of(communityRating);

        return this;
    }

    /**
     * Get communityRating
     * 
     * @return communityRating
     */
    @javax.annotation.Nullable
    @JsonIgnore

    public Float getCommunityRating() {
        return communityRating.orElse(null);
    }

    @JsonProperty(JSON_PROPERTY_COMMUNITY_RATING)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public JsonNullable<Float> getCommunityRating_JsonNullable() {
        return communityRating;
    }

    @JsonProperty(JSON_PROPERTY_COMMUNITY_RATING)
    public void setCommunityRating_JsonNullable(JsonNullable<Float> communityRating) {
        this.communityRating = communityRating;
    }

    public void setCommunityRating(@javax.annotation.Nullable Float communityRating) {
        this.communityRating = JsonNullable.<Float> of(communityRating);
    }

    public RemoteSubtitleInfo downloadCount(@javax.annotation.Nullable Integer downloadCount) {
        this.downloadCount = JsonNullable.<Integer> of(downloadCount);

        return this;
    }

    /**
     * Get downloadCount
     * 
     * @return downloadCount
     */
    @javax.annotation.Nullable
    @JsonIgnore

    public Integer getDownloadCount() {
        return downloadCount.orElse(null);
    }

    @JsonProperty(JSON_PROPERTY_DOWNLOAD_COUNT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public JsonNullable<Integer> getDownloadCount_JsonNullable() {
        return downloadCount;
    }

    @JsonProperty(JSON_PROPERTY_DOWNLOAD_COUNT)
    public void setDownloadCount_JsonNullable(JsonNullable<Integer> downloadCount) {
        this.downloadCount = downloadCount;
    }

    public void setDownloadCount(@javax.annotation.Nullable Integer downloadCount) {
        this.downloadCount = JsonNullable.<Integer> of(downloadCount);
    }

    public RemoteSubtitleInfo isHashMatch(@javax.annotation.Nullable Boolean isHashMatch) {
        this.isHashMatch = JsonNullable.<Boolean> of(isHashMatch);

        return this;
    }

    /**
     * Get isHashMatch
     * 
     * @return isHashMatch
     */
    @javax.annotation.Nullable
    @JsonIgnore

    public Boolean getIsHashMatch() {
        return isHashMatch.orElse(null);
    }

    @JsonProperty(JSON_PROPERTY_IS_HASH_MATCH)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public JsonNullable<Boolean> getIsHashMatch_JsonNullable() {
        return isHashMatch;
    }

    @JsonProperty(JSON_PROPERTY_IS_HASH_MATCH)
    public void setIsHashMatch_JsonNullable(JsonNullable<Boolean> isHashMatch) {
        this.isHashMatch = isHashMatch;
    }

    public void setIsHashMatch(@javax.annotation.Nullable Boolean isHashMatch) {
        this.isHashMatch = JsonNullable.<Boolean> of(isHashMatch);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RemoteSubtitleInfo remoteSubtitleInfo = (RemoteSubtitleInfo) o;
        return equalsNullable(this.threeLetterISOLanguageName, remoteSubtitleInfo.threeLetterISOLanguageName)
                && equalsNullable(this.id, remoteSubtitleInfo.id)
                && equalsNullable(this.providerName, remoteSubtitleInfo.providerName)
                && equalsNullable(this.name, remoteSubtitleInfo.name)
                && equalsNullable(this.format, remoteSubtitleInfo.format)
                && equalsNullable(this.author, remoteSubtitleInfo.author)
                && equalsNullable(this.comment, remoteSubtitleInfo.comment)
                && equalsNullable(this.dateCreated, remoteSubtitleInfo.dateCreated)
                && equalsNullable(this.communityRating, remoteSubtitleInfo.communityRating)
                && equalsNullable(this.downloadCount, remoteSubtitleInfo.downloadCount)
                && equalsNullable(this.isHashMatch, remoteSubtitleInfo.isHashMatch);
    }

    private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
        return a == b
                || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
    }

    @Override
    public int hashCode() {
        return Objects.hash(hashCodeNullable(threeLetterISOLanguageName), hashCodeNullable(id),
                hashCodeNullable(providerName), hashCodeNullable(name), hashCodeNullable(format),
                hashCodeNullable(author), hashCodeNullable(comment), hashCodeNullable(dateCreated),
                hashCodeNullable(communityRating), hashCodeNullable(downloadCount), hashCodeNullable(isHashMatch));
    }

    private static <T> int hashCodeNullable(JsonNullable<T> a) {
        if (a == null) {
            return 1;
        }
        return a.isPresent() ? Arrays.deepHashCode(new Object[] { a.get() }) : 31;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class RemoteSubtitleInfo {\n");
        sb.append("    threeLetterISOLanguageName: ").append(toIndentedString(threeLetterISOLanguageName)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    providerName: ").append(toIndentedString(providerName)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    format: ").append(toIndentedString(format)).append("\n");
        sb.append("    author: ").append(toIndentedString(author)).append("\n");
        sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
        sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
        sb.append("    communityRating: ").append(toIndentedString(communityRating)).append("\n");
        sb.append("    downloadCount: ").append(toIndentedString(downloadCount)).append("\n");
        sb.append("    isHashMatch: ").append(toIndentedString(isHashMatch)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static class Builder {

        private RemoteSubtitleInfo instance;

        public Builder() {
            this(new RemoteSubtitleInfo());
        }

        protected Builder(RemoteSubtitleInfo instance) {
            this.instance = instance;
        }

        public RemoteSubtitleInfo.Builder threeLetterISOLanguageName(String threeLetterISOLanguageName) {
            this.instance.threeLetterISOLanguageName = JsonNullable.<String> of(threeLetterISOLanguageName);
            return this;
        }

        public RemoteSubtitleInfo.Builder threeLetterISOLanguageName(JsonNullable<String> threeLetterISOLanguageName) {
            this.instance.threeLetterISOLanguageName = threeLetterISOLanguageName;
            return this;
        }

        public RemoteSubtitleInfo.Builder id(String id) {
            this.instance.id = JsonNullable.<String> of(id);
            return this;
        }

        public RemoteSubtitleInfo.Builder id(JsonNullable<String> id) {
            this.instance.id = id;
            return this;
        }

        public RemoteSubtitleInfo.Builder providerName(String providerName) {
            this.instance.providerName = JsonNullable.<String> of(providerName);
            return this;
        }

        public RemoteSubtitleInfo.Builder providerName(JsonNullable<String> providerName) {
            this.instance.providerName = providerName;
            return this;
        }

        public RemoteSubtitleInfo.Builder name(String name) {
            this.instance.name = JsonNullable.<String> of(name);
            return this;
        }

        public RemoteSubtitleInfo.Builder name(JsonNullable<String> name) {
            this.instance.name = name;
            return this;
        }

        public RemoteSubtitleInfo.Builder format(String format) {
            this.instance.format = JsonNullable.<String> of(format);
            return this;
        }

        public RemoteSubtitleInfo.Builder format(JsonNullable<String> format) {
            this.instance.format = format;
            return this;
        }

        public RemoteSubtitleInfo.Builder author(String author) {
            this.instance.author = JsonNullable.<String> of(author);
            return this;
        }

        public RemoteSubtitleInfo.Builder author(JsonNullable<String> author) {
            this.instance.author = author;
            return this;
        }

        public RemoteSubtitleInfo.Builder comment(String comment) {
            this.instance.comment = JsonNullable.<String> of(comment);
            return this;
        }

        public RemoteSubtitleInfo.Builder comment(JsonNullable<String> comment) {
            this.instance.comment = comment;
            return this;
        }

        public RemoteSubtitleInfo.Builder dateCreated(OffsetDateTime dateCreated) {
            this.instance.dateCreated = JsonNullable.<OffsetDateTime> of(dateCreated);
            return this;
        }

        public RemoteSubtitleInfo.Builder dateCreated(JsonNullable<OffsetDateTime> dateCreated) {
            this.instance.dateCreated = dateCreated;
            return this;
        }

        public RemoteSubtitleInfo.Builder communityRating(Float communityRating) {
            this.instance.communityRating = JsonNullable.<Float> of(communityRating);
            return this;
        }

        public RemoteSubtitleInfo.Builder communityRating(JsonNullable<Float> communityRating) {
            this.instance.communityRating = communityRating;
            return this;
        }

        public RemoteSubtitleInfo.Builder downloadCount(Integer downloadCount) {
            this.instance.downloadCount = JsonNullable.<Integer> of(downloadCount);
            return this;
        }

        public RemoteSubtitleInfo.Builder downloadCount(JsonNullable<Integer> downloadCount) {
            this.instance.downloadCount = downloadCount;
            return this;
        }

        public RemoteSubtitleInfo.Builder isHashMatch(Boolean isHashMatch) {
            this.instance.isHashMatch = JsonNullable.<Boolean> of(isHashMatch);
            return this;
        }

        public RemoteSubtitleInfo.Builder isHashMatch(JsonNullable<Boolean> isHashMatch) {
            this.instance.isHashMatch = isHashMatch;
            return this;
        }

        /**
         * returns a built RemoteSubtitleInfo instance.
         *
         * The builder is not reusable.
         */
        public RemoteSubtitleInfo build() {
            try {
                return this.instance;
            } finally {
                // ensure that this.instance is not reused
                this.instance = null;
            }
        }

        @Override
        public String toString() {
            return getClass() + "=(" + instance + ")";
        }
    }

    /**
     * Create a builder with no initialized field.
     */
    public static RemoteSubtitleInfo.Builder builder() {
        return new RemoteSubtitleInfo.Builder();
    }

    /**
     * Create a builder with a shallow copy of this instance.
     */
    public RemoteSubtitleInfo.Builder toBuilder() {
        return new RemoteSubtitleInfo.Builder().threeLetterISOLanguageName(getThreeLetterISOLanguageName()).id(getId())
                .providerName(getProviderName()).name(getName()).format(getFormat()).author(getAuthor())
                .comment(getComment()).dateCreated(getDateCreated()).communityRating(getCommunityRating())
                .downloadCount(getDownloadCount()).isHashMatch(getIsHashMatch());
    }
}
