/*
 * Copyright (c) 2010-2025 Contributors to the openHAB project
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 */

package org.openhab.binding.jellyfin.internal.api.version.legacy.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * ResponseProfile
 */
@JsonPropertyOrder({ ResponseProfile.JSON_PROPERTY_CONTAINER, ResponseProfile.JSON_PROPERTY_AUDIO_CODEC,
        ResponseProfile.JSON_PROPERTY_VIDEO_CODEC, ResponseProfile.JSON_PROPERTY_TYPE,
        ResponseProfile.JSON_PROPERTY_ORG_PN, ResponseProfile.JSON_PROPERTY_MIME_TYPE,
        ResponseProfile.JSON_PROPERTY_CONDITIONS })
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class ResponseProfile {
    public static final String JSON_PROPERTY_CONTAINER = "Container";
    @javax.annotation.Nullable
    private String container;

    public static final String JSON_PROPERTY_AUDIO_CODEC = "AudioCodec";
    @javax.annotation.Nullable
    private String audioCodec;

    public static final String JSON_PROPERTY_VIDEO_CODEC = "VideoCodec";
    @javax.annotation.Nullable
    private String videoCodec;

    public static final String JSON_PROPERTY_TYPE = "Type";
    @javax.annotation.Nullable
    private DlnaProfileType type;

    public static final String JSON_PROPERTY_ORG_PN = "OrgPn";
    @javax.annotation.Nullable
    private String orgPn;

    public static final String JSON_PROPERTY_MIME_TYPE = "MimeType";
    @javax.annotation.Nullable
    private String mimeType;

    public static final String JSON_PROPERTY_CONDITIONS = "Conditions";
    @javax.annotation.Nullable
    private List<ProfileCondition> conditions;

    public ResponseProfile() {
    }

    public ResponseProfile container(@javax.annotation.Nullable String container) {

        this.container = container;
        return this;
    }

    /**
     * Get container
     * 
     * @return container
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CONTAINER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getContainer() {
        return container;
    }

    @JsonProperty(JSON_PROPERTY_CONTAINER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setContainer(@javax.annotation.Nullable String container) {
        this.container = container;
    }

    public ResponseProfile audioCodec(@javax.annotation.Nullable String audioCodec) {

        this.audioCodec = audioCodec;
        return this;
    }

    /**
     * Get audioCodec
     * 
     * @return audioCodec
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_AUDIO_CODEC)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getAudioCodec() {
        return audioCodec;
    }

    @JsonProperty(JSON_PROPERTY_AUDIO_CODEC)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAudioCodec(@javax.annotation.Nullable String audioCodec) {
        this.audioCodec = audioCodec;
    }

    public ResponseProfile videoCodec(@javax.annotation.Nullable String videoCodec) {

        this.videoCodec = videoCodec;
        return this;
    }

    /**
     * Get videoCodec
     * 
     * @return videoCodec
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_VIDEO_CODEC)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getVideoCodec() {
        return videoCodec;
    }

    @JsonProperty(JSON_PROPERTY_VIDEO_CODEC)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setVideoCodec(@javax.annotation.Nullable String videoCodec) {
        this.videoCodec = videoCodec;
    }

    public ResponseProfile type(@javax.annotation.Nullable DlnaProfileType type) {

        this.type = type;
        return this;
    }

    /**
     * Get type
     * 
     * @return type
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public DlnaProfileType getType() {
        return type;
    }

    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setType(@javax.annotation.Nullable DlnaProfileType type) {
        this.type = type;
    }

    public ResponseProfile orgPn(@javax.annotation.Nullable String orgPn) {

        this.orgPn = orgPn;
        return this;
    }

    /**
     * Get orgPn
     * 
     * @return orgPn
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ORG_PN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getOrgPn() {
        return orgPn;
    }

    @JsonProperty(JSON_PROPERTY_ORG_PN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setOrgPn(@javax.annotation.Nullable String orgPn) {
        this.orgPn = orgPn;
    }

    public ResponseProfile mimeType(@javax.annotation.Nullable String mimeType) {

        this.mimeType = mimeType;
        return this;
    }

    /**
     * Get mimeType
     * 
     * @return mimeType
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_MIME_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getMimeType() {
        return mimeType;
    }

    @JsonProperty(JSON_PROPERTY_MIME_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMimeType(@javax.annotation.Nullable String mimeType) {
        this.mimeType = mimeType;
    }

    public ResponseProfile conditions(@javax.annotation.Nullable List<ProfileCondition> conditions) {

        this.conditions = conditions;
        return this;
    }

    public ResponseProfile addConditionsItem(ProfileCondition conditionsItem) {
        if (this.conditions == null) {
            this.conditions = new ArrayList<>();
        }
        this.conditions.add(conditionsItem);
        return this;
    }

    /**
     * Get conditions
     * 
     * @return conditions
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CONDITIONS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<ProfileCondition> getConditions() {
        return conditions;
    }

    @JsonProperty(JSON_PROPERTY_CONDITIONS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setConditions(@javax.annotation.Nullable List<ProfileCondition> conditions) {
        this.conditions = conditions;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ResponseProfile responseProfile = (ResponseProfile) o;
        return Objects.equals(this.container, responseProfile.container)
                && Objects.equals(this.audioCodec, responseProfile.audioCodec)
                && Objects.equals(this.videoCodec, responseProfile.videoCodec)
                && Objects.equals(this.type, responseProfile.type) && Objects.equals(this.orgPn, responseProfile.orgPn)
                && Objects.equals(this.mimeType, responseProfile.mimeType)
                && Objects.equals(this.conditions, responseProfile.conditions);
    }

    @Override
    public int hashCode() {
        return Objects.hash(container, audioCodec, videoCodec, type, orgPn, mimeType, conditions);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ResponseProfile {\n");
        sb.append("    container: ").append(toIndentedString(container)).append("\n");
        sb.append("    audioCodec: ").append(toIndentedString(audioCodec)).append("\n");
        sb.append("    videoCodec: ").append(toIndentedString(videoCodec)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    orgPn: ").append(toIndentedString(orgPn)).append("\n");
        sb.append("    mimeType: ").append(toIndentedString(mimeType)).append("\n");
        sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static class Builder {

        private ResponseProfile instance;

        public Builder() {
            this(new ResponseProfile());
        }

        protected Builder(ResponseProfile instance) {
            this.instance = instance;
        }

        public ResponseProfile.Builder container(String container) {
            this.instance.container = container;
            return this;
        }

        public ResponseProfile.Builder audioCodec(String audioCodec) {
            this.instance.audioCodec = audioCodec;
            return this;
        }

        public ResponseProfile.Builder videoCodec(String videoCodec) {
            this.instance.videoCodec = videoCodec;
            return this;
        }

        public ResponseProfile.Builder type(DlnaProfileType type) {
            this.instance.type = type;
            return this;
        }

        public ResponseProfile.Builder orgPn(String orgPn) {
            this.instance.orgPn = orgPn;
            return this;
        }

        public ResponseProfile.Builder mimeType(String mimeType) {
            this.instance.mimeType = mimeType;
            return this;
        }

        public ResponseProfile.Builder conditions(List<ProfileCondition> conditions) {
            this.instance.conditions = conditions;
            return this;
        }

        /**
         * returns a built ResponseProfile instance.
         *
         * The builder is not reusable.
         */
        public ResponseProfile build() {
            try {
                return this.instance;
            } finally {
                // ensure that this.instance is not reused
                this.instance = null;
            }
        }

        @Override
        public String toString() {
            return getClass() + "=(" + instance + ")";
        }
    }

    /**
     * Create a builder with no initialized field.
     */
    public static ResponseProfile.Builder builder() {
        return new ResponseProfile.Builder();
    }

    /**
     * Create a builder with a shallow copy of this instance.
     */
    public ResponseProfile.Builder toBuilder() {
        return new ResponseProfile.Builder().container(getContainer()).audioCodec(getAudioCodec())
                .videoCodec(getVideoCodec()).type(getType()).orgPn(getOrgPn()).mimeType(getMimeType())
                .conditions(getConditions());
    }
}
