/*
 * Copyright (c) 2010-2025 Contributors to the openHAB project
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 */

package org.openhab.binding.jellyfin.internal.api.version.legacy.model;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Class SessionInfo.
 */
@JsonPropertyOrder({ SessionInfo.JSON_PROPERTY_PLAY_STATE, SessionInfo.JSON_PROPERTY_ADDITIONAL_USERS,
        SessionInfo.JSON_PROPERTY_CAPABILITIES, SessionInfo.JSON_PROPERTY_REMOTE_END_POINT,
        SessionInfo.JSON_PROPERTY_PLAYABLE_MEDIA_TYPES, SessionInfo.JSON_PROPERTY_ID, SessionInfo.JSON_PROPERTY_USER_ID,
        SessionInfo.JSON_PROPERTY_USER_NAME, SessionInfo.JSON_PROPERTY_CLIENT,
        SessionInfo.JSON_PROPERTY_LAST_ACTIVITY_DATE, SessionInfo.JSON_PROPERTY_LAST_PLAYBACK_CHECK_IN,
        SessionInfo.JSON_PROPERTY_DEVICE_NAME, SessionInfo.JSON_PROPERTY_DEVICE_TYPE,
        SessionInfo.JSON_PROPERTY_NOW_PLAYING_ITEM, SessionInfo.JSON_PROPERTY_FULL_NOW_PLAYING_ITEM,
        SessionInfo.JSON_PROPERTY_NOW_VIEWING_ITEM, SessionInfo.JSON_PROPERTY_DEVICE_ID,
        SessionInfo.JSON_PROPERTY_APPLICATION_VERSION, SessionInfo.JSON_PROPERTY_TRANSCODING_INFO,
        SessionInfo.JSON_PROPERTY_IS_ACTIVE, SessionInfo.JSON_PROPERTY_SUPPORTS_MEDIA_CONTROL,
        SessionInfo.JSON_PROPERTY_SUPPORTS_REMOTE_CONTROL, SessionInfo.JSON_PROPERTY_NOW_PLAYING_QUEUE,
        SessionInfo.JSON_PROPERTY_NOW_PLAYING_QUEUE_FULL_ITEMS, SessionInfo.JSON_PROPERTY_HAS_CUSTOM_DEVICE_NAME,
        SessionInfo.JSON_PROPERTY_PLAYLIST_ITEM_ID, SessionInfo.JSON_PROPERTY_SERVER_ID,
        SessionInfo.JSON_PROPERTY_USER_PRIMARY_IMAGE_TAG, SessionInfo.JSON_PROPERTY_SUPPORTED_COMMANDS })
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class SessionInfo {
    public static final String JSON_PROPERTY_PLAY_STATE = "PlayState";
    @javax.annotation.Nullable
    private PlayerStateInfo playState;

    public static final String JSON_PROPERTY_ADDITIONAL_USERS = "AdditionalUsers";
    @javax.annotation.Nullable
    private List<SessionUserInfo> additionalUsers;

    public static final String JSON_PROPERTY_CAPABILITIES = "Capabilities";
    @javax.annotation.Nullable
    private ClientCapabilities capabilities;

    public static final String JSON_PROPERTY_REMOTE_END_POINT = "RemoteEndPoint";
    @javax.annotation.Nullable
    private String remoteEndPoint;

    public static final String JSON_PROPERTY_PLAYABLE_MEDIA_TYPES = "PlayableMediaTypes";
    @javax.annotation.Nullable
    private List<String> playableMediaTypes;

    public static final String JSON_PROPERTY_ID = "Id";
    @javax.annotation.Nullable
    private String id;

    public static final String JSON_PROPERTY_USER_ID = "UserId";
    @javax.annotation.Nullable
    private UUID userId;

    public static final String JSON_PROPERTY_USER_NAME = "UserName";
    @javax.annotation.Nullable
    private String userName;

    public static final String JSON_PROPERTY_CLIENT = "Client";
    @javax.annotation.Nullable
    private String client;

    public static final String JSON_PROPERTY_LAST_ACTIVITY_DATE = "LastActivityDate";
    @javax.annotation.Nullable
    private OffsetDateTime lastActivityDate;

    public static final String JSON_PROPERTY_LAST_PLAYBACK_CHECK_IN = "LastPlaybackCheckIn";
    @javax.annotation.Nullable
    private OffsetDateTime lastPlaybackCheckIn;

    public static final String JSON_PROPERTY_DEVICE_NAME = "DeviceName";
    @javax.annotation.Nullable
    private String deviceName;

    public static final String JSON_PROPERTY_DEVICE_TYPE = "DeviceType";
    @javax.annotation.Nullable
    private String deviceType;

    public static final String JSON_PROPERTY_NOW_PLAYING_ITEM = "NowPlayingItem";
    @javax.annotation.Nullable
    private BaseItemDto nowPlayingItem;

    public static final String JSON_PROPERTY_FULL_NOW_PLAYING_ITEM = "FullNowPlayingItem";
    @javax.annotation.Nullable
    private BaseItem fullNowPlayingItem;

    public static final String JSON_PROPERTY_NOW_VIEWING_ITEM = "NowViewingItem";
    @javax.annotation.Nullable
    private BaseItemDto nowViewingItem;

    public static final String JSON_PROPERTY_DEVICE_ID = "DeviceId";
    @javax.annotation.Nullable
    private String deviceId;

    public static final String JSON_PROPERTY_APPLICATION_VERSION = "ApplicationVersion";
    @javax.annotation.Nullable
    private String applicationVersion;

    public static final String JSON_PROPERTY_TRANSCODING_INFO = "TranscodingInfo";
    @javax.annotation.Nullable
    private TranscodingInfo transcodingInfo;

    public static final String JSON_PROPERTY_IS_ACTIVE = "IsActive";
    @javax.annotation.Nullable
    private Boolean isActive;

    public static final String JSON_PROPERTY_SUPPORTS_MEDIA_CONTROL = "SupportsMediaControl";
    @javax.annotation.Nullable
    private Boolean supportsMediaControl;

    public static final String JSON_PROPERTY_SUPPORTS_REMOTE_CONTROL = "SupportsRemoteControl";
    @javax.annotation.Nullable
    private Boolean supportsRemoteControl;

    public static final String JSON_PROPERTY_NOW_PLAYING_QUEUE = "NowPlayingQueue";
    @javax.annotation.Nullable
    private List<QueueItem> nowPlayingQueue;

    public static final String JSON_PROPERTY_NOW_PLAYING_QUEUE_FULL_ITEMS = "NowPlayingQueueFullItems";
    @javax.annotation.Nullable
    private List<BaseItemDto> nowPlayingQueueFullItems;

    public static final String JSON_PROPERTY_HAS_CUSTOM_DEVICE_NAME = "HasCustomDeviceName";
    @javax.annotation.Nullable
    private Boolean hasCustomDeviceName;

    public static final String JSON_PROPERTY_PLAYLIST_ITEM_ID = "PlaylistItemId";
    @javax.annotation.Nullable
    private String playlistItemId;

    public static final String JSON_PROPERTY_SERVER_ID = "ServerId";
    @javax.annotation.Nullable
    private String serverId;

    public static final String JSON_PROPERTY_USER_PRIMARY_IMAGE_TAG = "UserPrimaryImageTag";
    @javax.annotation.Nullable
    private String userPrimaryImageTag;

    public static final String JSON_PROPERTY_SUPPORTED_COMMANDS = "SupportedCommands";
    @javax.annotation.Nullable
    private List<GeneralCommandType> supportedCommands;

    public SessionInfo() {
    }

    /**
     * Constructor with only readonly parameters
     */
    @JsonCreator
    public SessionInfo(@JsonProperty(JSON_PROPERTY_PLAYABLE_MEDIA_TYPES) List<String> playableMediaTypes,
            @JsonProperty(JSON_PROPERTY_IS_ACTIVE) Boolean isActive,
            @JsonProperty(JSON_PROPERTY_SUPPORTS_MEDIA_CONTROL) Boolean supportsMediaControl,
            @JsonProperty(JSON_PROPERTY_SUPPORTS_REMOTE_CONTROL) Boolean supportsRemoteControl,
            @JsonProperty(JSON_PROPERTY_SUPPORTED_COMMANDS) List<GeneralCommandType> supportedCommands) {
        this();
        this.playableMediaTypes = playableMediaTypes;
        this.isActive = isActive;
        this.supportsMediaControl = supportsMediaControl;
        this.supportsRemoteControl = supportsRemoteControl;
        this.supportedCommands = supportedCommands;
    }

    public SessionInfo playState(@javax.annotation.Nullable PlayerStateInfo playState) {

        this.playState = playState;
        return this;
    }

    /**
     * Get playState
     * 
     * @return playState
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PLAY_STATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public PlayerStateInfo getPlayState() {
        return playState;
    }

    @JsonProperty(JSON_PROPERTY_PLAY_STATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPlayState(@javax.annotation.Nullable PlayerStateInfo playState) {
        this.playState = playState;
    }

    public SessionInfo additionalUsers(@javax.annotation.Nullable List<SessionUserInfo> additionalUsers) {

        this.additionalUsers = additionalUsers;
        return this;
    }

    public SessionInfo addAdditionalUsersItem(SessionUserInfo additionalUsersItem) {
        if (this.additionalUsers == null) {
            this.additionalUsers = new ArrayList<>();
        }
        this.additionalUsers.add(additionalUsersItem);
        return this;
    }

    /**
     * Get additionalUsers
     * 
     * @return additionalUsers
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ADDITIONAL_USERS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<SessionUserInfo> getAdditionalUsers() {
        return additionalUsers;
    }

    @JsonProperty(JSON_PROPERTY_ADDITIONAL_USERS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAdditionalUsers(@javax.annotation.Nullable List<SessionUserInfo> additionalUsers) {
        this.additionalUsers = additionalUsers;
    }

    public SessionInfo capabilities(@javax.annotation.Nullable ClientCapabilities capabilities) {

        this.capabilities = capabilities;
        return this;
    }

    /**
     * Get capabilities
     * 
     * @return capabilities
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CAPABILITIES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public ClientCapabilities getCapabilities() {
        return capabilities;
    }

    @JsonProperty(JSON_PROPERTY_CAPABILITIES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCapabilities(@javax.annotation.Nullable ClientCapabilities capabilities) {
        this.capabilities = capabilities;
    }

    public SessionInfo remoteEndPoint(@javax.annotation.Nullable String remoteEndPoint) {

        this.remoteEndPoint = remoteEndPoint;
        return this;
    }

    /**
     * Gets or sets the remote end point.
     * 
     * @return remoteEndPoint
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_REMOTE_END_POINT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getRemoteEndPoint() {
        return remoteEndPoint;
    }

    @JsonProperty(JSON_PROPERTY_REMOTE_END_POINT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRemoteEndPoint(@javax.annotation.Nullable String remoteEndPoint) {
        this.remoteEndPoint = remoteEndPoint;
    }

    /**
     * Gets the playable media types.
     * 
     * @return playableMediaTypes
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PLAYABLE_MEDIA_TYPES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<String> getPlayableMediaTypes() {
        return playableMediaTypes;
    }

    public SessionInfo id(@javax.annotation.Nullable String id) {

        this.id = id;
        return this;
    }

    /**
     * Gets or sets the id.
     * 
     * @return id
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getId() {
        return id;
    }

    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setId(@javax.annotation.Nullable String id) {
        this.id = id;
    }

    public SessionInfo userId(@javax.annotation.Nullable UUID userId) {

        this.userId = userId;
        return this;
    }

    /**
     * Gets or sets the user id.
     * 
     * @return userId
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_USER_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public UUID getUserId() {
        return userId;
    }

    @JsonProperty(JSON_PROPERTY_USER_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setUserId(@javax.annotation.Nullable UUID userId) {
        this.userId = userId;
    }

    public SessionInfo userName(@javax.annotation.Nullable String userName) {

        this.userName = userName;
        return this;
    }

    /**
     * Gets or sets the username.
     * 
     * @return userName
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_USER_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getUserName() {
        return userName;
    }

    @JsonProperty(JSON_PROPERTY_USER_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setUserName(@javax.annotation.Nullable String userName) {
        this.userName = userName;
    }

    public SessionInfo client(@javax.annotation.Nullable String client) {

        this.client = client;
        return this;
    }

    /**
     * Gets or sets the type of the client.
     * 
     * @return client
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CLIENT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getClient() {
        return client;
    }

    @JsonProperty(JSON_PROPERTY_CLIENT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setClient(@javax.annotation.Nullable String client) {
        this.client = client;
    }

    public SessionInfo lastActivityDate(@javax.annotation.Nullable OffsetDateTime lastActivityDate) {

        this.lastActivityDate = lastActivityDate;
        return this;
    }

    /**
     * Gets or sets the last activity date.
     * 
     * @return lastActivityDate
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_LAST_ACTIVITY_DATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public OffsetDateTime getLastActivityDate() {
        return lastActivityDate;
    }

    @JsonProperty(JSON_PROPERTY_LAST_ACTIVITY_DATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLastActivityDate(@javax.annotation.Nullable OffsetDateTime lastActivityDate) {
        this.lastActivityDate = lastActivityDate;
    }

    public SessionInfo lastPlaybackCheckIn(@javax.annotation.Nullable OffsetDateTime lastPlaybackCheckIn) {

        this.lastPlaybackCheckIn = lastPlaybackCheckIn;
        return this;
    }

    /**
     * Gets or sets the last playback check in.
     * 
     * @return lastPlaybackCheckIn
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_LAST_PLAYBACK_CHECK_IN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public OffsetDateTime getLastPlaybackCheckIn() {
        return lastPlaybackCheckIn;
    }

    @JsonProperty(JSON_PROPERTY_LAST_PLAYBACK_CHECK_IN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLastPlaybackCheckIn(@javax.annotation.Nullable OffsetDateTime lastPlaybackCheckIn) {
        this.lastPlaybackCheckIn = lastPlaybackCheckIn;
    }

    public SessionInfo deviceName(@javax.annotation.Nullable String deviceName) {

        this.deviceName = deviceName;
        return this;
    }

    /**
     * Gets or sets the name of the device.
     * 
     * @return deviceName
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DEVICE_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getDeviceName() {
        return deviceName;
    }

    @JsonProperty(JSON_PROPERTY_DEVICE_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDeviceName(@javax.annotation.Nullable String deviceName) {
        this.deviceName = deviceName;
    }

    public SessionInfo deviceType(@javax.annotation.Nullable String deviceType) {

        this.deviceType = deviceType;
        return this;
    }

    /**
     * Gets or sets the type of the device.
     * 
     * @return deviceType
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DEVICE_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getDeviceType() {
        return deviceType;
    }

    @JsonProperty(JSON_PROPERTY_DEVICE_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDeviceType(@javax.annotation.Nullable String deviceType) {
        this.deviceType = deviceType;
    }

    public SessionInfo nowPlayingItem(@javax.annotation.Nullable BaseItemDto nowPlayingItem) {

        this.nowPlayingItem = nowPlayingItem;
        return this;
    }

    /**
     * Gets or sets the now playing item.
     * 
     * @return nowPlayingItem
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_NOW_PLAYING_ITEM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BaseItemDto getNowPlayingItem() {
        return nowPlayingItem;
    }

    @JsonProperty(JSON_PROPERTY_NOW_PLAYING_ITEM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setNowPlayingItem(@javax.annotation.Nullable BaseItemDto nowPlayingItem) {
        this.nowPlayingItem = nowPlayingItem;
    }

    public SessionInfo fullNowPlayingItem(@javax.annotation.Nullable BaseItem fullNowPlayingItem) {

        this.fullNowPlayingItem = fullNowPlayingItem;
        return this;
    }

    /**
     * Class BaseItem.
     * 
     * @return fullNowPlayingItem
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_FULL_NOW_PLAYING_ITEM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BaseItem getFullNowPlayingItem() {
        return fullNowPlayingItem;
    }

    @JsonProperty(JSON_PROPERTY_FULL_NOW_PLAYING_ITEM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setFullNowPlayingItem(@javax.annotation.Nullable BaseItem fullNowPlayingItem) {
        this.fullNowPlayingItem = fullNowPlayingItem;
    }

    public SessionInfo nowViewingItem(@javax.annotation.Nullable BaseItemDto nowViewingItem) {

        this.nowViewingItem = nowViewingItem;
        return this;
    }

    /**
     * This is strictly used as a data transfer object from the api layer. This holds information about a BaseItem in a
     * format that is convenient for the client.
     * 
     * @return nowViewingItem
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_NOW_VIEWING_ITEM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BaseItemDto getNowViewingItem() {
        return nowViewingItem;
    }

    @JsonProperty(JSON_PROPERTY_NOW_VIEWING_ITEM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setNowViewingItem(@javax.annotation.Nullable BaseItemDto nowViewingItem) {
        this.nowViewingItem = nowViewingItem;
    }

    public SessionInfo deviceId(@javax.annotation.Nullable String deviceId) {

        this.deviceId = deviceId;
        return this;
    }

    /**
     * Gets or sets the device id.
     * 
     * @return deviceId
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DEVICE_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getDeviceId() {
        return deviceId;
    }

    @JsonProperty(JSON_PROPERTY_DEVICE_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDeviceId(@javax.annotation.Nullable String deviceId) {
        this.deviceId = deviceId;
    }

    public SessionInfo applicationVersion(@javax.annotation.Nullable String applicationVersion) {

        this.applicationVersion = applicationVersion;
        return this;
    }

    /**
     * Gets or sets the application version.
     * 
     * @return applicationVersion
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_APPLICATION_VERSION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getApplicationVersion() {
        return applicationVersion;
    }

    @JsonProperty(JSON_PROPERTY_APPLICATION_VERSION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setApplicationVersion(@javax.annotation.Nullable String applicationVersion) {
        this.applicationVersion = applicationVersion;
    }

    public SessionInfo transcodingInfo(@javax.annotation.Nullable TranscodingInfo transcodingInfo) {

        this.transcodingInfo = transcodingInfo;
        return this;
    }

    /**
     * Get transcodingInfo
     * 
     * @return transcodingInfo
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TRANSCODING_INFO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public TranscodingInfo getTranscodingInfo() {
        return transcodingInfo;
    }

    @JsonProperty(JSON_PROPERTY_TRANSCODING_INFO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTranscodingInfo(@javax.annotation.Nullable TranscodingInfo transcodingInfo) {
        this.transcodingInfo = transcodingInfo;
    }

    /**
     * Gets a value indicating whether this instance is active.
     * 
     * @return isActive
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_IS_ACTIVE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * Get supportsMediaControl
     * 
     * @return supportsMediaControl
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_SUPPORTS_MEDIA_CONTROL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getSupportsMediaControl() {
        return supportsMediaControl;
    }

    /**
     * Get supportsRemoteControl
     * 
     * @return supportsRemoteControl
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_SUPPORTS_REMOTE_CONTROL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getSupportsRemoteControl() {
        return supportsRemoteControl;
    }

    public SessionInfo nowPlayingQueue(@javax.annotation.Nullable List<QueueItem> nowPlayingQueue) {

        this.nowPlayingQueue = nowPlayingQueue;
        return this;
    }

    public SessionInfo addNowPlayingQueueItem(QueueItem nowPlayingQueueItem) {
        if (this.nowPlayingQueue == null) {
            this.nowPlayingQueue = new ArrayList<>();
        }
        this.nowPlayingQueue.add(nowPlayingQueueItem);
        return this;
    }

    /**
     * Get nowPlayingQueue
     * 
     * @return nowPlayingQueue
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_NOW_PLAYING_QUEUE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<QueueItem> getNowPlayingQueue() {
        return nowPlayingQueue;
    }

    @JsonProperty(JSON_PROPERTY_NOW_PLAYING_QUEUE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setNowPlayingQueue(@javax.annotation.Nullable List<QueueItem> nowPlayingQueue) {
        this.nowPlayingQueue = nowPlayingQueue;
    }

    public SessionInfo nowPlayingQueueFullItems(@javax.annotation.Nullable List<BaseItemDto> nowPlayingQueueFullItems) {

        this.nowPlayingQueueFullItems = nowPlayingQueueFullItems;
        return this;
    }

    public SessionInfo addNowPlayingQueueFullItemsItem(BaseItemDto nowPlayingQueueFullItemsItem) {
        if (this.nowPlayingQueueFullItems == null) {
            this.nowPlayingQueueFullItems = new ArrayList<>();
        }
        this.nowPlayingQueueFullItems.add(nowPlayingQueueFullItemsItem);
        return this;
    }

    /**
     * Get nowPlayingQueueFullItems
     * 
     * @return nowPlayingQueueFullItems
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_NOW_PLAYING_QUEUE_FULL_ITEMS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<BaseItemDto> getNowPlayingQueueFullItems() {
        return nowPlayingQueueFullItems;
    }

    @JsonProperty(JSON_PROPERTY_NOW_PLAYING_QUEUE_FULL_ITEMS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setNowPlayingQueueFullItems(@javax.annotation.Nullable List<BaseItemDto> nowPlayingQueueFullItems) {
        this.nowPlayingQueueFullItems = nowPlayingQueueFullItems;
    }

    public SessionInfo hasCustomDeviceName(@javax.annotation.Nullable Boolean hasCustomDeviceName) {

        this.hasCustomDeviceName = hasCustomDeviceName;
        return this;
    }

    /**
     * Get hasCustomDeviceName
     * 
     * @return hasCustomDeviceName
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_HAS_CUSTOM_DEVICE_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getHasCustomDeviceName() {
        return hasCustomDeviceName;
    }

    @JsonProperty(JSON_PROPERTY_HAS_CUSTOM_DEVICE_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setHasCustomDeviceName(@javax.annotation.Nullable Boolean hasCustomDeviceName) {
        this.hasCustomDeviceName = hasCustomDeviceName;
    }

    public SessionInfo playlistItemId(@javax.annotation.Nullable String playlistItemId) {

        this.playlistItemId = playlistItemId;
        return this;
    }

    /**
     * Get playlistItemId
     * 
     * @return playlistItemId
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PLAYLIST_ITEM_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPlaylistItemId() {
        return playlistItemId;
    }

    @JsonProperty(JSON_PROPERTY_PLAYLIST_ITEM_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPlaylistItemId(@javax.annotation.Nullable String playlistItemId) {
        this.playlistItemId = playlistItemId;
    }

    public SessionInfo serverId(@javax.annotation.Nullable String serverId) {

        this.serverId = serverId;
        return this;
    }

    /**
     * Get serverId
     * 
     * @return serverId
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_SERVER_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getServerId() {
        return serverId;
    }

    @JsonProperty(JSON_PROPERTY_SERVER_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setServerId(@javax.annotation.Nullable String serverId) {
        this.serverId = serverId;
    }

    public SessionInfo userPrimaryImageTag(@javax.annotation.Nullable String userPrimaryImageTag) {

        this.userPrimaryImageTag = userPrimaryImageTag;
        return this;
    }

    /**
     * Get userPrimaryImageTag
     * 
     * @return userPrimaryImageTag
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_USER_PRIMARY_IMAGE_TAG)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getUserPrimaryImageTag() {
        return userPrimaryImageTag;
    }

    @JsonProperty(JSON_PROPERTY_USER_PRIMARY_IMAGE_TAG)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setUserPrimaryImageTag(@javax.annotation.Nullable String userPrimaryImageTag) {
        this.userPrimaryImageTag = userPrimaryImageTag;
    }

    /**
     * Gets the supported commands.
     * 
     * @return supportedCommands
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_SUPPORTED_COMMANDS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<GeneralCommandType> getSupportedCommands() {
        return supportedCommands;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SessionInfo sessionInfo = (SessionInfo) o;
        return Objects.equals(this.playState, sessionInfo.playState)
                && Objects.equals(this.additionalUsers, sessionInfo.additionalUsers)
                && Objects.equals(this.capabilities, sessionInfo.capabilities)
                && Objects.equals(this.remoteEndPoint, sessionInfo.remoteEndPoint)
                && Objects.equals(this.playableMediaTypes, sessionInfo.playableMediaTypes)
                && Objects.equals(this.id, sessionInfo.id) && Objects.equals(this.userId, sessionInfo.userId)
                && Objects.equals(this.userName, sessionInfo.userName)
                && Objects.equals(this.client, sessionInfo.client)
                && Objects.equals(this.lastActivityDate, sessionInfo.lastActivityDate)
                && Objects.equals(this.lastPlaybackCheckIn, sessionInfo.lastPlaybackCheckIn)
                && Objects.equals(this.deviceName, sessionInfo.deviceName)
                && Objects.equals(this.deviceType, sessionInfo.deviceType)
                && Objects.equals(this.nowPlayingItem, sessionInfo.nowPlayingItem)
                && Objects.equals(this.fullNowPlayingItem, sessionInfo.fullNowPlayingItem)
                && Objects.equals(this.nowViewingItem, sessionInfo.nowViewingItem)
                && Objects.equals(this.deviceId, sessionInfo.deviceId)
                && Objects.equals(this.applicationVersion, sessionInfo.applicationVersion)
                && Objects.equals(this.transcodingInfo, sessionInfo.transcodingInfo)
                && Objects.equals(this.isActive, sessionInfo.isActive)
                && Objects.equals(this.supportsMediaControl, sessionInfo.supportsMediaControl)
                && Objects.equals(this.supportsRemoteControl, sessionInfo.supportsRemoteControl)
                && Objects.equals(this.nowPlayingQueue, sessionInfo.nowPlayingQueue)
                && Objects.equals(this.nowPlayingQueueFullItems, sessionInfo.nowPlayingQueueFullItems)
                && Objects.equals(this.hasCustomDeviceName, sessionInfo.hasCustomDeviceName)
                && Objects.equals(this.playlistItemId, sessionInfo.playlistItemId)
                && Objects.equals(this.serverId, sessionInfo.serverId)
                && Objects.equals(this.userPrimaryImageTag, sessionInfo.userPrimaryImageTag)
                && Objects.equals(this.supportedCommands, sessionInfo.supportedCommands);
    }

    @Override
    public int hashCode() {
        return Objects.hash(playState, additionalUsers, capabilities, remoteEndPoint, playableMediaTypes, id, userId,
                userName, client, lastActivityDate, lastPlaybackCheckIn, deviceName, deviceType, nowPlayingItem,
                fullNowPlayingItem, nowViewingItem, deviceId, applicationVersion, transcodingInfo, isActive,
                supportsMediaControl, supportsRemoteControl, nowPlayingQueue, nowPlayingQueueFullItems,
                hasCustomDeviceName, playlistItemId, serverId, userPrimaryImageTag, supportedCommands);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SessionInfo {\n");
        sb.append("    playState: ").append(toIndentedString(playState)).append("\n");
        sb.append("    additionalUsers: ").append(toIndentedString(additionalUsers)).append("\n");
        sb.append("    capabilities: ").append(toIndentedString(capabilities)).append("\n");
        sb.append("    remoteEndPoint: ").append(toIndentedString(remoteEndPoint)).append("\n");
        sb.append("    playableMediaTypes: ").append(toIndentedString(playableMediaTypes)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
        sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
        sb.append("    client: ").append(toIndentedString(client)).append("\n");
        sb.append("    lastActivityDate: ").append(toIndentedString(lastActivityDate)).append("\n");
        sb.append("    lastPlaybackCheckIn: ").append(toIndentedString(lastPlaybackCheckIn)).append("\n");
        sb.append("    deviceName: ").append(toIndentedString(deviceName)).append("\n");
        sb.append("    deviceType: ").append(toIndentedString(deviceType)).append("\n");
        sb.append("    nowPlayingItem: ").append(toIndentedString(nowPlayingItem)).append("\n");
        sb.append("    fullNowPlayingItem: ").append(toIndentedString(fullNowPlayingItem)).append("\n");
        sb.append("    nowViewingItem: ").append(toIndentedString(nowViewingItem)).append("\n");
        sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
        sb.append("    applicationVersion: ").append(toIndentedString(applicationVersion)).append("\n");
        sb.append("    transcodingInfo: ").append(toIndentedString(transcodingInfo)).append("\n");
        sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
        sb.append("    supportsMediaControl: ").append(toIndentedString(supportsMediaControl)).append("\n");
        sb.append("    supportsRemoteControl: ").append(toIndentedString(supportsRemoteControl)).append("\n");
        sb.append("    nowPlayingQueue: ").append(toIndentedString(nowPlayingQueue)).append("\n");
        sb.append("    nowPlayingQueueFullItems: ").append(toIndentedString(nowPlayingQueueFullItems)).append("\n");
        sb.append("    hasCustomDeviceName: ").append(toIndentedString(hasCustomDeviceName)).append("\n");
        sb.append("    playlistItemId: ").append(toIndentedString(playlistItemId)).append("\n");
        sb.append("    serverId: ").append(toIndentedString(serverId)).append("\n");
        sb.append("    userPrimaryImageTag: ").append(toIndentedString(userPrimaryImageTag)).append("\n");
        sb.append("    supportedCommands: ").append(toIndentedString(supportedCommands)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static class Builder {

        private SessionInfo instance;

        public Builder() {
            this(new SessionInfo());
        }

        protected Builder(SessionInfo instance) {
            this.instance = instance;
        }

        public SessionInfo.Builder playState(PlayerStateInfo playState) {
            this.instance.playState = playState;
            return this;
        }

        public SessionInfo.Builder additionalUsers(List<SessionUserInfo> additionalUsers) {
            this.instance.additionalUsers = additionalUsers;
            return this;
        }

        public SessionInfo.Builder capabilities(ClientCapabilities capabilities) {
            this.instance.capabilities = capabilities;
            return this;
        }

        public SessionInfo.Builder remoteEndPoint(String remoteEndPoint) {
            this.instance.remoteEndPoint = remoteEndPoint;
            return this;
        }

        public SessionInfo.Builder playableMediaTypes(List<String> playableMediaTypes) {
            this.instance.playableMediaTypes = playableMediaTypes;
            return this;
        }

        public SessionInfo.Builder id(String id) {
            this.instance.id = id;
            return this;
        }

        public SessionInfo.Builder userId(UUID userId) {
            this.instance.userId = userId;
            return this;
        }

        public SessionInfo.Builder userName(String userName) {
            this.instance.userName = userName;
            return this;
        }

        public SessionInfo.Builder client(String client) {
            this.instance.client = client;
            return this;
        }

        public SessionInfo.Builder lastActivityDate(OffsetDateTime lastActivityDate) {
            this.instance.lastActivityDate = lastActivityDate;
            return this;
        }

        public SessionInfo.Builder lastPlaybackCheckIn(OffsetDateTime lastPlaybackCheckIn) {
            this.instance.lastPlaybackCheckIn = lastPlaybackCheckIn;
            return this;
        }

        public SessionInfo.Builder deviceName(String deviceName) {
            this.instance.deviceName = deviceName;
            return this;
        }

        public SessionInfo.Builder deviceType(String deviceType) {
            this.instance.deviceType = deviceType;
            return this;
        }

        public SessionInfo.Builder nowPlayingItem(BaseItemDto nowPlayingItem) {
            this.instance.nowPlayingItem = nowPlayingItem;
            return this;
        }

        public SessionInfo.Builder fullNowPlayingItem(BaseItem fullNowPlayingItem) {
            this.instance.fullNowPlayingItem = fullNowPlayingItem;
            return this;
        }

        public SessionInfo.Builder nowViewingItem(BaseItemDto nowViewingItem) {
            this.instance.nowViewingItem = nowViewingItem;
            return this;
        }

        public SessionInfo.Builder deviceId(String deviceId) {
            this.instance.deviceId = deviceId;
            return this;
        }

        public SessionInfo.Builder applicationVersion(String applicationVersion) {
            this.instance.applicationVersion = applicationVersion;
            return this;
        }

        public SessionInfo.Builder transcodingInfo(TranscodingInfo transcodingInfo) {
            this.instance.transcodingInfo = transcodingInfo;
            return this;
        }

        public SessionInfo.Builder isActive(Boolean isActive) {
            this.instance.isActive = isActive;
            return this;
        }

        public SessionInfo.Builder supportsMediaControl(Boolean supportsMediaControl) {
            this.instance.supportsMediaControl = supportsMediaControl;
            return this;
        }

        public SessionInfo.Builder supportsRemoteControl(Boolean supportsRemoteControl) {
            this.instance.supportsRemoteControl = supportsRemoteControl;
            return this;
        }

        public SessionInfo.Builder nowPlayingQueue(List<QueueItem> nowPlayingQueue) {
            this.instance.nowPlayingQueue = nowPlayingQueue;
            return this;
        }

        public SessionInfo.Builder nowPlayingQueueFullItems(List<BaseItemDto> nowPlayingQueueFullItems) {
            this.instance.nowPlayingQueueFullItems = nowPlayingQueueFullItems;
            return this;
        }

        public SessionInfo.Builder hasCustomDeviceName(Boolean hasCustomDeviceName) {
            this.instance.hasCustomDeviceName = hasCustomDeviceName;
            return this;
        }

        public SessionInfo.Builder playlistItemId(String playlistItemId) {
            this.instance.playlistItemId = playlistItemId;
            return this;
        }

        public SessionInfo.Builder serverId(String serverId) {
            this.instance.serverId = serverId;
            return this;
        }

        public SessionInfo.Builder userPrimaryImageTag(String userPrimaryImageTag) {
            this.instance.userPrimaryImageTag = userPrimaryImageTag;
            return this;
        }

        public SessionInfo.Builder supportedCommands(List<GeneralCommandType> supportedCommands) {
            this.instance.supportedCommands = supportedCommands;
            return this;
        }

        /**
         * returns a built SessionInfo instance.
         *
         * The builder is not reusable.
         */
        public SessionInfo build() {
            try {
                return this.instance;
            } finally {
                // ensure that this.instance is not reused
                this.instance = null;
            }
        }

        @Override
        public String toString() {
            return getClass() + "=(" + instance + ")";
        }
    }

    /**
     * Create a builder with no initialized field.
     */
    public static SessionInfo.Builder builder() {
        return new SessionInfo.Builder();
    }

    /**
     * Create a builder with a shallow copy of this instance.
     */
    public SessionInfo.Builder toBuilder() {
        return new SessionInfo.Builder().playState(getPlayState()).additionalUsers(getAdditionalUsers())
                .capabilities(getCapabilities()).remoteEndPoint(getRemoteEndPoint())
                .playableMediaTypes(getPlayableMediaTypes()).id(getId()).userId(getUserId()).userName(getUserName())
                .client(getClient()).lastActivityDate(getLastActivityDate())
                .lastPlaybackCheckIn(getLastPlaybackCheckIn()).deviceName(getDeviceName()).deviceType(getDeviceType())
                .nowPlayingItem(getNowPlayingItem()).fullNowPlayingItem(getFullNowPlayingItem())
                .nowViewingItem(getNowViewingItem()).deviceId(getDeviceId()).applicationVersion(getApplicationVersion())
                .transcodingInfo(getTranscodingInfo()).isActive(getIsActive())
                .supportsMediaControl(getSupportsMediaControl()).supportsRemoteControl(getSupportsRemoteControl())
                .nowPlayingQueue(getNowPlayingQueue()).nowPlayingQueueFullItems(getNowPlayingQueueFullItems())
                .hasCustomDeviceName(getHasCustomDeviceName()).playlistItemId(getPlaylistItemId())
                .serverId(getServerId()).userPrimaryImageTag(getUserPrimaryImageTag())
                .supportedCommands(getSupportedCommands());
    }
}
