/*
 * Copyright (c) 2010-2025 Contributors to the openHAB project
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 */

package org.openhab.binding.jellyfin.internal.api.version.legacy.model;

import java.time.OffsetDateTime;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Class TaskExecutionInfo.
 */
@JsonPropertyOrder({ TaskResult.JSON_PROPERTY_START_TIME_UTC, TaskResult.JSON_PROPERTY_END_TIME_UTC,
        TaskResult.JSON_PROPERTY_STATUS, TaskResult.JSON_PROPERTY_NAME, TaskResult.JSON_PROPERTY_KEY,
        TaskResult.JSON_PROPERTY_ID, TaskResult.JSON_PROPERTY_ERROR_MESSAGE,
        TaskResult.JSON_PROPERTY_LONG_ERROR_MESSAGE })
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class TaskResult {
    public static final String JSON_PROPERTY_START_TIME_UTC = "StartTimeUtc";
    @javax.annotation.Nullable
    private OffsetDateTime startTimeUtc;

    public static final String JSON_PROPERTY_END_TIME_UTC = "EndTimeUtc";
    @javax.annotation.Nullable
    private OffsetDateTime endTimeUtc;

    public static final String JSON_PROPERTY_STATUS = "Status";
    @javax.annotation.Nullable
    private TaskCompletionStatus status;

    public static final String JSON_PROPERTY_NAME = "Name";
    @javax.annotation.Nullable
    private String name;

    public static final String JSON_PROPERTY_KEY = "Key";
    @javax.annotation.Nullable
    private String key;

    public static final String JSON_PROPERTY_ID = "Id";
    @javax.annotation.Nullable
    private String id;

    public static final String JSON_PROPERTY_ERROR_MESSAGE = "ErrorMessage";
    @javax.annotation.Nullable
    private String errorMessage;

    public static final String JSON_PROPERTY_LONG_ERROR_MESSAGE = "LongErrorMessage";
    @javax.annotation.Nullable
    private String longErrorMessage;

    public TaskResult() {
    }

    public TaskResult startTimeUtc(@javax.annotation.Nullable OffsetDateTime startTimeUtc) {

        this.startTimeUtc = startTimeUtc;
        return this;
    }

    /**
     * Gets or sets the start time UTC.
     * 
     * @return startTimeUtc
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_START_TIME_UTC)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public OffsetDateTime getStartTimeUtc() {
        return startTimeUtc;
    }

    @JsonProperty(JSON_PROPERTY_START_TIME_UTC)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setStartTimeUtc(@javax.annotation.Nullable OffsetDateTime startTimeUtc) {
        this.startTimeUtc = startTimeUtc;
    }

    public TaskResult endTimeUtc(@javax.annotation.Nullable OffsetDateTime endTimeUtc) {

        this.endTimeUtc = endTimeUtc;
        return this;
    }

    /**
     * Gets or sets the end time UTC.
     * 
     * @return endTimeUtc
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_END_TIME_UTC)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public OffsetDateTime getEndTimeUtc() {
        return endTimeUtc;
    }

    @JsonProperty(JSON_PROPERTY_END_TIME_UTC)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setEndTimeUtc(@javax.annotation.Nullable OffsetDateTime endTimeUtc) {
        this.endTimeUtc = endTimeUtc;
    }

    public TaskResult status(@javax.annotation.Nullable TaskCompletionStatus status) {

        this.status = status;
        return this;
    }

    /**
     * Gets or sets the status.
     * 
     * @return status
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_STATUS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public TaskCompletionStatus getStatus() {
        return status;
    }

    @JsonProperty(JSON_PROPERTY_STATUS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setStatus(@javax.annotation.Nullable TaskCompletionStatus status) {
        this.status = status;
    }

    public TaskResult name(@javax.annotation.Nullable String name) {

        this.name = name;
        return this;
    }

    /**
     * Gets or sets the name.
     * 
     * @return name
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getName() {
        return name;
    }

    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setName(@javax.annotation.Nullable String name) {
        this.name = name;
    }

    public TaskResult key(@javax.annotation.Nullable String key) {

        this.key = key;
        return this;
    }

    /**
     * Gets or sets the key.
     * 
     * @return key
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_KEY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getKey() {
        return key;
    }

    @JsonProperty(JSON_PROPERTY_KEY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setKey(@javax.annotation.Nullable String key) {
        this.key = key;
    }

    public TaskResult id(@javax.annotation.Nullable String id) {

        this.id = id;
        return this;
    }

    /**
     * Gets or sets the id.
     * 
     * @return id
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getId() {
        return id;
    }

    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setId(@javax.annotation.Nullable String id) {
        this.id = id;
    }

    public TaskResult errorMessage(@javax.annotation.Nullable String errorMessage) {

        this.errorMessage = errorMessage;
        return this;
    }

    /**
     * Gets or sets the error message.
     * 
     * @return errorMessage
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ERROR_MESSAGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getErrorMessage() {
        return errorMessage;
    }

    @JsonProperty(JSON_PROPERTY_ERROR_MESSAGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setErrorMessage(@javax.annotation.Nullable String errorMessage) {
        this.errorMessage = errorMessage;
    }

    public TaskResult longErrorMessage(@javax.annotation.Nullable String longErrorMessage) {

        this.longErrorMessage = longErrorMessage;
        return this;
    }

    /**
     * Gets or sets the long error message.
     * 
     * @return longErrorMessage
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_LONG_ERROR_MESSAGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getLongErrorMessage() {
        return longErrorMessage;
    }

    @JsonProperty(JSON_PROPERTY_LONG_ERROR_MESSAGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLongErrorMessage(@javax.annotation.Nullable String longErrorMessage) {
        this.longErrorMessage = longErrorMessage;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TaskResult taskResult = (TaskResult) o;
        return Objects.equals(this.startTimeUtc, taskResult.startTimeUtc)
                && Objects.equals(this.endTimeUtc, taskResult.endTimeUtc)
                && Objects.equals(this.status, taskResult.status) && Objects.equals(this.name, taskResult.name)
                && Objects.equals(this.key, taskResult.key) && Objects.equals(this.id, taskResult.id)
                && Objects.equals(this.errorMessage, taskResult.errorMessage)
                && Objects.equals(this.longErrorMessage, taskResult.longErrorMessage);
    }

    @Override
    public int hashCode() {
        return Objects.hash(startTimeUtc, endTimeUtc, status, name, key, id, errorMessage, longErrorMessage);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class TaskResult {\n");
        sb.append("    startTimeUtc: ").append(toIndentedString(startTimeUtc)).append("\n");
        sb.append("    endTimeUtc: ").append(toIndentedString(endTimeUtc)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    key: ").append(toIndentedString(key)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
        sb.append("    longErrorMessage: ").append(toIndentedString(longErrorMessage)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static class Builder {

        private TaskResult instance;

        public Builder() {
            this(new TaskResult());
        }

        protected Builder(TaskResult instance) {
            this.instance = instance;
        }

        public TaskResult.Builder startTimeUtc(OffsetDateTime startTimeUtc) {
            this.instance.startTimeUtc = startTimeUtc;
            return this;
        }

        public TaskResult.Builder endTimeUtc(OffsetDateTime endTimeUtc) {
            this.instance.endTimeUtc = endTimeUtc;
            return this;
        }

        public TaskResult.Builder status(TaskCompletionStatus status) {
            this.instance.status = status;
            return this;
        }

        public TaskResult.Builder name(String name) {
            this.instance.name = name;
            return this;
        }

        public TaskResult.Builder key(String key) {
            this.instance.key = key;
            return this;
        }

        public TaskResult.Builder id(String id) {
            this.instance.id = id;
            return this;
        }

        public TaskResult.Builder errorMessage(String errorMessage) {
            this.instance.errorMessage = errorMessage;
            return this;
        }

        public TaskResult.Builder longErrorMessage(String longErrorMessage) {
            this.instance.longErrorMessage = longErrorMessage;
            return this;
        }

        /**
         * returns a built TaskResult instance.
         *
         * The builder is not reusable.
         */
        public TaskResult build() {
            try {
                return this.instance;
            } finally {
                // ensure that this.instance is not reused
                this.instance = null;
            }
        }

        @Override
        public String toString() {
            return getClass() + "=(" + instance + ")";
        }
    }

    /**
     * Create a builder with no initialized field.
     */
    public static TaskResult.Builder builder() {
        return new TaskResult.Builder();
    }

    /**
     * Create a builder with a shallow copy of this instance.
     */
    public TaskResult.Builder toBuilder() {
        return new TaskResult.Builder().startTimeUtc(getStartTimeUtc()).endTimeUtc(getEndTimeUtc()).status(getStatus())
                .name(getName()).key(getKey()).id(getId()).errorMessage(getErrorMessage())
                .longErrorMessage(getLongErrorMessage());
    }
}
