/*
 * Copyright (c) 2010-2025 Contributors to the openHAB project
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 */

package org.openhab.binding.jellyfin.internal.api.version.legacy.model;

import java.time.OffsetDateTime;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Class UserItemDataDto.
 */
@JsonPropertyOrder({ UserItemDataDto.JSON_PROPERTY_RATING, UserItemDataDto.JSON_PROPERTY_PLAYED_PERCENTAGE,
        UserItemDataDto.JSON_PROPERTY_UNPLAYED_ITEM_COUNT, UserItemDataDto.JSON_PROPERTY_PLAYBACK_POSITION_TICKS,
        UserItemDataDto.JSON_PROPERTY_PLAY_COUNT, UserItemDataDto.JSON_PROPERTY_IS_FAVORITE,
        UserItemDataDto.JSON_PROPERTY_LIKES, UserItemDataDto.JSON_PROPERTY_LAST_PLAYED_DATE,
        UserItemDataDto.JSON_PROPERTY_PLAYED, UserItemDataDto.JSON_PROPERTY_KEY,
        UserItemDataDto.JSON_PROPERTY_ITEM_ID })
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class UserItemDataDto {
    public static final String JSON_PROPERTY_RATING = "Rating";
    @javax.annotation.Nullable
    private Double rating;

    public static final String JSON_PROPERTY_PLAYED_PERCENTAGE = "PlayedPercentage";
    @javax.annotation.Nullable
    private Double playedPercentage;

    public static final String JSON_PROPERTY_UNPLAYED_ITEM_COUNT = "UnplayedItemCount";
    @javax.annotation.Nullable
    private Integer unplayedItemCount;

    public static final String JSON_PROPERTY_PLAYBACK_POSITION_TICKS = "PlaybackPositionTicks";
    @javax.annotation.Nullable
    private Long playbackPositionTicks;

    public static final String JSON_PROPERTY_PLAY_COUNT = "PlayCount";
    @javax.annotation.Nullable
    private Integer playCount;

    public static final String JSON_PROPERTY_IS_FAVORITE = "IsFavorite";
    @javax.annotation.Nullable
    private Boolean isFavorite;

    public static final String JSON_PROPERTY_LIKES = "Likes";
    @javax.annotation.Nullable
    private Boolean likes;

    public static final String JSON_PROPERTY_LAST_PLAYED_DATE = "LastPlayedDate";
    @javax.annotation.Nullable
    private OffsetDateTime lastPlayedDate;

    public static final String JSON_PROPERTY_PLAYED = "Played";
    @javax.annotation.Nullable
    private Boolean played;

    public static final String JSON_PROPERTY_KEY = "Key";
    @javax.annotation.Nullable
    private String key;

    public static final String JSON_PROPERTY_ITEM_ID = "ItemId";
    @javax.annotation.Nullable
    private String itemId;

    public UserItemDataDto() {
    }

    public UserItemDataDto rating(@javax.annotation.Nullable Double rating) {

        this.rating = rating;
        return this;
    }

    /**
     * Gets or sets the rating.
     * 
     * @return rating
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_RATING)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Double getRating() {
        return rating;
    }

    @JsonProperty(JSON_PROPERTY_RATING)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRating(@javax.annotation.Nullable Double rating) {
        this.rating = rating;
    }

    public UserItemDataDto playedPercentage(@javax.annotation.Nullable Double playedPercentage) {

        this.playedPercentage = playedPercentage;
        return this;
    }

    /**
     * Gets or sets the played percentage.
     * 
     * @return playedPercentage
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PLAYED_PERCENTAGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Double getPlayedPercentage() {
        return playedPercentage;
    }

    @JsonProperty(JSON_PROPERTY_PLAYED_PERCENTAGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPlayedPercentage(@javax.annotation.Nullable Double playedPercentage) {
        this.playedPercentage = playedPercentage;
    }

    public UserItemDataDto unplayedItemCount(@javax.annotation.Nullable Integer unplayedItemCount) {

        this.unplayedItemCount = unplayedItemCount;
        return this;
    }

    /**
     * Gets or sets the unplayed item count.
     * 
     * @return unplayedItemCount
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_UNPLAYED_ITEM_COUNT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getUnplayedItemCount() {
        return unplayedItemCount;
    }

    @JsonProperty(JSON_PROPERTY_UNPLAYED_ITEM_COUNT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setUnplayedItemCount(@javax.annotation.Nullable Integer unplayedItemCount) {
        this.unplayedItemCount = unplayedItemCount;
    }

    public UserItemDataDto playbackPositionTicks(@javax.annotation.Nullable Long playbackPositionTicks) {

        this.playbackPositionTicks = playbackPositionTicks;
        return this;
    }

    /**
     * Gets or sets the playback position ticks.
     * 
     * @return playbackPositionTicks
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PLAYBACK_POSITION_TICKS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Long getPlaybackPositionTicks() {
        return playbackPositionTicks;
    }

    @JsonProperty(JSON_PROPERTY_PLAYBACK_POSITION_TICKS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPlaybackPositionTicks(@javax.annotation.Nullable Long playbackPositionTicks) {
        this.playbackPositionTicks = playbackPositionTicks;
    }

    public UserItemDataDto playCount(@javax.annotation.Nullable Integer playCount) {

        this.playCount = playCount;
        return this;
    }

    /**
     * Gets or sets the play count.
     * 
     * @return playCount
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PLAY_COUNT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getPlayCount() {
        return playCount;
    }

    @JsonProperty(JSON_PROPERTY_PLAY_COUNT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPlayCount(@javax.annotation.Nullable Integer playCount) {
        this.playCount = playCount;
    }

    public UserItemDataDto isFavorite(@javax.annotation.Nullable Boolean isFavorite) {

        this.isFavorite = isFavorite;
        return this;
    }

    /**
     * Gets or sets a value indicating whether this instance is favorite.
     * 
     * @return isFavorite
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_IS_FAVORITE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getIsFavorite() {
        return isFavorite;
    }

    @JsonProperty(JSON_PROPERTY_IS_FAVORITE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setIsFavorite(@javax.annotation.Nullable Boolean isFavorite) {
        this.isFavorite = isFavorite;
    }

    public UserItemDataDto likes(@javax.annotation.Nullable Boolean likes) {

        this.likes = likes;
        return this;
    }

    /**
     * Gets or sets a value indicating whether this MediaBrowser.Model.Dto.UserItemDataDto is likes.
     * 
     * @return likes
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_LIKES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getLikes() {
        return likes;
    }

    @JsonProperty(JSON_PROPERTY_LIKES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLikes(@javax.annotation.Nullable Boolean likes) {
        this.likes = likes;
    }

    public UserItemDataDto lastPlayedDate(@javax.annotation.Nullable OffsetDateTime lastPlayedDate) {

        this.lastPlayedDate = lastPlayedDate;
        return this;
    }

    /**
     * Gets or sets the last played date.
     * 
     * @return lastPlayedDate
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_LAST_PLAYED_DATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public OffsetDateTime getLastPlayedDate() {
        return lastPlayedDate;
    }

    @JsonProperty(JSON_PROPERTY_LAST_PLAYED_DATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLastPlayedDate(@javax.annotation.Nullable OffsetDateTime lastPlayedDate) {
        this.lastPlayedDate = lastPlayedDate;
    }

    public UserItemDataDto played(@javax.annotation.Nullable Boolean played) {

        this.played = played;
        return this;
    }

    /**
     * Gets or sets a value indicating whether this MediaBrowser.Model.Dto.UserItemDataDto is played.
     * 
     * @return played
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PLAYED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getPlayed() {
        return played;
    }

    @JsonProperty(JSON_PROPERTY_PLAYED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPlayed(@javax.annotation.Nullable Boolean played) {
        this.played = played;
    }

    public UserItemDataDto key(@javax.annotation.Nullable String key) {

        this.key = key;
        return this;
    }

    /**
     * Gets or sets the key.
     * 
     * @return key
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_KEY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getKey() {
        return key;
    }

    @JsonProperty(JSON_PROPERTY_KEY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setKey(@javax.annotation.Nullable String key) {
        this.key = key;
    }

    public UserItemDataDto itemId(@javax.annotation.Nullable String itemId) {

        this.itemId = itemId;
        return this;
    }

    /**
     * Gets or sets the item identifier.
     * 
     * @return itemId
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ITEM_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getItemId() {
        return itemId;
    }

    @JsonProperty(JSON_PROPERTY_ITEM_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setItemId(@javax.annotation.Nullable String itemId) {
        this.itemId = itemId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UserItemDataDto userItemDataDto = (UserItemDataDto) o;
        return Objects.equals(this.rating, userItemDataDto.rating)
                && Objects.equals(this.playedPercentage, userItemDataDto.playedPercentage)
                && Objects.equals(this.unplayedItemCount, userItemDataDto.unplayedItemCount)
                && Objects.equals(this.playbackPositionTicks, userItemDataDto.playbackPositionTicks)
                && Objects.equals(this.playCount, userItemDataDto.playCount)
                && Objects.equals(this.isFavorite, userItemDataDto.isFavorite)
                && Objects.equals(this.likes, userItemDataDto.likes)
                && Objects.equals(this.lastPlayedDate, userItemDataDto.lastPlayedDate)
                && Objects.equals(this.played, userItemDataDto.played) && Objects.equals(this.key, userItemDataDto.key)
                && Objects.equals(this.itemId, userItemDataDto.itemId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(rating, playedPercentage, unplayedItemCount, playbackPositionTicks, playCount, isFavorite,
                likes, lastPlayedDate, played, key, itemId);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UserItemDataDto {\n");
        sb.append("    rating: ").append(toIndentedString(rating)).append("\n");
        sb.append("    playedPercentage: ").append(toIndentedString(playedPercentage)).append("\n");
        sb.append("    unplayedItemCount: ").append(toIndentedString(unplayedItemCount)).append("\n");
        sb.append("    playbackPositionTicks: ").append(toIndentedString(playbackPositionTicks)).append("\n");
        sb.append("    playCount: ").append(toIndentedString(playCount)).append("\n");
        sb.append("    isFavorite: ").append(toIndentedString(isFavorite)).append("\n");
        sb.append("    likes: ").append(toIndentedString(likes)).append("\n");
        sb.append("    lastPlayedDate: ").append(toIndentedString(lastPlayedDate)).append("\n");
        sb.append("    played: ").append(toIndentedString(played)).append("\n");
        sb.append("    key: ").append(toIndentedString(key)).append("\n");
        sb.append("    itemId: ").append(toIndentedString(itemId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static class Builder {

        private UserItemDataDto instance;

        public Builder() {
            this(new UserItemDataDto());
        }

        protected Builder(UserItemDataDto instance) {
            this.instance = instance;
        }

        public UserItemDataDto.Builder rating(Double rating) {
            this.instance.rating = rating;
            return this;
        }

        public UserItemDataDto.Builder playedPercentage(Double playedPercentage) {
            this.instance.playedPercentage = playedPercentage;
            return this;
        }

        public UserItemDataDto.Builder unplayedItemCount(Integer unplayedItemCount) {
            this.instance.unplayedItemCount = unplayedItemCount;
            return this;
        }

        public UserItemDataDto.Builder playbackPositionTicks(Long playbackPositionTicks) {
            this.instance.playbackPositionTicks = playbackPositionTicks;
            return this;
        }

        public UserItemDataDto.Builder playCount(Integer playCount) {
            this.instance.playCount = playCount;
            return this;
        }

        public UserItemDataDto.Builder isFavorite(Boolean isFavorite) {
            this.instance.isFavorite = isFavorite;
            return this;
        }

        public UserItemDataDto.Builder likes(Boolean likes) {
            this.instance.likes = likes;
            return this;
        }

        public UserItemDataDto.Builder lastPlayedDate(OffsetDateTime lastPlayedDate) {
            this.instance.lastPlayedDate = lastPlayedDate;
            return this;
        }

        public UserItemDataDto.Builder played(Boolean played) {
            this.instance.played = played;
            return this;
        }

        public UserItemDataDto.Builder key(String key) {
            this.instance.key = key;
            return this;
        }

        public UserItemDataDto.Builder itemId(String itemId) {
            this.instance.itemId = itemId;
            return this;
        }

        /**
         * returns a built UserItemDataDto instance.
         *
         * The builder is not reusable.
         */
        public UserItemDataDto build() {
            try {
                return this.instance;
            } finally {
                // ensure that this.instance is not reused
                this.instance = null;
            }
        }

        @Override
        public String toString() {
            return getClass() + "=(" + instance + ")";
        }
    }

    /**
     * Create a builder with no initialized field.
     */
    public static UserItemDataDto.Builder builder() {
        return new UserItemDataDto.Builder();
    }

    /**
     * Create a builder with a shallow copy of this instance.
     */
    public UserItemDataDto.Builder toBuilder() {
        return new UserItemDataDto.Builder().rating(getRating()).playedPercentage(getPlayedPercentage())
                .unplayedItemCount(getUnplayedItemCount()).playbackPositionTicks(getPlaybackPositionTicks())
                .playCount(getPlayCount()).isFavorite(getIsFavorite()).likes(getLikes())
                .lastPlayedDate(getLastPlayedDate()).played(getPlayed()).key(getKey()).itemId(getItemId());
    }
}
