#!/bin/sh
#
#  Create needed copies of duplicate icons.
#

rm -f garagedoor-ajar.png   && cp -f garagedoor-70.png    garagedoor-ajar.png
rm -f garagedoor-ajar.svg   && cp -f garagedoor-70.svg    garagedoor-ajar.svg
rm -f garagedoor-closed.png && cp -f garagedoor-100.png   garagedoor-closed.png
rm -f garagedoor-closed.svg && cp -f garagedoor-100.svg   garagedoor-closed.svg
rm -f garagedoor-open.png   && cp -f garagedoor-0.png     garagedoor-open.png
rm -f garagedoor-open.svg   && cp -f garagedoor-0.svg     garagedoor-open.svg
rm -f garagedoor.png        && cp -f garagedoor-ajar.png  garagedoor.png
rm -f garagedoor.svg        && cp -f garagedoor-ajar.svg  garagedoor.svg

rm -f group.png             && cp -f house.png            group.png
rm -f group.svg             && cp -f house.svg            group.svg

rm -f heating-off.png       && cp -f heating-0.png        heating-off.png
rm -f heating-off.svg       && cp -f heating-0.svg        heating-off.svg
rm -f heating-on.png        && cp -f heating-100.png      heating-on.png
rm -f heating-on.svg        && cp -f heating-100.svg      heating-on.svg
rm -f heating.png           && cp -f heating-on.png       heating.png
rm -f heating.svg           && cp -f heating-on.svg       heating.svg

rm -f light-off.png         && cp -f slider-0.png         light-off.png
rm -f light-off.svg         && cp -f slider-0.svg         light-off.svg
rm -f light-on.png          && cp -f slider-100.png       light-on.png
rm -f light-on.svg          && cp -f slider-100.svg       light-on.svg
rm -f slider.png            && cp -f slider-100.png       slider.png
rm -f slider.svg            && cp -f slider-100.svg       slider.svg

rm -f lock.png              && cp -f lock-closed.png      lock.png
rm -f lock.svg              && cp -f lock-closed.svg      lock.svg

rm -f rollershutter.png     && cp -f rollershutter-70.png rollershutter.png
rm -f rollershutter.svg     && cp -f rollershutter-70.svg rollershutter.svg
