/**
 * Copyright (c) 2010-2017 by the respective copyright holders.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
/**
 * This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
 * See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
 * Any modifications to this file will be lost upon recompilation of the source schema. 
 * Generated on: 2017.03.09 at 08:34:29 PM CET 
 */

package org.openhab.binding.knx.internal.parser.knxproj13;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Installation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Installation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Topology" type="{http://knx.org/xml/project/13}Topology"/>
 *         &lt;element name="Buildings" type="{http://knx.org/xml/project/13}Buildings"/>
 *         &lt;element name="GroupAddresses" type="{http://knx.org/xml/project/13}GroupAddresses"/>
 *         &lt;element name="Trades" type="{http://knx.org/xml/project/13}Trades" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="InstallationId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="BCUKey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DefaultLine" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="IPRoutingMulticastAddress" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SplitType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CompletionStatus" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="IPRoutingLatencyTolerance" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Installation", propOrder = {
    "topology",
    "buildings",
    "groupAddresses",
    "trades"
})
public class Installation {

    @XmlElement(name = "Topology", required = true)
    protected Topology topology;
    @XmlElement(name = "Buildings", required = true)
    protected Buildings buildings;
    @XmlElement(name = "GroupAddresses", required = true)
    protected GroupAddresses groupAddresses;
    @XmlElement(name = "Trades")
    protected Trades trades;
    @XmlAttribute(name = "InstallationId")
    protected java.lang.String installationId;
    @XmlAttribute(name = "Name")
    protected java.lang.String name;
    @XmlAttribute(name = "BCUKey")
    protected java.lang.String bcuKey;
    @XmlAttribute(name = "DefaultLine")
    protected java.lang.String defaultLine;
    @XmlAttribute(name = "IPRoutingMulticastAddress")
    protected java.lang.String ipRoutingMulticastAddress;
    @XmlAttribute(name = "SplitType")
    protected java.lang.String splitType;
    @XmlAttribute(name = "CompletionStatus")
    protected java.lang.String completionStatus;
    @XmlAttribute(name = "IPRoutingLatencyTolerance")
    protected java.lang.String ipRoutingLatencyTolerance;

    /**
     * Gets the value of the topology property.
     * 
     * @return
     *     possible object is
     *     {@link Topology }
     *     
     */
    public Topology getTopology() {
        return topology;
    }

    /**
     * Sets the value of the topology property.
     * 
     * @param value
     *     allowed object is
     *     {@link Topology }
     *     
     */
    public void setTopology(Topology value) {
        this.topology = value;
    }

    /**
     * Gets the value of the buildings property.
     * 
     * @return
     *     possible object is
     *     {@link Buildings }
     *     
     */
    public Buildings getBuildings() {
        return buildings;
    }

    /**
     * Sets the value of the buildings property.
     * 
     * @param value
     *     allowed object is
     *     {@link Buildings }
     *     
     */
    public void setBuildings(Buildings value) {
        this.buildings = value;
    }

    /**
     * Gets the value of the groupAddresses property.
     * 
     * @return
     *     possible object is
     *     {@link GroupAddresses }
     *     
     */
    public GroupAddresses getGroupAddresses() {
        return groupAddresses;
    }

    /**
     * Sets the value of the groupAddresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupAddresses }
     *     
     */
    public void setGroupAddresses(GroupAddresses value) {
        this.groupAddresses = value;
    }

    /**
     * Gets the value of the trades property.
     * 
     * @return
     *     possible object is
     *     {@link Trades }
     *     
     */
    public Trades getTrades() {
        return trades;
    }

    /**
     * Sets the value of the trades property.
     * 
     * @param value
     *     allowed object is
     *     {@link Trades }
     *     
     */
    public void setTrades(Trades value) {
        this.trades = value;
    }

    /**
     * Gets the value of the installationId property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getInstallationId() {
        return installationId;
    }

    /**
     * Sets the value of the installationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setInstallationId(java.lang.String value) {
        this.installationId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setName(java.lang.String value) {
        this.name = value;
    }

    /**
     * Gets the value of the bcuKey property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getBCUKey() {
        return bcuKey;
    }

    /**
     * Sets the value of the bcuKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setBCUKey(java.lang.String value) {
        this.bcuKey = value;
    }

    /**
     * Gets the value of the defaultLine property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getDefaultLine() {
        return defaultLine;
    }

    /**
     * Sets the value of the defaultLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setDefaultLine(java.lang.String value) {
        this.defaultLine = value;
    }

    /**
     * Gets the value of the ipRoutingMulticastAddress property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getIPRoutingMulticastAddress() {
        return ipRoutingMulticastAddress;
    }

    /**
     * Sets the value of the ipRoutingMulticastAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setIPRoutingMulticastAddress(java.lang.String value) {
        this.ipRoutingMulticastAddress = value;
    }

    /**
     * Gets the value of the splitType property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getSplitType() {
        return splitType;
    }

    /**
     * Sets the value of the splitType property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setSplitType(java.lang.String value) {
        this.splitType = value;
    }

    /**
     * Gets the value of the completionStatus property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getCompletionStatus() {
        return completionStatus;
    }

    /**
     * Sets the value of the completionStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setCompletionStatus(java.lang.String value) {
        this.completionStatus = value;
    }

    /**
     * Gets the value of the ipRoutingLatencyTolerance property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getIPRoutingLatencyTolerance() {
        return ipRoutingLatencyTolerance;
    }

    /**
     * Sets the value of the ipRoutingLatencyTolerance property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setIPRoutingLatencyTolerance(java.lang.String value) {
        this.ipRoutingLatencyTolerance = value;
    }

}
