/**
 * Copyright (c) 2010-2024 Contributors to the openHAB project
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */
package org.openhab.binding.iaqualink.internal.v2.api.mapping;

import static org.junit.jupiter.api.Assertions.*;

import java.util.Collection;

import org.eclipse.jdt.annotation.NonNullByDefault;
import org.junit.jupiter.api.Test;

/**
 * Basic testing for extraction of channel definitions and conversion of updates into JSON
 *
 * @author Jonathan Gilbert - Initial contribution
 */
@NonNullByDefault
class ChannelMapperTest {

    @Test
    void testFindSWC0BoostChannel() {
        DeviceState document = DeviceState.parse(sampleJson);

        Collection<ChannelDef> channels = Channels.appliesToState(Channels.all(), document);

        assertFalse(channels.isEmpty(), "Should have at least one channel");
        assertTrue(channels.stream().anyMatch(def -> def.id().equals("SWC0_Boost")), "Should have SWC0");
        assertTrue(channels.stream().anyMatch(def -> def.id().equals("SWC0_TempSensor3")),
                "Should have SWC0_TempSensor3");
        assertTrue(channels.stream().anyMatch(def -> def.id().equals("SWC0_PhSensor1")), "Should have SWC0_PhSensor1");
    }

    @Test
    void testSimpleChannelUpdate() {
        ChannelDef testChannel = new ChannelDef("test", "test", "Switch", "test", "$.state.val");
        String updateJson = testChannel.updateJson(2).jsonString();
        assertEquals("{\"state\":{\"val\":2}}", updateJson);
    }

    String sampleJson = """
            {
               "state":{
                  "reported":{
                     "aws":{
                        "status":"connected",
                        "timestamp":1729779988154,
                        "session_id":"Test-Session-UUID"
                     },
                     "vr":"V85E4",
                     "vr_esp":"V85E4",
                     "equipment":{
                        "swc_0":{
                           "vr":"V85R70",
                           "version":"V1",
                           "lang":0,
                           "amp":1,
                           "aux230":0,
                           "sn":"TEST_SN",
                           "ph_only":0,
                           "dual_link":0,
                           "temp":1,
                           "vsp":1,
                           "exo_state":1,
                           "production":1,
                           "low":0,
                           "boost":0,
                           "boost_time":"24:00",
                           "error_state":0,
                           "error_code":0,
                           "aux_1":{
                              "type":"none",
                              "state":0,
                              "mode":0,
                              "color":0
                           },
                           "aux_2":{
                              "type":"none",
                              "state":0,
                              "mode":0,
                              "color":0
                           },
                           "filter_pump":{
                              "type":1,
                              "state":1
                           },
                           "orp_sp":700,
                           "ph_sp":72,
                           "swc":50,
                           "swc_low":10,
                           "sns_1":{
                              "sensor_type":"Ph",
                              "state":1,
                              "value":70
                           },
                           "sns_2":{
                              "sensor_type":"Orp",
                              "state":0,
                              "value":0
                           },
                           "sns_3":{
                              "sensor_type":"Water temp",
                              "state":1,
                              "value":27
                           }
                        }
                     },
                     "schedules":{
                        "supported":5,
                        "programmed":2,
                        "sch1":{
                           "id":"sch_1",
                           "name":"Salt Water Chlorinator 1",
                           "endpoint":"swc_1",
                           "enabled":1,
                           "active":0,
                           "timer":{
                              "start":"09:00",
                              "end":"14:00"
                           }
                        },
                        "sch2":{
                           "id":"sch_2",
                           "name":"Salt Water Chlorinator 2",
                           "endpoint":"swc_2",
                           "enabled":0,
                           "active":0,
                           "timer":{
                              "start":"00:00",
                              "end":"00:00"
                           }
                        },
                        "sch3":{
                           "enabled":1,
                           "active":0,
                           "timer":{
                              "start":"09:00",
                              "end":"15:00"
                           },
                           "id":"sch_3",
                           "name":"Filter Pump 1",
                           "endpoint":"ssp_1"
                        },
                        "sch10":{
                           "id":"sch_10",
                           "name":"Aux 2",
                           "endpoint":"aux2",
                           "enabled":0,
                           "active":0,
                           "timer":{
                              "start":"00:00",
                              "end":"00:00"
                           }
                        },
                        "sch4":{
                           "id":"sch_4",
                           "name":"Filter Pump 2",
                           "endpoint":"ssp_2",
                           "enabled":0,
                           "active":0,
                           "timer":{
                              "start":"00:00",
                              "end":"00:00"
                           }
                        }
                     }
                  }
               },
               "metadata":{
                  "reported":{
                     "aws":{
                        "status":{
                           "timestamp":1729779988
                        },
                        "timestamp":{
                           "timestamp":1729779988
                        },
                        "session_id":{
                           "timestamp":1729779988
                        }
                     },
                     "vr":{
                        "timestamp":1729779991
                     },
                     "vr_esp":{
                        "timestamp":1729779992
                     },
                     "equipment":{
                        "swc_0":{
                           "vr":{
                              "timestamp":1728437680
                           },
                           "version":{
                              "timestamp":1728437681
                           },
                           "lang":{
                              "timestamp":1728437683
                           },
                           "amp":{
                              "timestamp":1728437683
                           },
                           "aux230":{
                              "timestamp":1728437683
                           },
                           "sn":{
                              "timestamp":1728437683
                           },
                           "ph_only":{
                              "timestamp":1728437684
                           },
                           "dual_link":{
                              "timestamp":1728437684
                           },
                           "temp":{
                              "timestamp":1728437630
                           },
                           "vsp":{
                              "timestamp":1728437630
                           },
                           "exo_state":{
                              "timestamp":1728437633
                           },
                           "production":{
                              "timestamp":1730013707
                           },
                           "low":{
                              "timestamp":1730013702
                           },
                           "boost":{
                              "timestamp":1728437636
                           },
                           "boost_time":{
                              "timestamp":1728437637
                           },
                           "error_state":{
                              "timestamp":1728437638
                           },
                           "error_code":{
                              "timestamp":1728437639
                           },
                           "aux_1":{
                              "type":{
                                 "timestamp":1728437641
                              },
                              "state":{
                                 "timestamp":1728437642
                              },
                              "mode":{
                                 "timestamp":1728437643
                              },
                              "color":{
                                 "timestamp":1728437644
                              }
                           },
                           "aux_2":{
                              "type":{
                                 "timestamp":1728437645
                              },
                              "state":{
                                 "timestamp":1728989966
                              },
                              "mode":{
                                 "timestamp":1728437647
                              },
                              "color":{
                                 "timestamp":1728437648
                              }
                           },
                           "filter_pump":{
                              "type":{
                                 "timestamp":1728437649
                              },
                              "state":{
                                 "timestamp":1730013704
                              }
                           },
                           "orp_sp":{
                              "timestamp":1728437653
                           },
                           "ph_sp":{
                              "timestamp":1728437654
                           },
                           "swc":{
                              "timestamp":1728512953
                           },
                           "swc_low":{
                              "timestamp":1728437656
                           },
                           "sns_1":{
                              "sensor_type":{
                                 "timestamp":1728437657
                              },
                              "state":{
                                 "timestamp":1728437657
                              },
                              "value":{
                                 "timestamp":1728437657
                              }
                           },
                           "sns_2":{
                              "sensor_type":{
                                 "timestamp":1728437658
                              },
                              "state":{
                                 "timestamp":1728437658
                              },
                              "value":{
                                 "timestamp":1728437658
                              }
                           },
                           "sns_3":{
                              "sensor_type":{
                                 "timestamp":1730014119
                              },
                              "state":{
                                 "timestamp":1730014119
                              },
                              "value":{
                                 "timestamp":1730014119
                              }
                           }
                        }
                     },
                     "schedules":{
                        "supported":{
                           "timestamp":1728437660
                        },
                        "programmed":{
                           "timestamp":1728437660
                        },
                        "sch1":{
                           "id":{
                              "timestamp":1728437661
                           },
                           "name":{
                              "timestamp":1728437661
                           },
                           "endpoint":{
                              "timestamp":1728437661
                           },
                           "enabled":{
                              "timestamp":1729997985
                           },
                           "active":{
                              "timestamp":1729997985
                           },
                           "timer":{
                              "start":{
                                 "timestamp":1728989817
                              },
                              "end":{
                                 "timestamp":1728989817
                              }
                           }
                        },
                        "sch2":{
                           "id":{
                              "timestamp":1728437665
                           },
                           "name":{
                              "timestamp":1728437665
                           },
                           "endpoint":{
                              "timestamp":1728437665
                           },
                           "enabled":{
                              "timestamp":1728437666
                           },
                           "active":{
                              "timestamp":1728437666
                           },
                           "timer":{
                              "start":{
                                 "timestamp":1728437667
                              },
                              "end":{
                                 "timestamp":1728437667
                              }
                           }
                        },
                        "sch3":{
                           "enabled":{
                              "timestamp":1730001588
                           },
                           "active":{
                              "timestamp":1730001588
                           },
                           "timer":{
                              "start":{
                                 "timestamp":1728442819
                              },
                              "end":{
                                 "timestamp":1728442819
                              }
                           },
                           "id":{
                              "timestamp":1728437668
                           },
                           "name":{
                              "timestamp":1728437668
                           },
                           "endpoint":{
                              "timestamp":1728437668
                           }
                        },
                        "sch10":{
                           "id":{
                              "timestamp":1728437676
                           },
                           "name":{
                              "timestamp":1728437676
                           },
                           "endpoint":{
                              "timestamp":1728437676
                           },
                           "enabled":{
                              "timestamp":1728989967
                           },
                           "active":{
                              "timestamp":1728989967
                           },
                           "timer":{
                              "start":{
                                 "timestamp":1728437678
                              },
                              "end":{
                                 "timestamp":1728437678
                              }
                           }
                        },
                        "sch4":{
                           "id":{
                              "timestamp":1728437671
                           },
                           "name":{
                              "timestamp":1728437671
                           },
                           "endpoint":{
                              "timestamp":1728437671
                           },
                           "enabled":{
                              "timestamp":1728437673
                           },
                           "active":{
                              "timestamp":1728437673
                           },
                           "timer":{
                              "start":{
                                 "timestamp":1728437674
                              },
                              "end":{
                                 "timestamp":1728437674
                              }
                           }
                        }
                     }
                  }
               },
               "version":1680,
               "timestamp":1730014146
            }
            """;
}
